libtransmission/platform-quota.c
Signed-off-by: Waldemar Brodkorb <wbx@uclibc-ng.org>
=> uClibc-ng since 1.0.18 has sys/quota.h synced with GNU libc

AUTHORS, NEWS, cli/transmission-cli.1, configure.ac, daemon/daemon.c, daemon/remote.c, daemon/transmission-daemon.1, daemon/transmission-remote.1, dist/msi/Transmission.wxs, gtk/main.c, gtk/transmission-gtk.1, gtk/util.c, libtransmission/fdlimit.c, libtransmission/rpcimpl.c, macosx/Controller.m, macosx/Credits.rtf, macosx/PortChecker.m, macosx/TransmissionHelp/html/FAQ.html, macosx/TransmissionHelp/html/scripts.html, macosx/TransmissionHelp/index.html, qt/AboutDialog.ui, qt/MainWindow.cc, qt/README.txt, qt/transmission-qt.1, transmission-gtk.spec.in, utils/transmission-create.1, utils/transmission-edit.1, utils/transmission-show.1, web/javascript/transmission.js
This partly solves #39. Also see #73.
=> Update all website links to canonical HTTPS version

CMakeLists.txt, cmake/FindSYSTEMD.cmake, daemon/CMakeLists.txt
Fixes: https://github.com/transmission/transmission/issues/117
=> cmake: add FindSYSTEMD module

Transmission.xcodeproj/project.pbxproj, macosx/PrefsController.m
BTW: What about adding 
```
third-party/libevent
```
to `.gitignore`?
=> OS X misc improvements 1

gtk/transmission-gtk.desktop.in
Reasoning for the changes is included in commit messages.
You may want to add more keywords if you think of any useful ones.
=> Modernize the .desktop file a bit

libtransmission/net.c
Should make transmission slightly faster.
=> Add TCP_FASTOPEN support

gtk/actions.c, qt/MainWindow.ui
Makes reordering torrents in the queue less cumbersome in the Qt interface.
=> Added queue up/down hotkeys to the Qt interface.

libtransmission/platform-quota.c
The patch is taken from dports (Dragonfly ports).
=> Fixed platform-quota.c for DragonFly.

libtransmission/web.c
use secure by default and change the env var to match curl -k behaviour
=> Change TR_CURL_SSL_VERIFY to TR_CURL_SSL_INSECURE

web/javascript/main.js, web/style/transmission/mobile.css, web/style/transmission/mobile.scss
Afaik both Android and iPhone's have the capability to upload file's and it bugs me out that I cant do it from my iPhone :)
My sass compiler did a lot of changes to the css file but the actual changes (main.js and mobile.scss) are quite small. I also removed a class in the scss file that I think should have been removed in f70c4d8 (freespace-info).
=> (web) show upload torrent file button on mobile devices

libtransmission/rpc-server.c
The RPC Server does not appear to have any protection against brute force attacks using username:password combinations. The following patch will allow for up to 100 unsuccessful login attempts after which logins will be disabled.
=> anti-brute force for RPC Server

gtk/filter.c, gtk/msgwin.c, gtk/tr-limit-popover.c, gtk/tr-window.c
Tested-by: Pavel Rehak <pavel-rehak@email.cz>
=> wip/gtk-3.14: Make strings translatable

COPYING, gtk/main.c, macosx/Info.plist, macosx/QuickLookPlugin/QuickLookPlugin-Info.plist, macosx/da.lproj/InfoPlist.strings, macosx/de.lproj/InfoPlist.strings, macosx/en.lproj/InfoPlist.strings, macosx/es.lproj/InfoPlist.strings, macosx/fr.lproj/InfoPlist.strings, macosx/it.lproj/InfoPlist.strings, macosx/nl.lproj/InfoPlist.strings, macosx/pt_PT.lproj/InfoPlist.strings, macosx/ru.lproj/InfoPlist.strings, macosx/tr.lproj/InfoPlist.strings
Small update to copyright string
=> Updated copyright string to 2018

autogen.sh, daemon/my-valgrind.sh, extras/send-email-when-torrent-done.sh, gtk/my-valgrind.sh, libtransmission/fail.sh, qt/my-valgrind.sh, update-version-h.sh
This PR provides follow shell script improvement:
- Fixes of missing and wrong shebang 
- Consistent and more readable, maintainable styling, including indentation
- More robust syntaxes compare to legacy syntaxes, not well-defined syntaxes and syntaxes with potential issues, like globbing and word splitting
Please let me know if there is anything needs to be done here, many thanks.
=> Refactor shell scripts with syntax and styling fixes

libtransmission/jsonsl.c, libtransmission/jsonsl.h
source: https://github.com/mnunberg/jsonsl
=> chore: update jsonsl parser snapshot

qt/MainWindow.cc, qt/Torrent.cc, qt/Torrent.h, qt/Utils.h
Some of the issues were reported in #1106 which this PR is meant to fix.
=> Fixup recent Qt client changes

macosx/PeerProgressIndicatorCell.m
Fix the peer progress number in dark mode.
=> Fix the peer progress number in dark mode.

AUTHORS, cli/transmission-cli.1, daemon/transmission-daemon.1, gtk/main.c, gtk/transmission-gtk.1, macosx/Credits.rtf, qt/AboutDialog.cc, qt/transmission-qt.1, transmission-gtk.spec.in, utils/transmission-create.1, utils/transmission-edit.1, utils/transmission-remote.1, utils/transmission-show.1, web/javascript/inspector.js, web/javascript/prefs-dialog.js, web/javascript/remote.js, web/javascript/transmission.js
Revert c7cc8301dbab0a0c8fdf56bb75669afb35758f9d
=> fixup! (trunk) update credits

libtransmission/Makefile.am, macosx/Makefile.am, po/LINGUAS, third-party/Makefile.am
=> Add missing files that fail build from tarball

web/index.html
=> Remove unused html

gtk/hig.c, gtk/tr-icon.c, libtransmission/announcer.c, libtransmission/fdlimit.c, libtransmission/net.c, libtransmission/peer-io.c, libtransmission/port-forwarding.c, libtransmission/torrent-magnet.c, libtransmission/torrent.c, libtransmission/tr-dht.c, libtransmission/tr-lpd.c, libtransmission/tr-lpd.h, libtransmission/tr-macros.h, libtransmission/watchdir.c, libtransmission/web.c, libtransmission/web.h, libtransmission/webseed.c
* fix cross-platform static-assert warnings in tr-lpd
* fix a handful of MSVC-specific compiler warnings in libtransmission
* fix GtkMisc deprecation warnings in GTK client
=> chore: fix compiler warnings

CMakeLists.txt, daemon/daemon.c, gtk/details.c, gtk/msgwin.c, libtransmission/announcer.c, libtransmission/fdlimit.c, libtransmission/magnet.c, libtransmission/makemeta.c, libtransmission/peer-mgr.c, libtransmission/peer-msgs.c, libtransmission/rpc-server.c, libtransmission/subprocess-posix.c, libtransmission/torrent-magnet.c, libtransmission/torrent.c, libtransmission/tr-lpd.c, libtransmission/transmission.h, libtransmission/utils.c, libtransmission/utils.h, libtransmission/webseed.c, utils/remote.c, utils/show.c, web/javascript/common.js, web/javascript/file-row.js, web/javascript/formatter.js, web/javascript/inspector.js, web/javascript/prefs-dialog.js, web/javascript/remote.js, web/javascript/torrent-row.js, web/javascript/transmission.js
Fix a bunch of warnings that were unearthed by https://lgtm.com/projects/g/transmission/transmission/ . This PR doesn't get all of them, but it does make some good progress.
=> fix: resolve some lgtm warnings

qt/FaviconCache.cc, qt/Session.cc
feat: in addition to pinging tracker.domain.com/favicon.ico for the favicon, also try domain.com/ and www.domain.com/ since many trackers use different subdomains for their websites.
=> Scrape www subdomain for favicon

web/package.json, web/webpack.config.js, web/yarn.lock
webpack-dev-server added for web dev. environment.
'yarn dev' will start dev. server and it will watch code changes and build them, and hot reload.
dev. server also proxy '/rpc', please check webpack.config.js
=> chore(web): dev environment

gtk/filter.c, libtransmission/magnet.c, libtransmission/metainfo.c, libtransmission/peer-mgr.c, libtransmission/torrent-magnet.c, libtransmission/torrent.c, libtransmission/tr-dht.c
Refactor a handful of functions so that their code loops are simpler.
=> refactor: sonarcloud warnings about overly-complex looping logic

gtk/details.c, gtk/file-list.c, libtransmission/cache.c, libtransmission/file.c, libtransmission/makemeta.c, libtransmission/torrent.c, qt/Application.cc, qt/Application.h, qt/DetailsDialog.cc, qt/DetailsDialog.h, qt/FilterBar.cc, qt/InteropObject.cc, qt/MainWindow.cc, qt/Prefs.cc, qt/Torrent.cc, qt/Utils.cc, qt/Utils.h, qt/VariantHelpers.cc, utils/remote.c
* simpllify loop logic
* const correctness
* reduce cognitive complexity of some functions
=> refactor: fix more sonarcloud warnings

macosx/Controller.h, macosx/Controller.m, macosx/FileListNode.h, macosx/FileListNode.m, macosx/FileRenameSheetController.h, macosx/FileRenameSheetController.m, macosx/PrefsController.m, macosx/Torrent.h, macosx/Torrent.m, macosx/TrackerNode.h, macosx/TrackerNode.m
As per https://github.com/transmission/transmission/pull/1585#discussion_r555770484
=> Move ivars to @implementation.

gtk/conf.c, gtk/conf.h, gtk/notify.c, gtk/tr-prefs.h, libtransmission/variant.c, qt/.clang-tidy, qt/Application.cc, qt/Prefs.cc, qt/VariantHelpers.h
Fixes #1706. See that description for details.
=> refactor: torrent-complete-sound-command is a list

libtransmission/utils.cc
We know what strings are passed into `tr_strip_positional_args()`. Instead of using dynamic allocation, use a fixed-size array that's big enough to fit the strings that we have.
=> fix: clang nullptr dereference warning in utils.cc

libtransmission/variant.cc
@mikedld and I had a miscommunication on #1800 and he had some review comments that came in after I'd merged the PR. This followup addresses those comments :smiley:
=> refactor: variant fixups

libtransmission/announcer.cc, libtransmission/peer-mgr.cc, libtransmission/platform.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc
Update c0ed82 (#1778) to use C++ containers.
=> refactor: use std container for session torrents

libtransmission/session.cc
This PR replaces tr_list with std::list in session.cc sessionLoadTorrents().
=> refactor: replace tr_list with std::list in sessionLoadTorrents()

libtransmission/session.cc, libtransmission/variant-json.cc
This PR replaces tr_list with std::deque in variant-json.cc's ParentState struct.
=> refactor: use std::list in variant-json.cc

libtransmission/platform.cc
This PR replaces tr_list with std::list in platform.c's tr_getWebClientDir()
=> refactor: use std::list in tr_getWebClientDir()

libtransmission/rpc-server.cc
This PR replaces tr_list with std::list in rpc-server.cc's whitelists.
=> refactor: replace tr_list with std::list in rpc-server whitelists

libtransmission/web.cc
This PR replaces tr_list with std::set in web.cc's paused_easy_handles.
=> refactor: replace tr_list with std::set in web.cc

libtransmission/webseed.cc
This PR replaces tr_list with std::set in tr_webseed's task field.
=> refactor: use std::set in tr_webseed

libtransmission/verify.cc, libtransmission/webseed.cc
This PR replaces tr_list with std::set in verify.cc's code.
Note, this PR tries to stay limited to swapping from one container class to another. There are pre-existing code smells in this codebase that are not addressed in this refactor, e.g. the container is a static field that is not cleaned up on exit.
=> refactor: use std::set in verify.cc's verifyList

libtransmission/torrent.cc
A minor refactor to use std:: tools instead of bespoke ones.
This PR replaces a pair of local `tr_ptrArray` fields with a `std::set` and a `std::vector` in `deleteLocalData()`
=> refactor: use std::set in deleteLocalData()

libtransmission/announcer-udp.cc
This PR changes `tau_scrape_request.payload` to be a `std::vector<uint8_t>` instead of a raw `char*`.
=> refactor: use std::vector for tau_scrape_request.payload

libtransmission/announcer-udp.cc
This PR changes `tau_tracker.key` and `tau_tracker.host` to be `std::string`s instead of raw `char*`s.
=> refactor: use std::string in tau_tracker

libtransmission/announcer-udp.cc
This PR changes `tau_announce_request.payload` to be a `std::vector` instead of a raw `char*`.
=> refactor: use std::vector in tau_announce_request

libtransmission/announcer-udp.cc
=> fix: coverity regressions reported on 2021-10-01

libtransmission/announcer-udp.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/copy-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/subprocess-test.cc, tests/libtransmission/utils-test.cc
Fix some of the newly-reported Coverity regressions.
=> fix: some Coverity regressions reported on 2021-09-16

libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/webseed.cc
Fix three new issues in `master` that were found via testing.
=> fix: recent regressions

gtk/makemeta-ui.cc, libtransmission/bandwidth.cc, libtransmission/tr-lpd.cc, libtransmission/tr-macros.h, libtransmission/trevent.cc, qt/Session.cc, utils/remote.cc
Another incremental C++ization PR. Does what it says on the tin. No functional changes.
=> refactor: add [[fallthrough]] annotation

libtransmission/metainfo.cc, libtransmission/rpc-server.cc, libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
Used to take a char*, now takes a string_view.
=> refactor: tr_urlIsValid*() now takes a std::string_view

gtk/Application.cc, libtransmission/announcer-http.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/rpc-server.cc, libtransmission/variant.cc, utils/show.cc
Just like `tr_quark_get_string()`, but returns a `std::string_view`.
=> feat: add tr_quark_get_string_view()

libtransmission/log.cc, libtransmission/metainfo.cc, libtransmission/metainfo.h, tests/libtransmission/metainfo-test.cc
small changes to avoid unnecessary string allocations and unncessary strlen calls.
=> perf: minor perf improvements

libtransmission/bitfield.cc, libtransmission/bitfield.h, libtransmission/peer-msgs.cc, libtransmission/resume.cc, tests/libtransmission/bitfield-test.cc
yet another fixup of the tr_piece struct removal.
=> fixup! refactor: remove tr_piece struct (#2059)

libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent-ctor.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/transmission.h, macosx/Torrent.mm
as per discussion with @livings124.
Removing (nearly-)unused code.
=> refactor: remove tr_ctorSetMetainfoFromHash()

libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/magnet.cc, libtransmission/makemeta.cc, libtransmission/metainfo.cc, libtransmission/peer-io.h, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/web-utils.cc, qt/AddData.cc, tests/libtransmission/utils-test.cc, utils/remote.cc
Replace some of the heap-allocating string utils with string_view equivalents.
=> refactor: tr_strv*() util functions

daemon/daemon.cc, libtransmission/inout.cc, libtransmission/makemeta.cc, libtransmission/platform.cc, libtransmission/platform.h, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session-id.cc, libtransmission/session.cc, libtransmission/stats.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-macros.h, libtransmission/utils.h, libtransmission/variant.cc, libtransmission/watchdir.cc, libtransmission/web.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/copy-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/utils-test.cc
Add `tr_strvPath()`, a std::string version of `tr_buildPath()`
=> feat: add tr_strvPath()

gtk/FreeSpaceLabel.cc, libtransmission/platform-quota.cc, libtransmission/platform-quota.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/transmission.h, libtransmission/utils.cc, libtransmission/utils.h
- make tr_session.download_dir a  std::string
- make the platform-quota API std::string_view-safe
=> refactor: tr_dirSpace()

libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/session-test.cc
Add tr_session getter / setter methods for the incomplete dir and whether it's enabled
=> refactor: tr_session.incomplete_dir

utils/edit.cc
=> refactor: remove tr_variantDictFindStr() from transmission-edit

libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/transmission.h, tests/libtransmission/session-test.cc
Also fix tests and code comments for clarity.
=> fix: rpc-authorization regression from earlier today

libtransmission/torrent-ctor.cc, libtransmission/utils.cc, libtransmission/utils.h
For use by torrent-ctor when looping through thousands of files on startup
=> refactor: add a tr_loadFile() variant with reusable buffer

gtk/Prefs.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, tests/libtransmission/metainfo-test.cc, tests/libtransmission/subprocess-test.cc
Fix a handful of Coverity warnings. None serious.
=> fix: coverity warnings

cli/cli.cc, libtransmission/announcer.cc, libtransmission/magnet-metainfo.cc, libtransmission/magnet-metainfo.h, libtransmission/metainfo.cc, libtransmission/metainfo.h, libtransmission/platform-quota.cc, libtransmission/platform.cc, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc
Fix a few sonarcloud warnings. Nothing serious.
=> fix: some sonarcloud warnings

libtransmission/platform-quota.cc
Resolves build error for XFS #2188
=> Fix building for XFS

gtk/MainWindow.cc, gtk/transmission.gresource.xml
=> Use stock options and statistics icons in statusbar (GTK client)

libtransmission/tr-dht.cc
fix a dht regression introduced last week by #2187
Fixes #2195
=> fixup: benc parse string view

libtransmission/torrent.cc
fix off-by-one error introduced in #2220
=> fixup! refactor: tr_completion (#2220)

libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/handshake.cc, libtransmission/inout.cc, libtransmission/magnet-metainfo.cc, libtransmission/peer-mgr-active-requests.cc, libtransmission/rpcimpl.cc
Just a little housekeeping: clean up some sonarcloud code smells.
=> fix: sonarcloud

libtransmission/block-info.h, libtransmission/completion.cc, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/torrent.cc, libtransmission/verify.cc, libtransmission/webseed.cc, tests/libtransmission/block-info-test.cc, tests/libtransmission/completion-test.cc
No functional changes. Just renaming a couple of methods to be less prolix.
=> refactor: minor naming change in block_info

gtk/Application.cc, libtransmission/completion.cc, libtransmission/completion.h, libtransmission/peer-io.cc, libtransmission/peer-mgr-wishlist.cc, libtransmission/peer-mgr-wishlist.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/variant-benc.cc, qt/FileTreeModel.cc, qt/FileTreeModel.h, qt/VariantHelpers.h
Another sonarcloud janitorial PR to clean up some recent warnings / code smells.
No (intentional) behavior changes :smile_cat:
=> fix: sonarcloud warnings / code smells

libtransmission/file-win32.cc
This avoids ERROR_INVALID_NAME ("The filename, directory name, or volume label syntax is incorrect") errors since such normalization doesn't happen automatically for "\\?\"-prefixed paths.
Fixes: #1791
=> Squash consecutive path separators on Windows

libtransmission/block-info.h, libtransmission/torrent.h, libtransmission/tr-utp.cc, libtransmission/utils.cc, libtransmission/variant.cc, tests/libtransmission/metainfo-test.cc
fix a handful of recent warnings reported by sonarcloud / coverity.
=> fix: new warnings

libtransmission/torrent.cc
fix: fmr error with temporary strings
CC @mikedld
=> fixup! fix: env var leak in tr_spawn_async() (#2212)

libtransmission/torrent.cc
=> fix: crash in tr_file_priorities::filePriority()

libtransmission/resume.cc, libtransmission/torrent.cc, libtransmission/variant.cc, libtransmission/webseed.cc
Fix three memory leak regressions introduced over the last couple of weeks.
=> fix: memleak regressions

libtransmission/announcer.cc, libtransmission/announcer.h, libtransmission/torrent.cc, libtransmission/torrent.h
ensure announcer tracker count is correct.
=> fixup! refactor: add tr_torrentTrackers() (#2282)

libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/webseed.cc
remove the redundant function `tr_pieceOffset()`
=> refactor: remove tr_pieceOffset()

libtransmission/session.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent.cc, qt/AddData.cc, qt/OptionsDialog.cc, utils/show.cc
fix some recent sonarcloud warnings.
=> fix: sonarcloud warnings

libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant-benc.cc, libtransmission/web-utils.cc
=> refactor: prefer std::from_chars over strtoul

libtransmission/verify.cc
=> fix: clear verify_thread before releasing verify mutex lock

libtransmission/clients.cc
fix a sonarcloud bounds-check warning
=> fix: out-of-bound memory acess sonarcloud warning

libtransmission/torrent.cc
=> Fixup construction of temp dir path in `deleteLocalData`

libtransmission/web-utils.cc
=> fix: allow malformed magnet links to be added

libtransmission/inout.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h
=> fix: potential out-of-range error in io's readOrWritePiece()

libtransmission/torrent-metainfo.cc
Explicitly use unsigned chars.
Fixes #2106.
=> fix: assertion failed on non-English symbols

libtransmission/announcer-udp.cc
fixes https://github.com/transmission/transmission/issues/2438.
=> fix: string leak regression when udp announces fail

libtransmission/cache.cc
=> fix: remove assert() that shouldn't always be true

gtk/DetailsDialog.cc
Fixes #418. Commit author is @Akzuu; this branch is just an update of their branch to resolve merge conflicts with `main` that built up in the interm since Akzuu's branch was PR'ed.
Supersedes #1632.
=> fix: long error string truncated in GTK client

libtransmission/session.cc
=> fix: in check input before calling tr_sha1_from_string()

libtransmission/upnp.cc
Fixes #2480.
This leak is present in 2.94 / 3.00 as well
=> fix: memory leak in upnp

gtk/CMakeLists.txt
Derived from the [master] version of the file; fixes Issue #725
=> Fix icon install location

libtransmission/log.cc
run clang-format to make CI happy with `main`
=> fixup! [android] Use android logger (#585)

libtransmission/announcer.cc, libtransmission/benc.h, libtransmission/net.cc, libtransmission/peer-mgr.cc, libtransmission/resume.cc, libtransmission/torrent.cc, libtransmission/variant-benc.cc
fix some code smells that sonarcloud reported in the new benc and announcer code from the past few days.
=> fix: sonarcloud warnings in new code

libtransmission/peer-mgr.cc
fix Jan 22 regression in parsing port numbers from pex. Yeesh
=> fixup! refactor: use C++ objects in announcer (#2474)

libtransmission/rpc-server.cc
Fixes #2454 with the one-liner suggested by @mikedld :bow:
=> fix: use libdeflate_gzip_compress in rpc-server.cc

cli/transmission-cli.1
removing unrecognized cli options.
Fixes #1621
=> fix man pages listing invalid cli options

gtk/FileList.cc, gtk/MessageLogWindow.cc, gtk/Prefs.cc, gtk/Session.cc, gtk/SystemTrayIcon.cc, gtk/Utils.cc, libtransmission/announce-list.cc, libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/file-posix.cc, libtransmission/handshake.cc, libtransmission/net.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc
fix some sonarcloud 'code smells'
=> fix: some use-init-statement sonarcloud warnings

qt/Application.cc, qt/FaviconCache.cc, qt/FileTreeItem.cc, qt/FilterBarComboBox.cc, qt/FreeSpaceLabel.cc, qt/InteropObject.cc, qt/MainWindow.cc, qt/MakeDialog.cc, qt/PathButton.cc, qt/Prefs.cc, qt/PrefsDialog.cc, qt/RpcClient.cc, qt/Session.cc, qt/VariantHelpers.h, qt/WatchDir.cc
use init-if statements in transmission-qt to silence sonarcloud "code smell" warnings
=> refactor: sonarcloud

gtk/FileList.cc, gtk/PrefsDialog.cc, gtk/Session.cc, gtk/TorrentCellRenderer.cc, libtransmission/announce-list.cc, libtransmission/blocklist.cc, libtransmission/cache.cc, libtransmission/handshake.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/platform.cc, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-getopt.cc, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, libtransmission/variant.cc, libtransmission/web-utils.cc, qt/DetailsDialog.cc, qt/FileTreeModel.cc, qt/FileTreeView.cc
Yet Another Sonarcloud PR. This fixes the last of the low-hanging "use an if-init statement to reduce local variable scope" code smells.
=> refactor: sonarcloud "use if init" statements

libtransmission/rpcimpl.cc
fix potential memory leak reported by coverity.
=> fixup! add labels to torrent-add rpc method (#2539)

libtransmission/announcer-udp.cc
=> fix: make DNS queries lowercase

libtransmission/web.cc
Supersedes #605.
This is that PR, updated to fix merge conflicts with the current codebase. Author credits go to @AndreyPavlenko.
=> feat: use new envvar TR_CURL_PROXY_SSL_NO_VERIFY

gtk/OptionsDialog.cc, libtransmission/magnet-metainfo.cc, libtransmission/session.h, libtransmission/web-utils.cc, libtransmission/web.cc, libtransmission/webseed.cc, qt/FaviconCache.cc, utils/create.cc, web/src/torrent.js
fix a handful of code smells that sonarcloud has reported in new code.
=> fix: sonarcloud code smells

libtransmission/torrent.cc
=> fix: set torrent.doneDate when adding a new seed

cli/cli.cc, gtk/FaviconCache.cc, libtransmission/announcer-http.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
fix race condition in web threadfunc during bootstrap. Fixes #2639.
make tr_web::FetchDoneFunc a std::function.
=> refactor: tr_web

libtransmission/announcer-udp.cc
This, along with the http / https refactors, should fix #1815.
=> fix: do not hammer dns servers re-requesting udp trackernames

libtransmission/torrent-magnet.cc
fix for https://github.com/transmission/transmission/issues/2239
=> magnet links always pause after they get metainfo

web/src/torrent.js
fix oops in web client torrent filtering
=> fixup! fix: sonarcloud code smells (#2623)

libtransmission/makemeta.cc
fix unreleased regression that was introduced in bd68d3a
=> fix: unreleased regression in makemeta pieces hashes

libtransmission/peer-io.cc
=> fix: unsupported peer socket type 0 assertion failure

libtransmission/web.cc
fix race condition in TR_ASSERT introduced in f1a5384
=> fixup! refactor: tr_web (#2633)

docs/Blocklists.md, docs/Bug-Submission.md, docs/Building-Transmission.md, docs/Configuration-Files.md, docs/Editing-Configuration-Files.md, docs/Environment-Variables.md, docs/Transmission-Architecture.md, docs/Web-Interface.md, docs/Why-Are-My-Speeds-So-Slow.md, docs/Why-is-my-port-closed.md, docs/rpc-spec.md
=> docs: convert some wiki markup to markdown

libtransmission/block-info.cc, libtransmission/block-info.h, libtransmission/completion.cc, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.h, libtransmission/web.cc, tests/libtransmission/block-info-test.cc, tests/libtransmission/completion-test.cc, tests/libtransmission/file-piece-map-test.cc, tests/libtransmission/move-test.cc
=> fix: always use a block size of 16 KB

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/file-info.cc, libtransmission/file-info.h, libtransmission/makemeta.cc, libtransmission/makemeta.h, libtransmission/torrent-metainfo.cc, utils/create.cc
=> feat: warn when creating torrents with nonportable filenames

docs/Editing-Configuration-Files.md, docs/Scripts.md
=> docs: rpc password, systemd privs

libtransmission/block-info.cc, libtransmission/block-info.h, tests/libtransmission/block-info-test.cc, tests/libtransmission/completion-test.cc
=> refactor: remove unused tr_block_info.n_blocks_in_piece

libtransmission/announcer.cc
=> feat: stop announcing on not-registered tracker error

libtransmission/web.cc, libtransmission/webseed.cc
Fixup a webseed bookkeeping regression introduced in #2613
=> fixup: webseed

libtransmission/upnp.cc
Fixes https://github.com/transmission/transmission/issues/2711.
=> perf: do not block on upnpDiscover() call during startup

libtransmission/announcer.cc
This _may_ solve the crash described at https://github.com/transmission/transmission/issues/2571#issuecomment-1051388170 by calling tier.useNextTracker(); but if not, it also adds new assertions to try and fail sooner if the announcer gets into a bad state.
=> chore: exploratory change for #2571

libtransmission/rpc-server.cc, libtransmission/rpc-server.h
@mikedld Starting to address some of your comments from #2574.
=> fixup: unix socket implementation changes

libtransmission/torrent.cc, libtransmission/torrents.cc, libtransmission/webseed.cc
=> fix: webseed assertion failures

macosx/Controller.mm, macosx/FilterBar.xib, macosx/FilterBarController.h, macosx/FilterBarController.mm
This implements an error filter on the filter bar in the Mac client.
https://trac.transmissionbt.com/ticket/5460
=> Added ability to filter on error status.

libtransmission/rpc-server.cc
=> fix: rpc-server shutdown assertion failure

libtransmission/log.cc
Part 3 of a series to update Transmission's logging mechanism. #2755 is the previous in the series. The goals are described [here](https://github.com/transmission/transmission/pull/2749#pullrequest-875916992).
---
This PR sets a cutoff threshold for warnings, errors, and critical errors. After the Nth repetition of the same message (N is currently 30), logging for that error is stopped for the rest of the session. This can prevent excessive log noise.
Fixes #295.
=> refactor: stop logging repetitive warnings

Transmission.xcodeproj/project.pbxproj, gtk/MessageLogWindow.cc, macosx/MessageWindow.xib, macosx/MessageWindowController.mm
Take the new logging levels into account in the macOS GUI.
Fixes #2759.
=> fixup: macos log error

libtransmission/announcer-http.cc
=> fix: don't crash when processing multiple errors

daemon/transmission-daemon.1
Fixes #2766. Author is @timtas from the patchfile submitted [here](https://github.com/transmission/transmission/issues/2766#issue-1167407985).
=> docs: add pid-file to transmission-daemon manpage

libtransmission/net.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h
Fixes https://github.com/transmission/transmission/issues/2750.
=> perf: avoid excess filesystem checks

libtransmission/announce-list.cc, libtransmission/torrent.cc
=> fix for editing magnet link tracker list

libtransmission/web.cc
Tell our curl shared handle to share everything it can.
=> perf: tell curl_share to share everything

libtransmission/peer-io.cc
=> fix: set the utp state change log level to trace

utils/remote.cc
Option `-lg` lists all bandwidth groups with their bandwidth limits.
=> Add support for group-get RPC call to transmission-remote

libtransmission/announcer.cc, libtransmission/completion.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h
Add assertions to help track down #2727. I hope.
=> refactor: add tracer assertions or bug #2727

libtransmission/magnet-metainfo.cc, tests/libtransmission/completion-test.cc, tests/libtransmission/torrents-test.cc
- Fix a memory leak in the torrent test code
- FIx an array-bounds-read bug in the completion test code
- Fix an array-bounds-read bug in the magnet link parser
=> fix: three asan issues

libtransmission/blocklist.cc, libtransmission/blocklist.h, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/error.cc, libtransmission/error.h, libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/ptrarray.cc, libtransmission/ptrarray.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/torrents.cc, libtransmission/torrents.h, libtransmission/tr-lpd.cc, libtransmission/tr-lpd.h, libtransmission/transmission.h, libtransmission/web-utils.cc, libtransmission/web-utils.h, qt/Session.cc, qt/Session.h, qt/VariantHelpers.cc, qt/VariantHelpers.h
No functional changes; just removing unused functions.
:heart: to https://github.com/mgehre/xunused/
=> refactor: remove unused functions

libtransmission/blocklist.cc, libtransmission/clients.cc, libtransmission/file-win32.cc, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/web-utils.cc, tests/libtransmission/utils-test.cc
previously: https://github.com/transmission/transmission/pull/2867, https://github.com/transmission/transmission/pull/2871
=> refactor: remove tr_snprintf()

libtransmission/announce-list.h, libtransmission/announcer.cc, libtransmission/bandwidth.h, libtransmission/completion.cc, libtransmission/completion.h, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/quark.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.h, libtransmission/utils.h, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
no behavioral changes, just add nodiscard / constexpr / noexcept to methods
=> refactor: annotate nodiscard, constexpr, noexcept methods

daemon/daemon-posix.cc, daemon/daemon.cc, libtransmission/announce-list.cc, libtransmission/crypto-utils.cc, libtransmission/magnet-metainfo.cc, libtransmission/platform.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/session-id.cc, libtransmission/session.cc, libtransmission/subprocess-win32.cc, libtransmission/torrent.cc, libtransmission/utils.h, macosx/Torrent.mm, tests/libtransmission/announce-list-test.cc, tests/libtransmission/benc-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/torrents-test.cc, tests/libtransmission/utils-test.cc, utils/create.cc, utils/remote.cc, utils/show.cc
Use `fmt::format()` instead of `tr_strvJoin()`.
=> refactor: remove tr_strvJoin()

libtransmission/announcer.cc, libtransmission/handshake.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/ptrarray.cc, libtransmission/ptrarray.h, libtransmission/rpc-server.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/tr-macros.h, libtransmission/tr-utp.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/webseed.cc, tests/libtransmission/utils-test.cc
remove unused macros from `libtransmission/tr-macros.h`
=> refactor: remove unused macros

libtransmission/block-info.cc, libtransmission/block-info.h, libtransmission/completion.cc, libtransmission/completion.h, libtransmission/files.h, libtransmission/inout.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, tests/libtransmission/block-info-test.cc, tests/libtransmission/completion-test.cc, tests/libtransmission/file-piece-map-test.cc
*    refactor: make all tr_block_info fields private
*    refactor: make some tr_block_info methods private
*    refactor: remove unused tr_block_info methods
* `noexcept` correctness
=> refactor: tr_block_info

daemon/daemon.cc, libtransmission/log.cc, libtransmission/port-forwarding.cc, libtransmission/upnp.cc
=> fixup: minor log string formatting changes

code_style.sh
Our CI targets clang-format version 12 and other versions give slightly different results, so prefer `clang-format-12` if it's installed.
=> build: try clang-format-12 in code_style

libtransmission/torrent.cc
=> fix: do not load magnet file resume files

libtransmission/resume.cc
=> fix: when loading resume state, load filenames before mtimes

gtk/MainWindow.cc, gtk/TorrentCellRenderer.cc
Fix a couple more regressions from fcc1510ecb
=> fix: cell-renderer up/down ui layout order

libtransmission/webseed.cc
=> fix: corruption when downloading webseeds

libtransmission/file-piece-map.cc
=> perf: faster file priorities

libtransmission/bitfield.cc
=> perf: limit the scope of bitfield assertions

libtransmission/peer-mgr.cc
Preferring vector over map for cases where the number of items is very small
=> refactor: add Handshakes helper class in peer-mgr

.gitmodules, CMakeLists.txt, cmake/FindDEFLATE.cmake
=> deps: update libdeflate to v1.10

libtransmission/peer-mgr.cc
This removes one of the three remaining uses of `tr_ptrArray`. The goal is to finally get rid of `tr_ptrArray` and  use std tools instead.
=> refactor: make tr_swarm.peers a std::vector

.gitmodules
Fixes #2998. CC @mikedld @jech 
No code changes needed in libtransmission.
=> deps: update dht to 0.27

libtransmission/inout.cc
Previous commit which fixed one regression introduced a new one.
We really need some unit tests for this module
=> fixup! fix: ensure all bytes read / written to file (#2682)

libtransmission/open-files.h, libtransmission/torrent.cc
=> fixup: fix fd regression in tr_open_files

macosx/InfoActivityViewController.mm, macosx/InfoGeneralViewController.mm
Fixes a minor Xcode analyzer warning.
=> The left operand of '+' is a garbage value

libtransmission/open-files.h
All pull requests are failing their code style since #3036
=> Fix TeamCity Code Style

macosx/Torrent.mm
=> Support tr_sessionSet*

macosx/GroupsController.mm
Fix #3046.
Regression from #2973.
=> Fix retrieving groups with predicates

macosx/en.lproj/MainMenu.xib, macosx/fr.lproj/MainMenu.xib
=> Rename "Remove Data File" to "Trash Data File"

libtransmission/webseed.cc
=> fix: assertion failed: task->loc.byte <= task->end_byte

.gitmodules
Fixes https://github.com/transmission/transmission/issues/3132.
=> deps: use libdeflate 1.11

libtransmission/rpcimpl.cc
A minor cleanup refactor in rpcimpl.cc
=> refactor: prefer std::vector over raw array in torrentGet()

libtransmission/peer-mgr.cc
This code simplification is good on its own merits. It is also a _possible_ fix for #3153 but I'm not seeing the issue here so I'd appreciate feedback on this aspect
=> refactor: simplify atom pruning

libtransmission/torrent-files.cc
fix for https://github.com/transmission/transmission/issues/3085 and possibly https://github.com/transmission/transmission/issues/2379
=> fix removal of torrent files with a folder structure

libtransmission/torrent-metainfo.cc
=> fix: 'unexpected filehash' warning

libtransmission/variant-json.cc, macosx/PrefsController.mm, macosx/StatsWindowController.mm
One unused variable, one string format warning.
=> Silence Xcode warnings

libtransmission/peer-mgr.cc
Part 2 in a series of decoupling tr_peer from peer_atom. Part 1 was in #3175.
This PR removes the `peer_atom.peer` field, where peer was a pointer to the corresponding tr_peer.
=> refactor: remove peer_atom.peer field

libtransmission/peer-mgr.cc
more incremental progress towards decoupling tr_peer and peer_atom: this PR removes `peer_atom.shelfDate()` because it's not needed.
=> refactor: remove peer_atom.shelfDate()

gtk/FaviconCache.cc
=> fixup! fix: coverity warnings (#3168)

libtransmission/session.cc, libtransmission/utils.cc
=> fix: duplicate template instantiation on raspberry pi armv7

docs/rpc-spec.md
Fixes https://github.com/transmission/transmission/issues/3204
=> docs: fix documented type of rpc-version-semver

macosx/AddMagnetWindowController.mm, macosx/AddWindowController.mm, macosx/Controller.mm, macosx/CreatorWindowController.mm, macosx/MainWindow.h, macosx/MainWindow.mm, macosx/MessageWindowController.mm
removed fullscreen support, as it opens a can of worms trying to fully support it....
resolves https://github.com/transmission/transmission/issues/3215#issuecomment-1147477253
Fixes #3215.
=> macOS remove FullScreen support

docs/rpc-spec.md
=> docs: un-deprecate trackerAdd RPC

libtransmission/web.cc
Fixes #3242.
Introduced by #2693.
=> fix: deadlock between session and web mutexes

docs/rpc-spec.md, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/rpcimpl.cc
Fixes https://github.com/transmission/transmission/issues/2768.
=> feat: add rpc torrentGet.availability

libtransmission/inout.cc, libtransmission/magnet-metainfo.cc, libtransmission/peer-mgr.cc
fix a couple of warnings that are new to clang-15.
=> fix: clang-15 warnings

macosx/TrackerCell.mm
```objc
+ (NSData *)sendSynchronousRequest:(NSURLRequest *)request
returningResponse:(NSURLResponse * _Nullable *)response
error:(NSError * _Nullable *)error;
```
from `NSURLConnection` is deprecated on 10.11+
=> [macOS] Use DDG favicons service and migrate to NSURLSession

macosx/Controller.h, macosx/Controller.mm
=> [macOS] Fix global popover clipping.

macosx/ru.lproj/PrefsWindow.xib
Most of the changes are caused by Xcode touching XIB file.
Fixes #3284
=> [macOS] Update Preferences window sizing for Russian locale.

Transmission.xcodeproj/project.pbxproj
=> Roll libdeflate v1.12.

gtk/DetailsDialog.cc, gtk/StatsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h
Fixes #3214.
I'd like feedback from non-English speakers if possible on this one.
=> fix: add i18n options for past tense, future tense time

.github/workflows/actions.yml
does what it says on the tin: add another sanity CI job for building & testing with [musl](https://en.wikipedia.org/wiki/Musl)
=> build: add alpine/musl to github actions sanity

.github/workflows/actions.yml
- fix a bug I introduced into CI on Wednesday that broke tests.
- take the xcode project files into account when deciding what to CI jobs to run
=> build: fix sanity GitHub action

macosx/InfoFileViewController.mm
not sure why this wasn't connected up...
=> macOS fix quicklook in the Torrent Inspector files view

COPYING, cmake/Transmission.rc.in, gtk/Application.cc, gtk/Application.h, gtk/Dialogs.cc, gtk/Dialogs.h, gtk/main.cc, macosx/Info.plist, macosx/Info.plist.in, macosx/QuickLookPlugin/Info.plist.in, macosx/QuickLookPlugin/QuickLookPlugin-Info.plist, macosx/da.lproj/InfoPlist.strings, macosx/en.lproj/InfoPlist.strings, macosx/es.lproj/InfoPlist.strings, macosx/fr.lproj/InfoPlist.strings, macosx/it.lproj/InfoPlist.strings, macosx/nl.lproj/InfoPlist.strings, macosx/pt_PT.lproj/InfoPlist.strings, macosx/ru.lproj/InfoPlist.strings, macosx/tr.lproj/InfoPlist.strings, qt/LicenseDialog.ui
Must be done before 4.0.0 release.
=> Update Copyright Year to 2022.

macosx/Controller.mm
=> macOS fix quicklook toolbar icon status

gtk/DetailsDialog.cc, libtransmission/bandwidth.h, libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/transmission.h, libtransmission/webseed.cc
Replace `tr_peerMsgs.pendingReqsToClient()` with `tr_peer.activeReqCount()`.
=> refactor: add tr_peer.activeReqCount()

.github/workflows/actions.yml
I thought I fixed this once before?
=> build: re-fix the naming of workflow triggers

macosx/Controller.mm
=> [macOS] Use NSAlert APIs to show alert suppression checkbox

libtransmission/block-info.h, libtransmission/completion.cc, libtransmission/completion.h, tests/libtransmission/completion-test.cc
=> fix: assertion failed "s->leftUntilDone <= s->sizeWhenDone"

libtransmission/torrent-magnet.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/torrent-metainfo-test.cc
Fix a few minor compiler warnings. No functional changes.
=> fix: minor warnings

.gitmodules, CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, cmake/TrMacros.cmake, libtransmission/net.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-utp.cc, libtransmission/tr-utp.h
Fixes #2996.
CC @mikedld 
I think it might make sense to merge this into `main` to get some wider testing?
=> Update libutp to 3.4+ (TRAC-5888)

libtransmission/announcer-http.cc, libtransmission/blocklist.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/peer-socket.h, libtransmission/port-forwarding.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-dht.cc, libtransmission/tr-dht.h, libtransmission/tr-udp.cc, libtransmission/tr-utp.cc, libtransmission/upnp.cc, libtransmission/upnp.h, libtransmission/web-utils.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/peer-msgs-test.cc
This reverts commit 9a44eeaa2759413749dae1fc1183c29de1542304.
=> fix: revert "refactor: tr_address cleanup (#3422)"

macosx/Controller.mm
=> use the default toolbar button size on macOS 11+

libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/transmission.h
No functional changes; just removing a few unused fields.
=> refactor: remove unused tr_stat fields

macosx/Base.lproj/InfoActivityView.xib, macosx/Base.lproj/InfoOptionsView.xib
=> macOS fix some autolayout issues in Info window

macosx/Base.lproj/PrefsWindow.xib, macosx/da.lproj/Localizable.strings, macosx/en.lproj/Localizable.strings, macosx/es.lproj/Localizable.strings, macosx/it.lproj/Localizable.strings, macosx/nl.lproj/Localizable.strings, macosx/ru.lproj/Localizable.strings, macosx/tr.lproj/Localizable.strings
=> macOS preference window localization autolayout fixes

daemon/daemon.cc, gtk/Application.cc, gtk/Session.cc, gtk/Session.h, libtransmission/platform.cc, libtransmission/platform.h, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/stats.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/transmission.h, tests/libtransmission/blocklist-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/move-test.cc
Fixes #3508.
I don't know the root cause of the bug, but it's nasty enough that it's better to revert now and figure it out later. That way nightly users won't get bitten.
=> fix: 3508 location invalidation

macosx/CMakeLists.txt
=> Adjust CMake configs for Mac base internationalization

libtransmission/torrent-magnet.cc
When tracking which metadata pieces we need, use `std::vector` and `std::deque` instead of allocating raw pointers and managing memory ourselves. The old approach was a leftover from when libtransmission was written in C.
=> refactor: use STL containers in torrent-magnet.cc

cli/cli.cc, gtk/FileList.cc, libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/bitfield.cc, libtransmission/blocklist.cc, libtransmission/clients.cc, libtransmission/platform-quota.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/variant-json.cc, libtransmission/watchdir-win32.cc, libtransmission/watchdir.cc, libtransmission/web-utils.cc, qt/DetailsDialog.h
=> chore: iwyu cstring, cstdlib, optional, unordered_set

libtransmission/peer-mgr.cc
Another minor C++ification PR that does what it says on the tin.
=> refactor: use std::sort() in rechokeDownloads()

macosx/Base.lproj/InfoOptionsView.xib
=> macOS autolayout fixes on Inspector - Options tab

gtk/Session.cc, libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/announcer-common.h, libtransmission/announcer-udp.cc, libtransmission/clients.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/file-posix.cc, libtransmission/file.h, libtransmission/makemeta.h, libtransmission/net.cc, libtransmission/rpc-server.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.h, libtransmission/web-utils.h
=> refactor: fix recent sonarcloud warnings

libtransmission/torrent-metainfo.cc, tests/libtransmission/torrent-metainfo-test.cc
=> Fix out-of-bounds read in torrent parsing

daemon/daemon.cc, gtk/MessageLogWindow.cc, libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/log.cc, libtransmission/log.h, libtransmission/natpmp.cc, libtransmission/natpmp_local.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/port-forwarding.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent-magnet.cc, libtransmission/torrent-magnet.h, libtransmission/torrent.cc, macosx/MessageWindowController.mm
Removing the final pieces of code that haven't migrated to C++ memory management
=> refactor: remove tr_new, tr_free pt. 1

libtransmission/session.cc, libtransmission/session.h
Possible fix for #3628.
I haven't been able to reproduce the crash & so I can't confirm the fix firsthand, but I believe I see the cause; and if I'm seeing the _right_ cause, this should fix the issue :slightly_smiling_face:
=> fix: tr_session field order

libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent-ctor.cc, libtransmission/torrent-magnet.cc, libtransmission/tr-utp.cc, libtransmission/transmission.h
No functional changes; just baby steps towards encapsulating pieces of tr_session.
=> refactor: make tr_session.is_closing_private_

macosx/PiecesView.mm
Resolves https://github.com/transmission/transmission/issues/3660
=> For some reason self.fPieces.resize() won't work but _fPieces.resize() will

news/news-4.0.0-beta-1.md
still needs more work, but it is tiring work so here is forward progress :sleepy:
=> docs: update 4.0.0-beta.1 release notes

libtransmission/.clang-tidy, libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/completion.cc, libtransmission/net.cc, libtransmission/peer-msgs.cc, libtransmission/rpc-server.cc, libtransmission/subprocess-posix.cc, libtransmission/tr-dht.cc, libtransmission/tr-getopt.cc, libtransmission/upnp.cc, libtransmission/utils.cc
=> refactor: modernize-avoid-c-arrays pt. 2

libtransmission/cache.cc
=> fixup! refactor: modernize cache.cc (#3108)

libtransmission/torrent-magnet.cc, tests/libtransmission/torrent-magnet-test.cc
Add tests for `tr_torrentGetMetadataPiece()`.
=> test: add torrent-magnet tests

gtk/Application.cc, libtransmission/interned-string.h, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/variant.cc, qt/RpcClient.cc, qt/Session.cc, tests/libtransmission/quark-test.cc
=> refactor: remove tr_quark_get_string()

libtransmission/handshake.cc, libtransmission/session.h, libtransmission/stats.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/web-utils.cc
Make more simple functions `constexpr` where possible.
=> refactor: more constexpr

libtransmission/announcer-http.cc
=> refactor: reduce http announce timeout interval to 45 seconds

libtransmission/peer-mgr.cc
It's a small thing but it adds up in profiles when you've got a lot of torrents. Previously was checked every time we refilled the bandwidth allocations -- every half-second -- which is unnecessarily often.
=> perf: check torrrent seed ratio less frequently

libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/file.h, tests/libtransmission/blocklist-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/test-fixtures.h
some minor code refactors in file-*.cc, but mostly just testing + removing a few logic branches.
=> test: improve file-win32, file-posix test coverage

libtransmission/handshake.cc, libtransmission/peer-msgs.cc, libtransmission/tr-lpd.cc, libtransmission/tr-macros.h
this code needs to be redone and has been commented out forever; this PR removes it.
=> chore: remove dead "fast set" code

daemon/daemon.cc
Fold common daemon code into `Daemon` class, adjust related bits.
Signed-off-by: Dmitry Antipov dantipov@cloudlinux.com
=> refactor: fold common daemon code into C++ class

libtransmission/tr-dht.cc
Fix the following `clang-tidy` noise:
```
libtransmission/tr-dht.cc:56:8: warning: do not declare C-style
arrays, use std::array<> instead [modernize-avoid-c-arrays]
static unsigned char myid[20];
^
```
=> refactor: prefer std::array over plain C array

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/cache.cc, libtransmission/cache.h, libtransmission/handshake.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.h, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-dht.h, libtransmission/tr-udp.cc, libtransmission/tr-udp.h, libtransmission/tr-utp.cc, libtransmission/transmission.h, libtransmission/upnp.cc, libtransmission/variant-json.cc, libtransmission/webseed.cc
Fix some sonarcloud warnings that function arguments could be made const.
=> refactor: constify

daemon/daemon-posix.cc
If `signalfd(2)` interface is not available (i.e. everywhere except Linux), use `evsignal` interface to manage signals.
=> daemon: use evsignal-based signal handling on POSIX systems

libtransmission/crypto-utils.h, libtransmission/makemeta.h, libtransmission/net.h, libtransmission/peer-mgr.h, libtransmission/variant-common.h, libtransmission/variant.h, libtransmission/watchdir.h, libtransmission/web-utils.h, tests/libtransmission/web-utils-test.cc
does what it says on the tin: add `[[nodiscard]]` to various private libtransmission headers
=> refactor: add [[nodiscard]]

daemon/daemon-posix.cc, daemon/daemon-win32.cc, daemon/daemon.cc, daemon/daemon.h
Get rid of C-style callbacks on void pointers and convert (well, the most of) daemon code to (somewhat more) real C++, adjust related bits.
NOTE: I'm not an expert in Windows and this code was the very preliminary tested with `MinGW` only.
=> refactor: add more C++ glue for the daemon

libtransmission/peer-msgs.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-dht.cc, libtransmission/tr-dht.h, libtransmission/tr-udp.cc
Fixes #3847.
There is still more work to be done on the clearinghouse of issues that @Coeur listed in 3847 but here's a down payment :smile_cat:
=> fix: #3847 crash on session close

libtransmission/tr-dht.cc
=> Fix TR_ASSERT equality

libtransmission/announcer.cc, libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/port-forwarding.h, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/tr-lpd.h, libtransmission/tr-utp.cc, libtransmission/watchdir-base.h, libtransmission/watchdir-generic.cc, libtransmission/watchdir.cc, libtransmission/watchdir.h, libtransmission/webseed.cc, tests/libtransmission/handshake-test.cc, tests/libtransmission/lpd-test.cc
Add a mediator class to decouple `tr_port_forwarding` from `tr_session`
=> refactor: add tr_port_forwarding::Mediator

libtransmission/tr-dht.cc
=> fixup: new dht bootstrap regression

libtransmission/tr-dht.cc
=> fix: dht bootstrap regression

macosx/Torrent.mm
Fix #3880.
Fix #3882.
The author of #3871 (@Harm133) might be preparing a proper fix (for #101), but in the mean time, it's clearly a major issue, so I'd adopt this rollback.
=> Rollback #3871

macosx/Controller.mm
=> Sort order by activity is reversed

libtransmission/inout.cc
Fix minor runtime undefined behaviour.
=> Fix "Nullptr with nonzero offset"

Transmission.xcodeproj/project.pbxproj
watchdir-common.h was deleted in #3606
=> Fix red link in Xcode project

gtk/MessageLogWindow.cc
=> Don't scroll to message log bottom with no messages (GTK client)

libtransmission/announcer-udp.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/session.cc, libtransmission/tr-macros.h, libtransmission/tr-utp.cc, tests/libtransmission/CMakeLists.txt, tests/libtransmission/net-test.cc
Add `tr_address::fromSockaddr()` and add tests.
=> refactor: add tr_address::fromSockaddr()

gtk/ui/gtk3/MainWindow.ui, gtk/ui/gtk3/MessageLogWindow.ui, gtk/ui/gtk4/MessageLogWindow.ui
=> Increase message log window width, disable overflow menu (GTK client)

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/dns-ev.h, libtransmission/dns.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/timer-ev.h, tests/libtransmission/CMakeLists.txt, tests/libtransmission/dns-test.cc
make a DNS interface class to make announcer-udp more testable
=> refactor: add dns interface class

docs/Building-Transmission.md
Thanks @nevack and @GaryElshaw for figuring out the steps.
=> doc: Building the GTK app on macOS

gtk/TorrentCellRenderer.cc, gtk/TorrentCellRenderer.h, gtk/Utils.h
The change came out to be slightly bigger that expected. Despite kinda working, it also doesn't feel like the prettiest piece of code...
Fixes: #1998
=> Change progress bar color depending on torrent state (GTK client)

utils/create.cc
Now it should be fine when generating the gettext file.
Fixes #3995
=> Swapped plural and singular positions

gtk/Notify.cc
GLIBMM will catch them for us, but in two cases print a warning instead of suppressing, and in one other case still print a warning (as well as we do) but without context.
=> Catch dbus exceptions in async callbacks on completion (GTK client)

gtk/OptionsDialog.cc, gtk/Session.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/transmission.h, macosx/Torrent.mm, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/rpc-test.cc
=> Add user data parameter for torrent removal callback

libtransmission/cache.cc, libtransmission/cache.h, libtransmission/peer-io.cc, libtransmission/peer-msgs.cc
=> fix: crash when a torrent autopauses after encountering an error

libtransmission/announcer-udp.cc
=> fix: crash on large UDP announce response

Transmission.xcodeproj/project.pbxproj
Fix minor regression from #3986, but that duplicate ID was causing side-effects each time we were editing project settings.
=> Fix tr-buffer.h has same ID as tr-utp.h

gtk/DetailsDialog.cc, gtk/Session.h, libtransmission/peer-io.cc, libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent.cc
12e56409 uncovered some more signed-unsigned warnings, so fix this second round too.
=> fix: recent signed-unsigned comparison warnings

Transmission.xcodeproj/project.pbxproj, libtransmission/net.cc, libtransmission/rpc-server.cc, libtransmission/session-alt-speeds.cc, libtransmission/session-settings.cc
=> warning: empty expression statement has no effect

libtransmission/blocklist.cc
fixes #3969
~this PR provides a quick fix, but perhaps is not the best fix... maybe someone with more c++ knowledge can fix the underlying issue with the assert
@ckerr any ideas~
=> fix crash when updating blocklist

gtk/Session.cc
The method never returns `nullptr`, but instead throws if an error occurs. This regressed during the switch from GTK to GTKMM.
Fixes: #4076
=> Adjust `Gio::File::query_info()` error handling (GTK client)

libtransmission/variant.cc, macosx/NSStringAdditions.mm
This change will also have the benefit to reduce the number of strings to localize once @mikedld sync the translations again.
=> removing unreachable code

libtransmission/torrent.cc, libtransmission/transmission.h
=> Declare TR_ETA_NOT_AVAIL as time_t

libtransmission/bandwidth.h, libtransmission/block-info.h, libtransmission/history.h, libtransmission/interned-string.h, libtransmission/peer-common.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/platform.h, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session.h, libtransmission/timer-ev.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/utils.cc, libtransmission/variant-common.h, libtransmission/variant.cc, libtransmission/variant.h
Should be no behavioral changes; this just adds `[[nodiscard]]`, `constexpr`, and `noexcept` where appropriate.
=> refactor: add more nodiscard, constexpr, and noexcept

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/session-thread.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/timer-ev.cc, libtransmission/tr-buffer.h, libtransmission/tr-lpd.cc, libtransmission/tr-udp.cc, libtransmission/utils-ev.h, libtransmission/watchdir-kqueue.cc, libtransmission/web.cc, libtransmission/webseed.cc
Add helpers to wrap libevent objects inside `std::unique_ptr`s
=> refactor: add libtransmission::evhelpers

macosx/Controller.mm, macosx/Torrent.h, macosx/Torrent.mm
Fix: #101
Simplified code change of the solution found by @Harm133 in #3922.
=> feat: Align active filter macOS

libtransmission/peer-mgr.cc, libtransmission/timer-ev.cc, tests/libtransmission/CMakeLists.txt, tests/libtransmission/test-fixtures.h, tests/libtransmission/timer-test.cc
Add tests for libtransmission::Timer.
*edit:* fixes #4117
=> test: add libtransmission::Timer tests

libtransmission/file.h
Fix #3942 based on @kelbon feedback.
=> Remove std::enable_if<std::is_member_function_pointer>

macosx/PortChecker.h, macosx/PortChecker.mm, macosx/PrefsController.mm
Problem: NSURLConnection is deprecated since macOS 10.11
Solution: Use NSURLSession
=> Fix NSURLConnection is deprecated - Use NSURLSession

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
Hi `transmission/transmission`!
This is not an automatic, 🤖-generated PR, as you can check in my [GitHub profile](https://github.com/Kwstubbs), I work for GitHub and I am part of the [GitHub Security Lab](https://securitylab.github.com/) which is helping out with the migration of LGTM configurations to Code Scanning.
You might have heard that we've integrated LGTM's underlying CodeQL analysis engine natively into GitHub. The result is [__GitHub code scanning__](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning)!
With LGTM fully integrated into code scanning, we are focused on improving CodeQL within the native GitHub code scanning experience. In order to take advantage of current and future …
=> Add CodeQL workflow

.github/workflows/actions.yml, CMakeLists.txt, macosx/CMakeLists.txt
=> Fix default/minimum `CMAKE_OSX_DEPLOYMENT_TARGET` handling

macosx/Base.lproj/Creator.xib, macosx/CreatorWindowController.mm
Fix a UI glitch when you attempt to set piece size too high or too low.
=> Fix create torrent out-of-range piece size

libtransmission/rpcimpl.cc
Fixes https://github.com/transmission/transmission/issues/3931
=> fix: 4.0.0-beta.1 wrong RPC response for group-get

libtransmission/rpc-server.cc
=> fixup! refactor: decouple session settings from the session class (#4053)

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/announcer-udp.cc, libtransmission/announcer.h, libtransmission/dns-ev.h, libtransmission/dns.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/dns-test.cc, tests/libtransmission/net-test.cc, tests/libtransmission/settings-test.cc
=> perf: revert e065565cd to restore async dns lookups

libtransmission/peer-io.cc, libtransmission/peer-io.h
=> fix: nullptr crash in peer-io

macosx/Torrent.mm
Fix #420.
The hang just happened to me after a system update, as possibly this is a situation when many apps and files are updating their time machine exclusions.
```
11  -[Controller awakeFromNib] + 2276 (Controller.mm:735,28 in Transmission + 71824) [0x1040bd890] 1-11
11  -[Torrent initWithTorrentStruct:location:lib:] + 48 (Torrent.mm:123,12 in Transmission + 444768) [0x104118960] 1-11
11  -[Torrent initWithPath:hash:torrentStruct:magnetAddress:lib:groupValue:removeWhenFinishSeeding:downloadFolder:legacyIncompleteFolder:] + 644 (Torrent.mm:1776,5 in Transmission + 472464) [0x10411f590] 1-11
11  -[Torrent setTimeMachineExclude:] + 84 (Torrent.mm:2097,9 in Transmission + 479732) [0x1041211f4] 1-11
11  CSBackupSetItemExcluded + 588 (CarbonCore + 59016) [0x1877b1688] 1-11
11 …
```
=> Fix hang in CSBackupSetItemExcluded

macosx/PrefsController.mm
This change is retro-compatible with the deprecated password API.
=> fix: SecKeychain is deprecated

libtransmission/bitfield.cc, libtransmission/bitfield.h, libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/webseed.cc, tests/libtransmission/bitfield-test.cc
Use a bitwise-or of the peer bitfields to build tr_stat.desiredAvailable
=> perf: improve tr_peerMgrGetDesiredAvailable()

news/news-4.0.0-beta-1.md
=> Name correction

macosx/Controller.mm, macosx/FilterBarController.h, macosx/FilterBarController.mm
=> Fix deleting previously selected torrent when trying to clear search field using Command + Delete

macosx/Controller.mm, macosx/Torrent.mm
Some minor code simplification
=> refactor: Use getIndexes:maxCount:inIndexRange: directly

libtransmission/rpc-server.cc
=> fix: potentially incorrect error message in rpc-server whitelist

libtransmission/announcer.cc, libtransmission/clients.cc, qt/Prefs.cc
Use structured binding declarations.
=> fix: sonarcloud cpp:S6005

libtransmission/clients.cc, libtransmission/handshake.cc, libtransmission/magnet-metainfo.cc, libtransmission/peer-msgs.cc, libtransmission/platform.cc, libtransmission/quark.cc, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-magnet.cc, libtransmission/tr-lpd.cc, libtransmission/utils.cc, libtransmission/variant.cc, libtransmission/verify.cc, qt/DBusInteropHelper.cc, qt/FilterBar.cc, utils/remote.cc, utils/show.cc
reduce scope of variables by using if-based initializer
=> fix: sonarcloud cpp:S6004

libtransmission/peer-msgs.cc
Fixes https://github.com/transmission/transmission/issues/4046.
=> refactor: do not report peer EOF as an error

libtransmission/handshake.cc, libtransmission/peer-msgs.cc
=> refactor: avoid double logging of libevent errors

gtk/FaviconCache.cc
=> fixup! refactor: GTK favicon lookup improvements (#4278)

libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, tests/libtransmission/handshake-test.cc
=> refactor: stop tracking peerIo creation time

libtransmission/bitfield.cc
=> Fixed crash in tr_bitfield::operator|= range

docs/Building-Transmission.md
Are the old instructions still valid or can they be deleted?
=> Add windows build manual

gtk/Session.cc
Akin to #4079, handle the potential Glib exception.
Notes: Fixed `4.0.0-beta.1` regression leading to potential crash on startup upon watch directory setup.
=> Improve error handling upon watch directory setup

macosx/AddMagnetWindowController.mm, macosx/Base.lproj/AddMagnetWindow.xib
Notes: unneeded layout code removed from AddMagnetWindow
originally a part of #4366 but moved here into its own PR as I feel it deserves its own PR
=> removed redunant code from AddMagnetWindow

libtransmission/session.cc, libtransmission/session.h
=> fix: tear down utp _after_ peer-mgr

CMakeLists.txt, cli/CMakeLists.txt, daemon/CMakeLists.txt, gtk/CMakeLists.txt, libtransmission/CMakeLists.txt, qt/CMakeLists.txt, tests/libtransmission/CMakeLists.txt, utils/CMakeLists.txt
Use the opportunity to reduce duplication.
=> Use C++ (not C) flags for GTK client

gtk/Utils.cc, gtk/Utils.h, libtransmission/log.cc, libtransmission/log.h, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/transmission.h
Remove unused functions found by https://github.com/mgehre/xunused
=> refactor: xunused

macosx/Base.lproj/MainMenu.xib, macosx/Controller.mm
=> macOS remove defunct  share code

macosx/PiecesView.mm
=> Addressed lockFocus is deprecated

macosx/CMakeLists.txt
Follow up of #4417, as it seems I forgot one missing file.
=> Add missing GroupTextCell.h

macosx/StatsWindow.xib, macosx/StatsWindowController.mm
=> macOS - use autolayout in statistics view

libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, tests/libtransmission/crypto-test-ref.h
=> refactor: possible FTBFS fix on arm7

libtransmission/tr-udp.cc
Minor code simplification in `tr_udp_core::sendto()`
=> refactor: simplify tr_udp_core::sendto()

libtransmission/announcer-udp.cc, libtransmission/web.cc, libtransmission/webseed.cc
Minor refactor: add `constexpr` to some functions
=> refactor: add constexpr

libtransmission/utils.cc
Since operators were intentionally implicit and we don't want to add more `NOLINT` comments than necessary, rework the approach to deduce the argument type instead and cast to it.
=> Fix clang-tidy issue in `iconv` 2nd argument helper

libtransmission/tr-udp.cc
=> fix: Couldnt send to IPv6 address warnings

CMakeLists.txt, news/news-4.0.0-beta-3.md
- update release notes
- update version number
=> chore: 4.0.0-beta.3

libtransmission/web.cc
Fixes #4595.
Notes: Only download from webseed servers that support [Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) requests with [206 Partial Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206).
=> fix: handle webseed servers that do not serve partial content

libtransmission/announcer-http.cc, libtransmission/announcer.h, libtransmission/bitfield.cc, libtransmission/cache.cc, libtransmission/crypto-utils-ccrypto.cc, libtransmission/crypto-utils-fallback.cc, libtransmission/crypto-utils-mbedtls.cc, libtransmission/crypto-utils-wolfssl.cc, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/file-piece-map.cc, libtransmission/handshake.cc, libtransmission/inout.cc, libtransmission/log.cc, libtransmission/magnet-metainfo.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/rpcimpl.h, libtransmission/session.cc, libtransmission/torrent.h, libtransmission/tr-macros.h, libtransmission/transmission.h, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.h, libtransmission/web.cc, libtransmission/webseed.cc
No functional changes, literally just updating comment style.
=> style: use the new paragraph comment style everywhere

libtransmission/net.cc, qt/Application.cc, qt/FileTreeDelegate.cc, tests/libtransmission/announcer-udp-test.cc, utils/remote.cc
fix a handful of msvc warnings.
=> fix: msvc warnings

.github/workflows/actions.yml, code_style.sh, web/CMakeLists.txt, web/package-lock.json, web/package.json
Another transmission-app.js build cleanup PR.
=> build: minor ci cleanup

libtransmission/error.cc, libtransmission/error.h, libtransmission/file-posix.cc, libtransmission/makemeta.cc, libtransmission/makemeta.h, libtransmission/peer-io.cc, libtransmission/peer-socket.cc, libtransmission/tr-buffer.h
=> refactor: add tr_error_set_from_errno()

.github/workflows/actions.yml, CMakeLists.txt
=> fix: detect NPM version for ENABLE_WEB in cmake

libtransmission/announcer-udp.cc, libtransmission/handshake.cc, libtransmission/peer-common.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-msgs.cc, libtransmission/peer-socket.cc, libtransmission/tr-buffer.h, libtransmission/variant-benc.cc, libtransmission/variant-common.h, libtransmission/variant-json.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/buffer-test.cc
A minor snake_case refactor I did while investigating something else.
Eventually all the libtransmission methods will be snake_case.
=> refactor: buffer snake case

libtransmission/.clang-tidy, libtransmission/announcer.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/file-posix.cc, libtransmission/net.cc, libtransmission/platform-quota.cc, libtransmission/rpc-server.cc, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/tr-utp.cc, libtransmission/transmission.h, libtransmission/variant.cc, libtransmission/watchdir.cc, libtransmission/watchdir.h, libtransmission/web.cc
fix some c-style cast warnings in libtransmission.
=> fix: cppcoreguidelines-pro-type-cstyle-cast

gtk/TorrentCellRenderer.cc
I remember seeing better results when adding background during hue adjustment, but can't clearly see the difference now. Since using `DEST_OVER` Cairo operator results in crashes on some systems, don't bother with the background, hopefully still getting acceptable results.
Fixes: #4075
Notes: Fixed `4.0.0-beta.2` regression leading to crash during progress bars rendering on some systems.
=> Simplify progress bars coloring (GTK client)

libtransmission/torrent.cc
=> fix: call setHasPiece(piece, false) on checkPiece fail

web/src/utils.js
Fixes #4830.
Notes: Fixed `4.0.0` bug that failed to apply display settings changes immediately.
=> fix: incorrect debounce arguments

CMakeLists.txt, libtransmission/CMakeLists.txt
Fixes build on NetBSD.
Notes: Fixed `4.0.0` FTBFS on NetBSD.
=> fix: look for libquota and use it

qt/MainWindow.cc
Fixes #1978.
Notes: Fixed "Open Folder" feature for local sessions.
=> fix: open-folder does not work in qt client

CMakeLists.txt, web/CMakeLists.txt
=> build: add option to disable installation of web assets

web/assets/css/transmission-app.scss, web/src/overflow-menu.js
Fixes https://github.com/transmission/transmission/issues/5000.
=> fix: padding in overflow menu

macosx/Base.lproj/PrefsWindow.xib
=> fix: Adjust sizes to fix Call Script control cutoff.

web/src/prefs-dialog.js
Fixes #5009.
Notes: Fixed `4.0.0` bug that that failed to save alternate speed begin/end settings changes
=> fix: alt speed schedule not saved in web ui

macosx/PrefsController.mm, macosx/en.lproj/Localizable.strings
=> fix: Add tooltip explaining why auto adding for magnets is unavailable.

libtransmission/session.cc, libtransmission/torrent-metainfo.cc
Fixes #5007.
Notes: Fixed `4.0.0` bug where some torrents thought they were magnet links.
=> fix: some torrents think they are magnets

macosx/Base.lproj/InfoActivityView.xib
=> Set fPiecesControl segmentDistribution to fillProportionally

utils/remote.cc
=> fix: transmission-remote warning when adding magnet link

libtransmission/torrent.cc, libtransmission/torrent.h
=> recheckCompleteness on setDownloadDir

qt/MainWindow.cc
=> fix: 4981 open folder should open selected folder

macosx/FilePriorityCell.mm, macosx/TorrentCell.mm
This is a best guess attempt to fix #5077.
I do not know if it will have any impact for @AWHubGit. The best thing would be for them to try this change and give us feedback if it had any impact.
=> fix: complete copyWithZone for TorrentCell

libtransmission/peer-msgs.cc, libtransmission/tr-buffer.h
related to #5081.
Notes: Fixed assertion failure in `readBtPiece()`.
=> fix: assertion failure in readBtPiece()

libtransmission/web.cc
Fixes #5141 by ensuring that curl easy handles are removed from the 'paused handles' container when a task finishes.
Notes: Fixed `4.0.0` crash when downloading from too many webseeds.
=> fix: crash in curl_easy_pause()

README.md
Hi,
just a minor change in the README.
Have a nice week
midzer
=> docs: improve build instructions

libtransmission/web-utils.cc, tests/libtransmission/web-utils-test.cc
Fixes #5148.
Notes: Fixed display of IPv6 tracker URLs.
=> fix: display of ipv6 tracker URLs

macosx/TorrentCell.mm
Fix #5128
(I put the label "good first issue" for two weeks... you all missed an opportunity :))
=> fix: "Unrecognized colorspace number -1"

news/news-4.0.2.md
https://github.com/transmission/transmission/blob/docs/4.0.2-release-notes/news/news-4.0.2.md
=> docs: add 4.0.2 release notes

.github/workflows/actions.yml, qt/DetailsDialog.cc
Fixes #5236.
Notes: Fixed `4.0.2` FTBFS on Ubuntu 20.04 / Qt 5.13.
=> fix: FTBFS in Ubuntu 20.04 / Qt 5.13

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/magnet-metainfo.h, libtransmission/torrent-metainfo.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/utils.mm, tests/libtransmission/utils-test.cc
=> fix: crash when magnet dn isn't utf-8

libtransmission/announcer.cc, qt/RpcClient.cc
=> fix: wrong tier value in torrent get tracker stat response

web/src/action-manager.js
=> fix: use a Verify keyboard shortcut that does not conflict with Paste

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h
Fixes #5255.
This has other refactors too & is not semver-patch.
=> fix: crash in peer stats

libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/cache.cc, libtransmission/cache.h, libtransmission/inout.cc, libtransmission/inout.h, libtransmission/torrent.cc
Hi,
great work on v4!
https://github.com/danmar/cppcheck found minor performance opportunities in the codebase: pass some variables by reference and not copy them. I have not done any benchmark comparison.
Have a nice week
midzer
=> perf: pass by reference

libtransmission/peer-msgs.cc
Write non-piece peer messages directly to the peer's outbuf instead of waiting for a pulse() message to refill it. This can help with latency sending messages out.
Change the semantics of `tr_peerIo::get_write_buffer_space()`: this is now interpreted as the preferred minimum size, rather than the maximum. It's OK to enqueue an outgoing piece message as long as there's _some_ space left, even if the message is larger than that space.
Build peer messages with template fold expressions. This lets us move all the message-building to a single function and add some sanity checks to the outgoing messages.
Notes: Slightly reduced latency when sending protocol messages to peers.
=> perf: remove staging step for outbound peer msgs

libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-msgs.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-udp.cc
As suggested by @tearfur
Xref: https://github.com/transmission/transmission/pull/5329#discussion_r1166236165
=> refactor: add tr_address::is_any()

libtransmission/peer-msgs.cc
re-apply 47001a3 which got lost when e91af269, which predated it, was merged. Only affects `main` branch.
Fixes #5422.
=> fix: 5422 use-after-free in peerMsgs::canRead

web/src/inspector.js
Fixes #5459.
Notes: Fixes `null` tier name in the inspector's tier list.
=> fix: null tier name in inspector list

macosx/BlocklistScheduler.h
Fixes building on case sensitive systems
=> fix: wrong case in AppKit.h

web/assets/css/transmission-app.scss, web/src/torrent-row.js
addresses majority of suggetions in #5448
=> web client: edit some style and add space

web/assets/css/transmission-app.scss, web/src/action-manager.js, web/src/overflow-menu.js, web/src/prefs.js, web/src/transmission.js
An addition of two theme focused on hight contrast.
It gets the user value of prefers-contrast setting then setup the default value in the transmission cookie/prefs. A switch in the burger nav allow the user to switch it later off/on.
=> feat: high-contrast theme for web ui

macosx/Controller.mm, macosx/InfoTrackersViewController.mm, macosx/Torrent.mm
Fix some trivial grammar errors and typos in macOS codebase.
=> Typos in macosx

qt/TorrentDelegateMin.cc
matches GTK client behavior
Fixes #5483.
=> fix: show magnet name in compact mode

docs/Translating.md
See https://help.transifex.com/en/articles/7171815-web-application-s-domain-change
=> docs: update translation site names

tests/libtransmission/global-ip-cache-test.cc
fix -Wexit-time-destructors warnings
=> fixup! feat: add global IP cache, fix UDP connection failure warnings

libtransmission/announcer-udp.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mse.h, libtransmission/peer-msgs.cc, libtransmission/peer-socket.cc, libtransmission/tr-buffer.h, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/buffer-test.cc
No functional changes, just simplifying the Buffer class structure a little bit in preparation for the upcoming evbuffer -> sfl::small_vector migration.
=> refactor: add BufferReader, BufferWriter::reserve_space()

utils/remote.cc
=> fix: some labels not displayed in transmission-remote

utils/remote.cc
Fixes: https://github.com/transmission/transmission/issues/5571
=> fix: transmission-remote only list every other label (fixes #5571)

code_style.sh, libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, tests/libtransmission/handshake-test.cc
=> Identify atoms by address and port in swarm

utils/remote.cc
=> fix: add 'years' and 'Infinity' to ETA in transmission-remote

libtransmission/announcer-udp.cc, libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr-active-requests.cc, libtransmission/peer-mgr-wishlist.h, libtransmission/peer-msgs.cc, libtransmission/peer-socket.cc, libtransmission/peer-socket.h, libtransmission/tr-buffer.h, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, libtransmission/web.h, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/buffer-test.cc
Apparently this isn't ready for prime time yet; it's causing a regression in peer connections. I'll work on this some more.
=> chore: revert small buffer

libtransmission/global-ip-cache.cc
No functional changes intended.
=> refactor: global-ip-cache.cc nits

libtransmission/net.cc
Following up https://github.com/transmission/transmission/issues/5610#issuecomment-1599316348
=> perf: improve IPv4 `tr_address` comparison

qt/FileTreeView.cc, qt/MainWindow.cc, qt/RpcQueue.cc, qt/RpcQueue.h
refactor: prefer std::pair over QPair
=> refactor: prefer std::queue over QQueue

libtransmission/global-ip-cache.cc
=> fix: assert failure when Transmission quit with pending IP queries

libtransmission/peer-mgr.cc
Addresses https://github.com/transmission/transmission/pull/5723#discussion_r1252373679.
=> add constexpr to `peer_atom` methods

cli/cli.cc, daemon/daemon.cc, gtk/main.cc, libtransmission/session-thread.cc, libtransmission/tr-lpd.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/watchdir-win32.cc, libtransmission/web.cc, macosx/main.mm, qt/Application.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/dht-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/watchdir-test.cc, utils/remote.cc, utils/show.cc
=> fix: conform to libcurl requirements to avoid memory leak

CMakeLists.txt, libtransmission/peer-mgr.cc
https://github.com/transmission/transmission/issues/5714 would be resolved by this **but** I'm avoiding the "fixes N" phrasing here because there are some other good ideas in that ticket and I don't want GitHub to autoclose it if this PR is merged.
CC @tearfur for review
=> perf: faster get peer candidates

libtransmission/announcer.cc, libtransmission/net.cc, libtransmission/peer-mgr-wishlist.cc, libtransmission/peer-mgr.cc, libtransmission/utils.h, libtransmission/verify.cc, tests/libtransmission/net-test.cc
This is a small templated utility function to make libtransmission's sorting / comparison code more consistent and easier to read.
=> refactor: add tr_compare_3way()

gtk/DetailsDialog.cc
=> Fix missing #include in DetailsDialog.cc

libtransmission/peer-mgr.cc, libtransmission/tr-buffer.h
fix: crash regression in tr_peerMgr::make_new_peer_connections()
Fixes #5744.
=> fixup! perf: faster get peer candidates (#5734)

libtransmission/global-ip-cache.cc
=> fix: incorret log message in `global-ip-cache.cc`

libtransmission/global-ip-cache.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-mgr.cc, libtransmission/peer-socket.cc, libtransmission/peer-socket.h, libtransmission/tr-dht.cc, libtransmission/tr-udp.cc, tests/libtransmission/dht-test.cc, tests/libtransmission/handshake-test.cc, tests/libtransmission/net-test.cc
Add helpers, e.g. display_name()
=> refactor: make tr_socket_address a class

libtransmission/peer-mgr.cc
Another "avoid unnecessary heap allocations" PR.
Previously we created a new vector for each swarm. This PR changes that to create a single vector that is reused as reconnectPulse() iterates through all the swarms in the session.
It also changes the type from `std::vector` to `small::vector` so that all work can be done on the stack unless there's an unusually large swarm.
=> perf: reuse the vector in receonnectPulse()

libtransmission/peer-mgr.cc
Notes: Improved libtransmission code to use less CPU.
=> perf: improve sorting performance in `tr_peerMgrGetPeers()`

libtransmission/benc.h, libtransmission/blocklist.h, libtransmission/peer-io.h
No other changes; just `constexpr`izing a few methods where possible.
=> refactor: make a few more methods `constexpr`

.github/workflows/actions.yml, libtransmission/variant.cc
reduce sizeof(VariantWalker)
Fixes #5815.
=> fixup! perf: use small::max_size_vector in tr_torrentGetMetadataPiece

libtransmission/tr-lpd.cc
Discovered at https://github.com/transmission/transmission/pull/5786#issuecomment-1651817655.
Notes: Fixed `4.0.0` bug where the port numbers in LDP announces are sometimes malformed.
=> fix: disregard locale when building LDP announce message

docs/Editing-Configuration-Files.md
=> add documentation for `watch-dir-force-generic`

libtransmission/torrent-magnet.cc
=> fixup! refactor: `tr_torrent.incompleteMetadata` from raw pointer to `std::optional`

libtransmission/peer-mgr.h
=> fix: incorrect pex flags merge logic

macosx/Base.lproj/MainMenu.xib, macosx/SmallTorrentCell.h, macosx/SmallTorrentCell.mm, macosx/TorrentCell.h, macosx/TorrentCell.mm
Fix #5826 (regression from #5147) - autolayout alternative to #5846
@couer, here's an alternative to your proposed fix (#5846), using auto layout...
I haven't added in your refactored TorrentCell and SmallTorrentCell - I figured you could maybe submit another PR for that (assuming this version is preferable to your solution)
=> regression fix: missing priority icon in torrent cell

docs/rpc-spec.md
=> add documentation for `session-id` rpc field

AUTHORS
=> add myself to AUTHORS

web/assets/css/transmission-app.scss, web/src/transmission.js, web/src/utils.js
Allows main menu accessible on smaller browser window.
Fixes #5299
Additional fix made for context menu.
=> WebUI: Fix overflow-menu and context-menu positioning for small viewports

web/src/action-manager.js, web/src/transmission.js
- Listen to K to edit labels, closes #5752
- Suppress keyboard shortcuts when on textarea field
=> WebUI: Listen to K to edit labels

gtk/Application.cc, gtk/FilterBar.cc, gtk/Utils.h, libtransmission/announcer.cc, libtransmission/file-capacity.cc, libtransmission/session.cc, libtransmission/tr-udp.cc, libtransmission/utils.h, tests/libtransmission/announce-list-test.cc, tests/libtransmission/file-test.cc, utils/remote.cc
fix a handful of minor recent coverity warnings.
=> fix: minor coverity warnings

macosx/Base.lproj/MainMenu.xib, macosx/SmallTorrentCell.h, macosx/SmallTorrentCell.mm, macosx/TorrentCell.mm, macosx/TorrentTableView.mm
I factored TorrentCell and SmallTorrentCell to avoid duplicate code.
=> Refactor: torrent cell and small torrent cell

macosx/Controller.mm, macosx/TorrentTableView.h, macosx/TorrentTableView.mm
Fix #5838 (@sweetppro).
Fix #5717 (@GaryElshaw).
=> Fix selected torrents when moving rows

README.md, libtransmission/peer-mgr.cc
=> docs: fix comment typos

libtransmission/rpcimpl.cc, libtransmission/variant.h
fix use of invalidated pointer in rpcimpl.
Fixes #6003.
=> fixup! refactor: tr_variant API update (#5998)

libtransmission/file-posix.cc
fixes #5966)
- fallback to user-space copy for EINVAL of sendfile64
- without this fix, empty blocklist files are created on such devices
=> fix tr_sys_path_copy in file-posix.cc for some Synology Devices (#5966)

macosx/Controller.mm
=> feat: support redirects to magnet

docs/Building-Transmission.md
i am  using now debian 12 and with those commands that are on debian working fine .. so I decide it that will good idea to push it
=> updating debian release

libtransmission/net.cc, macosx/FilterBarController.h, macosx/TorrentTableView.h, qt/DetailsDialog.cc, qt/PrefsDialog.cc, qt/RpcClient.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/test-fixtures.h
This formatting will help making git contributions for those with current stable clang-format (https://formulae.brew.sh/formula/clang-format).
=> chore: apply clang-format version 17.0.1

web/assets/css/transmission-app.scss, web/src/inspector.js
1. Tweaked paddings.
2. Odd even row highlights now shown properly when a single torrent is selected.
| Before | After |
| --- | --- |
| ![image](https://github.com/transmission/transmission/assets/46261767/ab06ae75-1a49-4d66-a916-803ce8a2b9d4) | ![image](https://github.com/transmission/transmission/assets/46261767/c047a1ac-c077-4718-b94f-f428abb92dc2) |
| ![image](https://github.com/transmission/transmission/assets/46261767/1133745c-1157-492f-8ad2-788a6f45fdce) | ![image](https://github.com/transmission/transmission/assets/46261767/bc0e879b-5e0f-41f4-89ab-fb9ceab4dea3) |
CC @Rukario @dareiff
=> feat: WebUI torrent tracker list style improvements

docs/rpc-spec.md, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/transmission.h, web/src/action-manager.js, web/src/context-menu.js, web/src/force-verify-dialog.js, web/src/remote.js, web/src/transmission.js
Part 2 of tackling #83. Previous part at #5978.
This PR allows users to easily restart a torrent that lost its data files, no longer needing to remove and re-add the torrent.
Normal verify will error out if the data files that we had disappeared; while this new forced option will start the verify action regardless, effectively resetting Transmission's records about the pieces we have.
The next step will be to add this context menu item to the other apps, and amending the error message so that it instructs users to force a verify instead of removing and re-adding the torrent:
```patch
diff --git a/libtransmission/torrent.cc b/libtransmission/torrent.cc                                                                        
index f65284f49..67c3658a4 100644 …
```
=> feat: add option to force verify torrent in WebUI

web/src/force-verify-dialog.js
See the old description for comparison at #5981.
=> feat: better description for forced verify option

macosx/QuickLookPlugin/GeneratePreviewForURL.mm
Do so by constructing temporary tree-like data structure.
How to test:
```sh
qlmanage -c com.bittorrent.torrent \
-g <path/to/built/QuickLookPlugin.qlgenerator> \
-p <path/to/file.torrent>
```
How it looks:
Test file:
[temp.torrent.zip](https://github.com/transmission/transmission/files/12841894/temp.torrent.zip)
=> feat: render file tree in legacy html-based QuickLook preview

libtransmission/bandwidth.cc, libtransmission/bandwidth.h
Manual cherry pick to `4.0.x`.
=> fix: only consider piece data in bandwidth limit (#6082)

gtk/OptionsDialog.cc
Fixes #6130
Notes: Fix crash when opening torrent file from "Recently used" section in GTK 4.
=> fix: crash when selecting file from recently used in gtk file chooser

gtk/OptionsDialog.cc
=> fix: do not use get_files2 in 4.0.x branch

libtransmission/torrent.cc, libtransmission/torrent.h
Add a new method `tr_torrent::stat()` and make `tr_torrentStat()` a simple wrapper around it.
=> refactor: add tr_torrent::stat()

libtransmission/torrent.cc, libtransmission/torrent.h
refactor: make tr_torrent::file_priorities_ private
=> refactor: make tr_torrent::files_wanted_ private

libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/variant-json.cc, libtransmission/variant.cc, libtransmission/variant.h, utils/remote.cc
=> refactor: remove quark support from tr_variant

libtransmission/global-ip-cache.cc, libtransmission/net.h, libtransmission/session.h
Tie up some loose ends from #5878.
=> fixup! refactor: re-organise net.h member functions (#5878)

libtransmission/variant.h
experimental change for MSBC 19.37 FTBFS in CI
=> refactor: extract the lambda method in tr_variant::Map::find()

Transmission.xcodeproj/project.pbxproj
Fix build regression from #6138.
Same fix as #4231.
=> Fix building on macOS Mojave

web/assets/css/transmission-app.scss, web/public_html/index.html
Side note: The context menu and inspector page will use bigger shadow like others. We can tweak it if you think there's a better shadow to use...
Notes: Unified CSS shadow properties
=> refactor: unified shadow properties for web client

libtransmission/blocklist.cc, libtransmission/blocklist.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/blocklist-test.cc, tests/libtransmission/session-test.cc
move multifile blocklist handling into a blocklists class.
=> refactor: blocklists

libtransmission/torrent-files.cc, tests/libtransmission/torrent-files-test.cc
as suggested in https://github.com/transmission/transmission/issues/1325#issuecomment-1021668928
closes #1325
=> Sanitize torrent filenames depending on current OS

qt/AddData.cc, qt/AddData.h, qt/Application.cc, qt/Application.h, qt/MainWindow.cc, qt/OptionsDialog.cc, qt/Session.cc, qt/Session.h
=> fix: only append '.added' suffix to watchdir files

macosx/AboutWindowController.mm, macosx/AddMagnetWindowController.mm, macosx/AddWindowController.mm, macosx/Base.lproj/MainMenu.xib, macosx/BlocklistDownloaderViewController.mm, macosx/ColorTextField.mm, macosx/Controller.mm, macosx/CreatorWindowController.mm, macosx/FileOutlineController.mm, macosx/FileOutlineView.mm, macosx/FilterBarController.mm, macosx/FilterBarView.mm, macosx/GlobalOptionsPopoverViewController.mm, macosx/GroupsPrefsController.mm, macosx/InfoActivityViewController.mm, macosx/InfoFileViewController.mm, macosx/InfoOptionsViewController.mm, macosx/InfoPeersViewController.mm, macosx/InfoTrackersViewController.mm, macosx/InfoWindowController.mm, macosx/MessageWindowController.mm, macosx/PiecesView.mm, macosx/PrefsController.mm, macosx/StatsWindowController.mm, macosx/StatusBarController.mm, macosx/TorrentCellActionButton.mm, macosx/TorrentCellControlButton.mm, macosx/TorrentCellRevealButton.mm, macosx/TorrentTableView.mm, macosx/URLSheetWindowController.mm
Fix #6205.
(this was yet another regression from #5147, but hopefully the last one?)
=> Fix: torrentTableView crash after superview.superview.superview

web/src/inspector.js
=> feat: display full client name in tooltip [WebUI]

libtransmission/peer-mgr.cc
Fixes #6239, along with some minor copyediting.
Regression from 36f33c0d3036647c3c036b5000fcc538f536ab54.
=> fix: `assertion failed: is_connectable_.value_or(true) || !is_connected()`

libtransmission/session.cc, libtransmission/torrent.h
very small refactor to simplify some session code.
=> refactor: add a tr_direction arg to tr_torrent::is_queued()

docs/rpc-spec.md, libtransmission/announcer-http.cc, libtransmission/rpcimpl.cc, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc, tests/libtransmission/global-ip-cache-test.cc
See https://github.com/transmission/transmission/pull/5953#issuecomment-1820103438 for explanation.
CC @killemov
=> refactor: RPC `port-test` improvements

docs/Scripts.md
=> docs: remove dead link from Scripts.md

macosx/DefaultAppHelper.mm
Fix building Transmission on macOS Mojave.
(fix regression from #6120)
=> Compatibility to build with Xcode 11.3.1

docs/rpc-spec.md
=> docs: add description for torrent action requests

libtransmission/torrent-magnet.cc
(probably doesn't fix anything, but was bothering me)
=> improve magnet metadata progress

libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/announcer-common.h, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/rpcimpl.cc, libtransmission/transmission.h, tests/libtransmission/announce-list-test.cc
previous discussed at https://github.com/transmission/transmission/pull/5871#pullrequestreview-1563966858 .
=> refactor: in tr_announce_list, replace port_and_str with aggregated parsed url

libtransmission/bandwidth.cc, libtransmission/transmission.h
See explanation from https://github.com/transmission/transmission/pull/6079#discussion_r1413277573.
=> fixup! fix: low priority not working (#6079)

news/news-4.0.5.md
=> docs: 4.0.5 release notes

libtransmission/global-ip-cache.cc, libtransmission/global-ip-cache.h
=> fix: remove unnecessary locking in global ip cache

qt/TorrentDelegate.cc
This adds ETA to the compact view.
Its mostly a copy and paste from the *progressString* function.
Should resolve #1392
=> feat(qt): Add ETA to compact view

libtransmission/crypto-utils-mbedtls.cc, tests/libtransmission/crypto-test.cc
Notes: Fixed "CTR_DRBG - The requested random buffer length is too big" mbedtls crypto backend error.
Fixes: #5795
=> Fill random buffer in chunks with mbedtls crypto backend

libtransmission/peer-msgs.cc
Regression from 5ccd5a7700c406ab4b45d30fd39a02b3a356b33d
P.S. 2009 🤤
=> fix: use correct time to determine write buffer size

libtransmission/subprocess-win32.cc, libtransmission/torrent.cc, libtransmission/utils.h, utils/remote.cc
This was only used in a couple of places and didn't really add value.
=> refactor: remove tr_str_is_empty()

utils/remote.cc
=> ui: unify percent done format in `transmission-remote`

libtransmission/block-info.cc, libtransmission/block-info.h, libtransmission/variant.cc, libtransmission/variant.h, macosx/Controller.mm, macosx/PrefsController.mm, macosx/Torrent.mm
Fix various conversion warnings
=> Fix: Implicit conversion loses integer precision

libtransmission/peer-io.cc
=> fixup! fix: implement proper download limit for uTP (#6416)

cli/cli.cc, daemon/daemon-posix.cc, daemon/daemon-win32.cc, gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/FreeSpaceLabel.cc, gtk/MakeDialog.cc, gtk/Torrent.cc, gtk/TorrentCellRenderer.cc, libtransmission/announcer.cc, libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/handshake.cc, libtransmission/peer-msgs.cc, libtransmission/platform.cc, libtransmission/rpc-server.cc, libtransmission/subprocess-win32.cc, libtransmission/torrent-files.cc, libtransmission/torrent.cc, libtransmission/tr-assert.mm, libtransmission/tr-utp.cc, utils/remote.cc
does what it says on the tin :man_shrugging:
=> chore: remove FMT_STRING macros

qt/TorrentDelegate.cc, qt/TorrentDelegateMin.cc
=> Use semi-transparent color for inactive torrents

gtk/Application.cc, gtk/MessageLogWindow.cc, gtk/OptionsDialog.cc, gtk/OptionsDialog.h, gtk/PathButton.cc
=> Use native file chooser dialogs (GTK client)

CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-socket.cc
Cherry pick recent libutp updates and fixes from `main`.
=> chore: backport recent libutp-related changes

libtransmission/announcer-http.cc
(cherry picked from commit 077dcc8f9a339a6ffc3a4d0de15a8c0e9aca5536)
Notes: Improved parsing HTTP tracker announce response.
=> fix: parse all http announce responses (#6223)

libtransmission/peer-io.cc
(cherry picked from commit 4506d201366fd643ce8a16feb6ef3c7d9a3e44d1)
=> fix: add check for `EWOULDBLOCK` (#6350)

.github/workflows/actions.yml, .github/workflows/codeql.yml, .github/workflows/webapp.yml, libtransmission/variant.h
Looked over our CI actions to find which ones can be bumped after seeing the CI failure at https://github.com/transmission/transmission/actions/runs/8135215991/job/22229388789.
=> ci: bump CI actions

web/src/torrent-row.js
Removes code duplication. `TorrentRendererHelper` seems like a suitable place for this.
=> refactor(web): extract mime icon creation to the helper

.github/workflows/actions.yml, code_style.sh
It was recently suggested that we should discuss bumping to a newer clang-format version in #6622.
=> targeting clang-format version 17

CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, macosx/BadgeView.mm, macosx/CMakeLists.txt, macosx/InfoOptionsViewController.mm, macosx/InfoWindowController.mm, macosx/PortChecker.mm, macosx/StatusBarController.mm, macosx/TorrentTableView.mm, macosx/Utils.h, macosx/Utils.mm
Every commit can be reviewed separately and contains explanation in message.
If one of commits is not something wanted, I can drop it.
=> chore: fix warnings when compiling macOS client with either Xcode or CMake

macosx/InfoOptionsViewController.mm, macosx/Utils.h
Follow-up for a small regression introduced with #6676
=> fix multipleRatioLimits

libtransmission/peer-mgr.cc
=> run peerMgrPeerStats in session thread

qt/RpcClient.cc, tests/libtransmission/dht-test.cc, tests/libtransmission/timer-test.cc
=> fix compatibility with clang-format 18 (#6690)

.clang-format, gtk/OptionsDialog.cc, libtransmission/peer-mgr.cc, libtransmission/tr-dht.cc
Style: avoiding inconsistency with some blocks with empty lines and some blocks without.
=> KeepEmptyLinesAtTheStartOfBlocks: false

libtransmission/torrent.cc
Fix an assert failure when moving torrents to the bottom of the queue. e.g. by RPC `queue-move-bottom` method.
```
assertion failed: torrents_are_sorted_by_queue_position(torrents.get_all()) (/path/to/Transmission/libtransmission/torrent.cc:530)
```
Alongside with that, now `tr_torrent::set_unique_queue_position()` will always result in consecutive queue positions, whereas it *can* result in gaps before.
=> fix: assert failure when moving torrents to bottom of the queue

libtransmission/peer-mgr.cc, libtransmission/webseed.cc, libtransmission/webseed.h
=> refactor: convert `tr_webseed` to C++ interface

libtransmission/variant.cc, utils/remote.cc
Fix #6816
Fix a regression caused by #6723.
=> Fix crash in printTorrentList

libtransmission/crypto-utils-mbedtls.cc
this is backport of https://github.com/transmission/transmission/pull/6822 to 4.0.x branch
Signed-off-by: Seo Suchan <tjtncks@gmail.com>
=> [4.0.x] fix building with mbedtls 3.x

docs/Building-Transmission.md
Notes: How to build the QT app on macOS
=> Building the QT app with CMake

libtransmission/net.cc, libtransmission/net.h, libtransmission/tr-lpd.cc, tests/libtransmission/lpd-test.cc
https://www.bittorrent.org/beps/bep_0014.html
Notes: Add support for IPv6 Local Peer Discovery.
=> feat: ipv6 lpd

utils/remote.cc, utils/transmission-remote.1
This implements the feature discussed in #253
=> remote: Implement idle seeding limits

gtk/FileList.cc, gtk/FilterBar.cc, libtransmission/crypto-utils-mbedtls.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/crypto-utils-wolfssl.cc, libtransmission/crypto-utils.h, libtransmission/log.cc, libtransmission/net.h, libtransmission/peer-mgr.cc, libtransmission/quark.cc, libtransmission/session.h, libtransmission/settings.cc, libtransmission/torrent-magnet.h, libtransmission/tr-lpd.cc, libtransmission/utils.cc, libtransmission/watchdir-kqueue.cc, qt/FilterBar.cc, qt/OptionsDialog.h, qt/Prefs.h, qt/Session.cc, qt/TorrentModel.cc
=> chore: iwyu

docs/Editing-Configuration-Files.md
https://github.com/transmission/transmission/blob/ec6112e0b140d0fac176cf8c1de4211b96bf2d6a/libtransmission/transmission.h#L137-L140
=> docs: fix default value in docs

libtransmission/torrent.cc
The crash will happen if the following series of events happened:
1. Torrent verification starts for a `tr_torrent` object.
2. The session thread starts executing `tr_torrentFreeInSessionThread()`, about to free this `tr_torrent` object.
3. `tr_torrent::VerifyMediator::on_verify_done()` queues a lambda that captures a pointer to the `tr_torrent` object.
4. The `tr_torrent` object is freed.
5. The session thread executes the lambda from Step 3, and crashes when dereferencing the dangling `tr_torrent` pointer.
I *think* this fixes the recent CI crashes in `LT.TorrentMagnetTest.setMetadataPiece`, such as this one https://github.com/transmission/transmission/pull/6665#issuecomment-2132217599.
=> fix: crash in `tr_torrent::VerifyMediator::on_verify_done()`

libtransmission/session-alt-speeds.cc, libtransmission/session-alt-speeds.h
Fixes #5488.
Fixes #6938.
Notes: Fixed a bug where the turtle icon is active but not effective on starting Transmission.
=> fix: apply alt speed settings on load

libtransmission/peer-msgs.cc
confused myself until I realized this was DHT-specific.  Make it clear in code.
=> chore: clarify DhtPort specific usage

libtransmission/announcer-udp.cc
=> refactor: simplify addrinfo unique_ptr definition

web/src/open-dialog.js, web/src/prefs-dialog.js, web/src/transmission.js
=> chore: misc WebUI fixes and cleanup

gtk/transmission-ui.css, gtk/ui/gtk3/AddTrackerDialog.ui, gtk/ui/gtk3/DetailsDialog.ui, gtk/ui/gtk3/EditTrackersDialog.ui, gtk/ui/gtk3/FilterBar.ui, gtk/ui/gtk3/MainWindow.ui, gtk/ui/gtk3/MakeDialog.ui, gtk/ui/gtk3/MakeProgressDialog.ui, gtk/ui/gtk3/MessageLogWindow.ui, gtk/ui/gtk3/OptionsDialog.ui, gtk/ui/gtk3/PrefsDialog.ui, gtk/ui/gtk3/RelocateDialog.ui, gtk/ui/gtk3/StatsDialog.ui, gtk/ui/gtk3/TorrentUrlChooserDialog.ui, gtk/ui/gtk4/AddTrackerDialog.ui, gtk/ui/gtk4/DetailsDialog.ui, gtk/ui/gtk4/EditTrackersDialog.ui, gtk/ui/gtk4/MainWindow.ui, gtk/ui/gtk4/MakeDialog.ui, gtk/ui/gtk4/MessageLogWindow.ui, gtk/ui/gtk4/OptionsDialog.ui, gtk/ui/gtk4/PrefsDialog.ui, gtk/ui/gtk4/RelocateDialog.ui, gtk/ui/gtk4/StatsDialog.ui, gtk/ui/gtk4/TorrentListItemFull.ui, gtk/ui/gtk4/TorrentUrlChooserDialog.ui
This is similar to #6518 but for the GTK client instead of the Qt client.
Without whitespace changes: 548 insertions(+), 621 deletions(-)
Notes: Improve GTK client's accessibility.
Xref: #6512
=> GTK client accessibility improvements

docs/rpc-spec.md
See the discussion in #5578. I don't think anyone would expect otherwise, but it doesn't hurt to be explicit.
=> Clarify file order and indexes

libtransmission/tr-lpd.cc
Fixes #7125.
Fixes #6953.
Regression from #6700.
=> fix: calculate size of one hash line in lpd correctly

libtransmission/peer-mgr.cc
=> refactor: improve criteria for choosing peers to save to resume

libtransmission/torrent.h
=> remove TR_ASSERT(now >= latest)

libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h
Fixes #6942.
Notes: Fixed a bug where Transmission does not properly reconnect on handshake error.
=> fix: properly reconnect on handshake error

libtransmission/peer-mgr.cc
=> fix: always sort peer candidates by score

web/assets/css/transmission-app.scss, web/src/file-row.js, web/src/formatter.js, web/src/inspector.js, web/src/torrent-row.js, web/src/torrent.js
<details>
<summary>Old screenshot</summary>
Animated diff from original
Notes: Added percent digits into the progress bar.
=> feat: display percent in progress bar for web client

daemon/daemon.cc, docs/Editing-Configuration-Files.md
=> fix: add missing `settings.json` docs and app defaults

libtransmission/variant.cc
=> refactor: use string_view literals instead of C string literals

.github/workflows/actions.yml
=> CI: updrading deprecated macOS 12 to macOS 13

.github/workflows/actions.yml
=> ci: remove macos pkgconf workaround

CMakeLists.txt, news/news-4.1.0-beta.1.md
Add 4.1.0-beta.1 notes.
Bump version to 4.1.0-beta.1.
=> docs: add 4.1.0-beta.1 notes

libtransmission/peer-mgr-wishlist.cc, tests/libtransmission/peer-mgr-wishlist-test.cc
=> feat: download first and last piece first in sequential mode

web/src/transmission.js
Large popup like inspector page can stick while a new popup lesser important to it can open to co-exist and dismiss even lesser popups if there's any, the system works like hierarchy, lesser important ones go away before others.
Notes: Implemented a new popup management system for web client to support multiple popups in a hierarchy-like system.
=> feat: multiple popups in a hierarchy-like system

macosx/Base.lproj/MainMenu.xib, macosx/TorrentTableView.mm
This gets things closer, but not exactly matching, the previous layout.
=> Update some spacing constrains in the torrent cells

web/src/transmission.js
A refinement upon #7297 with change suggestions from other conversation.
=> refactor: multiple popups code refinement

macosx/Base.lproj/MainMenu.xib, macosx/SmallTorrentCell.mm, macosx/TorrentCell.mm
This matches the previous behavior.
=> In the small view, show the action buttons when hovering anywhere over the cell

tests/libtransmission/dht-test.cc
=> test(dht): use static IP address

libtransmission/benc.h, qt/AddData.h, qt/DBusInteropHelper.h, qt/FileTreeDelegate.h, qt/FileTreeModel.h, qt/FileTreeView.h, qt/FilterBarComboBox.h, qt/FilterBarComboBoxDelegate.h, qt/Filters.h, qt/IconToolButton.h, qt/InteropHelper.h, qt/InteropObject.h, qt/MainWindow.h, qt/MakeDialog.h, qt/PathButton.h, qt/Torrent.h, qt/TorrentFilter.h, qt/TrackerDelegate.h, qt/TrackerModel.h, qt/TrackerModelFilter.h, qt/WatchDir.h, tests/libtransmission/test-fixtures.h
PR is literally just a bunch of `[[nodiscard]]` additions :)
=> refactor: fix modernize-use-nodiscard warnings by adding [[nodiscard]]

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, tests/libtransmission/handshake-test.cc
=> fix: abort handshake if the torrent is stopped

libtransmission/resume.cc
Another PR for modernising the code base. There should be no change in behaviour.
> [!NOTE]
> ~This PR is blocked by #6892.~ Edited: Merged
=> refactor: use new `tr_variant` API for resume

.gitmodules
Bump cmake_minimum_version to a supported version.
=> chore: bump libevent

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, tests/libtransmission/announcer-test.cc, tests/libtransmission/announcer-udp-test.cc
Housekeeping the announcer code for a bit. There shouldn't be any change in behaviour.
=> refactor: announcer code housekeeping
