transmission/transmission

macosx/BlocklistDownloader.mm

Problem: arguments only accept an array of strings.
Solution: use file.path like with `untarFrom:` and `gunzipFrom:`.
This was a regression from #2191.
But I didn't test it... as I don't know any blocklist address where I can download one. If you know of any blocklist provider in **zip** format, I'd be thankful for further testing.

Fix BlockListDownloader unzipFrom

---

libtransmission/announcer-http.cc
libtransmission/net.cc
libtransmission/net.h
libtransmission/peer-msgs.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/tr-udp.cc

Fixes #4406.
Fixes #4410.
Notes: Fixed `4.0.0-beta.2` IPv6 μTP socket binding regression.

refactor: udp_core constructor

---

qt/FileTreeDelegate.cc
qt/StyleHelper.cc
qt/StyleHelper.h
qt/TorrentDelegate.cc
qt/TorrentDelegateMin.cc

This is a workaround for [QTBUG-67830](https://bugreports.qt.io/browse/QTBUG-67830), where progress bars seem to be drawn regardless of style option's rect top-left coordinates.
Fixes: #4470

Fix progress bars positioning in Qt client on Mac

---

macosx/URLSheetWindowController.mm

This was a minor regression from b6c21343387de783f91cf5e38de58131b65b73e4 (10 years ago, @livings124).
Now... I'll add "needs UI review", because I'd like to confirm first if returning to that behavior from 10 years ago is good or not.
To test it:
- Transmission menu, "Open Torrent Address", and attempt to open any URL.
- Transmission menu, "Open Torrent Address" a second time: the previous URL should be pre-filled (only for the duration of the session: if you quit the app, it won't remember it).

Fixed dead code in "Open Torrent Address"

---

libtransmission/announcer-http.cc
libtransmission/session.h

Fixes https://github.com/transmission/transmission/issues/4501.
Notes: Followed [BEP7](https://www.bittorrent.org/beps/bep_0007.html) suggestion to remove ipv4 and ipv6 query parameters from tracker announcements.

fix: remove announce ipv4 ipv6 query params

---

libtransmission/net.h
libtransmission/peer-msgs.cc
libtransmission/quark.cc
libtransmission/quark.h

Notes: Updated extension protocol handshake to include `yourip` value as suggested by [BEP10](https://www.bittorrent.org/beps/bep_0010.html).
Fixes https://github.com/transmission/transmission/issues/4503.

feat: add `yourip` to extension protocol handshake

---

utils/remote.cc

fix(remote): Fix tr_strltime to output days correctly

---

libtransmission/announcer-common.h
libtransmission/announcer-udp.cc
libtransmission/announcer.cc
libtransmission/torrent.h
libtransmission/tr-macros.h

Notes: Changed the tracker announce &key=  param to be unique per-torrent.
Previously it was unique per-session, meaning all torrents were announced with the same key.
This key is discussed in [BEP 7](https://www.bittorrent.org/beps/bep_0007.html):
> The client SHOULD include a key parameter in its announces. The key should remain the same for a particular infohash during a torrent session. Together with the peer_id this allows trackers to uniquely identify clients for the purpose of statistics-keeping when they announce from multiple IP .
and in [BEP 15](https://www.bittorrent.org/beps/bep_0015.html):
> Clients that resolve hostnames to v4 and v6 and then announce to both should use the same key for both so that trackers that care about accurate statistics-keeping can match the two …

refactor: make announce key param unique per-torrent

---

libtransmission/announcer-udp.cc
libtransmission/peer-socket.cc

perf: avoid vector temporary in announcer-udp

---

Transmission.xcodeproj/project.pbxproj
libtransmission/CMakeLists.txt
libtransmission/utils-ev.cc
libtransmission/utils-ev.h

Move the libevent helpers' implementations into a .cc file to prevent a `-Wredundant-decls` warning

fix: -Wredundant-decls warning when building with g++

---

libtransmission/platform-quota.cc
libtransmission/rpc-server.cc

No functional changes; just silencing some minor warnings

refactor: fix readability-redundant-string-cstr clang-tidy-16 warnings 

---

libtransmission/tr-udp.cc

fix regression [reported by Coverity](https://scan5.scan.coverity.com/reports.htm#v48014/p10174/fileInstanceId=230611125&defectInstanceId=53050531&mergedDefectId=1518899)

fixup! fix: Couldnt send to IPv6 address warnings (#4527)

---

CMakeLists.txt
libtransmission/announcer-udp.cc
libtransmission/file-posix.cc
libtransmission/resume.cc
libtransmission/torrent.cc
libtransmission/tr-getopt.cc
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/variant.cc

Fix another batch of `misc-use-anonymous-namespace` clang-tidy-16 warnings.

refactor: misc-use-anonymous-namespace pt. 2

---

libtransmission/announcer-http.cc
libtransmission/announcer.cc
libtransmission/crypto-utils-openssl.cc
libtransmission/error.cc
libtransmission/makelog
libtransmission/peer-mgr.cc
libtransmission/platform-quota.cc
libtransmission/platform.cc
libtransmission/port-forwarding-upnp.cc
libtransmission/subprocess-posix.cc
libtransmission/torrent.cc
libtransmission/tr-utp.cc

Another batch of moving static methods into an anonymous namespace for the clang-tidy-16 check `misc-use-anonymous-namespace`

refactor: misc-use-anonymous-namespace pt. 4

---

libtransmission/bandwidth.cc
libtransmission/bandwidth.h
libtransmission/file-posix.cc
libtransmission/peer-common.h
libtransmission/peer-io.cc
libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h
libtransmission/peer-msgs.cc
libtransmission/port-forwarding-natpmp.cc
libtransmission/session.cc
libtransmission/torrent-ctor.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent.h

Another batch of moving static methods into an anonymous namespace for the clang-tidy-16 check `misc-use-anonymous-namespace`
This fixes the final batch of warnings & is the last in the series.

refactor: misc-use-anonymous-namespace pt. 5

---

gtk/CMakeLists.txt
gtk/FilterBar.cc
gtk/FilterBase.h
gtk/FilterBase.hh
gtk/FilterListModel.h
gtk/FilterListModel.hh
gtk/Session.cc
gtk/SortListModel.h
gtk/SortListModel.hh
gtk/SorterBase.h
gtk/SorterBase.hh
gtk/TorrentFilter.cc
gtk/TorrentFilter.h
gtk/TorrentSorter.cc
gtk/TorrentSorter.h

Factor out parts of `TorrentFilter` and `TorrentSorter` classes into reusable `FilterBase<>` and `SorterBase<>` templates.
Factor out filter and sort models setup from `FilterBar` and `Session` classes into reusable `FilterListModel<>` and `SortListModel<>` templates.

Refactor sorting and filtering compatibility code (GTK client)

---

.github/workflows/actions.yml

Try to fix a recent CI issue where the Windows GitHub actions will  fail on `error: unknown target 'pack-msi'` e.g. [this build](https://github.com/transmission/transmission/actions/runs/3868921795/jobs/6594694631).
@mikedld I _think_ this is right but am not sure; would appreciate a 2nd opinion here

test: GH Action should only try pack-msi if making dist or qt

---

.github/workflows/actions.yml

Fix GitHub CI actions warning for set-output

---

CMakeLists.txt
Transmission.xcodeproj/project.pbxproj
libtransmission/CMakeLists.txt
libtransmission/torrent-metainfo.cc
libtransmission/utils.cc
libtransmission/utils.h
tests/libtransmission/utils-test.cc

build: remove explicit iconv dependency in libtransmission

---

libtransmission/rpc-server.cc
libtransmission/utils.h

Change the http server's error messages to be more generic, on the theory that it will be harder for an attacker to determine what software is running.
Fixes #693.

feat: change 403 error message

---

libtransmission/torrent.cc

fix: tr_torrentStat() acquires a session thread lock

---

libtransmission/announcer.cc
libtransmission/announcer.h
libtransmission/torrent.cc

Extra callback data is not actually used and so can be dropped

chore: simplify announcer add callback

---

macosx/Controller.mm

NSAlert is a high level feature that expect a fully loaded app.
It is currently used during the app initialization which cause an issue with the help menu.
Using a lower level implementation of the alert window prevents this issue.

Fix two Help menus in macOS

---

libtransmission/announcer.cc
libtransmission/announcer.h
libtransmission/torrent.cc
libtransmission/torrent.h

This is a follow-up for the recently merged https://github.com/transmission/transmission/pull/4573 and mostly intended to use `tr_torrent` methods as an announcer callback functions.

refactor: use std::function for announcer callback

---

macosx/TorrentCell.mm

An ongoing battle. This is my last attempt to increase the minimum font size within the main window of the macOS client. 
This is not deficient, nor is it 'arbitrary'. 9.0 should not be used as a baseline font size for the main window of an application such as Transmission. This change breaks nothing in the design or code, and does nothing but increase information values.
I have suggested elsewhere that the gui could adopt a better methodology for increasing font size values for user needs across the client. In the absence of that, there is this.

Increase font size in TorrentCell

---

libtransmission/web.cc

Also, change `CURLOPT_ENCODING` usage to `CURLOPT_ACCEPT_ENCODING`. This key was renamed upstream in 7.21.6; our CURL_MINIMUM is 7.28.0.
Fixes #753.
Notes: Improved how Transmission handles webseed servers that return a content-encoding that was not requested.

fix: when setting Accept-Encoding to identity, disable curl decoding.

---

daemon/daemon.cc
daemon/daemon.h
libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.h

When running as a `systemd` unit, standard error of `transmission-daemon` is redirected to a socket, so `isatty()` precaution added in https://github.com/transmission/transmission/commit/2bcb8f8535a08764ff51e836cb5a9ecbc614a7fc is not enough. This is the real one.

daemon: check whether log file is regular and may be flushed

---

libtransmission/peer-socket.h

Default implementations for these functions may leak sockets during destructing and moving.
For example, the original default destructor and move assignment operator of tr_peer_socket will leak the socket the object originally holds when called, and the original move constructor and move assignment operator do not cleanly invalidate or "absorb" the object passed in.
Sadly this commit does not fix what issue #3677, the leaked sockets seem to come from the http tracker client based on libcurl.

Add valid dtor, move ctor, and move operator= for tr_peer_socket

---

gtk/RelocateDialog.cc

Notes: Fixed `4.0.0-beta.1` regression making it impossible to close "Set location" dialog (GTK 3 only).
Fixes: #4606

Destroy message dialog on error (#3805 regression)

---

cmake/LargeFileSupport.cmake

Fixes #4626.
Add a linefeed to the beginning of `LFS_TEST_PROGRAM`.
The issue comes a little later down in the diff:
```
check_c_source_compiles("${LFS_TEST_PROGRAM}" NO_LFS_MACROS_REQUIRED)
if(NOT NO_LFS_MACROS_REQUIRED)
if(NOT DEFINED FILE_OFFSET_BITS_LFS_MACRO_REQUIRED)
check_c_source_compiles("#define _FILE_OFFSET_BITS 64 ${LFS_TEST_PROGRAM}" FILE_OFFSET_BITS_LFS_MACRO_REQUIRED)
if(NOT FILE_OFFSET_BITS_LFS_MACRO_REQUIRED AND NOT DEFINED LARGE_FILES_LFS_MACRO_REQUIRED)
check_c_source_compiles("#define _LARGE_FILES 1 ${LFS_TEST_PROGRAM}" LARGE_FILES_LFS_MACRO_REQUIRED)
endif()
endif()
```
Note that `${LFS_TEST_PROGRAM}` comes on the same line as the `#define`, so the line `#include <sys/types.h>` was being included as part of the `#define` macro which made the second and third calls to …

fix: largefile support cmake tests

---

utils/remote.cc

This caused a crash when running `transmission-remote -si`

fix(remote): Don't draw "Yes" or "No" as an integer

---

web/assets/css/transmission-app.scss
web/src/file-row.js
web/src/inspector.js
web/src/utils.js

fix: when comparing priority for rpc call, cast to string first https://github.com/transmission/transmission/issues/3763
When clicking on priority buttons, you could only set to normal, not high or low.
This is because the switch was comparing "1" to `1`, `-1`, or default. (And default was getting selected.)
I believe this was from the original rewrite from 2 years ago.
- use toString on file.priority
- compare string to string instead of number to string
- use that!
Fixes #3763.
Notes: Fixed `4.0.0-beta.1` regression that broke file priority buttons in the web client.

fix: when comparing priority for rpc call, cast to string first

---

utils/remote.cc

This caused a crash when running `transmission-remote -t1 -it`

fix(remote): Crash caused by typo when displaying tracker info

---

libtransmission/rpcimpl.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h

Fixes #4632.
Notes: Fixed `4.0.0-beta.1` regression that did not update the UI when a user removed a tracker from the announce list.

fix: announcer not updated after torrent announce list edited

---

libtransmission/announce-list.cc
libtransmission/bandwidth.h
libtransmission/history.h
libtransmission/net.h
libtransmission/peer-common.h
libtransmission/peer-mgr.cc
libtransmission/peer-msgs.h
libtransmission/torrent-metainfo.h
libtransmission/torrent.h
libtransmission/tr-getopt.h
libtransmission/tr-strbuf.h
libtransmission/transmission.h
libtransmission/utils.h
libtransmission/variant.h
libtransmission/web.h

This is somewhat a followup to #4628, in regard to variable names in documentation comments.
1. The main change is the addition of backticks in documentation comments around variable and function names with underscores, to avoid them being half-italized from markdown interpretation.
2. The second important change is the uniformisation of the order of declarations: I put all getters before their corresponding setter in transmission.h. The choice to have getters before setters is because: (1) when bridging an header with some other languages, the order `get set` is preferred by convention (might be for alphabetical historical reasons?), and (2) while a getter is required, a setter can be optional, in particular for constant values, hence the getter is best declared first.
3. Some minor …

underscores in documentation comments should be code escaped

---

.github/workflows/actions.yml

temporary workaround for Homebrew/homebrew-core/issues/121081 since we're still hitting this on fresh install CI boxes.
IDK what the pipeline is for homebrew but presumably this will work itself out; will check back in a week.

chore: pin brew libpsl to 0.21.1

---

code_style.sh
web/README.md
web/package-lock.json
web/package.json
web/src/prefs.js
web/src/utils.js
web/stylelint.config.js
web/webpack.config.js

revert to older transmission-web build dependencies to make it easier to build on stock older systems, e.g. Ubuntu 20.04 which ships with Node 10.

build: downgrade web deps

---

.github/workflows/webapp.yml

Fixes #4060.
Fixes #4042.
Supersedes #4061.
Adds GitHub actions to:
- Fail CI if a user-submitted PR changes generated files (e.g. `transmission-app.js`).
- Open a new PR ([sample](https://github.com/ckerr/transmission/pull/10)) that refreshes the generated files when changes to the web app source code are pushed into `main`.
- Lint any changes to the web app's source code.
- User-submitted changes to generated files are a potential attack vector #4060 or bug vector #4024
- Generating the files at build time on systems without internet access is problematic since `npm install` requires adding an npm cache that's populated from another system. #4042 
- Generating the files at build time on older systems is problematic since their package repositories may not have access to a modern version …

build: add webapp github actions

---

macosx/PrefsController.mm

Fixes #4657.
After the first time, subsequent calls are always centered via 
https://github.com/transmission/transmission/blob/096db96bca139bf6623ecc937dca282d183c02ff/macosx/Controller.mm#L2219 .

fix: ensure prefs window is centered the first time shown

---

web/README.md
web/package-lock.json
web/package.json
web/src/prefs.js
web/stylelint.config.js

This was done in #4644 to make it easier to build the web app's static files on older systems; however, #4658 means that this is no longer necessary so we can use modern devDependencies again.

chore: revert 5b14df51c, restore up-to-date web app devDependencies

---

libtransmission/announcer-http.cc

Fixes #4671.
Notes: Fixed `4.0.0-beta.1` FTBFS error on CentOS 7.

fix: remove CURL_VERSION_BITS macro

---

libtransmission/web.cc

Fixes #4674.
Notes: Fixed 4.0.0-beta.1 FTBFS error on CentOS 7.

fix: omit curlopt options if curl is old

---

qt/DetailsDialog.ui

Fixes #988.
Notes: Made display order of  speed limits consistent between Properties, Details dialogs.

fix: make torrent speed limit order consistent in prefs, details dialogs

---

libtransmission/net.cc

chore: don't warn on ECONNREFUSED to peer sockets.

---

libtransmission/bandwidth.h
libtransmission/bitfield.cc
libtransmission/bitfield.h
libtransmission/completion.cc
libtransmission/completion.h
libtransmission/net.cc
libtransmission/peer-mgr.cc
libtransmission/peer-mse.cc
libtransmission/torrent-ctor.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent-metainfo.cc
libtransmission/torrent-metainfo.h
libtransmission/tr-buffer.h
libtransmission/web-utils.cc
libtransmission/web.cc

- Ensure that helper functions are hidden in unnamed namespaces
- Make some class members private
- Remove some unused class methods

refactor: tidy libtransmission symbol visibility

---

libtransmission/interned-string.h
libtransmission/peer-mgr-wishlist.h
libtransmission/peer-mgr.h
libtransmission/peer-msgs.cc
libtransmission/peer-msgs.h
libtransmission/port-forwarding-upnp.h
libtransmission/quark.h
libtransmission/rpc-server.h
libtransmission/session.h
libtransmission/torrent-files.cc
libtransmission/torrent-files.h
libtransmission/torrent-metainfo.h
libtransmission/torrent.h
libtransmission/torrents.h
libtransmission/tr-arc4.h
libtransmission/utils.cc
libtransmission/utils.h
libtransmission/variant.cc
libtransmission/variant.h
libtransmission/web-utils.h
libtransmission/web.h

Still enabling + cleaning up some more clang-tidy warnings in libtransmission.

fix: clang-tidy header warnings

---

macosx/VDKQueue/VDKQueue.h

Issue specific to .h files (not .m files): `#warning` should be capitalized, otherwise it will duplicate the warning depending on the context where it is imported.

#warning in header file should start with capital letter

---

libtransmission/cache.cc

If there is the only block to write (which is the most common case IIUC), an extra data copy may be omitted.

perf: optimize the only block case in Cache::writeContiguous()

---

docs/rpc-spec.md

This reverts commit 0976e6259e1e549c5e57a5ebd0d829fcf3847fb9.
Discussion @ https://github.com/transmission/transmission/issues/3226#issuecomment-1411331325

docs: deprecate trackerAdd, trackerRemove, trackerReplace RPC

---

.gitignore
Transmission.xcodeproj/project.pbxproj
libtransmission/web-utils.cc

<s>While ideally psl_builtin should never be null, this pull request adds a workaround which is compatible with most tracker cases (at least, the hundred of popular trackers that I'm aware of) in case psl_builtin is null.
Of course, lacking the [~10k entries of the Public Suffix List](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) can't be solved with just maths or a regex, but the code I wrote will give at least better results than just `www` (which was what the function was most often returning before this improvement).</s>
This PR adds libpsl support when using Xcode.

Fix WebUtilsTest.urlParse and psl_builtin for Xcode

---

macosx/BlocklistDownloader.mm

Recently we discovered we do not properly handle broken tar archives.
The problem is running tar (in linting mode) on invalid archive and piping stdout to NSPipe introduces a hang as NSPipe cannot process such huge data amounts.
Fixing this problem by adding a precheck with tar (listing mode) with piping stdout to /dev/null.
Fixes: #4702

fix: Add precheck for tar archive test.

---

libtransmission/tr-assert.mm

I *think* this is aborting the application before it has a chance for the uncaught exception handler to be reached, which is why crashes reports that people include in bug reports never include the assertion failure message.
Example: the crash report shown in  https://github.com/transmission/transmission/issues/4695 has the process ending in the `abort()` that's removed from here, so we never see what the assertion message is.
Marking as `needs code review` because I'd like a second opinion on this theory

fix: remove abort() call from tr_assert_message()

---

web/assets/css/transmission-app.scss

On my phone screen, the two filter selections become empty lists.
Fix this by preventing display:none on option tags.

Fix webui filter selection on mobile

---

libtransmission/announcer-udp.cc

This is an interim fix to unblock 4.0.0. See ticket 4719 for details.
Fixes #4719.

fix: ensure ipv4 for udp announces.

---

libtransmission/rpcimpl.cc

Fixes #4713.
Notes: Fixed potential race condition when invoking libtransmission via RPC.

fix: race condition in RPC

---

macosx/Controller.mm
macosx/Toolbar.h
macosx/Toolbar.mm

Fix #4604
Apparently, on the customization palette (right-click on Toolbar > Customize), if the label is larger than a groupItem, then Apple's autolayout on macOS 13.2 will enter into some infinite loop with increasing memory usage, causing the app to hang then crash.
My workaround: enlarge artificially each groupItem in the palette so that they are larger than their label.
Tested in all locales.

Workaround for CoreAutoLayout hang during runCustomizationPalette on macOS 13.2

---

news/news-4.0.0.md

rendered text: 
https://github.com/transmission/transmission/blob/6d238ec98c58d0fa88140368b1d390717ddc8279/news/news-4.0.0.md

docs: add 4.0.0 release notes

---

.github/workflows/codeql.yml
CMakeLists.txt
cmake/TrMacros.cmake

Fixes: #4752
Notes: Fixed `4.0.0` regression of mistakenly treating warnings as errors when building bundled libb64 and libutp.

Include libb64 and libutp as subprojects

---

libtransmission/resume.cc

Fixes #4712.
Notes: Silenced a misleading "unable to read resume file" error message when adding torrents.

fix: misleading error message when resume file is missing

---

macosx/TorrentCell.mm

The scroller on macOS covers parts of the UI. This PR addresses that.
Fixes: #261
**Before:**
**After:**

added padding to widgets in macOS client to avoid being hidden below scroller

---

docs/Building-Transmission.md

Building instructions for got to mention the requirements for the `python3` package to be installed

Doc: Python v3 required for Debian 11 Bullseye build

---

tests/libtransmission/lpd-test.cc
tests/libtransmission/timer-test.cc
tests/libtransmission/watchdir-test.cc

This shouldn't be a long-term fix -- each of these tests should be fixed instead of disabled -- but they are causing so much noise in CI that I'm disabling them for now and then they can be re-enabled when fixed.
Closes #4747.

chore: disable flaky unit tests

---

.github/workflows/codeql.yml
.github/workflows/webapp.yml

I noticed #4803 triggered runs involving compiling the source code while it was merely suggesting a change to the documentation.
I suppose this PR wil lalso trigger them.
This proposal aims at reducing the cost of PRs merely addressing docs or pipelines definitions.

Fix: Prevent lengthy compilation workflows to run needlessly

---

libtransmission/makemeta.cc
tests/libtransmission/makemeta-test.cc

Fixes #4771 .
Also add a test to ensure that the info-hashes generated for torrents with "private" and/or "source" flags are different to the same torrent without them set.

Fix: Put "private" and "source" inside the metadata "info" key

---

cmake/TrMacros.cmake

Hides a warning when building the dht library.
```
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_CXX_FLAGS
CMAKE_INSTALL_LIBDIR
```

cmake: pass --no-warn-unused-cli to child cmake process

---

libtransmission/announcer.cc

Fixes #4738.
Notes: Fixed nullptr dereference compiler warning.

Fix: Protect against potential nullptr dereference

---

.github/workflows/actions.yml
tests/libtransmission/CMakeLists.txt
tests/libtransmission/file-test.cc
tests/libtransmission/platform-test.cc

By using gtest_discover_tests() each testcase is exposed to ctest as a single test.
This allows more fine-grained reporting and also parallel execution of testcases.

tests: expose libtransmission gtests to ctest

---

libtransmission/peer-io.cc

Fixes a long-standing bug (affects 4.0.0, 3.00, and apparently earlier) where Transmission initiates connection to a BitTorrent peer via uTP and just doesn't realize that the connection is not happening. Ideally we'd fail out of this and retry the connection via TCP.
A less intrusive "quick fix" that's more appropriate for a patch release is to just swap the TCP / uTP order to try TCP first, since we know whether the TCP socket is connected as soon as we call `connect()`.
This gets the job done but I'd like to revisit this to ensure uTP connection failure is detected properly even when we try it as the fallback option.
Notes: Fixed issue that prevented connecting to some BitTorrent peers.

fix: sometimes fails to detect when a uTP socket isn't writable & doesn't connect

---

libtransmission/session.cc

Notes: Fixed `4.0.0` regression that stopped changes to the port forwarding setting from being saved between sessions.
Fixes #4818.

fix: port forwarding flag not saved between sessions

---

qt/TrackerDelegate.cc

Fixes #4782 .
Notes: Fixed display of tracker announce URLs in the details dialog.

fix: display correct tracker port in qt torrent-details

---

libtransmission/peer-mgr.cc

Fixes #4844.
Notes: Fixed `4.0.0` crash that occurred when removing a webseed torrent while downloading.

fix: tr_swarm order of destruction

---

libtransmission/tr-assert.mm

This reverts commit 0493542f62ea362929cc78fe7a8388219dbf4963.
There were no changes in crash reports, and it was causing an extra warning due to `[noreturn]`.

Revert "fix: remove abort() call from tr_assert_message() (#4696)"

---

libtransmission/peer-mse.h

Fixes #4078.
This assertion was based on an invalid premise.

chore: remove invalid assertion test

---

libtransmission/peer-mgr.cc
libtransmission/resume.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent-magnet.h
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h
macosx/Torrent.mm

Fixes #4740.
This is working for me but I'd appreciate testers give it a spin because ... there are so many options & factors that it's complicated :sweat_smile: CI will build executables that you can try while this is still an unmerged PR -- just click to the latest Sanity actions page https://github.com/transmission/transmission/actions/runs/4160296004 scroll to the 'Artifacts' section, and the executables should be there when they finish building.
I'd welcome testers to try this out & test that the right thing happens when you:
CC @Coeur and @sweetppro as collaborators & potential testers, and everyone in 4856 who would like to test

fix: magnet links paused when added

---

libtransmission/completion.cc
libtransmission/completion.h

Fixes #4695.
Notes: Fixed assertion failure in `tr_torrentStat()`.
The bug was in the implementation of `tr_completion::removePiece()`, which would throw off the bookkeeping with pieces that didn't align cleanly on block boundaries.

fix: assertion failed leftUntilDone <= sizeWhenDone

---

libtransmission/inout.cc

Fixes excessive checksum failures when downloading from peers on torrents whose piece size is not a clean multiple of BitTorrent block size.
Thanks to @GaryElshaw and to @sweetppro for pointing in the right direction on this one.
See also: #4879.
Notes: Fixed `4.0.0` regression that caused checksum failures to incorrectly fail when downloading certain torrents.

fix: checksum of pieces that don't align on block boundaries

---

libtransmission/cache.cc
libtransmission/cache.h
libtransmission/peer-msgs.cc
libtransmission/torrent.cc
libtransmission/webseed.cc
tests/libtransmission/move-test.cc

Previous related: #3324, #4879, #4880.
Possibly fixes #820.
Thanks to @GaryElshaw for correctly noticing this smelled similar to 3324 and to @Coeur and @sweetppro for providing test data that helped uncover the problem.
Notes: Fixed `4.0.0` regression that caused checksum failures to incorrectly fail when downloading certain torrents.

fix: handle block fragments that arrive from peers out-of-order

---

macosx/Base.lproj/InfoActivityView.xib

fix an issue where the pieces view can jump around:
https://user-images.githubusercontent.com/7323792/218632047-994e6ce4-18db-45f0-b968-cdf0d10a5292.mov
Notes: Fixed `4.0.0` layout issue in the pieces view

macOS autolayout fixes in info activity view

---

libtransmission/torrent.cc
libtransmission/transmission.h

This is a temporary measure to avoid a regression in Transmission 4.0.1.
Fetching metainfo early will be postponed to #4874 in 4.1.0.

Don't autofetch metainfo at startup and new torrents.

---

gtk/DetailsDialog.cc

Fixes #4883.
Notes: Fixed awkward grammar in the Details Dialog's running-time row.

fix: awkward grammar in details dialog running-time display

---

macosx/GroupTextCell.h
macosx/GroupTextCell.mm
macosx/TorrentTableView.mm

Fixes: #4806
Notes: Fixed `4.0.0` bug that didn't highlight the current selection in `View > Use Groups`.

macOS fix selected Group text color

---

.github/workflows/actions.yml
gtk/CMakeLists.txt
gtk/Percents.cc
gtk/Percents.h
gtk/Torrent.cc
gtk/Torrent.h
gtk/TorrentCellRenderer.cc
gtk/TorrentSorter.cc
gtk/Utils.h

Fixes: #4891
Notes: Fixed `4.0.0` rounding error in the progressbar's percentage display.

Store percents as integer, with 2 digits of precision

---

libtransmission/tr-popcount.h

The `popcnt` feature checks weren't actually checking the ISA feature or cpuid. This caused an illegal instruction exception on x86 hardware that doesn't support `popcnt` when compiled with MSVC.
Since MSVC doesn't support any x86 ISA defines, the only way to check for `popcnt` is with cpuid. Since this is a tiny inline function, dynamic dispatch is likley not worth it so just removing the MSVC for `popcnt`. MSVC will now fallback to the generic implementation.
Fixes #4872.
Notes: Fixed `4.0.0` illegal instruction exception on some x86 Windows machines.

fix: Remove faulty `popcnt` features checks for MSVC [#4872]

---

libtransmission/peer-io.cc
libtransmission/tr-utp.cc

Fixes: #4750
Notes: Fixed `4.0.0` regression resulting in build failures due to incompatible system and bundled libutp headers.

Bump bundled libutp to rollback anonymous unions fix

---

libtransmission/torrent.cc

This reverts commit e4b480ecd45f79ff302a60ad2347a10e8dd7d4db.
This fix is too burdensome; it causes a lot of thread contention. I need to find a different solution.
Reopening https://github.com/transmission/transmission/issues/3811.

fix: revert tr_torrentStat() acquires a session thread lock (#4571

---

libtransmission/handshake.cc
libtransmission/peer-io.cc
libtransmission/tr-utp.cc

A followup to #4826 which correctly diagnosed a problem (utp connections did not timeout correctly) but had a suboptimal solution. **Big** thanks to @reardonia for the review and analysis of both Tr3 and Tr4.
This PR:
- Reverts 4826 to restore the behavior of trying a uTP peer connection before TCP.
- Fixes a Tr3 and Tr4 bug that did not start the uTP upkeep timer until there was uTP peer data received. This meant that in the edge case of starting a new Transmission session with a new torrent whose peers were TCP-only, those uTP connection attempts would never timeout because the "check timeouts" timer had never been started :dizzy: 
- Fixes a Tr4 bug that did not handle uTP errors correctly in `handshake.cc`, preventing a TCP retry from occurring.
@reardonia code review welcomed :heart: …

fix: try utp connection first; fix utp timeout issues.

---

gtk/Utils.cc

Fixes: #4934
Notes: Fixed `4.0.0` regression leading to application becoming unresponsive on show/hide via system tray icon menu (GTK 3 only).

Only show/hide top-level windows on systray action

---

cmake/FindUTP.cmake

Configuring yielded:
Could NOT find UTP (missing: UTP_LIBRARY UTP_INCLUDE_DIR)
Call Stack (most recent call first):
/very/long/path/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
cmake/FindUTP.cmake:74 (find_package_handle_standard_args)
cmake/TrMacros.cmake:136 (find_package)
CMakeLists.txt:503 (tr_add_external_auto_library)
-- Configuring incomplete, errors occurred!
See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeError.log".
The error logs included this bit:
/very/long/path/bin/ld: /very/long/path/lib/libutp.a(utp_internal.cpp.o): in function `UTP_FreeAll(UTPSocketHT*)':
(.text+0xc15): undefined reference to `operator delete(void*)'
After changing …

build: Use CXX symbol checking to verify system libutp

---

web/src/transmission.js

Right now the `labels:` filter does not allow searching labels containing spaces or hyphens, this minor change fixes it.

Allow searching labels with spaces and hyphens

---

libtransmission/blocklist.cc

Fixes #4949.
Notes: Fixed `4.0.0` bug that caused blocklists to use more memory than necessary.

fix: blocklists allocate more memory than they need

---

.github/workflows/actions.yml
cmake/TrMacros.cmake

Don't copy third-party directories into themselves (actually, don't copy them at all) by switching from `URL` to `SOURCE_DIR`. Separate build, source, and install directories for third-party libraries.
Despite out-of-source builds being "strongly encauraged"[^1], people unfamiliar with CMake keep doing the opposite (see #1264, #2997, #3062, #3479, #4945). I first considered erroring out when in-source build is attempted, but this would've led to us still needing to educate people on what building out-of-source means, which is not something I want to spend my time on.
[^1]: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html

Support in-source builds

---

cmake/FindDEFLATE.cmake

`DEFLATE_VERSION` was never set but was listed as required. Move it from `REQUIRED_VARS` to `VERSION_VAR` and populate properly.
Notes: Fixed build issue that prevented preinstalled copies of libdeflate from being used

build: fix libdeflate find module never finding anything

---

tests/CMakeLists.txt

Setting `-DENABLE_UTILS=0 -DENABLE_TESTS=1` causes CMake errors due to tests/utils/CMakeLists.txt referencing `$<TARGET_FILE:transmission-show>` which is undefined.  Fixed by including the tests/utils/ directory only if `ENABLE_UTILS` is true.

build: do not test utils if not building utils

---

libtransmission/open-files.cc

Fixes #4977.
Notes: Fixed `4.0.0` build failure when compiling with Clang on Windows.
Thanks to @fghzxm for realizing the problem

fix: cannot build with clang on Windows

---

web/assets/css/transmission-app.scss

Mostly fixes #4983
(images from @rcunov)
Before:
After:

fix: make context menu highlighted row readable in dark mode

---

docs/rpc-spec.md

Followup to #1682.
Fixes #4997.
Notes: Fixed `4.0.0` RPC spec documentation error.

docs: fix RPC documentation error

---

news/news-4.0.1.md

quick link to rendered page:
https://github.com/transmission/transmission/blob/docs/4.0.1-release-notes/news/news-4.0.1.md

docs: add 4.0.1 release notes

---

libtransmission/torrent.cc

At least on my Linux box, a script doing `export | grep TR_` showed weird results like:
`declare -x TR_TIME_LOCALTIME="TR_APP_VERSION=4.0.0-dev"`
or
`declare -x TR_TIME_LOCALTIME="TR_TIME_LOCALTIME"`
This patch fixes it, since the formatted time string is now kept on the stack.
Notes: fix the value of TR_TIME_LOCALTIME passed to scripts

fix: TR_TIME_LOCALTIME contained garbage when calling a script

---

macosx/Controller.mm

Fixes #5013
<details>
<summary>After:</summary>
</details>

fix: Use bounds for relative NSPopover positioning.

---

macosx/InfoWindow.xib

```
transmission/macosx/InfoWindow.xib:5:1: Minimum size {350, 77} is larger than content size {403, 70}
```

fix: Update Inspector window frame to fix AutoLayout warning.

---

libtransmission/file-posix.cc

This reportedly helps with copying to cifs target where `copy_file_range()` would sometimes return `EINVAL` for no apparent reason when copying large files. Extending the limit to `sendfile64()` to avoid similar issue there, if it exists.
Overall, copying at most 2 GiB at a time will result in more syscalls but shouldn't affect the performance gain in any noticeable way.
Notes: Limited in-kernel file copying to 2 GiB blocks at a time to avoid potential issues with CIFS mounts.

Limit in-kernel file copying to 2 GiB blocks at a time

---

macosx/Controller.mm

Fix: #4683
It's a regression between Transmission 3.0.0 and 4.0.0, introduced by #2343.

Workaround for Firefox downloads happening in two steps: first time being an empty file

---

web/src/action-manager.js

I changed the modifier key from `Alt` to `Control`, which makes it possible to use it on macOS.
The `Deselect all` shortcut has also been changed from `Control+A` to `Control+D`.
fixes #4829

change alt to control for shortcuts

---

macosx/CocoaCompatibility.h
macosx/GroupsPrefsController.mm

Only on macOS Ventura (13.0+), as AppKit changes were introduced here.
Somewhat fixes #5011
<details>
<summary>Comparison</summary>
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="752" alt="Screenshot 2023-02-24 at 01 20 12" src="https://user-images.githubusercontent.com/8330119/221043652-1b4df3d0-2068-4172-be3e-695231d99a9b.png">
<td><img width="752" alt="Screenshot 2023-02-24 at 01 18 13" src="https://user-images.githubusercontent.com/8330119/221043678-19da1f18-ce33-4c4d-87a2-77f90e32852d.png">
</table>
</details>

feat: Use updated minimal NSColorWell style for Groups.

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml

There has been a wealth of users over-sharing their unlicensed or illegal content during the 4.0 release process when they file issues, and i thought it might be worthwhile to make it explicit that it's not wanted. I usualy ask people to obscure it, but some think this is a suggestion.

docs: warn users about bannable actions in the issue template

---

libtransmission/peer-mgr.cc

Fixes #5069.
Notes: Fixed `4.0.0` assertion failure when a user-configured setting specified a very low peer limit.

fix: std::clamp() assertion failure in rechokeDownloads()

---

docs/Editing-Configuration-Files.md
docs/rpc-spec.md

When bringing my `transmission-daemon` settings up to version 4.0, I had to search through the commit history to find out what some of the new settings do. I documented all those settings based on what I found and tested.
I'm not entirely certain if I missed something for `enable-tcp`, e. g. I'm not sure whether it influences the connection to the tracker.
I also fixed some minor typos.
I could not find ` tr_inactvelimit`, `tr_inactivelimit` or spelling variations thereof in the source code, so I'm also not sure whether it should even still be there.

docs: document new settings

---

libtransmission/peer-io.cc

fix: 4.0.0 regression that broke speed limits for utp peers

---

web/assets/css/transmission-app.scss
web/src/torrent-row.js

This was a regression that I missed from last year.
The web client now uses the same progress indicators from the client,
and also slightly changes the color based on light/dark mode.
Fixes #4303

fix: restore client-level progress indicators

---

libtransmission/peer-io.cc

Fixes #5057.
@GaryElshaw there are always going to be second-to-second discrepancies -- particularly in the qt client because its UI is intentionally designed to "lazy-update" so that the same code that runs for a local session can play nice with a remote session that may involve a lot of lag -- but there was a bookkeeping error here that could throw off instantaneous counts. Thanks for reporting this!

fix: 4.0.0 bookkeeping of protocol overhead when receiving peer messages

---

macosx/NSStringAdditions.mm

Fix: max 4 significant digits for speed.
Three edge values were fixed:
- A speed of `999.95` should display as "1.00 M", not "1000.0 K"
- A speed of `99995` should display as "100.0 M", not "100.00 M"
- A speed of `999950` should display as "1.00 G", not "1000.0 M"

fix: max 4 significant digits for speed

---

libtransmission/makemeta.cc
tests/libtransmission/makemeta-test.cc

Fixes #5105.
Notes: Always include a `announce` key when creating a new torrent, regardless of multitracker status.

fix: always add `announce` key even when including announce-list

---

libtransmission/resume.cc
libtransmission/resume.h
libtransmission/torrent-metainfo.cc
libtransmission/torrent.cc
tests/libtransmission/rename-test.cc

Fixes #5053.
Old torrent files will still reappear once since they are sitting around in the `torrents/` directory from years before. But the worse issue was about how they would keep coming back again and again after being removed.
This PR should fix that by ensuring that any files using the old `${name}.${infohash.substr(0, 16)}.torrent` naming scheme will be migrated to the new `${infohash}.torrent` naming scheme.
Notes: Fixed `4.0.0` bug where macOS users could see some of their old torrents reappear after removing & restarting.

fix: 5053 old torrent files keep appearing

---

qt/DetailsDialog.cc
qt/RpcClient.cc

Fixes #4985.
Notes: Fixed `4.0.0` bug that prevented batch-adding trackers to multiple torrents at once.

fix: correctly handle batch-adding trackers to multiple torrents

---

libtransmission/variant-json.cc
tests/libtransmission/json-test.cc

Fixes #1718.
According to [ECMA 404](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) : 
> To escape a code point that is not in the Basic Multilingual Plane, the character may be represented as a twelve-character sequence, encoding the UTF-16 surrogate pair corresponding to the code point. So for example, a string containing only the G clef character (U+1D11E) may be represented as "\uD834\uDD1E".
This currently doesn't work correctly in Transmission, as it converts the internal UTF-8 representation of its strings to UTF-32 and appends the absolute code point value as the escaped `\u` token. This is incorrect, since the UTF-16 encoding is not equal to UTF-32 for characters outside the BMP due to UTF-16's usage of high and low surrogates to …

fix: escaped representation of non-BMP characters when generating JSON

---

.github/workflows/actions.yml

Homebrew libraries aren't meant for redistribution so don't use them for one of the two Mac builds to make it suitable for testing. Making Transmission binary inside the bundle executable is still necessary, but that's minor. Build time seems to be about the same.
Related to the discussion in #5079.

Use bundled deps for GHA build from tarball on Mac

---

docs/Testing-Transmission.md

Documenting the required steps to get a CI build to run on macOS, in order to more easily inform testers and avoid the trouble that happened during #5079.

doc: How to find and open a CI build on macOS

---

libtransmission/peer-msgs.cc

Fixes 7f9ef4730 regression reported by @boreq in https://github.com/transmission/transmission/issues/5081#issuecomment-1454986632.
Marking as `notes:none` since this bug was only present in the nightlies.

fix: 7f9ef4730 use-after-free in peerMsgs::canRead

---

web/assets/css/transmission-app.scss

Current selected color `#2e2e2e` is indistinguishable from unselected even row `#292929`. Make it bluish `#0c2d6b`. It's copied from github's dark mode `--color-scale-blue-8`. I'm open to any other values though.
Before:
After:

fix: selected torrent row color in dark mode

---

macosx/BadgeView.mm

Fix #5072
The adopted approach is with the existing images UpArrowTemplate and DownArrowTemplate, at a fixed position and size for the arrow, and a fixed font size for the text.
Rendering after second commit:
Rendering after third commit:
This needs UI review from multiple reviewers, regarding:
a. is that image usage desirable (it matches the other displays of speed in the app), or would we want to change it to a new glyph, like ▲ and ▼?
b. do we want the arrow at a fixed horizontal position, or left-attached to the text?
c. do we want the arrow at a fixed size, or variable size matching the text height?
d. do we want to keep the text in the center, or do we want to left or right-align the text now?

feat: Badge with arrow

---

docs/Building-Transmission.md

Just adding this because I had to install `libmbedtls-dev` in addition to the packages already listed in `Building-Transmission.md` for Ubuntu, in order for CMake to configure properly.
I am on Ubuntu 22.04 LTS.

docs: add libssl-dev to Ubuntu dependencies

---

libtransmission/announcer.cc

This is a quick solution to #2932 which "does no harm". But it really deserves a more complete refactor.
To restate the problem: if the announcer never saw a "leechers" key in the response from the tracker, then the response.leechers value remains unset.  publishPeerCounts() actually ignores "seeders" value but does use the leechers value to set the SwarmIsAllSeeds flag, which in turn determines whether outbound connections are made.  The way the code is structured, the local-scope leechers value is set to {0} while the response.leechers value remains at {-1}, but the former is sent to publishPeerCount(). So most torrents end-up in a ping-pong between the announce&scrape, where SwarmIsAllSeeds is set/unset incorrectly.
Note that out of 12 private trackers I tested, only 1 was returning …

Only publish 'leechers' if it was actually returned during the announce

---

libtransmission/file-piece-map.cc
libtransmission/file-piece-map.h
tests/libtransmission/file-piece-map-test.cc

Discussion @ https://github.com/transmission/transmission/pull/4795#issuecomment-1455131323
First & last prioritization was the correct behavior in 3.00 and earlier but that logic got lost in 4.0.0. This PR restores it.
Notes: Fixed `4.0.0` regression that stopped increasing the download priority of files' first and last pieces. These pieces are important for making incomplete downloads previewable / playable while still being downloaded.
CC @pldubouilh

fix: increase priority of first and last piece of each file

---

docs/rpc-spec.md
libtransmission/rpcimpl.cc

This patch forces the "wanted" RPC field as an integer-proxy for bool during JSON serialization.
Ok, this will probably raise a few eyebrows, but offering this to fix a Tr3 compat problem:
Tr3 and earlier serialize the "wanted" RPC field as a 0/1 integer, not a "true/false" bool. During the Tr4 refactor (git@ecef0feb0c) a change was made for the output serialization from Int() -> Bool() so that it would match the input serialization, but unfortunately this breaks backward compat.
Older code (and many older JSON libraries) may not be particularly resilient to the use of "true/false" vs "0/1".  In particular, the popular _Transmission Remote GTK_ tool wants this to be a 0/1 integer or fails to recognize the do-not-download state (DND in <=Tr3) of individual files.
Recommend keeping the Tr3 …

Revert "wanted" RPC field to integer, not bool

---

gtk/Application.cc
gtk/Application.h
gtk/main.cc

Fixes: #5094
Notes: Fixed `4.0.0` ignoring `-m`/`--minimized` command line option.

Split current and initially requested minimized state

---

macosx/BadgeView.mm
macosx/NSStringAdditions.mm

Increasing fontSize by 2 (from 21 to 23), based on feedback from @ilikepeaches on #5095. The fontSize of 21 was a visual regression caused by me preserving too much space for the arrow in previous PR.

Hardcoding BadgeView fontSize

---

docs/Testing-Transmission.md

On macOS, downloading the other artefact may not work on all machines, due to what was explained in #5126.

Download needs to be the "from-tarball" artefact

---

.github/workflows/actions.yml
.github/workflows/webapp.yml
libtransmission/rpcimpl.cc
libtransmission/torrent.cc
libtransmission/torrent.h

Fix a couple of clang-tidy warnings introduced in recent commits.
Add CI check to ensure clang-tidy libtransmission passes.
No behavioral changes.

ci: check for clang tidy errors in libtransmission

---

macosx/BadgeView.mm
macosx/NSStringAdditions.h
macosx/NSStringAdditions.mm

So... historically
1. I didn't choose whether adding a UI element was a "patch" or a "minor" change. I had no particular opinion, positive not negative. But I'm happy with the result ([thank you ckerr](https://github.com/transmission/transmission/pull/5095#issuecomment-1450545388)).
2. I wrongly assumed that the longest string would be "987,6 K". Actually, "64,40 M" is the longest one in system font.
3. I originally had a left margin of `badgeSize.height * 0.15`, but I followed code review recommendations to increase it to `badgeSize.height * 0.2` (and this was a good change: it looks better, [thank you nevack](https://github.com/transmission/transmission/pull/5095#issuecomment-1452253094)).
4. When I made calculations for ideal font size (21), it got considered too small ([thanks for …

fix: change badge font size, position and precision

---

libtransmission/peer-mgr.cc

Fixes #5165.
I'm considering including this for 4.0.2 which is scheduled for Wed Mar 15 but before then, I'd *really* like to get some testing on this. It's working really well for me but I'd like more opinions on what effect (if any) this change has on downloading.
This dances dangerously close to the "speeds are slow" issue that is a catch-all for everything under the sun and so I want to spell out specifically what this will do:
- In `4.0.2`: Transmission shows interest in a peer if it has pieces that we want **and** if we haven't sent "too many" cancels to any peer in the swarm recently. (This was intended as a heuristic for deciding if bandwidth limits were being reached.)
- In this PR: Transmission shows interest in a peer iff it has pieces that we want.

fix: remove interest strategy code that could make dl speeds oscillate up & down

---

qt/Torrent.h

Fixes #4708 by updating `Torrent::ratio()` to match #2770.
Notes: Fixed per-torrent ratio display in main window.

fix: update Torrent::ratio() to match #2770

---

tests/libtransmission/CMakeLists.txt

Based on discussion in SynoCommunity/spksrc#5616 and [cmake/cmake#18840](https://gitlab.kitware.com/cmake/cmake/-/issues/18840).
Notes: Fixed `4.0.1` failure to discover tests when cross-compiling without an emulator.

Don't discover tests when cross-compiling w/o an emulator

---

libtransmission/rpcimpl.cc

Fixes #5201.
Notes: Fixed `4.0.0` error that did insufficient sanity checking of unsupported magnet links added via RPC.

fix: check tr_ctorSetFoo() return values before adding torrent via RPC

---

libtransmission/peer-msgs.cc

Fixes https://retrace.fedoraproject.org/faf/reports/631667/ .
The issue was a call to `std::clamp(val, lo, hi)` where we passed a `hi` that was less than `lo`.
similar fix in peer-mgr.cc: ac319321b #5080
Notes: Fixed `std::clamp()` assertion failures.

fix: std::clamp() assertion failure in maxAvailableReqs()

---

macosx/NSStringAdditions.mm

Fix small regression in precision ranges caused by #5184.

fix: precision in stringForSpeedCompact

---

libtransmission/inout.cc

Fixes #1130.
Notes: Fixed a misleading error message when Transmission is unable to write to the incomplete-dir.

 fix: wrong error message when writing to incomplete dir

---

cli/transmission-cli.1

I saw a patch in[ debian repository](https://salsa.debian.org/debian/transmission/-/blob/2bc995ee96301ac8d1797475384919eb6100b23b/debian/patches/0002-fix-remove-empty-line-in-manpage.patch) made by Leo and figured it might as well be in the main repository to make their future packaging job cleaner.

Remove empty line in manpage

---

web/src/prefs-dialog.js

`max-peers-global` and `max-peers-per-torrent` does not have a corresponding `*-enable` option or anything equivalent to that.

fix: remove extra checkboxes from webui peers preferences

---

docs/Editing-Configuration-Files.md
libtransmission/announcer.cc
libtransmission/peer-mgr.cc
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/session-settings.h
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h

Fixes #5232.
Notes: Updated Peer ID generation to happen once per session.

fix: generate peer-id on launch

---

utils/remote.cc

'Downloaded' field is now shown when calling transmission-remote -i. Fixes #5262 .

Fix: 'downloaded' field

---

.github/workflows/actions.yml
libtransmission/file-piece-map.cc
libtransmission/file-piece-map.h

Figuring out which blocks to ask for next got more expensive in terms of CPU in #5167 due to the extra logic in that function. The code isn't that complicated, but it's called so many times that it adds up quite a bit.
This PR is a minimal do-no-harm refactor to add `constexpr` and avoid an unnecessary test. This doesn't entirely fix the CPU regression (which is why this is pt. 1) but it does help and is a minimal change.
Notes: Fixed CPU load regression that #5167 introduced in 4.0.2.

fix: 4.0.2 wishlist CPU perf regression pt. 1

---

gtk/ui/gtk3/PrefsDialog.ui
gtk/ui/gtk4/PrefsDialog.ui

Fixes #5257.
Notes: Fixed preferences dialog being too large for small displays.

fix: GTK client prefs window too large for small displays

---

libtransmission/completion.cc

Might be a bogus analyzer warning from Xcode 14.3 (released two days ago), but now it's going to always show for months if we don't workaround it.

fix: The right operand of '<' is a garbage value

---

libtransmission/utils.cc

This includes percents, ratios, sizes, speeds, etc. coming from shared formatting helpers. Previously based on sprintf-like functions using locale, now using libfmt which doesn't use locale by default and needs to be instructed to do it explicitly.
Fixes: #5284

Use locale-dependent decimal separators for user-visible numbers

---

macosx/Controller.mm

Problem: while [`NSApplicationLaunchUserNotificationKey` is documented as returning an `NSUserNotification`](https://developer.apple.com/documentation/appkit/nsapplicationlaunchusernotificationkey?language=objc), it is actually an `UNNotificationResponse` in reality. So when you tap on a notification button "Show", Transmission may crash on launch. This is a regression introduced with #3040.
Solution: adopt the correct handler for macOS 10.14 and newer.
Tested: on macOS 10.14.6 and macOS 13.3.

fix crash on launch from tapping on a notification

---

AUTHORS

Update the `AUTHORS` file, as inspired by [this discussion](https://github.com/transmission/transmission/discussions/4736#discussioncomment-5357038) about giving people credit where it's due.
CC @transmission/contributors for review
Goals:
- Elevate @transmission/contributors to give them their due credit
- Remove email addresses
- Make explicit that individual contributions are now credited in release notes so that extra contributions get extra shout-outs. No need to update `AUTHORS` when someone new lands a PR.
Questions
- Gary's not on here. I could've sworn he was in `@transmission/contributors` but apparently not? I don't remember what's going on here so thought I'd ask. I don't want to omit anyone who wants credit.
- One other active contributor :heart:  is omitted here. I did that …

docs: update AUTHORS

---

docs/Editing-Configuration-Files.md
libtransmission/announcer-http.cc
libtransmission/net.cc
libtransmission/net.h

Closes #5206.
Added more details to the docs that describe the behaviour of the `bind-address-ipv*` settings. You may notice that IPv4 and IPv6 behaviour are not entirely the same. ~I intend to align `bind-address-ipv6` behaviour with `bind-address-ipv4` after this PR, hence "intermediate fix"~.
Edit: I now see that the reason for the IPv6 behaviour is for efficient DHT, and the reason why IPv4 is not like IPv6 is because of the existence of NAT. I won't align the behaviour.
For the very least, setting `"bind-address-ipv6": "::"` and `"bind-address-ipv4": "0.0.0.0"` now gives the behaviour you would expect.
`main` branch before this PR:
- **If libcurl version < 7.77.0, and/or `announce-ip-enabled: true`, and/or `bind-address-ipv6: "::"`:**
Transmission will announce once without …

Intermediate fix for HTTP announce behaviour affected by `bind-address-ipv*`

---

libtransmission/net.cc

```
commit 36edd516aa550c8b08f0b18fd9cc3e51b843e3f4
Author: Charles Kerr <charles@charleskerr.com>
Date:   Sun Nov 6 10:35:48 2022 -0600
refactor: replace tr_boundinfo with tr_session::BoundSocket (#4103)
diff --git a/libtransmission/net.cc b/libtransmission/net.cc
--- a/libtransmission/net.cc
+++ b/libtransmission/net.cc
@@ -500,1 +496,1 @@
-        auto const fd = tr_netBindTCPImpl(&tr_in6addr_any, port, true, &err);
+        auto const fd = tr_netBindTCPImpl(tr_address::AnyIPv4(), port, true, &err);
```

Fix tr_net_hasIPv6()

---

libtransmission/session.cc

Right now, the daemon logs will miss any logs below `ERROR` level when constructing `tr_session`.

Set log level before constructing tr_session for daemon

---

gtk/ui/gtk3/PrefsDialog.ui
gtk/ui/gtk4/PrefsDialog.ui

A follow-up to #5276 that hopefully resolves user feedback. https://github.com/transmission/transmission/pull/5276#issuecomment-1500055454
Notes: Fixed preferences dialog being too large for small displays.

Reduce GTK Prefs.ui size to 90

---

libtransmission/torrent-metainfo.cc

Fixes #5354.
Notes: Fixed minor warnings for `cross_seed_entry` and `uid` entries in torrent files.

fix: silence torrent-metainfo warnings for cross_seed_entry, uid

---

Transmission.xcodeproj/project.pbxproj
libtransmission/CMakeLists.txt
libtransmission/utils.mm
macosx/CMakeLists.txt
macosx/QuickLookPlugin/CMakeLists.txt

Fix #5212.
Followup of #5244 for compilation flags when using cmake.
I cherry picked #4931 because really that one should have been a patch, otherwise building with Xcode and cmake are using different compilation flags and that causes unexpected behaviors depending on which tool is used for a release.

Fix Potential leak of an object of type 'NSString * _Nullable'

---

.github/workflows/actions.yml

Fixes `Sanity / Windows` GitHub Actions CI failure:
```
Uninstalling the following packages:
openssl.light
openssl.light is not installed. Cannot uninstall a non-existent package.
Chocolatey uninstalled 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
- openssl.light - openssl.light is not installed. Cannot uninstall a non-existent package.
If a package uninstall is failing and/or you've already uninstalled the
software outside of Chocolatey, you can attempt to run the command
with `-n` to skip running a chocolateyUninstall script, additionally
adding `--skip-autouninstaller` to skip an attempt to automatically
remove system-installed software. Only the packaging files are removed
and not things like software installed to …
```

ci: fix Sanity/Windows GitHub Actions

---

libtransmission/rpcimpl.cc

Same behavior as Transmission 3 to avoid unnannounced API change.
Fixes #5355.

fix: return success on RPC add-torrent duplicate

---

libtransmission/torrent-metainfo.cc

Fixes #5347.
Notes: Fixed use of metainfo display-name as a fallback name.

fix: only torrent metainfo display-name as a fallback

---

web/src/transmission.js

Fixes #5326.
Notes: Turned off keyboard shortcuts when input fields have focus.

fix: check for input focus before looking at keyboard shortcuts

---

news/news-4.0.3.md

rendered: https://github.com/transmission/transmission/blob/docs/release-notes-4.0.3/news/news-4.0.3.md

docs: add 4.0.3 release notes

---

libtransmission/utils.cc
libtransmission/utils.h

Three changes:
1. This change re-adds 1 digit after the dot/comma for small values, in order to align with macOS string display (partial revert of efc306a8d34eab842b296e4833cf7fafe8e3bb80)
2. This change increases digits precision for large values, in order to align with macOS string display.
3. Edge cases significants (same as #5100):
- A speed of 999.95 should display as "0.98 M" or "1.00 M", not "1000.0 K" (only affects after adding 1 digit after the dot)
- A speed of 99995 should display as "100.0 M", not "100.00 M" (only affects when kilo is 1000)
- A speed of 999950 should display as "1.00 G", not "1000.0 M" (only affects when kilo is 1000)

Align tr_formatter_speed_KBps with `stringForSpeed: kb: mb: gb:`

---

macosx/Base.lproj/MainMenu.xib
macosx/Controller.mm
macosx/Torrent.h
macosx/Torrent.mm

(This supersedes #2302)
This fixes #2279.
This new feature for macOS adds one string for translation ("ETA" in the xib), so it's not appropriate for Transmission 4 and should be only merged for Transmission 5.
Presently, with the ETA sort, I sort seeding torrents by name (same logic as sorting by progress).
Alternatively, with the ETA sort, we could sort seeding torrents by completion date (but do we have this information?).

Add sort by ETA for macOS

---

macosx/Base.lproj/MainMenu.xib
macosx/Controller.h
macosx/Controller.mm

This is a enhancement for the macOS app: added missing support for showing "Show Toolbar" after hiding the toolbar.
As this requires translations, setting Milestone to "Decide after 4.0".

feat: added support for displaying "Show Toolbar"

---

qt/DetailsDialog.cc
qt/PrefsDialog.cc
qt/Utils.cc
qt/Utils.h
qt/translations/transmission_sl.ts

As mentioned in #5111, thanks for the feedback.
If `%1` is omitted, the behaviour stays the same as before (the string is used as suffix only).
How would integration with transifex work, if this code is merged? Also, would it be better to change all spinboxes to this format, or should it be done on case-by-case basis?

Add more complex formatting to a spinbox

---

libtransmission/tr-buffer.h
tests/libtransmission/buffer-test.cc

This is a prerequisite step for decoupling message-building from Buffer.
For example, it would be nice to use a stack-allocated container from [sfl-library](https://github.com/slavenf/sfl-library) instead of requiring heap memory via `evbuffer` or `std::vector`.

feat: Add libtransmission::BufferWriter class

---

libtransmission/bitfield.cc
libtransmission/bitfield.h
tests/libtransmission/bitfield-test.cc

Faster than `operator &=` if we only need to know that some intersection exists.

feat: add tr_bitfield::intersects()

---

libtransmission/session-id.h

Valgrind complains about these not being initialized.

fix uninitialized session_id_t values

---

macosx/BlocklistDownloader.h
macosx/BlocklistDownloader.mm
macosx/Controller.h
macosx/Controller.mm
macosx/FileOutlineController.mm
macosx/InfoWindowController.mm
macosx/PortChecker.h
macosx/PortChecker.mm
macosx/PrefsController.mm
macosx/StatusBarController.mm
macosx/Torrent.h

Continuing the work from https://github.com/transmission/transmission/pull/3974, this PR updates the remaining enums defined in objc code to use idiomatic types (NSUInteger as opposed to unsigned int) and names (port_status_t -> PortStatus).
The advantages are the following:
- It's easier to differentiate from types defined in C/C++ (e.g. libtransmission types)
- It unifies the naming & typing with Apple-defined enums, and most other objc enums in the project
- It facilitates the potential usage of these enums from Swift

refactor: use idiomatic enum names & types in objc

---

macosx/QuickLookPlugin/GeneratePreviewForURL.mm
macosx/QuickLookPlugin/style.css

Adopts more Finder style for QuickLook plugin:
1. A grey background with round corner for one row out of two.
2. File size in grey font.
This is inspired by #1739, although I didn't change the font size, which was the primary request of the originator.

quicklook: alternate row background color

---

libtransmission/tr-buffer.h

Improve libtransmission::Buffer iterator performance.
This was a preexisting condition but it was exacerbated by increased iterator use in ed4919a4f49343d2e73559e6758bd1462838b930 (#5154).

perf: in Buffer::Iterator, defer evbuffer API calls

---

cli/cli.cc

Fixes #5424.
Notes: Fixed "no such file or directory" warning when adding a magnet link.

fix: no such file or directory warning in transmission-cli

---

libtransmission/tr-buffer.h
tests/libtransmission/buffer-test.cc

fixup unreleased Buffer bug introduced by the BufferWriter refactor in ed4919a4f49343d2e73559e6758bd1462838b930. The problem was that the move operator should not change the parent BufferWriter's pointer field.
Fixes #5422.
Does not affect 4.0.x branch since `BufferWriter` is new in 4.1.0-dev

fix: Buffer::Buffer(Buffer&&) bug 

---

libtransmission/peer-io.cc

fix `tr_peerIo::write(Buffer&)`, which broke as a side-effect of the 4.1.0-dev BufferWriter refactor. 4.0.x is unaffected.
The issue is that `tr_peerIo::write(Buffer&)` still needs to consume the buffer contents.
Fixes #5423.

fixup! feat: Add BufferWriter class (#5154)

---

libtransmission/torrent-magnet.cc

Fixes off-by-one bug in [BEP 9](https://www.bittorrent.org/beps/bep_0009.html) implementation that prevented the final piece of metadata from being sent.
Affects `4.0.0` through `4.0.3`.
Notes: Fixed bug in sending metadata files to peers.

fix: bug that prevented providing the final metadata piece

---

.github/workflows/actions.yml

Temporary workaround for what appears to be an upstream issue from https://github.com/Homebrew/homebrew-core/pull/129122 -- that landed at the same time that this breakage was introduced.
I haven't opened an upstream issue yet since I haven't tested firsthand on a macOS box.
The breakage is:
> In file included from /Users/runner/work/transmission/transmission/src/libtransmission/port-forwarding-natpmp.cc:16: /usr/local/include/natpmp.h:52:10: fatal error: 'natpmp_declspec.h' file not found
> 1 error generated.

ci: do not install homebrew libnatpmp on macos 11

---

cli/cli.cc
daemon/daemon.cc
gtk/main.cc
libtransmission/utils.cc
libtransmission/utils.h
macosx/main.mm
qt/Application.cc
tests/libtransmission/json-test.cc
tests/utils/run_transmission_show.cmake
utils/create.cc
utils/edit.cc
utils/remote.cc
utils/show.cc

Previous fix adding `L` format specifier was correct but only fixed half of the problem, as C++ locale is set up to be "C" by default. GTK client used to call `setlocale(LC_ALL, "")` to set up user-preferred locale which only affected C functions and `std::locale` (used by libfmt) was unaware of those changes.
Apply the fix to all the binaries since they're all doing some sort of output to the user and calling libtransmission helpers, as well as using libfmt directly.
Fixes: #5284

fix: use user-preferred locale

---

tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/buffer-test.cc
tests/libtransmission/dht-test.cc
tests/libtransmission/session-alt-speeds-test.cc
tests/libtransmission/utils-test.cc

Minor typo fixes,
Hmmm a few things there i can see i've mistakenly 'corrected'. The changes that look good are:
- tests/libtransmission/announcer-udp-test.cc
- tests/libtransmission/dht-test.cc
- tests/libtransmission/session-alt-speeds-test.cc
- tests/libtransmission/utils-test.cc

Typos in libtransmission tests

---

libtransmission/bitfield.cc
libtransmission/net.cc
libtransmission/session.cc
libtransmission/tr-utp.cc

One of a few potential typo fixes in libtransmission

Typos in libtransmission

---

libtransmission/net.cc
libtransmission/net.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/tr-udp.cc

Follow up of #5329.
1. Removed `tr_session::bindAddress()`. It was added for `tr_global_ip_cache` to get the `bind-address-ipv*` parameters, but it is no longer used.
2. Replaced `tr_net_hasIPv6()` usages with `tr_session::has_ip_protocol()`.

Follow-up and clean-up of `tr_global_ip_cache` PR

---

gtk/transmission-gtk.metainfo.xml.in

The first patch is derived from a patch that has been included in the Flathub version for 5+ years. The others are improvements I added while I was here.

GTK: Improve appstream metainfo

---

gtk/DetailsDialog.cc
gtk/FilterBar.cc
libtransmission/announce-list.cc
libtransmission/announce-list.h
libtransmission/announcer.cc
libtransmission/rpcimpl.cc
libtransmission/torrent.cc
libtransmission/transmission.h
macosx/Torrent.mm
macosx/TrackerNode.mm
tests/libtransmission/announce-list-test.cc

Having port information in a "host" field is non-intuitive and potentially bugprone if someone uses the host field as a host.

refactor: rename tr_tracker_view.host to .host_and_port for clarity

---

libtransmission/announcer-udp.cc
libtransmission/peer-msgs.cc
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/variant-json.cc
libtransmission/variant.cc

Now that we have BufferReader and BufferWriter base classes, modify functions that took Buffer references to take Reader / Writer references instead.
This is partly a cleanliness PR, since code that needs a reader doesn't need access to a Buffer's Writer methods, and partly prepwork for adding sfl-library Buffers.

refactor: use BufferReader, BufferWriter as function args

---

libtransmission/peer-msgs.cc

Since max size is small and known at compile time, we can avoid extra heap allocations

perf: use std::bitset instead of tr_bitfield in incoming_piece_data

---

libtransmission/peer-mgr-active-requests.cc

Both a perf  improvement and a fix of unintentional (but harmless) code: avoid accidentally inserting elements into a map in `ActiveRequests::count()`.

fix: avoid unintentional map insertions in ActiveRequests::count()

---

libtransmission/cache.cc
libtransmission/cache.h
libtransmission/peer-msgs.cc
libtransmission/webseed.cc
tests/libtransmission/move-test.cc

block size is known at compile time, so use a `std::array` instead of a `std::vector` to hold block data.

perf: avoid extra heap alloc in block cache

---

libtransmission/handshake.cc
libtransmission/handshake.h

Cache the value of `ENCRYPT(VC)` instead of recomputing it every time `read_vc()` is called.
Notes: Avoid unnecessary heap memory allocations.

perf: avoid extra work in read_vc()

---

libtransmission/announcer-udp.cc
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mse.h
libtransmission/peer-msgs.cc
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/tr-buffer.h
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/variant.cc
tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/buffer-test.cc

There have been a lot of CI failures in the couple of days. I don't understand the regression yet but it appears to be related to the buffer refactor, so this PR reverts that. If CI is happy with this PR, I'll merge it and try to figure out what was wrong with the refactor.

fix: revert buffer reserve space

---

code_style.sh

In many cases the webui code is not updated for core libtransmission changes and changes in the utils/clients. Therefore, check to see if any web changes are made before running npm linting.

Only format JS if files in web/ change

---

libtransmission/peer-msgs.cc
libtransmission/tr-buffer.h
tests/libtransmission/buffer-test.cc

experimental rollback of part of 2cf96787 to narrow down what caused the CI failure

refactor: restore part of Buffer::reserve_space()

---

libtransmission/handshake.cc
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mse.cc
libtransmission/peer-mse.h
libtransmission/tr-arc4.h
tests/libtransmission/crypto-test.cc

another incremental PR. Follows up to #5529 and is on the path leading to the sfl-library refactor.
This refactors `tr_peerIo` to use the new `BufferWriter::reserve_space()` and `BufferWriter::commit_space()` API.

refactor: use reserve_space() in peer-io

---

libtransmission/announcer-udp.cc
libtransmission/peer-io.h
libtransmission/peer-msgs.cc
libtransmission/peer-socket.cc
libtransmission/tr-buffer.h
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
tests/libtransmission/announcer-udp-test.cc

Try to pass references to `BufferReader&` or `BufferWriter&` instead of `libtransmission::Buffer&` to decouple from implementation classes.
This code was written awhile back in the sfl branch draft branch and I'm now applying it incrementally to try and have single-topic PRs.

refactor: migrate methods to buffer reader

---

libtransmission/peer-msgs.cc

The common case is to receive an entire block in a single peer message, so optimize for that. Only use the `blocks` map iff the block data is broken into more than one peer message.
Notes: Avoid unnecessary heap memory allocations.

perf: avoid map insertion for complete blocks received

---

Transmission.xcodeproj/project.pbxproj
libtransmission/port-forwarding-natpmp.cc

This fixes a build regression from #5308
Problem: libnatpmp and miniupnpc have "version" files which are incorrectly read as broken headers
Solution: we limit system headers to .h files

Fix building Xcode project

---

macosx/InfoPeersViewController.mm
macosx/da.lproj/Localizable.strings
macosx/de.lproj/Localizable.strings
macosx/en.lproj/Localizable.strings
macosx/es.lproj/Localizable.strings
macosx/fr.lproj/Localizable.strings
macosx/it.lproj/Localizable.strings
macosx/nl.lproj/Localizable.strings
macosx/pt_PT.lproj/Localizable.strings
macosx/ru.lproj/Localizable.strings
macosx/tr.lproj/Localizable.strings

In French, "Port:" should be "Port :", like the other strings.
Harmonizing the format with other strings, I'm changing the localized string "Port" with "Port:".
This breaks existing strings, so setting Milestone to "decide after 4.0".

Support localized punctuation for "Port:"

---

libtransmission/utils.cc

`tr_parseNum<>()` is implemented with `fast_float::from_chars()`, and the latter is documented as "expecting a locale-indepent format equivalent to what is used by std::strtod in the default ("C") locale". To accomodate locale independent number parsing, switch back to locale-independent number formatting in `tr_truncd()` by both removing a `L` format specifier from `fmt::format_to_n()` call and using a fixed "." decimal separator when truncating the value.
Broken-by: #5288, #3748, #2872
Fixes: #5503

Avoid locale use in `tr_truncd()`

---

.github/workflows/actions.yml
libtransmission/platform.cc

experimental change to possibly fix https://github.com/transmission/transmission/actions/runs/5237106884/jobs/9455075792?pr=5510.
Appears to be new with the Python 3.11.4 bump, that landed about 5 hours ago at https://github.com/Homebrew/homebrew-core/pull/133015. That's consistent with CI being red now but was working last night. That doesn't prove whose bug it is :smile: I haven't done enough investigation to know whether it's Transmission or homebrew-core

ci: add "brew upgrade" step

---

libtransmission/global-ip-cache.cc
libtransmission/global-ip-cache.h
libtransmission/session.cc
libtransmission/session.h
tests/libtransmission/global-ip-cache-test.cc

1. Enable global IP query, thanks to the new endpoints on transmissionbt.com. https://github.com/transmission/transmission/pull/5329#discussion_r1189389905
2. Fix unintended behavioural change in `tr_address::publicAddress()` for IPv6.
3. Added a new test for the callback of the global IP query feature.
4. Refactor `tr_global_ip_cache` to use a mediator, so that more tests are possible.
Fixes #5554.

Enable global IP query and fixes/refactorings

---

macosx/FileNameCell.h
macosx/FileNameCell.mm
macosx/TorrentCell.mm

(Previously: <s>`attempt to fix #5212`</s>)
This is a small performance refactor.
I'm replacing NSMutableDictionary with non-mutable static attributes.
So now there are only a total of 4-6 non-mutable static attribute dictionaries instead of 2 mutable instance copies for each torrent.

refactor: replace NSMutableDictionary with constant attributes

---

macosx/PiecesView.mm
macosx/TorrentTableView.mm

fix 'setNeedsDisplay' is deprecated: first deprecated in macOS 10.14

---

gtk/Application.cc
libtransmission/file-posix.cc
libtransmission/variant-json.cc

despite the major version bump, it seems to be semver/minor safe for our API use
Fixes #5511.
Possibly fixes #5627.
Notes: Bumped [fmtlib](https://github.com/fmtlib/fmt) snapshot to [10.0.0](https://github.com/fmtlib/fmt/releases/tag/10.0.0).

deps: bump libfmt to v10.0.0

---

libtransmission/peer-msgs.cc

https://github.com/transmission/transmission/issues/5542#issuecomment-1556710922
The original LTEP handshake code assumes that we are not behind an IPv6 NAT. This PR removes that assumption.

handle IPv6 NAT during LTEP handshake

---

libtransmission/torrent.cc
tests/libtransmission/rename-test.cc

My attempt at resolving [this issue](https://github.com/transmission/transmission/issues/5555#issue-1723972944).
*edit by @ckerr:* @basilefff use the phrase "Fixes #DDDD" so GitHub will understand and link the issue and PR together :tada:
Fixes #5555.

fix: return error when renaming into existing file

---

libtransmission/rpc-server.cc
libtransmission/rpc-server.h

Still needs to be tested. I'd also like to make some actual tests for this, but I'm a little unsure how the testing framework works.

fixup: dedup tr_rpc_address with tr_address

---

qt/MainWindow.cc

This is intended to fix the following deprecation warning observed when building against `qt-6.5.0`:
```
qt/MainWindow.cc: In member function ‘void MainWindow::toggleWindows(bool)’:
qt/MainWindow.cc:1113:38: warning: ‘static void QApplication::setActiveWindow(QWidget*)’ is deprecated: Use QWidget::activateWindow() instead. [-Wdeprecated-declarations]
1113 |         QApplication::setActiveWindow(this);
|         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /usr/include/qt6/QtWidgets/QApplication:1,
from qt/transmission-qt_autogen/include/ui_AboutDialog.h:14,
from qt/AboutDialog.h:13,
from qt/MainWindow.cc:23:
/usr/include/qt6/QtWidgets/qapplication.h:84:17: note: declared here
84 |     static void setActiveWindow(QWidget* act);
|                 ^~~~~~~~~~~~~~~
```

fix: Qt 6.5 deprecation warning

---

libtransmission/net.cc
libtransmission/peer-msgs.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/tr-udp.cc

Following up on https://github.com/transmission/transmission/pull/5565#issuecomment-1577875205 to add the ability to include the `ipv4` parameter during LTEP handshake as well. [BEP-10](https://www.bittorrent.org/beps/bep_0010.html)
Also renamed `tr_session::publicAddress()` to `tr_session::bind_address()` as a follow up of https://github.com/transmission/transmission/pull/5565#issuecomment-1596255260.

Add support for sending the `ipv4` parameter during ltep handshake

---

libtransmission/peer-mgr.cc

Follow up of #5619.
TODO: Too many `std::make_pair()` calls now for my liking. Further refactoring coming up in a future PR.

fixup: refactor handshake objects to use socket address as key as well

---

.gitmodules
CMakeLists.txt
Transmission.xcodeproj/project.pbxproj
cmake/FindSmall.cmake
libtransmission/CMakeLists.txt
libtransmission/cache.h
libtransmission/peer-mgr-wishlist.cc
libtransmission/peer-mgr-wishlist.h
libtransmission/platform.cc
libtransmission/variant.cc

Add header-only library https://github.com/alandefreitas/small for use in libtransmission. Part 1 of N.
- add scaffolding for using small
- in cache, replace the bespoke `BlockData` struct with a `small::max_size_vector`
- in variant's WalkNode helper, use `small::vector<>` for the stack
ObPedant: the name is `small` not `libsmall` but saying something like "add small dependency" or "add dependency of small header library" is just too confusing :smile_cat:

refactor: add libsmall dependency

---

libtransmission/announcer-http.cc

encode `&key=` as fixed-width 8-digit hex

---

libtransmission/announcer-udp.cc
libtransmission/handshake.cc
libtransmission/peer-io.h
libtransmission/peer-msgs.cc
libtransmission/tr-buffer.h
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/web.h
tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/buffer-test.cc

Start using https://github.com/alandefreitas/small in libtransmission,  e.g. to avoid heap allocations for short-term buffers that only need to exist on the stack.
Part 2 of N; first in the series is #5649.
- refactor: migrate `libtransmission::Buffer` from `evbuffer` to `small::vector`
- perf: use stack-based buffers in announcer-udp, variant-json, variant-benc, handshake, and peer-msgs.

perf: use small in libtransmission

---

macosx/NSStringAdditions.mm

Some languages use different percentage formatting style other than 100% (e.g. Turkish and French, %100-100 %). This commit enables the use of NSNumberFormatter(), in order to provide localized formatting.

fix: apply i18n to percentage values

---

libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mgr-active-requests.cc
libtransmission/peer-mgr-wishlist.h
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/tr-buffer.h
tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/buffer-test.cc

Part 3 in a series. Part 1 was https://github.com/transmission/transmission/pull/5649.
- Expose GrowthFactor in Buffer so that we can fine-tune its growth
- Give peer message buffers a large growth factor so that once we get a block message, we preallocate room for more of them
- Since we know there is a max of `EndgameMaxPeers` concurrent block requests per block, use `small::map<EndgameMaxPeers>` for bookkeeping in ActiveRequests
- Cleanup in peer-socket and in tests

perf: use libsmall in libtransmission, pt 3

---

libtransmission/handshake.cc
libtransmission/handshake.h
libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h
libtransmission/peer-msgs.cc
tests/libtransmission/handshake-test.cc

(Partially? Hopefully?) fixes #5610.
1. To address the high CPU usage of `tr_swarm::get_existing_atom()`, the member `pool` of `tr_swarm` was changed from a dequeue to a map.
2. Refactored related functions to streamline function calls.
Notes: Made internal peer bookkeeping more efficient.

Use a map container to store peers in `tr_swarm`

---

daemon/daemon-posix.cc
daemon/daemon.cc
gtk/Application.cc
libtransmission/transmission.h
libtransmission/utils.cc
tests/libtransmission/json-test.cc

No functional changes intended.
1. Changed C-style `<???.h>` standard headers to `<c???>`.
2. Replaced C-style casts with C++ casts.
3. Removed undefined-usages of `std::ignore`. Its behaviour is only formally defined when used in conjunction with `std::tie`.
4. Avoid descending an extra level in `transmission-daemon` when not compiled with systemd support.
Nitpicking, I know. 🤣

refactor: replace some C idioms with C++ ones 

---

libtransmission/rpc-server.cc

The changes in #5523 made two errors in the new implementation
1. tr_unix_address::to_string() got the ternary check backwards, leading to always printing an empty string when the address is valid.
2. The inputs to tr_strvStartsWith in tr_unix_address::from_string() were backwards as well, leading to the check failing for valid socket addresses.
@ckerr sorry about that, apparently I didn't test this properly. As a side note, I'm interesting in writing unit tests for this, but I'm not quite sure how to do that for non-exported classes/functions.
This can be tested with
```
curl -X POST --unix-socket /tmp/lol.sock http://localhost/transmission/rpc -d '{"method":"session-stats"}'
```

fix: fix broken unix socket support

---

libtransmission/announcer-udp.cc
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mgr-active-requests.cc
libtransmission/peer-mgr-wishlist.h
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/web.h

Partially restore the changes from #5650 and #5653 that were reverted in #5654. These pieces are either code cleanup (e.g. using typedefs to make it easier to substitute in a new Buffer class) or non-buffer refactors (e.g. the changes in peer-mgr-active-requests). These seem to be working and aren't the cause of the bug that made 5654 necessary.

refactor: small again

---

libtransmission/cache.cc
libtransmission/cache.h

Change the `cache_trim()` approach from flushing the oldest block to flushing the biggest contiguous span. This should result in data being written to disk in bigger batches.
Fixes the first bullet point in #5667.
CC @tearfur for review & feedback? This seems to be working pretty well in practice and I'd be OK with this going in as-is but am also open to the idea of different approaches to fix the `Cache::find_contiguous()` bug.

perf: in cache, flush biggest contiguous blocks

---

libtransmission/log.cc

On Windows, I encountered an issue with an electron application I'm developing. It would crash when launched from the file explorer but worked without any problems when started from the terminal. The application worked fine on Linux.
After several days debugging using `WinDbg`, I discovered that the application was crashing in `logAddImpl`.
On windows, according to the [getstdhandle](https://learn.microsoft.com/en-us/windows/console/getstdhandle) documentation, the function can return NULL if standard handles are not correctly redirected.
To prevent this crash, I implemented the following patch: libtransmission would now ignore writing logs if the file handler equals to `TR_BAD_SYS_FILE`.

fix: do not write log if file handler is bad

---

libtransmission/announcer-udp.cc
libtransmission/tr-buffer.h
tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/buffer-test.cc

Everything's been migrated to `StackBuffer`, so remove the now-unused `libtransmission::Buffer`.

refactor: remove libtransmission::Buffer

---

libtransmission/cache.cc
libtransmission/cache.h

Avoid constructing a new compare callable object each time the member functions in `cache.cc` are called.

refactor: share `CompareCacheBlockByKey` by constexpr static member

---

docs/Environment-Variables.md
libtransmission/log.cc

This feature was originally meant to redirect verbose logging to *any* fd, but it now only supports writing to stdout or stderr, and defaults to stderr.
Redirecting to stdout isn't very useful and complicates the code, so just remove it and always use stderr.
Removing a feature is usually a `semver/major` change; but since it's a debug-only feature that's not working correctly anyway, I don't think anyone will miss it and am OK with removing it without a major bump. :man_shrugging:

refactor: remove useless TR_DEBUG_FD env var

---

cli/cli.cc
libtransmission/utils.h
libtransmission/verify.cc
libtransmission/web.cc
tests/libtransmission/test-fixtures.h

`tr_wait()` used to have a bespoke implementation, but now it's just a wrapper around `std::this_thread::sleep_for()`.
This PR removes the wrapper and uses `std::` directly.

chore: remove tr_wait(); use std::this_thread::sleep_for() instead

---

docs/Editing-Configuration-Files.md

Updated logging levels in configuration documentation as they are no longer accurate.
This was discovered after [reporting an issue](https://github.com/linuxserver/docker-transmission/issues/240) to `linuxserver/docker-transmission` and @sbrudenell discovered this inconsistency.
The current logging levels can be seen below.
https://github.com/transmission/transmission/blob/6b0e49bbb296f1c84785275b8a8f18b4210180af/libtransmission/log.h#L16-L41

Updated logging levels in configuration documentation

---

libtransmission/net.cc
tests/libtransmission/net-test.cc

Reverts transmission/transmission#5651 and added tests for the IP address compare function.
Refer to https://github.com/transmission/transmission/issues/5677#issuecomment-1615566780 for explanaiton.

Revert "perf: improve IPv4 `tr_address` comparison"

---

libtransmission/inout.cc
qt/FileTreeItem.cc
qt/FileTreeView.cc
qt/RpcQueue.cc

Fix #5704 FTBFS regression (when building in Debug mode) reported by @tearfur in https://github.com/transmission/transmission/pull/5704#discussion_r1248617868.
Also fix a couple of recent minor clang-tidy regressions.

fix: recent build warnings and errors

---

libtransmission/cache.cc

Use raw pointers instead of iterators for this loop.
In a profile of just downloading a torrent with no other activity, this lowers `write_contiguous()` from 9.8% to 4.5% in my per testing

perf: faster Cache::write_contiguous()

---

libtransmission/file-piece-map.cc

This is a good candidate for replacing a `std::set` with a `small::set`: we know the max size in advance + the items are added in sorted order, so there won't be any moves necessary. TBH we could probably even use a `vector` here, but the `set` interface simplifies the code.

perf: use small:set in tr_file_piece_map::reset()

---

libtransmission/torrent.cc

This is a good candidate for a `small::` container since the number of unique file suffixes in a torrent is likely to be very small, and since both key and value are cheap to move.

perf: use small::unordered_map in tr_torrent::primary_mime_type()

---

daemon/daemon.cc

Use a stack buffer when building most log messages.

perf: use small::string in daemon::printMessage()

---

libtransmission/crypto-utils.cc
libtransmission/crypto-utils.h
libtransmission/magnet-metainfo.h
libtransmission/tr-strbuf.h
qt/AddData.cc
qt/Torrent.h

human-readable sha1 and sha256 hex strings have fixed widths (40 hex chars and 64 hex chars respectively); so when aggregating them in a `tr_magnet_metainfo`, use fixed-width strings instead of `std::string`s.
Notes: When beneficial, use fewer heap allocations.

perf: avoid string allocations by using fixed-width hash strings

---

libtransmission/CMakeLists.txt
libtransmission/observable.h
libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h

There are a lot of places in the codebase where one part of the code directly calls another part because it just knows what's needed, e.g. torrent calling peer-mgr.
This refactor adds a lightweight typesafe observer / observable implementation to help decouple this a little bit.
I *think* this mostly a good tradeoff between reducing coupling and not adding too much overhead, but I'd welcome suggestions both at the code review level & at the idea review level

refactor: add lightweight observable / observer for decoupling 

---

libtransmission/makemeta.h
libtransmission/peer-mgr.cc
libtransmission/torrent-metainfo.h
libtransmission/torrent.h

A handful of minor cleanup tweaks, e.g. returning `bool` instead of `bool const&` since the former is simpler and cheaper.
Arguably a `perf` PR but any perf improvements will be minimal.

perf: minor cleanups

---

libtransmission/net.cc
libtransmission/net.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mgr.cc
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/session.cc
libtransmission/tr-utp.cc
tests/libtransmission/handshake-test.cc

For performance benefits from avoid constructing `std::pair`s.

refactor: use `std::pair` to store socket addresses

---

libtransmission/.clang-tidy
libtransmission/handshake.h
libtransmission/net.cc
libtransmission/net.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h
libtransmission/peer-msgs.cc
libtransmission/peer-msgs.h
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/tr-dht.cc

It's still a `std::pair<tr_address, tr_port>`; it just feels semantically clearer to give it a name.

refactor: add tr_socket_address typedef 

---

daemon/daemon-posix.cc
daemon/daemon-win32.cc
daemon/daemon.cc
daemon/daemon.h

It shouldn't matter much since there will only ever be one signal handling event struct, but anyway.
```
==245222== 128 bytes in 1 blocks are definitely lost in loss record 106 of 144
==245222==    at 0x484182F: malloc (vg_replace_malloc.c:431)
==245222==    by 0x5CF964: event_mm_malloc_ (event.c:3492)
==245222==    by 0x5CF964: event_new (event.c:2211)
==245222==    by 0x435705: tr_daemon::setup_signals() (daemon-posix.cc:73)
==245222==    by 0x4220D2: tr_daemon::start(bool) (daemon.cc:692)
==245222==    by 0x4386EC: tr_daemon::spawn(bool, int*, tr_error**) (daemon-posix.cc:184)
==245222==    by 0x41CC3F: main (daemon.cc:947)
```

fix: memory leak from signal handling event in daemon

---

libtransmission/net.h
tests/libtransmission/net-test.cc

Somehow Palpatine retu-
No I mean somehow the code compiled.

fix: spelling mistake in `net.h` function call

---

libtransmission/tr-buffer.h

fix: high memory use regression.
Fixes #5735.
I was wary about the cost of this new `memmove()` call, but in local testing it happens far less often than I expected and is not a major factor in my perf tests. So I'm OK with this approach until / unless we see it causing problems.
CC @tearfur since even though you're a member of Transmission org, the GitHub UI won't let me request a review :confused:

fixup! refactor: remove libtransmission::Buffer (#5676)

---

README.md

Whenever a new `third-party` submodule is being added, without the `--init` sub-command in `git submodule update --recursive`, the user will get bitten by compilation error due to an uninitialized submodule dependency.
Fixes #5674

`--init` added in `Building Transmission from Git (updating)` section

---

libtransmission/peer-mgr.cc

Before this PR, every time some peers are selected from the peer candidate list, a front portion of the list will be erased, causing the rest of the elements to be copied/moved.
This PR avoids that.
Should help with #5714.

perf: avoid copying/moving elements in peer candidate list

---

libtransmission/handshake.cc
libtransmission/handshake.h
libtransmission/peer-mgr.cc
tests/libtransmission/handshake-test.cc

These seed-to-seed connections can still be useful for a short time, e.g. for peer exchange, so we shouldn't unconditionally disconnect.

feat: do not auto-disconnect when seeding & a known seed handshakes

---

libtransmission/peer-msgs.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent-magnet.h
libtransmission/variant.cc
tests/libtransmission/torrent-magnet-test.cc

Notes: When beneficial, use fewer heap allocations.

perf: use small::max_size_vector in tr_torrentGetMetadataPiece()

---

libtransmission/torrent.cc

The code removed is covering a case that no longer exist.
The seed limit check is now done in `rechokePulse()` instead of `bandwidthPulse()`, and the check will be done as long as the torrent is running.

remove redundant seed limit check

---

libtransmission/bitfield.cc
libtransmission/bitfield.h
libtransmission/peer-mgr-wishlist.cc
libtransmission/peer-mgr.cc
libtransmission/resume.cc

~I don't see any reason why the interesting piece bitfield needs to be constructed individually for each peer. They shoud be all the same.~
Edit: Turns out I misread the code. So all that's left to this PR is just code cleanup.

chore: minor code cleanup

---

libtransmission/peer-msgs.cc
libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.h

This PR fixes a few minor issues with `tr_peerMsgs`.
1. BEP-11: Transmission now will not advertise pex support in ltep handshakes if `pex-enabled` is set to `false`.
2. BEP-11: Transmission now advertises pex support regardless of whether the peer supports it.
3. BEP-9: Transmission now checks if `total_size` in the `data` message received is the same as the `metadata_size` field in the ltep handshake received before.

fix/cleanups to tr_peerMsgsImpl

---

gtk/ui/gtk3/MainWindow.ui
gtk/ui/gtk4/MainWindow.ui

`<property name="tooltip-text" translatable="yes">Remove torrent</property>`
Notes: Fixed missing 'Remove torrent' tooltip in GK client

fix: add missing tooltip for 'remove torrent' button

---

gtk/Torrent.cc
gtk/TorrentSorter.cc
gtk/Utils.h
libtransmission/announcer.cc
libtransmission/peer-mgr.h
qt/FileTreeItem.cc
qt/FileTreeItem.h
qt/Torrent.cc
qt/TorrentFilter.cc

use `tr_compare_3way()` everywhere instead of implementing it again in the `gtk/` and `qt/` clients.

refactor: tr_compare_3way()

---

libtransmission/bandwidth.cc

A next to harmless bug but a bug nonetheless.

fix: clamp down harder for upload as well

---

web/README
web/assets/css/transmission-app.scss
web/public_html/index.html

These are very minor changes that cover a few issues:
- Fixes #4209
On very small screens (for-phone-only), we modify width on some fields for less overlap. But we also truncate using `text-overflow: ellipsis` and `overflow-x: hidden`.
- properly style up/down speed icons
Moved SVG contents into index.html so we can make these style changes based on the `prefers-color-scheme` media query.
I also set a min-width, text-align: right on the download/upload label so they aren't shifting when going from 1 kB/s to 800 Mb/s.
- Add README for `web` directory
It made sense to add some super simple getting-started instructions for the directory. So, super light instructions on getting started with development, plus a very simple bookmarklet to anonymize the interface with lorem ipsum before …

Add readme with light setup instructions; minor UI tweaks

---

libtransmission/variant.cc
libtransmission/variant.h

This is an incremental step. Ultimately `tr_variant_string` will be replaced by `std::string_view` and `std::string`  in a `std::variant`, but we can't drop the union  yet until some other code is in place first.
This PR makes all the string implementation details private to `tr_variant` .

refactor: use std::variant in tr_variant, pt 1: make tr_variant_string private

---

.github/workflows/actions.yml

This is not an error, but a warning when building/running tests with CMake/GoogleTest.
Use `sysctl -n hw.logicalcpu` to get parallelization number.
See: https://github.com/memkind/memkind/issues/33#issuecomment-540614162
No changes affecting users, so no `Notes:` here.

fix: CI: Do not use nproc on macOS hosts.

---

.github/workflows/actions.yml

The CI no longer rebuilds the web directory after #4760 since the CMake parameter was renamed.
This PR fixes that.

fix: fix ci web cmake option

---

libtransmission/CMakeLists.txt
libtransmission/utils.cc

Fix #5626.
Note: @barracuda156 to give it a try.
We'll need to cherry pick it for 4.0.x branch too.

fix -fobjc-arc with GCC

---

.clang-format
code_style.sh
libtransmission/tr-dht.h
libtransmission/tr-strbuf.h
macosx/Torrent.mm
tests/libtransmission/dht-test.cc

`QualifierAlignment` option is available since clang-format v14 and works better than our own script.

Use clang-format for qualifier alignment

---

Transmission.xcodeproj/project.pbxproj

This is an automated removal by Xcode.
It was accidentally added by #5147.

Xcode cleanup of leftover reference

---

.github/workflows/actions.yml
CMakeLists.txt
gtk/CMakeLists.txt
gtk/DetailsDialog.cc
gtk/DynamicPropertyStore.h
gtk/FileList.cc
gtk/FilterBar.cc
gtk/GtkCompat.h
gtk/MainWindow.cc
gtk/MessageLogWindow.cc
gtk/Percents.h
gtk/PrefsDialog.cc
gtk/Session.cc
gtk/Torrent.cc
gtk/Torrent.h
gtk/TorrentCellRenderer.cc
gtk/TorrentCellRenderer.h
gtk/Utils.cc
gtk/Utils.h
gtk/transmission-ui.css
gtk/ui/gtk4/MainWindow.ui
gtk/ui/gtk4/TorrentListItemCompact.ui
gtk/ui/gtk4/TorrentListItemFull.ui
gtk/ui/gtk4/transmission-ui.gresource.xml

One more PR in the gradual move to GTK 4. GTK 3 build is still supported and shouldn't show any difference.
Note that I'm bumping minimum required GTK 4 version to 4.11.1 (unstable; stable 4.12 is not released yet) which adds `tab-behavior` property to item views. I was holding off on filing this PR for quite some time (first due to encountering the tab navigation issue and waiting for a fix, then due to waiting for a stable GTK release), but I believe it'll be better to merge it now so that people understand just how "ready" GTK 4 is for our use, and for general consumption.
This PR also moves colors used in torrent list out of C++ code and into CSS, for both GTK 3 and 4 builds; @GaryElshaw might find it easier to adjust the colors there.

Switch to list view for torrents list (GTK 4)

---

libtransmission/session.h
libtransmission/tr-lpd.cc
libtransmission/tr-lpd.h
tests/libtransmission/lpd-test.cc

Fixes #5874.
Notes: Fixed a bug where Transmission may not announce LPD on its listening interface.

fix: announce LDP on listening interface

---

libtransmission/announce-list.cc
libtransmission/announce-list.h
tests/libtransmission/announce-list-test.cc

I've added a comparison about the query part of announce's comparison. It fixes #5802.

fix: announce with query replace bug (fixes #5802)

---

web/assets/css/transmission-app.scss
web/public_html/index.html

Left: this PR, right: original
Top: not selecting any torrent (inspector not graying out for original), bottom: selected a torrent (inspector is ungrayed as normal for original)
animated diff:

WebUI: Fix graying out inspector

---

libtransmission/session.h
libtransmission/tr-lpd.cc
libtransmission/tr-lpd.h
tests/libtransmission/lpd-test.cc

@tearfur this is a  cherry-pick of 28d423d + this change because `4.0.x` still has that `PublicAddressResult` struct that got subsumed by the `tr_address::is_any*()` funcs in `main`.
Submitting to you for review to make sure this is what's intended, since at this point you understand this part of the code better than I do. :smile_cat:

fix: cherry-pick 28d423d

---

libtransmission/peer-mgr.cc
tests/libtransmission/CMakeLists.txt
tests/libtransmission/tr-peer-info-test.cc

Fixes #5869.
After #5801, it is possible for a connectable pool entry to be marked as "connected" by an ltep port handshake within the time frame from Transmission initiating an outgoing handshake to a remote peer and the handshake completing. In the current state of `main`, if the handshaked failed, the peer info object will be marked is "not connectable" despite Transmission being connected to the peer, leading to an invalid state and failing the assertion.

fix: do not mark peer as not connectable when we are currently connected

---

libtransmission/peer-msgs.cc
libtransmission/resume.cc
libtransmission/session.cc
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/variant.cc
libtransmission/variant.h
qt/TorrentModel.cc
qt/VariantHelpers.h
tests/libtransmission/json-test.cc
tests/libtransmission/rpc-test.cc
tests/libtransmission/variant-test.cc
utils/remote.cc

Part 2 in a PR series to modernize `tr_vector`. Previous: #5923.
This PR uses `std::`-inspired naming for the functions that check the variant's type.
- `tr_variantIsFoo()` -> `tr_variant::holds_alternative<Foo>()`
- `tr_variantIsEmpty()` -> `!tr_variant::has_value()`

refactor: replace tr_variant::is_T() with tr_variant::holds_alternative<T>()

---

libtransmission/variant-json.cc
libtransmission/variant.cc
libtransmission/variant.h

Part 2 in a PR series to modernize tr_vector. First: #5923. Previous: #5930.
This PR replaces the union in `tr_variant` with a `std::variant`.
It leaves in place all the C API calls, but they're next in line :axe:

refactor: use std::variant in tr_variant

---

news/news-4.0.4.md

CC @transmission/contributors 
- [Rendered version of the release notes](https://github.com/transmission/transmission/blob/docs/new-4.0.4.md/news/news-4.0.4.md).
- Now's the time if you have any bugfixes that belong in 4.0.4 :hourglass_flowing_sand:

docs: add release notes for 4.0.4

---

libtransmission/announce-list.cc
libtransmission/announcer-common.h
libtransmission/announcer-http.cc
libtransmission/announcer-udp.cc
libtransmission/announcer.cc
libtransmission/announcer.h
tests/libtransmission/announcer-test.cc
tests/libtransmission/announcer-udp-test.cc

Address some points raised by @reardonia in https://github.com/transmission/transmission/issues/2932#issuecomment-1100916297.
*Didn't touch this because I'm not too sure how @reardonia wanted to use the mask.*
Also fixed a ping-ponging problem with scrape `downloaders`, similar in nature with what #5164 tackles.
Closes #2932.

refactor: tidy up announcer code

---

libtransmission/variant.cc

Fixes `main` regression reported in #5958.

fix: transmission-remote -l regression

---

web/assets/css/transmission-app.scss
web/src/inspector.js
web/src/prefs-dialog.js
web/src/transmission.js
web/src/utils.js

- Responsive UI on torrent selection change, 200ms delay removed
- Continue torrent selection after popup dismiss
- Refresh play/pause UI on torrent status change
- Refresh status sooner for paused torrent
- Less dismissable Inspector: Clicking outside will not close it out of the blue (e.g. if you want to play/pause a torrent), only new popup or new X button can dismiss it.
- Doubleclick listener cleanup
Later commit pulls codes from #5910:
- Implemented X button as way to dismiss right hand windows (inspector and prefs dialog)
- Quick fix for "Connection failed" after closing the prefs dialog too quickly. What has happened is the port check was still ongoing and once it gets a response it will try to update the status label but failed because the window is no longer around.

WebUI: General responsive UI

---

libtransmission/web.cc

For trackers that host the torrent files on HTTPS and the tracker itself on HTTP, and on the same hostname, the shared HSTS cache might upgrade the announces to HTTPS and cause it to fail.
Fixes #5199.
Notes: Fixed HTTP tracker announces and scrapes sometimes failing after adding a torrent file by HTTPS URL.

fix: workaround HSTS upgrading HTTP trackers announces to HTTPS

---

libtransmission/torrent.cc

When magnet metadata download completes the tracker info is merged into a new metainfo which causes the tracker IDs to change.  This should be accounted for by calling on_announce_list_changed()
Fixes #5293.

fix: magnet data invalidates tracker IDs

---

cli/cli.cc
daemon/daemon.cc
gtk/Application.cc
gtk/Prefs.cc
gtk/Prefs.h
libtransmission/rpc-server.cc
libtransmission/rpc-server.h
libtransmission/session-alt-speeds.cc
libtransmission/session-alt-speeds.h
libtransmission/session-settings.cc
libtransmission/session-settings.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/transmission.h
libtransmission/variant-converters.cc
libtransmission/variant.h
macosx/Controller.mm
qt/Prefs.cc
qt/Prefs.h
qt/Session.cc
tests/libtransmission/session-test.cc
tests/libtransmission/settings-test.cc

A slightly easier-to-use API, since clients no longer have to instantiate & initialize a `tr_variant` before calling the `tr_session*Settings()` functions.
Example:
```diff
- tr_variant settings;
- tr_variantDictInit(&settings, 0);
- tr_sessionGetDefaultSettings(&settings);
+ auto settings = tr_sessionGetDefaultSettings();
```

refactor: public tr_session settings API now returns tr_variants

---

libtransmission/peer-mgr.cc

Fixes #5940.
Fixes #5881.
Fixes #5926.

fix: heap-use-after-free in peer communications

---

web/src/prefs-dialog.js

Fixes #5956. The original issue stated that most of these excessive calls were `session-get`, while they are actually `session-set`.
Notes: Removed excessive `session-set` RPC calls related to WebUI preference dialogue.
Calling `session-set` in the callback function of `session-get` was unnecessary, so I removed it.

perf: do not call `session-set` in `session-get` callback

---

libtransmission/variant.cc
libtransmission/variant.h

add API for creating tr_variant maps/vectors.
culled from the refactor/variant-rpcimpl branch into a separate PR.

refactor: tr_variant API update

---

web/assets/css/transmission-app.scss

Simple fix, Fixes #6009
TorrentRendererFull actually uses the class `full` to add seeding progress. We can get seeding progress functionality in compact mode if we just apply the same progress indication to the compact rows, too. (Put simply: don't rely on the `full` class to apply progress percentage.)

fix: add seed progress percentage to compact rows

---

web/assets/css/transmission-app.scss
web/src/about-dialog.js
web/src/overflow-menu.js

Always show fullscreen option, larger viewports seem capable of going fullscreen so why need small viewport to see this option? Alternatively why this option at all?
Links Tip Jar -> Help Donate, inspired from QT application!
Relocated links to save space on overflow menu. Removed Source Code link - is it worthwhile?
Notes: Improved overflow menu for web client
Left/top: this PR right/bottom: original
animated diff (well, our naked eyes can see the diffs above just fine!):
Both are having bottom padding problem which I'll do separate PR about it soon.

feat: improved overflow menu for web client

---

macosx/Base.lproj/InfoActivityView.xib
macosx/Base.lproj/InfoGeneralView.xib
macosx/Base.lproj/InfoOptionsView.xib
macosx/CreatorWindowController.mm
macosx/FilterBar.xib
macosx/InfoFileView.xib
macosx/InfoPeersView.xib
macosx/InfoTrackersView.xib
macosx/MessageWindowController.mm
macosx/PrefsController.mm
macosx/StatsWindowController.mm
macosx/StatusBar.xib

Fix https://github.com/transmission/transmission/discussions/5839
Repro steps:
- install macOS Sonoma 14.0
- install Xcode 15 and open Settings > Locations > Command Line Tools and re-apply "Xcode 15.0" explicitly, or alternatively `sudo xcode-select -s /Applications/Xcode15.app/Contents/Developer`
- build Transmission (ninja or Xcode) and turn on filter bar and/or status bar
Result:
- The filter bar or status bar is going to completely overlap and hide the TorrentTableView.
- The Preferences and CreateTorrent controllers crashes.
- The Inspector has various UI glitches
Cause:
I found this in the UIKIt source:
```
/* Defaults to NO on macOS 14 and later. Defaults to YES on previous releases. Note some classes (like NSClipView) set their own default values differently than NSView itself. …
```

Fix broken UI and windows on macOS Sonoma

---

libtransmission/handshake.cc
libtransmission/handshake.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-mse.h
libtransmission/tr-buffer.h

Fixes #6022.
This PR makes a number of changes, most notably:
1. Transmission used to ignore plaintext `crypto_select` (`0x01`) and keep using encrypted connections, this is now fixed.
2. Transmission did not check if the VC sent from the MSE handshake initiator is valid, the check has been added back.
3. Transmission used to read more than 512 bytes for PadA and PadB, this is now fixed.
4. `sizeof` was used to check to the total size of an `std::array`. This is not reliable, and `std::tuple_size_v` is now used instead.
5. Deduped code for reading and parsing BT handshakes.

feat: BT and MSE handshake rework

---

web/src/inspector.js
web/src/utils.js

There are several ways to deselect the torrent to be selected again: Mouse click while holding a Ctrl key or click on the blank below torrent list. When the torrent was selected again the magnet link in Inspector page isn't updating. This PR should resolve it.
Notes: Fixed updating magnet link after selecting same torrent again.

fix: Fixed updating magnet link after selecting same torrent again

---

macosx/ProgressBarView.mm

duplicate of https://github.com/transmission/transmission/pull/6014. I'm pushing a separate branch because there's something going on with PR that seems to have confused GitHub. :dizzy: 
Credit for this PR goes to @Coeur; I'm just PR'ing this to work around a GitHub hiccup.
Notes: Fixed "Unrecognized colorspace number -1" error message.

fix: "Unrecognized colorspace number -1"

---

macosx/Base.lproj/InfoActivityView.xib
macosx/Base.lproj/InfoGeneralView.xib
macosx/Base.lproj/InfoOptionsView.xib
macosx/CreatorWindowController.mm
macosx/FilterBar.xib
macosx/InfoFileView.xib
macosx/InfoPeersView.xib
macosx/InfoTrackersView.xib
macosx/MessageWindowController.mm
macosx/PrefsController.mm
macosx/StatsWindowController.mm
macosx/StatusBar.xib

Cherry-pick of #6016 for the 4.0.x branch, otherwise that branch is unusable when building from source on current stable macOS.
Notes: Support macOS Sonoma when building from sources

Fix macOS 14 UI not clipping views and crashing on window restoration

---

libtransmission/peer-mgr.cc

99% of the time this line of debug log is triggered by `ENOTCONN`, which just means that a peer disconnected with us. But since it does not print the error code and error message, I've seen it falsely alerting a lot of issue authors, thinking this has to do with the issue they are facing.
This PR adds the error code and error message to the log line.

chore: more specific peer error log

---

daemon/transmission-daemon.1

Man page does not contain entry for log-level, does not describe log-error, log-info, log-debug as deprecated.

Update transmission-daemon.1 to sync with --help

---

libtransmission/torrent.cc

Part 1 of tackling #83. Next part at #5981.
Suppose Transmission displayed the error message `No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.` because the user moved the torrent files to another location.
To clear the error, the user currently has to set the torrent location, then try to resume the torrent to see if the error clears.
With this PR, the files will immediately be checked after setting torrent location, and the error will clear if Transmission finds the files.
Notes: Transmission now checks if local files exists after setting torrent location.
Fixes #6048.

feat: check if local files exist after setting location

---

libtransmission/makemeta.cc

fixup! refactor: remove redundant code when adding announce lists to metainfo (#6050)

---

libtransmission/peer-mgr.cc

Fixes #5881.
The existing code that cleans up after a disconnected peer does not correctly handle peers that uses the same port for initiating outgoing connections and listening for incoming connections. This is common when uTP is being used.
What would happen is:
```
We get an incoming connection from a peer (conn1).
We create a tr_peer_info object (obj1) for it and stores it in incoming_pool.
│
│
▼
We get an ltep port handshake on conn1. Consequentially,
obj1 gets moved from incoming_pool to connectable_pool.
│
│
▼
We get another incoming connection from the same peer (conn2).
We create a tr_peer_info object (obj2) for it and stores it in incoming_pool.
│
│
▼
conn1 disconnects and we perform the cleanup for it.
We will accidentally delete obj2 because it has the same key as obj1 did …
```

fix: `assertion failed: port_empty` in `tr_swarm::remove_peer()`

---

gtk/DetailsDialog.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h

This function only one caller, and it was always called at intervals too infrequently for us to hit the cache -- so there is no benefit in keeping this function. For that reason I'm not bothered by this API removal from libtransmission; but at some point we should decide on how seriously to take semver in `libtransmission/transmission.h` :thinking:

refactor: remove tr_torrentStatCached()

---

libtransmission/rpcimpl.cc
libtransmission/rpcimpl.h
tests/libtransmission/rpc-test.cc
tests/libtransmission/test-fixtures.h
utils/remote.cc

Another in the `tr_variant` refactor series. Previous: #6006.
There is just so much use of the variant API that it's not practical to update everything all at once, so this is another incremental step.

refactor: more tr_variant API

---

libtransmission/torrent.cc
libtransmission/torrent.h

This is to encapsulate / make more readable some of the massaging we do to speeds when calculating `tr_stat.eta` and `.etaIdle`.
Also,  as with other recent refactors, make two more `tr_torrent` fields private.

refactor: add a SimpleSmoothedSpeed helper class

---

libtransmission/session.cc

Whether uTP is enabled or not affects the UDP socket buffer sizes, but toggling uTP mid-execution does not refresh the buffer sizes (by reconstructing `udp_core_`).
https://github.com/transmission/transmission/blob/68f3c89e3c84c862f83fc91c08fbb3a26e05e4e0/libtransmission/tr-udp.cc#L175
https://github.com/transmission/transmission/blob/68f3c89e3c84c862f83fc91c08fbb3a26e05e4e0/libtransmission/tr-udp.cc#L209
On the other hand, toggling DHT does reconstruct `udp_core_` in the current code. I removed this behaviour because I don't see any reason why it needs to.

fix: reconstruct `utp_core_` when toggling utp

---

libtransmission/observable.h
libtransmission/torrent-magnet.cc
libtransmission/torrent.h

- lower the preallocated size of the `SimpleObservable.observers` array to 4. In practice we only have 1 or 2; the previous size was just unnecessarily large.
- make `tr_torrent.incomplete_metadata` a `std::unique_ptr` instead of a `std::optional`. This way we avoid allocating it for each torrent that already has metadata (most of them) and also avoid the extra overhead that `std::optional` introduces (it is 2x the size of the type it wraps, which in this case was 120 bytes)
- re-arrange some `tr_torrent` fields to avoid padding holes.
None of these has any intentional behavior changes, but does shrink the size of a `t_torrent` instance by a good amount.

perf: reduce unnecessary size overhead in tr_torrent struct

---

docs/Peer-ID-and-User-Agent.md

Closes #6076. I took the liberty to rewrite/reformat slightly.
I'm not sure how recent the `User-Agent` section is though.

Update peer-id documentation to account for post-3.00 changes

---

web/src/inspector.js

Just so that there is at least somewhere you can see the full IPv6 addresses.

feat: WebUI display full peer address in tooltip

---

libtransmission/inout.cc
libtransmission/peer-msgs.cc
libtransmission/resume.cc
libtransmission/torrent.cc
libtransmission/torrent.h

Another incremental PR to reduce `tr_torrent`  sprawl by dividing its code into more self-contained chunks.
This replaces three error fields (`error`, `error_string`, and `error_announce_url`) with a single `error` field that is an instance of a new helper class to improve semantics, e.g. client code can call `error().set_tracker_warning()` instead of manually updating all the fields.

refactor: add tr_torrent::Error helper class

---

web/src/torrent-row.js

What is .toFixed(2) supposed to do if the number is not a floating-point number ¯\\_(ツ)_/¯
Notes: Removed a rounding method to enable using decimal for granular progress bar growth.

feat: progress bar precision for web client

---

libtransmission/utils.cc
libtransmission/utils.h
libtransmission/variant-json.cc
tests/libtransmission/json-test.cc

Fixes #5967.
This PR fixes 3 problems:
1. It is escaping characters that does not need to be escaped (e.g. non-BMP characters), which in turn:
1. Makes the JSON object unnecessarily long.
2. Gives more room for error because of extra code to escape stuff.
2. It decides which characters to escape using `isprint()`, which gives different output depending on locale. This is causing Transmission to improperly escaping strings in some locales.
3. The JSON tests were not following the locale settings of the apps, so locale issues were being swept under the rug.
JSON strings can contain *any* Unicode characters (with a few well-defined exceptions), so escaping non-BMP characters is optional. This PR modifies Transmsision to do as little escaping as possible.
> All Unicode characters may be …

fix: json string serializer improperly escaping characters

---

libtransmission/announcer-udp.cc
libtransmission/net.h
libtransmission/tr-buffer.h

Fixes #6125.
Notes: Fixed `4.0.0` bug where the `IP address` field in UDP announces are not encoded in network byte order. [[BEP-15](https://www.bittorrent.org/beps/bep_0015.html)]

fix: encode `ip` in network byte order for udp announce

---

libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h

Periodically purge inactive peer info objects from the peer pool, so that the pool size doesn't grow indefinitely.
This and my other pending PRs marks the point where I'd consider the peer communications code ready for `4.1.0` release.
Notes: Improved libtransmission code to use less CPU.

perf: periodically purge inactive peer info objects from pool

---

libtransmission/utils.cc
libtransmission/utils.h
libtransmission/variant-json.cc
tests/libtransmission/json-test.cc

fix: json string serializer improperly escaping characters (#6005)

---

libtransmission/announcer-udp.cc
libtransmission/tr-buffer.h

(cherry picked from commit c70c49e87bf29828045920b7cd2ac2741107daf6)
Manual cherry pick to `4.0.x`.

fix: encode `ip` in network byte order for udp announce (#6126)

---

macosx/Base.lproj/PrefsWindow.xib

Fix #6098
Before:
After:
This does not make it resizable or scrollable, but it's a good enough enhancement for now. I do not plan to do better this year.

UI fix: larger display group name

---

web/babel.config.js
web/package-lock.json
web/package.json

Bump some build dependencies to fix indirect dependencies that have CVEs.
I don't think we're affected by these vulnerabilities, but there's no harm in bumping the build-deps anyway.

chore: bump vulnerable web build deps

---

macosx/PrefsController.mm

feat: directly open macOS notifications preferences for app

---

macosx/Base.lproj/PrefsWindow.xib
macosx/PrefsController.mm

I think this was missing out.
I confess, I use other torrent clients from time to time, for no particular reason.
And some of them like to set itself as default app without even bothering to ask the user.
XIB diff as always is botched, so take a look at IB preview:

feat: add option to set macOS client as default for torrent files

---

libtransmission/peer-mgr.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc

A minor decoupling refactor to reduce `tr_peerMgr`'s direct dependency on `tr_session`.

refactor: reduce coupling between tr_session and tr_peerMgr

---

libtransmission/resume.cc
libtransmission/rpcimpl.cc
libtransmission/torrent-ctor.cc
libtransmission/torrent.cc
libtransmission/torrent.h

another minor scope-limiting PR -- this time to make the `tr_torrent::labels_` field private

refactor: make tr_torrent::labels_ private

---

README.md
docs/Building-Transmission.md

1. Updated Transmission release verison in README.
2. Use more generic build commands (e.g. `make` -> `cmake --build`)
3. Combined commands.
4. Updated syntax highlighting.

chore: update build instructions

---

macosx/BlocklistDownloader.mm

in file macosx/BlocklistDownloader.mm:
in (void)startDownload: now trimming whitespaces at the beginning and end of the BlocklistURL, otherwise the download will fail, if the URL contains a beginning or trailing whitespace.

fix: URL cleanup in BlocklistDownloader on macOS

---

libtransmission/peer-mgr.cc
libtransmission/peer-socket.cc
libtransmission/peer-socket.h
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/torrents.cc
libtransmission/torrents.h

Pass a `tr_torrents&` and `TimerMaker&` into the `tr_peerMgr` and `HandshakeMediator` constructors so they can be used directly instead of indirectly via `tr_session`.

refactor: minor decoupling in peer-mgr

---

libtransmission/peer-msgs.cc

Cut away a few unnecessary copy operation in the `can_read()` callback of peer IO.

perf: cut down excess copying when downloading

---

web/assets/css/transmission-app.scss

Side note: This is for 4.1.0 only, graying out buttons in 4.0.x is controlled by opacity
Closes #5919
Notes: A quick fix to buttons not graying out in dark mode

fix: fixed graying out buttons in dark mode for web client

---

web/src/formatter.js
web/src/inspector.js
web/src/torrent-row.js

- Torrent running time will display number of days, hours and minutes (excluding seconds if it's been more than a minute).
- Torrent date added will display in date as well as time.
Closes #5917
Notes: Added display and time in torrent detail
See screenshot
Animated diff from original

feat: display date & time in torrent detail for web client

---

gtk/Torrent.cc
libtransmission/resume.cc
libtransmission/torrent.cc
libtransmission/transmission.h
macosx/Torrent.mm

this interim function should have been removed when tr_torrentView() was introduced.
This is an older PR; cleaning out some local branches that I hadn't gotten around to PRing yet.

refactor: remove tr_torrentTotalSize()

---

libtransmission/peer-msgs.cc

Fixes #6168.
Empty peer message payload are completely normal, and I accidentally added an assert for non-empty payload.

fixup! perf: cut down excess copying when downloading (#5907)

---

libtransmission/tr-getopt.cc

Since #3551, the space between the option argument and the description in the command line help message is gone.
This PR restores it.
For example, in `transmission-daemon`'s help message (before: top, after: below):
```console 
-c   --watch-dir            <directory>Where to watch for new torrent files
-c   --watch-dir            <directory> Where to watch for new torrent files
```

fix: formatting cmdline help message

---

libtransmission/rpcimpl.cc
tests/libtransmission/rpc-test.cc

Follow up for #5604
Fixes #6172

fix: crash after nullptr dereference in rpcimpl

---

libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrents.h

Follow up for #6177 that cleans up overlap of responsibilities between `tr_session::getAllTorrents()` and `tr_torrents::sorted_by_id()`.
tldr:
```diff
- tr_session::getAllTorrents()
- tr_torrents::sorted_by_id()
+ tr_session::get_matches(UnaryPredicate) { ... }
+ tr_session::get_all() { return get_if([](tr_torrent const*){ return true; }); }
```

refactor: move tr_session::getAllTorrents to tr_torrents

---

Transmission.xcodeproj/project.pbxproj
macosx/CMakeLists.txt
macosx/DefaultAppHelper.h
macosx/DefaultAppHelper.mm
macosx/PrefsController.mm

~~Supersedes #6099 as GitHub doesn't support parent/dependent PR as a concept.
Creating this before #6099 is merged to gather feedback and to run CI checks.~~
Parent PR is merged.

refactor: move macOS default app logic to dedicated class 

---

macosx/Info.plist
macosx/Info.plist.in
macosx/QuickLookPlugin/Info.plist.in
macosx/QuickLookPlugin/QuickLookPlugin-Info.plist
macosx/nl.lproj/InfoPlist.strings
qt/LicenseDialog.ui

While testing #6195, I noticed that some front-facing copyright notices had escaped the last update. Now all years in notices should be covered (either gone with #4850 or already changed from #4834 and other PRs); and the remaining ones should/will be automatically updated on January 1st by #6195.
Cheers!

chore: updated some leftover front-facing copyright years

---

macosx/Info.plist
macosx/Info.plist.in
macosx/TorrentTableView.mm

```objc
NSPasteboardType NSURLPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeURL", macos(10.0,10.14));
NSPasteboardType NSStringPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeString", macos(10.0,10.14));
```
Should be safe and back compatible, as they represent the same constants, but the latter is typed as extensible enum.

chore: replace deprecated NSNamePboardType with NSPasteboardTypeName

---

libtransmission/torrent-files.cc
tests/libtransmission/torrent-files-test.cc

fix #5112
The current sanitation is (partially) only valid for Windows and is too aggressive for Linux/Apple, losing correct filenames.
- leading and trailing spaces are valid on Unix-like
- trailing dots are valid on Unix-like
- no reserved filenames on Unix-like except "." and ".."
- control chars are reserved on Win32
Testing:
1. make files or folders with such characteristics (like leading space, trailing space, quotes, slashes, backslashes, ...
2. `transmission-create <that file>`
3. `transmission-show <the generated torrent>`
tip: to create files with control characters:
```
date > "$(printf "foo\tbar")"
date > "$(printf "foo\nbar")"
```
This will create two distinct files.

fix: appendSanitizedComponent is too aggressive on non-WIN32 (and not enough aggressive on WIN32)

---

gtk/DynamicPropertyStore.h
libtransmission/favicon-cache.h
libtransmission/global-ip-cache.cc
libtransmission/global-ip-cache.h
libtransmission/observable.h
libtransmission/tr-lpd.cc
libtransmission/utils.mm
macosx/DefaultAppHelper.h
macosx/DefaultAppHelper.mm
macosx/GroupCell.h
macosx/GroupCell.mm
macosx/ProgressBarView.h
macosx/ProgressBarView.mm
macosx/SmallTorrentCell.h
macosx/SmallTorrentCell.mm
macosx/TorrentCellActionButton.h
macosx/TorrentCellActionButton.mm
macosx/TorrentCellControlButton.h
macosx/TorrentCellControlButton.mm
macosx/TorrentCellRevealButton.h
macosx/TorrentCellRevealButton.mm
macosx/VDKQueue/VDKQueue.h
macosx/VDKQueue/VDKQueue.mm
tests/libtransmission/global-ip-cache-test.cc
tests/libtransmission/tr-peer-info-test.cc
web/public_html/transmission-app.js.LICENSE.txt
web/src/force-verify-dialog.js

See #4850. Did a sweep through the repo to catch some "wrong" copyright headers and correct them. We should be good now.

chore: cleanup timespans in remaining headers

---

macosx/AddMagnetWindowController.mm
macosx/AddWindowController.mm
macosx/Controller.mm
macosx/DragOverlayWindow.mm
macosx/FilterBarController.mm
macosx/InfoActivityViewController.mm
macosx/InfoOptionsViewController.mm
macosx/InfoWindowController.mm
macosx/MessageWindowController.mm
macosx/PrefsController.mm
macosx/StatusBarController.mm
macosx/Torrent.mm
macosx/TorrentTableView.mm

According to the docs, targeting macOS 10.11+ allows us to remove the code that manually deregisters NSObjects from receiving NSNotificationCenter notifications. This PR does just that. 
In a few cases, this code did nothing as no notifications were sent in the first place.

refactor: remove unnecessary NSNotificationCenter observer removals

---

.github/workflows/actions.yml
libtransmission/torrent.h

This is an experimental PR to see if github has more `macos-12` runners available, since the `macos-11` actions seem to be permanently hung waiting for an available macos-11 runner.
I haven't seen any announcement that the macos-11 runners are being removed, so this is guesswork on my part from [this table](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and from #6197. 6197 tells us that the runners have been getting updates lately, and the table shows us that actions support the latest two versions of each OS and that macos-13 has been in beta. So maybe what's happening is actions have moved on to macos-12 + macos-13.
Hey macOS @transmission/contributors, is there any …

ci: bump macos-11 to macos-12 in github actions

---

.github/workflows/actions.yml

- Update workflow to Qt 6 on macOS
- Remove weird (probably copy-pasted) brew-related lines for Linux

Update workflow to Qt 6 on macOS

---

macosx/Controller.mm
macosx/PiecesView.mm
macosx/ProgressBarView.mm
macosx/Torrent.h
macosx/Torrent.mm

A minor warning fix:
>Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'

fix: Implicit conversion loses integer precision

---

qt/MakeDialog.ui

Modify the new torrent -dialog piece size slider to have a range between 16KiB - 256MiB
This fixes feature disparity for Qt https://github.com/transmission/transmission/issues/5955

Adjust slider limits in Qt

---

qt/CMakeLists.txt

Trying to workaround #6206 build regression on macOS, by increasing CMAKE_OSX_DEPLOYMENT_TARGET, but only for Qt.

!build: turning Qt6 MACOS_SUPPORT_MINIMUM up to 11

---

.gitignore

This file should be placed in the project root
for clangd to pick it up.
At least VSCode do not have settings to specify some custom path.

chore: Add compile_commands.json to .gitignore

---

libtransmission/announcer-http.cc

Fixes #6216.
Until Ubuntu fixes their tracker, users may still see that they got just 1 peer from the announce response. But those who used to connect to just 1 peer should connect to more peers now.
Notes: Improved parsing HTTP tracker announce response.

fix: parse all http announce responses

---

libtransmission/peer-common.h
libtransmission/peer-mgr.cc
libtransmission/torrent.cc
libtransmission/transmission.h
macosx/InfoPeersViewController.mm
macosx/Torrent.h
macosx/Torrent.mm

New feature: display stats for known peers (instead of just stats for connected peers).
Some other torrent clients already have this feature, and I feel this is kind of a must-have for Transmission, especially in light of all the connection issues that we could be facing.
Screenshots: check the last line where it's written "known".
Fixes #1054.

feat: add stats for known peers, not just connected ones

---

libtransmission/completion.cc
libtransmission/file-piece-map.cc
libtransmission/file-piece-map.h
libtransmission/inout.cc
libtransmission/torrent.h
libtransmission/webseed.cc
tests/libtransmission/file-piece-map-test.cc

Part 1/4 of adding empty file support to Transmission. Part 4 of this series will resolve #417 and #6190.
Next part at #6230.

refactor: optionally include 0 byte files when computing file offset

---

libtransmission/peer-mgr.cc
tests/libtransmission/file-piece-map-test.cc

fix two enw clang-tidy warnings.
- implicit bool -> int conversion in `file-piece-map-test.cc`
- potential nullptr dereference in `on_handshake_done()`

fix: recent clang-tidy warnings

---

libtransmission/variant-json.cc

Followup to https://github.com/transmission/transmission/pull/6233, fix one more clang-tidy warning.

fix: clang-analyzer-core.NullDereference warning in tr_variant_serde::parse_json()

---

.github/workflows/update-copyright.yml

This is a re-submit of PR #4852. Sorry for the inconvinience.
Added a workflow/action that will run at 03:00 AM in January 1st (or on demand) to update the copyright year in the following files:
- COPYING (aka the license file)
- User-facing/GUI files:
- gtk/Application.cc
- qt/LicenseDialog.ui
- macosx/*/InfoPlist.strings
- macosx/Info.plist
- macosx/Info.plist.in
- macosx/QuickLookPlugin/Info.plist.in
- macosx/QuickLookPlugin/QuickLookPlugin-Info.plist
- cmake/Transmission.rc.in (string file in CMAKE)
The Action will create a new branch called "license/copyright-to-YYYY" and a matching PR ("chore: update copyright years") with 4 commits inside (one for the license, two for user facing files, one for the CMAKE string). PR/commits will originate from the "github-actions" user. You are …

chore: automated copyright update with GitHub Actions

---

gtk/Session.cc
libtransmission/resume.cc
libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/variant.cc
libtransmission/variant.h
qt/VariantHelpers.cc
tests/libtransmission/variant-test.cc
utils/edit.cc

This branch is from awhile back but I didn't get around to PRing it. I should have done, so here it is.
This PR removes most of the older `tr_variantInitFoo()` methods.

refactor: migrate variant api

---

libtransmission/bandwidth.cc
libtransmission/bandwidth.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-msgs.cc
libtransmission/resume.cc
libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h
libtransmission/utils.cc
libtransmission/webseed.cc
tests/libtransmission/utils-test.cc
tests/libtransmission/values-test.cc

This PR uses the `Values::Speed` class in `tr_bandwidth` and in the code that calls it.
This is part 2 in the [`libtransmission::Values`](https://github.com/transmission/transmission/pull/6215) series. See #6215 for more information.

refactor: Values pt. 2 - use Speed in tr_bandwidth

---

libtransmission/inout.cc
libtransmission/lru-cache.h
libtransmission/open-files.cc
libtransmission/open-files.h
tests/libtransmission/open-files-test.cc

Part 2/4 of adding empty file support to Transmission. Part 4 of this series will resolve #417 and #6190.
Previous part at #6229, next part at #6231.

refactor: thread-safe `lru-cache` and `tr_open_files`

---

Transmission.xcodeproj/project.pbxproj

This is the Xcode proj equivalent of #1026 (November 2019) and 077f4d8d2b50adcd27720e8e8aa411bb819f6364 (August 2020):
- setting C11 and C++17 as **default** for the whole project (instead of GNU98 and GNU++98).
This change is needed for fixing https://github.com/transmission/libutp/issues/6 because newer libutp will no longer build with C++98.

Bumping pbxproj to C11/C++17 for all targets

---

libtransmission/cache.cc
libtransmission/cache.h
libtransmission/torrents.cc
libtransmission/torrents.h

Part 3/4 of adding empty file support to Transmission. Part 4 of this series will resolve #417 and #6190.
Previous part at #6230, next part at #6232.

refactor: thread-safe `Cache`

---

libtransmission/announcer-udp.cc
libtransmission/announcer.cc
libtransmission/announcer.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/web.cc
libtransmission/web.h

Fixes #6249.
Fixes `Closing transmission session...assertion failed: n_stops > 0U (/home/hyy/git_src/Transmission/libtransmission/announcer.cc:197)` after #6223, which made `n_stops` no longer reliable.
To ensure all `&event=stop` announces were sent out, instead of using yet another counter, just check if `web_` and `announcer_udp_` are currently idle or not.

refactor: directly check if announcers are idle instead of using a stop counter

---

libtransmission/rpcimpl.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/torrents.cc

Minor refactor to make some `tr_torrent` fields private:
- obfuscated_hash_
- is_deleting_
- is_dirty_
- is_queued_
- is_stopping_

refactor: make some tr_torrent fields private

---

libtransmission/peer-mgr.cc
libtransmission/resume.cc
libtransmission/session.cc
libtransmission/torrent.cc
libtransmission/torrent.h

Convenience / safety class used by `tr_torrent`:
```c++
CumulativeCount bytes_corrupt_;
CumulativeCount bytes_downloaded_;
CumulativeCount bytes_uploaded_;
```

refactor: add private helper class CumulativeCount

---

gtk/DetailsDialog.cc
gtk/MainWindow.cc
gtk/PrefsDialog.cc
gtk/Torrent.cc
gtk/Torrent.h
gtk/Utils.cc
gtk/Utils.h
gtk/main.cc
libtransmission/torrent.h
libtransmission/utils.cc
libtransmission/utils.h
libtransmission/values.h
macosx/Controller.mm
qt/Application.cc
qt/Application.h
qt/DetailsDialog.cc
qt/FileTreeItem.cc
qt/FileTreeView.cc
qt/Formatter.cc
qt/Formatter.h
qt/FreeSpaceLabel.cc
qt/MainWindow.cc
qt/MakeDialog.cc
qt/PrefsDialog.cc
qt/Speed.h
qt/StatsDialog.cc
qt/TorrentDelegate.cc
qt/TrackerDelegate.cc
tests/libtransmission/values-test.cc

This PR
- removes the `tr_formatter_init` API from `utils.h` and uses the `libtransmission::Values` instead.
- increases use of `Values::Speed` in the GTK client
This is part 7 in the libtransmission::Values series. See #6215 for more information.

refactor: Values pt. 7 - remove tr_formatter_init methods

---

libtransmission/resume.cc
libtransmission/resume.h
libtransmission/session.cc
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/rename-test.cc

One reason why `tr_torrent` has so many public fields is so that the `resume.cc` functions -- some of which are in an anonymous namespace and can't be declared as friends of `tr_torrent` -- can serialize / deserialize them into `.resume` files. 
These could be moved out of the anonymous namespace and be made friends, but this PR lets `resume.cc` do its job with more limited access with a new helper class, `tr_torrent::ResumeHelper`, which is a simple [attorney-client](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Friendship_and_the_Attorney-Client) class to let `resume` get _some_ access to `tr_torrent`'s internals. This lets us make more of `tr_torrent` private.
As a proof-of-concept in this initial PR, these `tr_torrent` fields and methods are now private:
- …

refactor: make tr_torrent::seconds_[seeding,downloading] private

---

libtransmission/peer-mgr.cc
libtransmission/resume.cc
libtransmission/torrent.cc
libtransmission/torrent.h

Part 2 in a "make `tr_torrent` fields private" series. See more info in Part 1 at https://github.com/transmission/transmission/pull/6279
This PR makes these fields private:
- tr_torrent::date_active_
- tr_torrent::date_added_ 
- tr_torrent::date_changed_ 
- tr_torrent::date_done_ 
- tr_torrent::date_edited_ 
- tr_torrent::date_started_

refactor: make tr_torrent date fields private

---

.github/workflows/webapp.yml
web/assets/css/transmission-app.scss

This is a minor css cleanup PR. It replaces some sass use with modern css.
- prefer [css calc()](https://caniuse.com/calc) over sass.math
- prefer [css variables](https://caniuse.com/css-variables) over sass variables
- remove some unused sass mixins
This PR came about because I was reading through our sass use for #6280, but FWIW this is just a sass cleanup PR that doesn't affect the bigger changes in 6280.
CC @niol because this upstreams some of his work e.g. removing the sass math

refactor: prefer css vars over sass

---

libtransmission/announcer.cc
libtransmission/cache.cc
libtransmission/peer-mgr.cc
libtransmission/resume.cc
libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/webseed.cc
tests/libtransmission/move-test.cc

Part 3 in a "make `tr_torrent` fields private" series. See more info in Part 1 at #6279.
This PR makes the following private:
- `tr_torrent::download_dir_`
- `tr_torrent::incomplete_dir_`
- `tr_torrent::current_dir_`
- `tr_torrent::finished_seeding_by_idle_`
- `tr_torrent::file_mtimes_`
- `tr_torrent::fpm_`
- `tr_torrent::completion_`
- `tr_torrent::bandwidth_`
- `tr_torrent::metainfo_`
- `tr_torrent::blocks()`
- `tr_torrentt::set_has_piece()`
- `tr_torrent::recheck_completeness()`
- `tr_torrent::on_tracker_response()`
- `tr_torrent::init_checked_pieces()`
- `tr_torrent::idle_seconds_left()`
- `tr_torrent::set_needs_completeness_check()`
- `tr_torrent::init()`
- `tr_torrent::checked_pieces_`
- `tr_torrent::is_running_`
- `tr_torrent::start_in_session_thread()`

refactor: make tr_torrent fields, methods private where possible

---

libtransmission/tr-dht.cc
libtransmission/variant.h

fix: Local variable 'pex' will be copied despite being returned by name

---

macosx/TorrentTableView.mm

In Xcode 11, we're encountering this runtime warning:
>It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
Setting a breakpoint on _NSDetectedLayoutRecursion reveals that it's caused by the two "redraw buttons" lines. Changing `display` to `needsDisplay` solves the runtime warning.
I think that it was originally `[controlView setNeedsDisplayInRect:cellFrame];` and that it was changed to `display` in #5147, so I'll let @sweetppro review this.

Fix warning: "It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out."

---

libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h

Part 4 in a series to make more `tr_torrent` fields and methods private. See more info in Part 1 at #6279.
This PR makes `tr_torrent::queuePosition` private.

refactor: make tr_torrent::queue_position_ private

---

libtransmission/rpcimpl.cc
libtransmission/torrent.cc
libtransmission/torrent.h

Part 5 in a series to make more tr_torrent fields and methods private. See more info in Part 1 at #6279.
This PR makes `tr_torrent::on_announce_list_changed()` private.

refactor: make tr_torrent::on_announce_list_changed() private

---

libtransmission/peer-mgr.cc
libtransmission/resume.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h

Part 6 in a series to make more tr_torrent fields and methods private. See more info in Part 1 at #6279.
This PR makes these fields / methods private:
- `tr_torrent::byte_span()`
- `tr_torrent::completeness_`
- `tr_torrent::is_dirty()`
- `tr_torrent::mark_changed()`
- `tr_torrent::mark_edited()`
- `tr_torrent::max_connected_peers_`
- `tr_torrent::metainfo()`
- `tr_torrent::set_dirty()`
- `tr_torrent::start_when_stable_`

refactor: make more tr_torrent fields private

---

macosx/VDKQueue/VDKQueue.h
macosx/VDKQueue/VDKQueue.mm

Context: a year ago, we took responsibility to maintain a fork of VDKQueue (#4202).
Today, @gobbledegook suggested a memory fix to the legacy repo (https://github.com/bdkjones/VDKQueue/pull/20).
Their observation is that `[NSThread detachNewThreadSelector:@selector(watcherThread:) toTarget:self withObject:nil]` will prevent `self` from ever being released.
The present pull request:
- fix the memory leak (more elegantly, in my opinion, than how gobbledegook is suggesting to do it, because I do not introduce an extra method (that has also the benefit of staying a drop-in replacement of the original VDKQueue).
- name the detached thread ("VDKQueue") for debugging.
- handle any form of paths, even those with `~`, by standardizing them.
Testing:
1. No regressions: if you go into Transmission …

VDKQueue: support deallocating the object

---

web/src/open-dialog.js

Select dialog now uses the [accept attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept) so only torrent files are shown in the dialog. Saves the UI being cluttered with unrelated files.
Specifies torrent files as either being files ending in `.torrent` or having the [application/x-bittorrent mime-type](https://mimeapplication.net/x-bittorrent) associated with them

feat: Only show .torrent files in the web UI

---

libtransmission/error.h
libtransmission/peer-msgs.cc
libtransmission/resume.cc
libtransmission/rpcimpl.cc

avoid a few unnecessary temporary heap allocations.

perf: fewer temporary strings

---

libtransmission/cache.cc
libtransmission/cache.h
libtransmission/inout.cc
libtransmission/inout.h
libtransmission/open-files.cc
libtransmission/open-files.h
libtransmission/peer-msgs.cc
libtransmission/session-settings.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h
libtransmission/variant-converters.cc
tests/libtransmission/open-files-test.cc
tests/libtransmission/settings-test.cc

A minor cleanup to make inout's code `const` where possible.
This PR is just a cleanup, but my eventual goal here is to have `tr_cache` and `inout` have a consistent API so that they can be decoupled, and to decouple `inout` from the `tr_torrent` object as much as possible to make it easier to make file IO async.

refactor: constify the inout module

---

docs/Editing-Configuration-Files.md
libtransmission/cache.cc
libtransmission/cache.h
libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.h
libtransmission/inout.cc
libtransmission/inout.h
libtransmission/peer-msgs.cc
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/session-settings.h
libtransmission/session.h
libtransmission/verify.cc

Prefetch was added as a way to ameliorate blocking disk reads in the session thread.
It's unimplemented on Win32, we've never done any metrics on its benefits / lack of benefits on Linux / macOS, and it's unnecessary when we're moving to async disk IO.

refactor: remove prefetch

---

libtransmission/block-info.cc
libtransmission/block-info.h
libtransmission/file-piece-map.cc
libtransmission/file-piece-map.h
libtransmission/resume.cc
libtransmission/torrent-metainfo.cc
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/block-info-test.cc
tests/libtransmission/file-piece-map-test.cc

Not what I was expecting to do today, but I wound up with a few of hours with no internet connectivity, so I did this cleanup PR.
This cleanup PR to `tr_block_info`, `tr_file_piece_map`, `tr_file_priorities`, `tr_files_wanted`:
- adds `const` to method args where possible
- moves complicated / non-constexpr methods out of the headers into the .cc files
- changes a couple of methods from public to private
- removes a couple of unused methods
- uses consistent method naming between classes (e.g. `foo_span_for_bar()`)
- fixes some minor signed vs unsigned comparisons / assignments
- uses standard class order declaration, e.g. public methods first, then private methods, then private fields

refactor: tr_block_info cleanup

---

qt/FileTreeItem.cc
qt/FileTreeItem.h

Update how a file's progress % is calculated in the Qt client's file tree s.t. zero-byte files show as complete.
CC @tearfur @Coeur 
Xref https://github.com/transmission/transmission/pull/6232#issuecomment-1827944236

refactor: show 1.0 progress for zero-byte files

---

libtransmission/peer-io.cc

`EWOULDBLOCK` is interchangeable with `EAGAIN` according to POSIX.1-2001, but it was not included in `canRetryFromError()`.

fix: add check for `EWOULDBLOCK`

---

gtk/transmission-gtk.metainfo.xml.in

This also cherry-picks my change from #5407.
The second patch also applies to the main branch. Let me know how best to handle this.

GTK: Add missing 4.0.4 and 4.0.5 releases to metainfo

---

libtransmission/peer-msgs.cc
libtransmission/torrent-magnet.cc

Fixes #5943.
Regression from ca4cb1a675fb951f6ca975e8bb3d4de1ae25ad57.
Cheers to @Xist12gh for discovering the cause of the bug https://github.com/transmission/transmission/pull/6272#issuecomment-1848599934.

fix: sometimes stuck magnet metadata transfer

---

macosx/Controller.mm
macosx/TorrentTableView.mm

NSScreen.frame does not account for the dock, which can be at the bottom or any of the sides. As a result, layout errors that smash things into the dock can occur in the Y or X direction. visibleFrame accounts for the dock.
Should fix #4779. Untested.

Use screen.visibleFrame instead of screen.frame

---

gtk/GtkCompat.h
gtk/OptionsDialog.cc

fix: build when compiling with GTKMM-4

---

libtransmission/variant-json.cc

Fixes this test failure in TeamCity for the new test `TorrentMagnetTest.setMetadataPiece` added in #6383:
```
302/406 Test #302: LT.TorrentMagnetTest.setMetadataPiece ............................................................................................................***Exception: Illegal  0.67 sec
Running main() from ../../../third-party/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = TorrentMagnetTest.setMetadataPiece
```

fix: TeamCity `Illegal instructions` error

---

gtk/transmission-gtk.metainfo.xml.in

This is the novel patch from #6357. The other one was already on main.

GTK: Add 4.0.4 and 4.0.5 releases to metainfo

---

libtransmission/verify.cc
libtransmission/verify.h

This should fix the test failure at https://github.com/transmission/transmission/actions/runs/7237936380/job/19718165673. Since this is a previous regression that is not related to the PR that triggered the failed test, I have separated this fix out to its own PR.
Regression from ed4fad9b1868bbdddfe58d4aaf55032ba3eac70a.

fix: allow aborting torrent verify mid-way again

---

libtransmission/torrent.cc

Fixes #6403.
Notes: Fixed `4.0.0` bugs where some RPC methods don't put torrents in `recently-active` anymore.

fix: mark torrent as changed when stopping

---

.gitignore

Separated out from #6401 since it's simple. See https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html for more info. Note that even though presets require 3.19, it is not required that `cmake_minimum_version()` be 3.19, just that the actual cmake binary be that version.

add user presets to .gitignore

---

gtk/FileList.cc
gtk/OptionsDialog.cc
libtransmission/net.h
libtransmission/resume.cc
libtransmission/subprocess-posix.cc
libtransmission/transmission.h
macosx/FilePriorityCell.mm
tests/gtest/CMakeLists.txt
tests/libtransmission/net-test.cc

Fix some warnings generated when building with g++-13.

fix: gcc-13 warnings pt. 2

---

web/esbuild.mjs

Fixes #6362.
https://esbuild.github.io/content-types/#data-url
Notes: Fixed `4.0.5` bug where svg and png icons in the WebUI might not be displayed.

fix: esbuild load `svg` and `png` as `dataurl` type

---

tests/libtransmission/makemeta-test.cc

See https://github.com/transmission/transmission/pull/5961#issuecomment-1859040164 for the test failure that this PR is supposed to fix.
Regression from ed4fad9b1868bbdddfe58d4aaf55032ba3eac70a.

fix: don't create all 0-byte files in `MakemetaTest::makeRandomFiles()`

---

web/README.md

I forgot about these in #6409.
Notes: Fixed `4.0.5` bug where svg and png icons in the WebUI might not be displayed.

fix: update WebUI build instructions to use `dataurl` loader for images

---

libtransmission/rpc-server.cc
libtransmission/session-thread.cc
libtransmission/session-thread.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent.cc
libtransmission/webseed.cc
tests/libtransmission/move-test.cc

This PR allows code that is running in the session thread to queue functions to the session thread instead of executing them immediately.
This removes the need for the `tr_torrentMagnetDoIdleWork()` indirection step, see https://github.com/transmission/transmission/pull/6383#discussion_r1429202253 for more details about this topic.
A patch to demonstrate how this can be done after this PR and #6383 are merged (already tested):
<details>
<summary>patch</summary>
```patch
From 1351cd07a168daa64c8e50219a32b7891ad5b6ad Mon Sep 17 00:00:00 2001
From: Yat Ho <lagoho7@gmail.com>
Date: Mon, 18 Dec 2023 15:13:54 +0800
Subject: [PATCH] refactor: check metadata transfer completion in
`set_metadata_piece()`
---
libtransmission/peer-mgr.cc       |  1 -
libtransmission/torrent-magnet.cc | 24 …
```

refactor: allow explicitly queuing functions in session thread

---

libtransmission/announce-list.h
libtransmission/announcer-common.h
libtransmission/favicon-cache.h
libtransmission/file-piece-map.h
libtransmission/log.cc
libtransmission/magnet-metainfo.cc
libtransmission/magnet-metainfo.h
libtransmission/makemeta.cc
libtransmission/makemeta.h
libtransmission/net.h
libtransmission/peer-io.h
libtransmission/torrent-ctor.h
libtransmission/tr-buffer.h
libtransmission/tr-macros.h
libtransmission/utils.h
libtransmission/values.h
libtransmission/verify.cc

- Remove unnecessary #include calls from utils.h
- Remove places where we include utils.h without using it
- If a header function uses utils.h and can be moved to a .cc file, do that to reduce other files including as a side-effect
- Fix a couple of nearby iwyu warnings

refactor: reduce utils.h includes

---

gtk/Session.cc
gtk/Session.h
libtransmission/transmission.h

Its main use was removed in 69577ea4b9acfe512322ea2740b9149b42287864 and it remaining use was just incidental, so this PR finishes removing it.

refactor: remove tr_parse_result enum

---

daemon/CMakeLists.txt
daemon/transmission-daemon.service

See the commit message for the rationale. Fedora 40 is also looking to do [something similar](https://fedoraproject.org/wiki/Changes/SystemdSecurityHardening).
I have personally been running my daemon, with 1000+ torrents, for weeks without this blocking or preventing anything. I think this should also be distro-agnostic, but if anyone wants to attempt to test this on their own installs, you can do
```sh
systemctl edit transmission-daemon.service
systemctl restart transmission-daemon.service
```

Harden systemd service

---

libtransmission/rpcimpl.cc

Add sequentialDownload to list of rpc get response keys

---

utils/remote.cc

fix: `sequentialDownload` support in `transmission-remote`

---

macosx/VDKQueue/VDKQueue.h
macosx/VDKQueue/VDKQueue.mm

Fix https://github.com/bdkjones/VDKQueue/pull/22.
Instead of polling `kevent` every second, we remove the `timeout` and we send a one-shot event when we want to stop watching.
Testing: with DEBUG_LOG_THREAD_LIFETIME enabled, I can see "watcherThread finished." instantly after turning off the "Watch for torrent files" option in the Transmission settings.

perf: Don't poll every second for kevents

---

web/assets/css/transmission-app.scss
web/src/torrent-row.js

Picking up @GaryElshaw's work from #5961 to bring the WebUI's colours closer to the macOS app, and also improve readability.
Changes:
- For paused torrents, instead of just the torrent name, now all text and also the MIME icon will be greyed out. I think this looks better and makes it even more obvious that the torrent is paused.
- Compact mode will also grey out paused torrents now.
- Following macOS app's palettte, the text for selected torrents will now be white to stand out against the bright blue background. Light/dark, normal/contrast mode differ only in the shade of white.
In https://github.com/transmission/transmission/pull/5961#issuecomment-1872068850, I stated that I prefer *not* greying out paused torrents. I have changed my mind now, because it is quite hard to notice at a …

webui: make torrent row colours more readable

---

po/CMakeLists.txt

Only leave translations that are 90+% complete. This means the dropped ones won't be installed, but (as with Qt client) will still be there in the repo to avoid the need in adding them back if/when the time comes.
This somewhat addresses #6474.

Remove low-quality gettext locales from the list

---

CMakeLists.txt
libtransmission/CMakeLists.txt

Fix #6415
Would also need to be cherry picked to 4.0.x branch.
Regression was caused by #5632 which uses CXX_COMPILER_ID and COMPILE_LANGUAGE with comma-separated lists, which is only possible since https://cmake.org/cmake/help/v3.15/manual/cmake-generator-expressions.7.html.
Rewriting CXX_COMPILER_ID and COMPILE_LANGUAGE usages to not use comma-separated lists would be a bit complex.
So I prefer to bump cmake minimum requirement.
cmake 3.12 was released on [Nov 30, 2018](https://github.com/Kitware/CMake/releases/tag/v3.12.0)
cmake 3.15 was released on [Jul 17, 2019](https://github.com/Kitware/CMake/releases/tag/v3.15.0)
So the version jump is less than 1 year diff, even though we raised to 3.12 about a year ago, in #4507.

Fix libtransmission build on very old cmake versions

---

macosx/Controller.h
macosx/Controller.mm
macosx/TorrentTableView.mm

Adopts Apple recommendations and support multiple URL objects instead of a single one from pasteboard.
In practice:
- replace `URLFromPasteboard` with `readObjectsForClasses:@[ [NSURL class] ]`
- move the code outside of TableViewController

Support multiple URL objects from pasteboard

---

libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-socket.cc

Part 2 of a series to fix #6361.
See the discussion and description of this PR series at part 1 https://github.com/transmission/libutp/pull/15.

fix: implement proper download limit for uTP

---

libtransmission/peer-mgr.cc
libtransmission/peer-msgs.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent-magnet.h
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/test-fixtures.h
tests/libtransmission/torrent-magnet-test.cc

2 commit containing minor functional changes:
- `refactor: unset peer BEP-9 support if size hint is invalid`
- `refactor: check metadata transfer completion in set_metadata_piece()`
It's a big refactor, so some help on spotting regressions and comments about how to improve code organisation is welcomed.

refactor: convert `tr_incomplete_metadata` to c++ class

---

gtk/Application.cc
gtk/DetailsDialog.cc
gtk/Session.cc
gtk/Session.h
libtransmission/rpc-server.cc
libtransmission/rpcimpl.cc
libtransmission/rpcimpl.h
qt/RpcClient.cc
qt/RpcClient.h
tests/libtransmission/rpc-test.cc

This PR dusts off some work I did a month or two back, but never merged.
It updates `rpcimpl.cc` to use the new `tr_variant` API.

refactor: use new tr_variant API in rpcimpl

---

libtransmission/session-alt-speeds.h

Fixes #6449.
Regression from 611d36ac84f24adf4b4237b49a411cba3276ca60.
Notes: Fixed `4.0.0` bug where `alt-speed-enabled` had no effect in `settings.json`.

fix: restore `alt-speed-enabled` config parameter

---

libtransmission/file-piece-map.cc
libtransmission/torrent.cc

fix a minor bug in `tr_file_piece_map::file_span_for_piece()`  that took a reference to values returned by `std::equal_range()`

fix: reference to temporary

---

cli/cli.cc
daemon/daemon-win32.cc
daemon/daemon.cc
gtk/Prefs.cc
libtransmission/crypto-utils-mbedtls.cc
libtransmission/crypto-utils-wolfssl.cc
libtransmission/file-win32.cc
libtransmission/net.cc
libtransmission/web.cc
qt/DetailsDialog.cc
qt/PrefsDialog.cc
utils/edit.cc
utils/remote.cc

https://releases.llvm.org/16.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/misc/use-anonymous-namespace.html

chore: fix misc-use-anonymous-namespace warnings from clang-tidy

---

cli/cli.cc
daemon/daemon.cc
gtk/Prefs.cc
libtransmission/session.cc
libtransmission/transmission.h
qt/Prefs.cc
qt/Session.cc

Regression from ebb1b775afa6ebac4e271cfec530d9639003f0df.
One example of the effects of this regression is that `rpc-enabled` should default to `true` for the daemon, but it does not right now in `main`.

fix: app defaults should override libtransmission defaults

---

libtransmission/rpcimpl.cc
tests/libtransmission/rpc-test.cc

Fixes #6482.
Regression from 22cde5d4b9ac43ac73f1309cb1021f0dd187e9f0.

fix: restore the `tag` key in RPC response

---

web/src/statistics-dialog.js
web/src/torrent-row.js

Fixes #6356.
Notes: Fixes a `4.0.0` bug where infinite ratio symbol is not displayed properly in the WebUI.

fix: WebUI render html entity in torrent ratio

---

web/assets/css/transmission-app.scss

These changes got lost when I was messing with git rebase and whatnot...
61ed621f55f6b4c8f5414260159c18129f304899 introduced a visual regression where the upload/download speed labels are not aligned to the right of the viewport, this PR restores it.

fixup! chore: webui scss cleanup (#6471)

---

utils/edit.cc

fix `[[nodisard]]` tyop introduced in 646883174b

fixup! chore: fix misc-use-anonymous-namespace warnings from clang-tidy

---

update-version-h.sh

Fix #6485
Bug was caused by #3867
Should be ported back to 4.0.x

fix: base62 conversion in peer-id generation

---

web/src/statistics-dialog.js
web/src/torrent-row.js

(cherry picked from commit 3b017dbd86ec41403bebb74a8106d004241540e9)
Notes: Fixes a `4.0.0` bug where infinite ratio symbol is not displayed properly in the WebUI.

fix: WebUI render html entity in torrent ratio (#6491)

---

qt/VariantHelpers.cc

Prior to Transmission 4.00 / RPC 5.3.0, sitenames were constructed from announce urls and used for filtering, favicon cache lookups, etc. Since Transmission 4.00 / RPC 5.3.0, sitenames are part of the RPC spec and can be fetched from the server. When a 4.00 client communicates with a 3.00 server, this behavior breaks and filtering and favicon lookup no longer work. This PR reintroduces compatibility of 4.00 clients with pre-RPC 5.3.0 servers.
Fixes #6402

fix: parsing sitename info from 3.xx Servers

---

gtk/FileList.cc
gtk/FilterBar.cc
gtk/FilterBase.h
gtk/ListModelAdapter.h
gtk/Session.h
gtk/SorterBase.h
gtk/Torrent.h
gtk/TorrentFilter.h
gtk/Utils.h
libtransmission/announcer-udp.cc
libtransmission/peer-msgs.cc
libtransmission/port-forwarding-upnp.cc
libtransmission/rpc-server.cc
libtransmission/rpcimpl.cc
libtransmission/torrent-metainfo.cc
libtransmission/tr-dht.cc
tests/libtransmission/watchdir-test.cc

Another PR in a series to get the codebase green when checked with clang-tidy-18.
This is a smaller PR that fixes the `performance-enum-size` warnings

fix: performance-enum-size warnings

---

libtransmission/rpc-server.cc
libtransmission/rpc-server.h

Fixes #6473.
Notes: Fixed `4.0.0` bug where the GTK client's "Use authentication" option is not saved across sessions.

fix: use one variable to store `TR_KEY_rpc_authentication_required`

---

qt/DetailsDialog.cc
qt/DetailsDialog.ui
qt/FilterBar.cc
qt/FilterBar.h
qt/MakeDialog.ui
qt/PrefsDialog.ui
qt/RelocateDialog.ui
qt/SessionDialog.ui
qt/StatsDialog.ui
qt/TrackersDialog.ui

What's in this PR:
* Replace section labels with group boxes, planning on doing the same for GTK client
* Change where turtle is placed in preferences dialog (group box titles don't handle rich formatting and :turtle: emoji isn't widely supported)
* Fix tab order
* Strip unnecessary HTML in [read-only] text edit controls and tooltips
* Make value labels focusable in torrent properties and statistics dialogs, assign buddies (fixes #6512)
* Replace text browser with read-only plain text edit for comment field in torrent details
What's not in this PR:
* Path button/edit controls accessibility (will need code changes)
* Updating prefix/suffix for plurals in spin edit controls (will need code changes)
* Accessible names/descriptions for controls which need it, mostly those w/o buddy labels …

Qt client accessibility improvements (part 1)

---

appveyor.yml

Using ccache 4.9 leads to puzzling errors such as C1090 "PDB API call failed, error code '23'" when building for x64.

Pin ccache to 4.8.3 on AppVeyor

---

qt/AccessibleSqueezeLabel.cc
qt/AccessibleSqueezeLabel.h
qt/Application.cc
qt/CMakeLists.txt
qt/SqueezeLabel.cc
qt/SqueezeLabel.h
qt/StatsDialog.ui

Expose label text as accessible value instead of accessible name, and get accessible name from buddy label as any proper input widget does. Don't expose label tooltip as accessible description unless it's different from its text (which isn't the case when displayed text is truncated). Notify on label text and selection changes.
Switch to `SqueezeLabel` for values in statistics dialog which has similar layout to information tab of torrent properties dialog.
Notes: Improve Qt client's accessibility.

Make `SqueezeLabel` [more] accessible

---

.github/workflows/codeql.yml

See https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2

Bump CodeQL to v3 (v2 is to be deprecated)

---

qt/MakeDialog.cc

Label update is made when slider changes its value, and on source change slider value is being set to a newly calculated, but not necessarily different from the previous one, value. This means that the slider change signal may not be emitted, in which case label continues to show previous text, including "No source selected", which is misleading.
The issue could also lead to piece size slider staying disabled, preventing user from adjusting the size.
Notes: Fixed `4.0.0` bug where piece size description text and slider state in torrent creation dialog is not always up-to-date.

Update pieces label on source change even if piece size doesn't change

---

libtransmission/peer-io.cc

Fixes #5261.
Instead of scheduling an ACK to be sent when the read buffer is empty, this PR schedules an ACK as soon as we read a packet from libutp.
I've noted in https://github.com/transmission/transmission/issues/5261#issuecomment-1880924976 that this change improves download speeds a lot for me, and I think this a natural result.
For any TCP-like protocols, when receiving a packet, it is more beneficial to send the ACK sooner than later, so that the sender can also move on to the next packets sooner, thus maintaining a higher transfer rate. In our case, the `UTP_ON_READ` callback is called whenever libutp processed an incoming data packet, so it makes sense to call `utp_read_drained()` here unconditionally.
Notes: Improved µTP download performance.

fix: always schedule uTP ack after receiving a packet

---

web/src/open-dialog.js

This reverts commit c853ec33587c58059f17d1f3942dca065668f43c.
Explanation: https://github.com/transmission/transmission/pull/6320#issuecomment-1896968904

Revert "feat: Only show .torrent files in the web UI (#6320)"

---

gtk/.clang-tidy
gtk/FileList.cc
libtransmission/file-posix.cc
libtransmission/subprocess-posix.cc
qt/.clang-tidy
tests/libtransmission/.clang-tidy
tests/libtransmission/bitfield-test.cc

Each of these changes are each a little involved, which maybe is a sign that the guidelines are correct in their assessment that `do-while` leads to overly complex / bugprone code :man_shrugging: 
I've tried to make these new forms either simpler / easier to read (e.g. `get_filename_to_open()`, `tr_sys_file_lock()`); or failing that, at least not worse (e.g. `handle_sigchld()`)

refactor: fix cppcoreguidelines-avoid-do-while warnings

---

libtransmission/peer-io.cc

Fixes #6506.
I found the "edge case" that I couldn't find at https://github.com/transmission/transmission/pull/6481#issuecomment-1874977937.

fix: keep peer io alive inside utp callback

---

libtransmission/rpcimpl.cc

Regression from 22cde5d4b9ac43ac73f1309cb1021f0dd187e9f0.
Currently, `files-wanted` has the same effect as `files-unwanted`. This PR fixes that.

fix: restore `files-wanted` argument of `torrent-set`

---

gtk/.clang-format
gtk/Application.cc
gtk/MessageLogWindow.cc
gtk/TorrentFilter.cc
gtk/TorrentSorter.cc
libtransmission/log.cc
libtransmission/peer-mgr-wishlist.cc
libtransmission/torrents.cc
libtransmission/utils.cc
qt/FileTreeItem.cc
qt/FileTreeModel.cc
qt/FilterBar.cc
qt/FilterBar.h
qt/OptionsDialog.h
qt/Prefs.cc
qt/Prefs.h

Replace `std::map` and `std::string` with `small::` counterparts in unambiguous cases, e.g. where the size is known upfront to be relatively small.

perf: prefer small containers

---

macosx/Controller.mm
macosx/CreatorWindowController.mm
macosx/Torrent.mm
macosx/TrackerCell.mm

Attempt to fix #6522. Regression from #4208.
Notes: fix app unable to start when having many torrents and TimeMachine enabled

only use a single concurrent queue for timeMachineExclude instead of one queue per torrent

---

libtransmission/torrent.cc

These needed manual backporting because the API changed.
Notes: Fixed `4.0.0` bugs where some RPC methods don't put torrents in `recently-active` anymore.

chore: backport recently active fixes

---

web/README.md
web/src/move-dialog.js

Notes: Fixed `4.0.5` bug where svg and png icons in the WebUI might not be displayed.
Notes: Fixed `4.0.0` bug where the WebUI "Set Location" dialogue does not auto fill the selected torrent's current download location.

chore: backport recent WebUI fixes

---

update-version-h.sh

cherry pick of #6486 for 4.0.x

fix: base62 conversion in peer-id generation (#6486)

---

docs/Editing-Configuration-Files.md
libtransmission/peer-msgs.cc
libtransmission/session-settings.h
libtransmission/session.h
libtransmission/tr-dht.cc
libtransmission/tr-dht.h
tests/libtransmission/dht-test.cc

Notes: Improved DHT performance.
This PR does 4 things:
1. Fixes a `4.0.0` regression from 5ce503f1ab23efb497c64386615c48a4a75d4b46 where Tr clients on IPv4-only networks does not send DHT Port message *at all*.
2. Fixes a `4.0.0` regression from 9e06cf8f2e23f9aa708d7b6c16f8fd13bda39399 where the node ID is no longer initialised randomly.
3. Modifies Tr's behaviour so that we send a DHT Port message as long as DHT is supported by both ends.
**Rationale**
We used to avoid sending IPv6 DHT Port messages if our IPv6 bind address is not a global unicast address, because BEP-32 says that `The IPv6 DHT should use a socket bound to one of the host's global unicast IPv6 addresses rather than the "unspecified address" (::/128).`. I think this should not stop us from sending DHT Port messages. …

fix: various DHT bugs

---

libtransmission/peer-mgr-wishlist.cc
libtransmission/peer-mgr-wishlist.h
libtransmission/peer-mgr.cc
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/peer-mgr-wishlist-test.cc

Fixes #6535, more explanation can be found in the GitHub issue.
This PR basically reintroduces the wishlist implementation in `3.00`, which caches piece candidates, and prefers rarer pieces (`4.0.x` wishlist doesn't do any of these).
If your download speed in `4.0.x` has been bottlenecked by CPU, and if my test results don't lie, then you should notice speed improvements in this PR.
Attached a flamegraph captured in a debug build, I captured many other flamegraphs in this PR, and they look about the same as this one:
Notes: Improved libtransmission code to use less CPU.

perf: restore `3.00` wishlist with cached candidates

---

macosx/Controller.mm
macosx/CreatorWindowController.mm
macosx/Torrent.mm
macosx/TrackerCell.mm

cherry pick of #6523 for 4.0.x
note: fix macOS startup when using Time Machine with many torrents

only use a single concurrent queue for timeMachineExclude instead of one queue per torrent (#6523)

---

libtransmission/session-alt-speeds.h

(cherry picked from commit 4cfd9f0c9e6ef17e55b31e66a61b289fb0a27284)
Notes: Fixed `4.0.0` bug where `alt-speed-enabled` had no effect in `settings.json`.

fix: restore `alt-speed-enabled` config parameter (#6483)

---

macosx/Controller.mm

1. This is an improvement over #3087, which granted support to one magnet per line: now I'm granting support to multiple magnets per line, in the same vein as what is supported for normal torrent links. And one can even mix a list of links and magnets altogether.
2. This also addresses the question written as a `#warning` introduced with 2a670d54a9d2c454c8a75933e20d88b44dc6e219 by providing code comments explaining that we're doing the right thing.
I tested the change.
Notes: Support pasting multiple magnets on the same line

Support multiple magnets on the same line

---

libtransmission/net.cc

fix crash on empty filedescriptor after `accept`

---

libtransmission/peer-mgr-wishlist.cc
libtransmission/peer-mgr-wishlist.h

This PR introduces further performance improvements to #6549, and also refactors `Wishlist` using the PImpl idiom.
`Wishlist::resort_piece()` was especially improved, it has virtually no overhead now.
Notes: Improved libtransmission code to use less CPU.
See #6549.

perf: followup improvements to `3.00` Wishlist

---

docs/Editing-Configuration-Files.md
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/session-settings.h
libtransmission/session.cc
libtransmission/variant-converters.cc
libtransmission/verify.cc
libtransmission/verify.h
tests/libtransmission/settings-test.cc

Should close #1331. This pull request comes with an additional feature that let power users modify the verification process's behavior dynamically. By leveraging the newly implemented `sleep_per_seconds_during_verify` setting, it is now possible to adjust the sleep duration between piece verifications, in order to reduce I/O utilization.

feat: added `sleep-per-seconds-during-verify` to settings.json

---

gtk/transmission-gtk.metainfo.xml.in

`developer_name` has become mandatory on Flathub, so I've added these patches to the Flathub build of Transmission.

GTK: Add developer name (and screenshot caption) to metainfo

---

libtransmission/announcer-http.cc
libtransmission/announcer-udp.cc
libtransmission/announcer.cc
libtransmission/file-posix.cc
libtransmission/global-ip-cache.cc
libtransmission/open-files.cc
libtransmission/peer-io.cc
libtransmission/peer-mgr.cc
libtransmission/peer-msgs.cc
libtransmission/rpc-server.cc
libtransmission/rpcimpl.cc
libtransmission/session-id.cc
libtransmission/session.cc
libtransmission/torrent-ctor.cc
libtransmission/torrent-metainfo.cc
libtransmission/torrent.cc
libtransmission/tr-assert.cc
libtransmission/tr-dht.cc
libtransmission/tr-lpd.cc
libtransmission/tr-udp.cc
libtransmission/utils.cc
libtransmission/watchdir-inotify.cc
libtransmission/web.cc

fix a handful of warnings found by clang-tidy-19.

fix: clang-tidy-19 warnings

---

docs/Previous-Releases.md

Completely supersedes #6493 with correct versions, names, links and hash.
Notes: document OS X 10.10 - macOS 10.12 compatibility with previous-releases

add OS X 10.10 - macOS 10.12 compatibility to previous-releases

---

web/src/prefs-dialog.js

A follow up of #5953.
Align the WebUI with the Qt and GTK changes from #6525, show `Error` instead of `Closed` in the port test if the daemon did not return a result.
Notes: The WebUI now does separate port checks for IPv4 and IPv6.

feat: WebUI add `Error` case in port test result

---

libtransmission/peer-mgr.cc

Fixes regression introduced by 168d56cefc61871ab40425f23d14ef9163006410.

fixup! perf: restore `3.00` wishlist with cached candidates (#6549)

---

macosx/InfoTrackersViewController.mm

This warning was added by @livings124 in b80a6765e23249fb3e481efda2d826ee0ccde7c4 and is not actionable: there are no bugs to fix.
You can try adding a tracker with a blank address, but AppKit won't call [`tableView:setObjectValue:forTableColumn:row:`](https://developer.apple.com/documentation/appkit/nstableviewdatasource/1526317-tableview) and no tracker will be added.

remove old warning "doesn't like blank addresses"

---

macosx/InfoPeersViewController.mm

warning was added by @livings124 in d5f4c15fb855ec38994b6eba836181ef092d1d3b and addressed in efce4e9

remove old warning: "subclass?"

---

libtransmission/peer-mgr.h

Fixes an edge case that got left out in #6111.
In effect, this bug will cause a lot of the freshly added peer info object that have never seen peer activity to be deleted immediately.

fix: don't consider peer info inactive if any of the time values is 0

---

libtransmission/session.h
libtransmission/torrent.cc
libtransmission/tr-macros.h
tests/libtransmission/subprocess-test.cc
tests/libtransmission/test-fixtures.h
tests/libtransmission/watchdir-test.cc

Minor cleanup that does what it says on the tin.
`TR_PATH_DELIMITER_STR` was removed in dde626d5e5b9ec4e66dc6ee45addb7e21a1de132; this finishes the job.

refactor: remove TR_PATH_DELIMITER

---

libtransmission/peer-msgs.cc
libtransmission/torrent.cc
libtransmission/torrent.h

It's only needed in peer-msgs.cc, so move from the global namespace in `torrent.h` to an anonymous namespace in `peer-msgs.cc`.

refactor: make tr_torrentReqIsValid() private

---

libtransmission/makelog
qt/PathButton.cc
qt/PathButton.h
qt/RpcClient.cc
qt/RpcClient.h
qt/RpcQueue.h
qt/Session.cc
qt/Session.h

There are a handful of getters that are simple one-liners. Inline these and make them `constexpr`.

refactor: inline simple getters in qt client

---

libtransmission/net.cc

Cherry-pick of #6054 otherwise I can't commit on 4.0.x

chore: apply clang-format version 17.0.1 (#6054)

---

daemon/daemon.cc
daemon/daemon.h
libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.cc
libtransmission/file.h
libtransmission/log.cc
tests/libtransmission/subprocess-test-program.cc

Use std streams and `fmt::print()` in daemon.
This lets us remove a handful of bespoke utilities:
- `tr_sys_file_get_std()`
- `tr_sys_file_flush_possible()`
- `tr_sys_file_write_line()`
- `tr_std_sys_file_t`
---
I'm of two minds about this and would like a second opinion:
1. On the one hand, we already have a self-contained API for manipulating files. It works and has all the features we need. This takes away features and now we are using two file APIS: the one in `libtransmission/file.h`, and the one in `cstdio`. Arguably this a change for the worse.
2. On the other hand, appending text to the end of a file is well-supported  by the std library, so duplicating that effort is both redundant and increases the amount of platform-specific code that we need to maintain. If `std::` can do it …

refactor: replace tr_sys_file_write_line() with fmt::print("...\n")

---

web/src/utils.js

`createTabsContainer` seems to be superseded by `createTextualTabsContainer` and is unused
```console
$ grep -nr createTabsContainer src/
src/utils.js:85:export function createTabsContainer(id, tabs, callback) {
```
`setChecked` seems to be superseded by `addCheckedClass` (a bit odd naming as it actually toggles the class) and is unused.
```console
$ grep -nr setChecked src/
src/utils.js:213:export function setChecked(element, b) {
```

refactor(web): Remove unused functions from utils.js

---

web/src/remote.js

Partially fixes [#6396](https://github.com/transmission/transmission/issues/6396)
> But the second problem is a bug in my opinion - when the next POST request succeeds, the error message should disappear and the UI should be updated, but it does not happen.

fix(web): close connection failed alert on successful request

---

libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.h
tests/libtransmission/subprocess-test-program.cc
tests/libtransmission/test-fixtures.h

It was only used in tests. Is it needed? Let's find out by seeing if CI stays green without it.

refactor: remove tr_sys_file_flush()

---

web/src/utils.js

crypto.randomUUID() is the most up to date way to generate UUIDs. It works in secure context (HTTPS) and for localhost. https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
It has a wide browser support, but we are keeping the fallback for older browsers and for cases where users are using a custom hostname without HTTPS, that's not consider a secure context. https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

refactor(web): use crypto.randomUUID for UUID if available

---

.github/workflows/actions.yml
release/windows/build-qt6.ps1

CMake 3.28 dropped support for deriving installation prefix(es) based on `PATH` environment variable on Windows[^1]. Since all the other built packages already pass necessary prefix path(s) explicitly via `CMAKE_PREFIX_PATH` and it works for them, do the same for Qt 6 as well. Building Qt 5 isn't affected as it doesn't use CMake.
Using wrong environment variable name when configuring Transmission itself resulted in empty `CMAKE_PREFIX_PATH` CMake setting value, which showed the effects of CMake 3.28 changes yet again.
[^1]: https://cmake.org/cmake/help/latest/release/3.28.html#other-changes

Support CMake 3.28+ in CI jobs on Windows

---

docs/rpc-spec.md

#5170 restored the behaviour of `torrent-get.wanted` to pre-4.0.0 behaviour for backward compatibility, but it incorrectly updated the docs for `torrent-get.fileStats.wanted` instead. This PR fixes that.
I also think that we should eventually fix this quirk (say 5.0.0), so I've added a note to announce this change in advance.
Notes: Fixed RPC spec that confused `torrent-get.wanted` with `torrent-get.fileStats.wanted`.

docs: fix `torrent-get` `fileStats` and `wanted` docs

---

web/src/remote.js

Fixes regression introduced in 250f43ae, fixes #6674
Somehow didn't figure that the side effect of my previous fix is to always close every other pop-up on successful rpc requests.

fix(web): do not close all popups on successful rpc requests

---

.github/workflows/actions.yml
appveyor.yml

Version 3.14 was recently released with security fixes, and GitHub runners have been updated to use it. Don't hardcode the version in Program Files directory name to support any 3.x. Since 3.x support will be dropped within a year, need to plan migration to 5.x when it's released (4.x isn't suitable because of missing heat replacement).
Fixes #6680.

Support WiX toolset versions other than 3.11

---

libtransmission/favicon-cache.h
qt/RpcClient.cc
tests/libtransmission/dht-test.cc
tests/libtransmission/timer-test.cc

```
✗ clang-format --version
clang-format version 18.1.1
```

fix compatibility with clang-format 18

---

.github/workflows/actions.yml
tests/CMakeLists.txt

Fix #6697 by running the tests on macOS instead of Ubuntu.
[edit]
Running on macOS gave me the error that `-fsanitize=leak` is not supported by Clang, so I removed it:
https://github.com/transmission/transmission/actions/runs/8295707626/job/22703306911
>clang: error: unsupported option '-fsanitize=leak' for target 'arm64-apple-darwin23.2.0'

add sanitizer-tests-macos

---

.gitmodules
CMakeLists.txt
Transmission.xcodeproj/project.pbxproj

Fix #5609.
Same as #3020, but rebased to main.
Adopting miniupnpc 2.2.6 (which is aligned with miniupnp 2.3.4).
From @ckerr :
>When building our own miniupnpc instead of using the system library, build version 2.3.0.
>
>Happily the API changes that have built up since the last time we updated (API version 14 -> API version 17, detailed at https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/apiversions.txt) all seem to be additive and compatible with our existing code, so no code changes were made in libtransmission.
>
>This PR does make one other change though: it replaces the transmission/miniupnpc submodule with transmission/miniupnp simply to make future upkeep easier. as the latter is forked from the upstream miniupnp repo. (miniupnpc is a subdirectory in the miniupnp …

deps: update miniupnp to 2.3.4 (miniupnpc 2.2.6)

---

.github/workflows/actions.yml

Now we don't have to commit a comment just to trigger the tests.
P.S. Also enabled testing for `macos-12`.

ci: trigger CI when changing CI definitions

---

tests/libtransmission/announce-list-test.cc
tests/libtransmission/test-fixtures.h
tests/libtransmission/torrent-metainfo-test.cc
tests/libtransmission/utils-test.cc

bumping googletest from 1.11.0 to 1.14.0
Note that this bumps to `cmake_minimum_required(VERSION 3.13)` for tests (while we have `cmake_minimum_required(VERSION 3.12)` for libtransmission).
---
This was originally an attempt to address #6697, unfortunately, with same problem in sanitizer:
https://github.com/transmission/transmission/actions/runs/8294876755/job/22700749870?pr=6702
>Exception: SegFault

bumping googletest from 1.11.0 to 1.14.0

---

.gitmodules

- bumping libdeflate from 1.18 to 1.19
- bumping small from 0.2.0 to 0.2.1
- bumping utfcpp from 3.2.1 to 4.0.5
- <s>using original repositories when there are zero modifications necessary for Transmission, allowing easier updates of those dependencies, since almost nobody can make pull requests to the Transmission forks.</s>

bumping libdeflate/small/utfcpp to newer versions

---

libtransmission/quark.cc
libtransmission/quark.h
libtransmission/tr-dht.cc
tests/libtransmission/dht-test.cc

A follow up for #6569.
DHT node ID were indefinitely persistent across sessions, and this PR makes is so that the node ID is refreshed every 30 days.
People who started using Transmission from `4.0.0` or above are stuck with a zero DHT node ID, which is not ideal for their DHT performance. This PR allows their DHT node ID to refresh to a randomly generated one without any user intervention.
Notes: Improved DHT performance.

feat: periodically refresh dht node id

---

docs/Scripts.md
libtransmission/torrent.cc

This PR adds a `TR_TORRENT_PRIORITY` env var to the completion script, represented by directly stringifying the [`tr_priority_t` enum][priority_enum] values.
[priority_enum]: https://github.com/transmission/transmission/blob/7f029acf6e1057b5e81cc91905b3bdd23ea6170e/libtransmission/transmission.h#L75

Add torrent priority to completion script environment variables

---

libtransmission/announcer-http.cc
libtransmission/blocklist.cc
libtransmission/net.cc
libtransmission/net.h
libtransmission/peer-io.cc
libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h

- `tr_address` should be invalid by default, now it is IPv4 by default.
- Allow loopback address for LPD[^1] and incoming peers.
- Blocklist `parseCidrline()` needs to use `tr_address` factory functions to ensure all fields are properly set.
[^1]: You *can* get peers with loopback addresses if you run multiple torrent clients on the same interface.

fix: misc net.cc and blocklist.cc fixes

---

tests/libtransmission/lpd-test.cc
tests/libtransmission/timer-test.cc
tests/libtransmission/watchdir-test.cc

Fix #6464.
Similar idea as #4808: it's only meant to be temporary. But as I had this specific failure hitting my pull requests more than a dozen of times, and often causing them to be mostly ignored because they wouldn't pass all tests, this has been bugging me for too long.
Scope of this PR is to disable the test, not to fix it. If you have a fix in mind, kindly open a separate PR since I don't have a Windows machine. But in the mean time, we should merge this now to make other pull requests green.
Sister pull request which I also recommend to merge: #6715

Disable a long-lived and recurrent flaky test

---

tests/libtransmission/peer-mgr-active-requests-test.cc

Fixes warning:
```
libtransmission/peer-mgr-active-requests-test.cc:18:1: warning: class 'tr_peer' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
```

fix: mismatched `class` forward declaration for `struct tr_peer`

---

.github/workflows/actions.yml

While I know that GitHub action for [macos-11 is deprecated and will be removed in June 2024](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/), I want to see if it builds and if it could have caught the `return map` build issue.

add macos-11 to actions.yml

---

libtransmission/net.cc
libtransmission/tr-udp.cc
libtransmission/web-utils.cc
tests/libtransmission/announcer-test.cc
tests/libtransmission/net-test.cc
tests/libtransmission/web-utils-test.cc

More misc fixes for networking functions.
1. To conform to RFC3986[^1], fix `tr_urlParse()` to include the encapsulating square brackets for IPv6 addresses in the `host` component.
2. Modify `tr_address::from_string()` to allow square brackets encapsulating IPv6 address strings.
3. When creating the IPv6 UDP socket, set `IPV6_V6ONLY` *before* binding. Otherwise, the operation will always return `EINVAL` on Linux.
4. Don't set `SO_REUSEADDR` for listening sockets on Windows, because it is equivalent to `SO_REUSEPORT` on Unix systems[^2]. Windows already allow rebinding to `TIME_WAIT` sockets by default[^3], or in other words, its default behaviour is equivalent to explicitly setting `SO_REUSEADDR` on most other systems.
5. Don't enclose IPv4 addresses in square brackets when generating the …

fix: more misc `net.cc` fixes

---

libtransmission/peer-mgr.cc

This reverts commit 8709ec60e69a31367da325e17463714aa5a5d2f3.
This is an attempt to fix win32 nightly distributions: #6714.
To @mikedld to merge if he thinks that helps. We can always re-include that change later.

Win32 compatibility for get_peer_stats

---

libtransmission/completion.cc
libtransmission/completion.h
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/completion-test.cc
tests/libtransmission/lpd-test.cc
tests/libtransmission/watchdir-test.cc

Avoid virtual inheritance with `tr_torrent` class, since the parent interface class only had one method and can be replaced with a `std::function`.

refactor: remove torrent_view virtual class

---

libtransmission/handshake.cc
libtransmission/peer-io.cc

Fixes #6744
- Don't discard the `tr_peer_socket` object after `tr_peerIo::reconnect()` failed, because it still contains useful info.
- Ensure `tr_peerIo::reconnect()` is called at most once for each `tr_handshake::on_error()` call.

fix: invalid socket address in `tr_peerIo::reconnect()`

---

web/assets/css/transmission-app.scss

created PR as asked by @tearfur 
fixes #6375 
Screenshot:

fix(web): don't use 2 rows for upload/download speed info

---

libtransmission/rpcimpl.cc
libtransmission/session.cc
libtransmission/settings.cc
libtransmission/variant.cc
libtransmission/variant.h

Fixes #6630.
Restored the loose data type parsing in RPC and `settings.json`. For example, the boolean can now accept `1`, `0`, `"true"`, `"false"` again. Note that while we make an effort to implement these loose data types, they were never officially in our docs, nor they will be in the future, so they should never be relied on.
Incorporated the loose data type parsing that was in `tr_variantGet*()` methods into `tr_variant`. Now there is a new distinction between `find_if()/get_if` and `value_if()` methods:
- `find_if()/get_if()`: Strict data type.
- `value_if()`: Loose data type.

fix: restore loose data type parsing in RPC and `settings.json`

---

tests/libtransmission/timer-test.cc

I thought when I did #6722 that the failure was exclusive to Windows, but I just found out that it's also happening on Mac:
https://github.com/transmission/transmission/actions/runs/8454701793/job/23160406569
So I'm reverting a part of #6722 and disabling those two tests for all platforms.

Disable restartWithDifferentInterval for all platforms

---

libtransmission/resume.cc
libtransmission/resume.h
libtransmission/torrent.h

Save the sequential download setting of each torrent across sessions.
#4795 did try to do this, but the implementation is not complete.

fix: save sequential download across sessions

---

.github/workflows/actions.yml

This PR is for ubuntu CI.
Note that I also hope to land macOS-14 CI: https://github.com/transmission/transmission/pull/6626
The workaround I used for ubuntu is that extra line:
```
sudo sysctl vm.mmap_rnd_bits=28
```

re-enabling ubuntu tests

---

.github/workflows/actions.yml
CMakeLists.txt

This improves cmake configuration to support building arm64 on x86_64, or x86_64 on arm64.
This configures macos-14-from-tarball to build both (x86_64;arm64).
Note: on macOS, it is not possible to brew install universal dependencies, consequently it is not easy to have a universal qt or universal gtk installation in GitHub actions, consequently the universal build is only defined for the Mac app when all the `USE_SYSTEM_*` are set to OFF.

support macos-14 universal builds in CI

---

macosx/VDKQueue/VDKQueue.h
macosx/VDKQueue/VDKQueue.mm

That #warning was added by me long ago, before knowing that alternatives were also using kqueue under the hood.

doc: no need to adopt an alternative to VDKQueue

---

macosx/en.lproj/InfoPlist.strings

Fix the comment in https://github.com/transmission/transmission/issues/6554#issuecomment-1924416885
Testing: on macOS, after running Transmission at least once, in any language (not necessarily English), you can now use Spotlight (CMD+SPACE) to search for "torrent" or "magnet" or other keywords, and it will find Transmission.

feat: support "torrent" in Spotlight indexation

---

libtransmission/port-forwarding-upnp.cc
libtransmission/port-forwarding-upnp.h
libtransmission/port-forwarding.cc
libtransmission/port-forwarding.h
libtransmission/session.h

Use the local port as the internal port, and the advertised port as the external port for UPnP.
While this shouldn't make a difference in almost all cases, if someone somehow ended up with a different advertised port than the local port, we'll be ready for it.

feat: support different internal and external port for UPnP

---

qt/Session.cc
qt/Session.h

Keys for MainStatKeys can now be added dynamically in order to only make certain RPC calls depending on options the user has enabled.
This PR is useful for #6517 and #5319.

qt: add dynamic RPC keys

---

macosx/Base.lproj/InfoGeneralView.xib
macosx/InfoGeneralViewController.mm
macosx/Torrent.h
macosx/Torrent.mm

Fix #4388.
- Based on #4435
- Plus tricky rebase done to properly address conflict
- Plus fix to avoid UI regression on long filenames
Sample:
Implicitly, this is both a code review approval and UI review approval of the work done by @BogdanArdelean.

feat(macos): added last known location

---

macosx/Controller.mm
macosx/Defaults.plist

This is a partial enhancement toward #4917:
- it's only for the mac app, not QT/GTK/daemon/...
- it's a random default port, but not one assigned by the system. In order to get a random port assigned by the system, we would need to start with port 0, then read the port number assigned by the system and save that value. That would be best handled by libtransmission itself, hence why I'm not doing it as part of this PR.

Replace mac app default BindPort with a random port

---

libtransmission/net.h

To be in line with std::hash declaration
See https://en.cppreference.com/w/cpp/utility/hash

Make std::hash specialization for tr_socket_address a struct

---

docs/Why-is-my-port-closed.md
macosx/TransmissionHelp/html/FAQ.html
macosx/TransmissionHelp/html/check.html
macosx/TransmissionHelp/html/gettingstarted.html
macosx/TransmissionHelp/html/peers.html
macosx/TransmissionHelp/html/pffirewall.html
macosx/TransmissionHelp/html/pfrouter.html
macosx/TransmissionHelp/html/portforward.html
macosx/TransmissionHelp/html/remote.html
macosx/TransmissionHelp/html/speed.html
macosx/TransmissionHelp/html/tracker.html
macosx/TransmissionHelp/html/usingt.html

Those are UTF-8 documents: no need to use HTML entities, as it makes it harder to read.

Avoiding &rarr; in UTF-8.

---

gtk/Application.cc
libtransmission/file-posix.cc
libtransmission/variant-json.cc

Fix #6804
Partial cherry-pick of #5635 to make Transmission 4.0.x compilable with both fmt 8 and fmt 10.

compatibility with libfmt v10.0.0

---

gtk/DetailsDialog.cc

Resolves https://github.com/transmission/transmission/issues/5736.
Fixes build on *BSD's.

fix: missing #include in DetailsDialog.cc

---

web/assets/css/transmission-app.scss

Fix declaration order, otherwise it's not possible to commit on 4.0.x anymore.

Expected white-space to come before width  order/properties-alphabetical-order

---

libtransmission/torrent-metainfo.cc

Fixes #6799.
Regression from #2542.
Since the regression PR, Transmission does not sanitize the filename for single-file torrents.
Notes: Fixed `4.0.0` bug where the filename for single-file torrents aren't sanitized.
P.S. `tr_torrent_files::makeSubpathPortable()` doesn't seem like an appropriate name for what it currently does, so I'll be making another PR for it.

fix: escape single file torrent name

---

gtk/transmission-gtk.metainfo.xml.in

cherry picked from commit de11cbdf8568c9fbf61a4c896844c2b475836118, aka #6720

chore: add Add <launchable> tag to GTK client metainfo (#6720)

---

libtransmission/torrent.cc

Fixes #6528.
Regression from #4393.
`tr_torrent::seconds_downloading_before_current_start_` and `tr_torrent::seconds_seeding_before_current_start_` needs to be updated when the torrent is stopped, otherwise these stats will be reset.
Notes: Fixed `4.0.0` bug where `secondsDownloading` and `secondsSeeding` will be reset when stopping the torrent.

fix: store seconds downloading/seeding when stopping torrent

---

.clang-format
third-party/.clang-format

See https://clang.llvm.org/docs/ClangFormatStyleOptions.html#sortincludes

Fix incorrect value for SortIncludes in .clang-format

---

macosx/TransmissionHelp/html/speed.html
utils/transmission-remote.1

As discussed in #6739, "sec" is a Canadianism and should be avoided.
cc @killemov

Avoiding "sec" as abbreviation

---

libtransmission/peer-mgr.cc
libtransmission/torrent-magnet.cc
libtransmission/torrent-magnet.h
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/torrent-magnet-test.cc

Fixes #6706.
Stack trace at https://github.com/transmission/transmission/pull/4178#issuecomment-2080390580.
This PR backtracks some changes made in #6383:
- Reverted a change that queues the `tr_torrentVerify()` call instead of executing it immediately after completing the metadata of a magnet link. This is the crux of the bug this PR fixes, more on that below.
- Re-implemented `tr_torrentMagnetDoIdleWork()` that got removed.
#6383 changed `tr_torrent::on_metainfo_completed()` so that it queues `tr_torrentVerify()` to be executed in the session thread when it is free, instead of executing it immediately.
This was needed because `tr_torrentVerify()` will stop the torrent, thus freeing all `tr_peerMsgs` objects belonging to that torrent (i.e. disconnecting all peers), and this might trigger …

fix: possible heap-use-after-free with magnet links

---

libtransmission/verify.h

std::chrono::duration is just a wrapper, underlying numerical value member will be default initialized to zero as expected.
See https://en.cppreference.com/w/cpp/chrono/duration

Default initialize sleep callback duration in tr_verify_worker

---

libtransmission/makemeta.cc
libtransmission/makemeta.h
libtransmission/resume.cc
libtransmission/torrent-files.cc
libtransmission/torrent-files.h
libtransmission/torrent-metainfo.cc
libtransmission/torrent-metainfo.h
libtransmission/torrent.cc
libtransmission/torrent.h
macosx/QuickLookPlugin/GeneratePreviewForURL.mm
tests/libtransmission/makemeta-test.cc
tests/libtransmission/remove-test.cc
tests/libtransmission/torrent-files-test.cc
utils/create.cc

Follow up of #6846:
> P.S. `tr_torrent_files::makeSubpathPortable()` doesn't seem like an appropriate name for what it currently does, so I'll be making another PR for it.
Also fixed a regression from #6187 that broke `transmission-create`'s portable file path check.
https://github.com/transmission/transmission/blob/740ce3b904b78cf4bec120ebb5a1cfd326375a87/utils/create.cc#L220-L225

fix: restore portable file path check

---

libtransmission/crypto-utils-mbedtls.cc

per https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md, functions with _ret prefixs replaced old without return and renamed without suffix.

fix building with mbedtls 3.X

---

web/assets/css/transmission-app.scss
web/public_html/index.html

Implement my suggestion at https://github.com/transmission/transmission/pull/6577#issuecomment-2016481876.
Fix the width of the upload speed info, so that the download speed info will not move around in response to upload speed changes.
| Before | After |
| :--: | :--: |
| ![before](https://github.com/transmission/transmission/assets/46261767/fecbc45d-ebbb-4b63-9de9-4c3b1c6ced8f) | ![after-2](https://github.com/transmission/transmission/assets/46261767/44e981ea-1489-4624-9f6b-e25805b741bf) |
Edit: Moved the arrows to the right of the text as suggested by https://github.com/transmission/transmission/pull/6739#issuecomment-2020649976.
<details>
<summary>previous iteration</summary>
</details>

webui: fixed width for speed info

---

libtransmission/settings.h

Add virtual destructor to the polymorphic Settings class

---

.github/workflows/actions.yml

can re-enable when brew is fixed

build: temporarily disable macos-11 sanity checks

---

utils/remote.cc

Fixes wrong speed units in `transmission-remote` torrent details.

fix: torrent details speed info unit

---

libtransmission/port-forwarding-natpmp.cc
libtransmission/port-forwarding-upnp.cc

Fixes #462
Fixes #5464
Allow port forwarding state to recover from error, e.g. recover from a temporary network stoppage.
Notes: Allow port forwarding state to automatically recover from error.

feat: allow port forwarding state to recover from error

---

macosx/Controller.mm
macosx/FileOutlineController.mm
macosx/PrefsController.mm
macosx/Torrent.h
macosx/Torrent.mm

1. Remove `- (void)startQueue` because it's just one line and it just posts a notification. Instead, post this notification directly.
2. Replace that synchronous notification with a `NSNotificationCoalescingOnName`, "_to prevent stack overflow on lots of torrents changing state at the same time_" (same logic as in `- (void)update`)
3. Remove the used object for this notification, since it needs to update the whole list of torrents
4. Rename the notification to UpdateTorrentsState

rename "UpdateQueue" to "UpdateTorrentsState"

---

libtransmission/peer-mgr.cc
libtransmission/peer-msgs.cc
libtransmission/peer-msgs.h

Should fix #6594.
Instead of directly storing the objects in the map nodes and splicing the nodes across different maps, manage their lifecycles using shared pointers.
This PR is the result of me fed up of dealing with the various obscure edge cases that comes with managing the lifecycles of the peer info objects manually. Each of these cases costs me a few days of work just to identify.

refactor: store peer info objects in shared pointers

---

libtransmission/resume.cc

Removed the `have` key in the resume file, which has been redundant for many years. Also cleaned up a bunch of minor issues along the way.

chore: resume file remove redundant `have` key and other cleanup

---

libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h

Another step for #5261.
No matter how I think about it, the feature that this PR restores sounds like a process that's integral to keeping Transmission fast even after running for a very long time. So I was a bit bewildered by why it was removed completely with no replacement at all.
This is all I can find about the history at the moment:
1. `atomPulse()` was commented out at #3182 to prevent some crashes, the PR description says it was just a hack to unbreak the nightly builds.
2. Afterwards, for whatever reason, what remained of `atomPulse()` got removed completely at #3192. There was no explanation.
So for now, I opted to restore it, with a small change to the calculation for limiting the number of peer info objects.
@ckerr if you still remember where you were going after #3192, I'd be …

perf: restore 3.00 peer info (atom) pool pruning

---

libtransmission/peer-mgr.cc

This is needed because if the torrent is stopped to be verified, the pieces we have may change, and the wishlist will need to be re-calculated from scatch.

fix: reset wishlist when stopping torrent

---

gtk/SystemTrayIcon.cc

Fix these `cert-err58-cpp` warnings:
> [95/150] Building CXX object gtk/CMakeFiles/transmission-gtk.dir/SystemTrayIcon.cc.o
/home/charles/src/transmission/gtk/SystemTrayIcon.cc:58:12: warning: initialization of 'TrayIconName' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
auto const TrayIconName = Glib::ustring("transmission-tray-icon"s);
^
/usr/include/glibmm-2.4/glibmm/ustring.h:403:14: note: possibly throwing constructor declared here
GLIBMM_API ustring(std::string&& src);
^
/home/charles/src/transmission/gtk/SystemTrayIcon.cc:59:12: warning: initialization of 'AppIconName' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
auto const AppIconName = Glib::ustring("transmission"s);
^ …

fix: cert-err58 warning in GTK client

---

libtransmission/mime-types.h
libtransmission/mime-types.js

This is related to #4850 since libtransmission/mime-types.js generates libtransmission/mime-types.h and puts it there. Also add a note that the file is automatically generated for good measure.

libtransmission: fix copyright header generation

---

libtransmission/net.cc
libtransmission/peer-io.cc

Fixes #6880.
Before `tr_peerIo::set_socket()` is called on a new `tr_peerIo` object, the underlying socket address object is not yet well defined (maybe causing `inet_ntop()` to return a nullptr? idk), so `tr_peerIo::display_name()` may cause problems.

fix: don't call `tr_logAddTraceIo` before `tr_peerIo::set_socket()`

---

libtransmission/session.h
libtransmission/torrent.cc
libtransmission/torrent.h

That change wouldn't fix the root cause of #6833, but it would avoid further issues in release by preventing returning a negative idle_seconds.
I see for instance that we read `date_active_` from a resume file, so that could be a scenario where date_active_ is above now. Or the system clock was modified.

refactor: harden idle_seconds

---

libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/move-test.cc
tests/libtransmission/rename-test.cc

Fixes #690.
Notes: Partial file suffixes will now be updated after torrent verification.

fix: update partial file suffix after verifying torrent

---

macosx/MessageWindowController.mm

Warning introduced in fa687d092846ee38baf6a83afba4dcf6b762358b (18 November 2007 by @livings124)
Formula modified in 84b10c43127990857e5bfeadc443ec68f3d9d445 (18 November 2007 by @livings124)
As of Today, 3 June 2024, I'm not seeing any cutoff, so I'm suspecting that the issue got fixed on the same day that the warning was introduced?
No actions needed, so removing the warning.

Remove warning "don't cut off end"

---

.github/workflows/actions.yml

Manually set Xcode to the version was used in macos-11 runner.
See:
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xcode

chore: update older macos build verification workflow to macos-12

---

cmake/CheckAtomic.cmake
libtransmission/CMakeLists.txt

Following https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067625 and failure to build transmission on specific platforms that require `-latomic`, here is the way to a proper fix.

build with -latomic on platforms that need it

---

Transmission.xcodeproj/project.pbxproj
libtransmission/port-forwarding-upnp.cc

bump miniupnpc from 2.2.7 to to 2.2.8

bump miniupnpc to 2.2.8

---

.github/workflows/actions.yml
libtransmission/announcer-udp.cc

`clang-tidy-14` has been crashing when being run on `peer-mgr.cc` since 96de1706af82e8141f5ec31ce2c0f09a38b7d695.
According to https://github.com/llvm/llvm-project/issues/95631, upgrading to `clang-tidy-18` fixes this.

ci: bump `clang-tidy` from 14 to 18

---

cli/cli.cc

When the --config-dir/-g option was passed, this bug caused all options
preceeding it on the command line to be ignored.
Also remove the superfluous break statement.
Regression introduced by e49747ab51953a3c2f81767b320f1f415eba9150.

fix: restore tr_optind in all getConfigDir branches

---

libtransmission/handshake.cc
libtransmission/handshake.h

this is a per-algorithm key, not for crypto generally. If additional algos are ever added, they would be "CryptoProvideXXX" and "CryptoProvideYYY".

clarify MSE crypto algo usage

---

libtransmission/resume.cc

Regression from #2059.
Notes: Fixed a `4.0.0` bug where `2.20`-`3.00` torrent piece timestamps saved in the resume file aren't loaded correctly.

fix: loading `2.20-3.00` progress from resume

---

libtransmission/variant-json.cc
tests/libtransmission/variant-test.cc

- Fixes a regression from #6138 where `tr_variant_serde::end_` isn't set after calling `parse_json()`.
- Fixed the cursor position used to generate the error string.
- Fixed the parser to stop when a complete JSON root is parsed, matching the behaviour of our benc parser.

fix: `tr_variant_serde::parse_json()` bug fixes

---

docs/Editing-Configuration-Files.md
libtransmission/session.h

Fixes #7038.
- `message-level`: Default value was incorrectly documented as `2` instead of `4` as far back as I can trace. https://web.archive.org/web/20181002135848/https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#misc
- `peer-socket-tos`: Changed in #2594, but the docs were not updated accordingly.
- `rename-partial-files`: Regression from #4053. The PR looks to be purely a refactor, but the default value was changed from `true` to `false`.

fix: `settings.json` default value and docs

---

macosx/Controller.mm

fix this warning:
>WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

Opt-in to secure coding explicitly

---

libtransmission/cache.cc

Minor refactor to avoid re-calculating an iterator.

perf: avoid `std::advance` in cache.cc

---

libtransmission/file-posix.cc

clang-tidy emits bugprone-unchecked-optional-access warning for `tr_sys_file_lock`. however, this is a false positive: the lines warned about cannot be reached if the optional does not contain a value. adding an `assert` silences these warnings.

fix: silence bugprone-unchecked-optional-access warnings

---

gtk/DetailsDialog.cc

This adds the required include of `<fmt/ranges.h>` for compatibility with fmt 11.

compatibility with libfmt v11

---

gtk/Session.cc
libtransmission/torrent-files.cc
libtransmission/torrent.cc
libtransmission/torrent.h
libtransmission/transmission.h
libtransmission/utils.cc
libtransmission/utils.h

Apply changes previously suggested in #6055. Remove unused code and simplify. Fixup crash if `tr_file_move()` passed null error.

Refactor async torrent removal logic

---

libtransmission/log.cc

Closes #7046.
Sample:
```
[2024-08-12T14:20:59.731+0800] inf session.cc:418 Listening to incoming peer connections on 0.0.0.0:51413 (session.cc:418)
[2024-08-12T14:20:59.731+0800] inf session.cc:418 Listening to incoming peer connections on [::]:51413 (session.cc:418)
```
Notes: Daemon log timestamps are now in local ISO8601 format.

feat: log timestamps in local ISO8601 format

---

daemon/daemon.cc
gtk/MessageLogWindow.cc
libtransmission/log.cc
libtransmission/log.h
macosx/MessageWindowController.mm

Currently, daemon logs take the timestamp when they are printed, instead of when they are queued. This PR changes the behaviour to the latter, so that they more accurately reflect when the event happened.
Notes: More accurate timestamps for daemon logs.

fix: accurate timestamp in daemon logs

---

gtk/MainWindow.cc

Since gtkmm 4.15.0 a new overload for Gdk::Cursor::create exists which creates an ambiguity when passing a string literal.
We can avoid the ambiguity by explicitly constructing a Glib::ustring from the string literal before calling the method.
https://gitlab.gnome.org/GNOME/gtkmm/-/issues/159

fix: Avoid ambiguous overload when calling Gdk::Cursor::create

---

web/assets/css/transmission-app.scss
web/src/inspector.js

Supersedes: #6288 along with more fixes
Left: This PR, Right: Original
The top part of the screenshot is observation of a problem that calls for an addition of name to the info page.
Notes: Fixed truncated hash in inspector page, added name section to inspector page

fix: make name and hash readable

---

libtransmission/block-info.h
libtransmission/file-piece-map.cc
libtransmission/torrent.cc
tests/libtransmission/file-piece-map-test.cc

This was added in #2220, ~I'm not sure what it's supposed to fix.~
Edit: I've realise what it is catering to, and written code to work around it.
It prevents `byte_loc()` from returning a past-the-end piece/block index, but I think `byte_loc()` will be more useful if it does return past-the-end.
P.S. It actually costed me a few hours of debugging. 🤡

refactor: remove last byte special case in `tr_block_info::byte_loc()`

---

libtransmission/peer-mgr.cc

It was bothering me that we duplicated the call to `->has()` and that the first element of the loop would bitwise compare with itself, so I refactored it to a more classic logic with an initialisation to zero.

refactor: avoid `front()` prior to loop

---

libtransmission/handshake.cc
libtransmission/handshake.h
libtransmission/peer-mse.cc
libtransmission/peer-mse.h
tests/libtransmission/crypto-test.cc

Avoid generating a Diffie-Hellman private key when we are using a plain connection.

perf: lazy initialise Diffie-Hellman in handshake

---

qt/Application.cc
qt/Application.h
qt/CMakeLists.txt
qt/main.cc

Support special (optional) `--` argument to explicitly separate options from filenames. Support special `---` argument to separate client arguments from Qt arguments.
Conflicts with #6633.
Notes: Change Qt client CLI options parsing to accept Qt options as a separate group.

Move Qt client's tr_main() into a separate file

---

libtransmission/peer-common.h
libtransmission/peer-mgr.cc
libtransmission/peer-msgs.cc
libtransmission/peer-msgs.h
libtransmission/webseed.cc

Fixes #267.
Notes: Limit the number of bad pieces to accept from a webseed before banning it.

fix: limit number of bad pieces to accept from a webseed

---

libtransmission/handshake.cc
libtransmission/handshake.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-msgs.cc

Fixes #6909.
Notes: Fixed a bug where BT messages that immediately follows a handshake might be discarded.

fix: process BT messages that immediately follows handshake

---

libtransmission/announcer-http.cc

Fixes #7078.
Regression from #6223.
Notes: Fixed `4.0.6` bug where Transmission might spam HTTP tracker announces.

fix: don't process http announce error if already succeeded

---

gtk/FileList.cc

Manually calculated font size needs to be recalculated (which we weren't doing), otherwise leading to wrong size on global font size and/or scale factor changes.
Simplify file list columns setup where possible.
Notes: Fix file list text size adjustment based on global settings.
Fixes: #7093

Use "scale" cell renderer property to adjust file list font size

---

gtk/Session.cc

Notes: Fix `4.0.0` regression causing GTK client to hang in some cases.
Broken-by: #4430

Fix infinite loop when searching for missing torrents by id

---

qt/Prefs.cc

The qt app does not have the "Show extra peer details" checkbox in the peers tab of the torrent detail diaogue like the GTK app does. So this app default is now unused.

chore: remove unused `TR_KEY_show_extra_peer_details` app default

---

daemon/CMakeLists.txt

This is a common path across Linux distros.
Checked distros:
* Arch Linux
* Fedora
* Gentoo
* openSUSE
* Ubuntu

fix: Use non-lib64 systemd system unit dir path

---

docs/rpc-spec.md

Transmission renumbers torrents on restart. This may catch RPC clients off-guard if the daemon happens to restart between two related RPCs.

Clarify that torrent ids are not stable

---

libtransmission/torrent.cc

Fixes #6994.
If a piece is found to be incomplete after verifying, Transmission need to assume that it needs to be downloaded from scratch. This is because the smallest unit of data when verifying a torrent is a piece, and so Transmission cannot tell apart a piece that is not downloaded at all and a piece that is partially downloaded.
The current code fails to do that. It does not reset the piece's progress if the piece was incomplete before verifying and stays incomplete after verifying. So if a piece that was thought to be partially completed is in fact not downloaded at all, the current code will fail to recognise that and wrongly assume it has a part of the piece even after verifying the torrent.
Notes: Fixed a bug where torrent progress is not properly updated after verifying.

fix: update torrent progress when verifying partially completed pieces

---

libtransmission/open-files.cc

Fixes #7081
Fixes #5664
Notes: Fixed a bug where disk IO rate is much higher than transfer rate.
CC @yasezbk

perf: don't open torrent file descriptors with `TR_SYS_FILE_SEQUENTIAL`

---

libtransmission/torrent.h

`tr_torrent::has_file()` does not work properly for 0-byte file. This PR fixes that.

fixup! fix: update partial file suffix after verifying torrent (#6871)

---

.github/workflows/actions.yml

Fix macos-12-x86_64-from-tarball CI action by moving the QT part to macos-13
Example error: https://github.com/transmission/transmission/actions/runs/11316014753/job/31467946321
Supersedes #7166

ci: fix macos-12-x86_64-from-tarball from GitHub workflows

---

gtk/FilterBase.h
gtk/SorterBase.h
qt/DetailsDialog.cc

```
➜  ~ clang-format --version
clang-format version 19.1.2
```
I had to use clang-format macros to make it compatible both new (19) and old (17) clang-format.
Note that on macOS, brew will only let you install clang-format 19 or clang-format 11: the version 17 is not directly supported anymore.
```
➜  ~ brew search clang-format
==> Formulae
clang-format ✔      clang-format@11     clang-format@8
```

fix: code should be clang-formatted

---

daemon/daemon.cc

fix: check `tr_num_parse` result in daemon

---

libtransmission/torrent.cc
libtransmission/torrent.h

Fixes #6899.
Detailed explanation at https://github.com/transmission/transmission/issues/6899#issuecomment-2226087791.
Notes: Fixed edge cases where `date done` and `recently-active` does not get updated after torrent state change.

fix: `date done` and `recently-active` not updated on state change

---

web/src/open-dialog.js
web/src/utils.js

Dialogs by themselves aren't submitted when pressing the Enter key,
for that we need to add an event handler to the dialog itself.
One approach I tried was to add a form to the dialog. This worked, but
needed a CSS workaround to keep the buttons in the same order.
Tested with some other dialogs as well:
* edit labels; and
* set location.
References:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#handling_the_return_value_from_the_dialog
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#formmethod
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method
Fixes #6553

fix(web): pressing the enter key now submits dialogs

---

qt/DetailsDialog.cc

fixes https://github.com/transmission/transmission/issues/6859
doesn't display last activity if there was no last activity (if the torrent started in a paused state)

correct "Queue for download" last activity

---

libtransmission/announcer.cc
libtransmission/bandwidth.cc
libtransmission/bitfield.cc
libtransmission/crypto-utils.cc
libtransmission/handshake.cc
libtransmission/peer-mgr-active-requests.cc
libtransmission/peer-mgr.cc
libtransmission/peer-mse.cc
libtransmission/session-alt-speeds.cc
libtransmission/session.cc
libtransmission/torrent-ctor.cc

fix some clang-tidy-20 warnings in libtransmission.

fix: clang-tidy-20 warnings

---

macosx/Controller.mm

This is a minor UI improvement on #1690.
Instead of freezing the download and upload speeds when the app is quitting (which incorrectly gives the impression that this speed is still in effect), we can immediately clear the download/upload indicators while the session is closing itself.
Testing: use cmd+Q to quit the app

feat: clear the badge when quitting app

---

qt/FileTreeModel.cc
qt/FileTreeView.cc
qt/PathButton.cc
qt/SqueezeLabel.cc
qt/Torrent.h
qt/TorrentDelegate.cc
qt/TorrentDelegateMin.cc
qt/TrackerDelegate.cc
qt/VariantHelpers.cc

Mostly small changes like adding parenthesis to make order-of-precedence explicit, but clang-tidy did find an unused `TorrentHash` construtor :+1:

fix: clang-tidy-20 warnings in transmission-qt

---

libtransmission/peer-mgr.cc

Fixes a bug from #6549 where webseeds are not counted when calculating piece replication for the wishlist.

fix: count webseeds when calculating piece replication

---

libtransmission/torrent.cc

Regression from #2308.
The code is supposed to clear the torrent's error state if the error was from a tracker that was just removed. But now the error is cleared if the tracker was not removed.
Notes: Fixed a `4.0.0` bug where the tracker error is not cleared when the tracker is removed from the torrent.

fix: clear tracker error if tracker is removed

---

libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.h

We don't use `TR_SYS_FILE_LOCK_UN`, so let's remove it. If we ever need it in the future, we can look the code back up in the repo history and restore it.

refactor: remove unused TR_SYS_FILE_LOCK_UN

---

CMakeLists.txt
libtransmission/file-posix.cc
libtransmission/file-win32.cc
libtransmission/file.h
tests/libtransmission/file-test.cc

Title says it all: we don't use `TR_SYS_FILE_APPEND`, so this PR removes its code.
This PR does start from the assumption that unused code should be removed -- if we need it again at some point, it will still be in the repo history and can be restored. But until we need it, we shouldn't build it :man_shrugging:

refactor: remove unused TR_SYS_FILE_APPEND

---

CMakeLists.txt

Fail the CMake configuration step if clang-tidy is not found when `-DRUN_CLANG_TIDY=ON`.
Currently, `-DRUN_CLANG_TIDY=ON` and `-DRUN_CLANG_TIDY=AUTO` has no difference (if not running on LGTM/appveyor).
This causes the clang-tidy CI to silently stop functioning when it cannot find a clang-tidy installation, as demonstrated in https://github.com/transmission/transmission/actions/runs/11559805177/job/32175311506?pr=7206. The CI succeeded but clang-tidy was never run.

build: fail if clang-tidy is not found when `-DRUN_CLANG_TIDY=ON`

---

web/generate-buildonly.js

Fix the CI failure seen at https://github.com/transmission/transmission/actions/runs/11599451344/job/32297619804.
```
> generate-buildonly
> node generate-buildonly.js
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:405:5)
at validateString (node:internal/validators:162:11)
at Object.join (node:path:1171:7)
at file:///home/runner/work/transmission/transmission/web/generate-buildonly.js:6:24
at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
at async loadESM (node:internal/process/esm_loader:34:7)
at async handleMainPromise (node:internal/modules/run_main:106:12) { …
```

fix: support nodejs below v20.11 for `generate_buildonly.js`

---

libtransmission/torrent.cc

Fixes #870
Regression from 24bb159bfe7b24c3956777e8dcca6ebb561c2a1b (2009 again!! 😄 )
Xref: https://trac.transmissionbt.com/ticket/2317
Notes: Fixed a bug where resume files are not saved when shutting down Transmission.
Cheers to @reardonia for discovering this https://github.com/transmission/transmission/pull/6992#issuecomment-2437979883.
Edit: Seems like it was reported in 2019 but no one took notice.

fix: save resume when shutting down

---

macosx/ProgressBarView.mm

fix: support dark mode colors with pieces bar on macOS

---

macosx/InfoGeneralViewController.mm

The crash happens when checking the file info of a magnet link: both location and lastKnownDataLocation are nil, but stringValue must not be nil.

Crash fix: "Invalid parameter not satisfying: aString != nil"

---

CMakeLists.txt

Make `REBUILD_WEB` accept values other than `OFF` as False.
Apart from `OFF`, CMake accepts a variety of values as False[^1], such as `NO`. But now `-DREBUILD_WEB=NO` is equivalent to `-DREBUILD_WEB=AUTO`, very weird.
[^1]: https://cmake.org/cmake/help/v3.12/command/if.html

build: accept false constant other than `OFF` for `REBUILD_WEB`

---

libtransmission/session.cc
libtransmission/session.h
libtransmission/web.cc
libtransmission/web.h

Fixes #7221.
Regression from #2633.
Notes: Fixed `4.0.0` bug where the download rate of webseeds are double-counted.
The code removed in this PR were new in #2633, and I am having a really hard time figuring out what they were intended for. `webseed.cc` has been the only code using the `tr_web` speed limit features, but these lines couldn't have been written for `webseed.cc`, since `webseed.cc` were already reporting their bandwidth usage by themselves before #2633.
https://github.com/transmission/transmission/blob/2315903015dae4063338a0cce68e65a9fd5e8795/libtransmission/webseed.cc#L266

fix: don't double count webseed download data rate

---

libtransmission/web.cc

Remove a redundant `curl_easy_setopt()` call introduced in #2689 to set `CURLOPT_MAXREDIRS`.
The redundant code is benign, just confusing to read. There should be no change in behaviour.

refactor: set `CURLOPT_MAXREDIRS` once

---

libtransmission/peer-mgr.h
libtransmission/peer-msgs.cc

Fixes a regression from #6917 where the "failure count" on peers are being incremented indiscriminately when stopping the torrent, causing them to have a longer reconnect timeout than they should. More details in the discussion from https://github.com/transmission/transmission/pull/6975#issuecomment-2437912381 to https://github.com/transmission/transmission/pull/6975#issuecomment-2461231249.
CC @reardonia 
P.S. The discussion took place in #6975, but this regression is not actually related to it.

fix: don't increment failure count when stopping torrent

---

libtransmission/peer-mgr.cc

Fixes #6971.
`tr_peer_info::reconnect_interval_has_passed()` contains logic to increase the reconnect interval for unreachable peers, but it has no effect at all currently because they wouldn't be tried in the first place.

fix: allow unreachable peers to be retried

---

web/CMakeLists.txt

the files web/prettier.config.js and web/stylelint.config.js were renamed in b9f4509, but web/CMakeLists.txt was not updated correspondingly. hence, using `REBUILD_WEB` would cause FTBFS.
Fixes #7240

build: update web/CMakeLists.txt to reflect renamed files (Fixes #7240)

---

web/assets/css/transmission-app.scss

Left: This PR, Right: Original
Notes: Updated gray color for grayed out objects

feat: more gray for grayed out objects

---

libtransmission/bandwidth.h
libtransmission/cache.h
libtransmission/error-types.h
libtransmission/file.h
libtransmission/handshake.h
libtransmission/log.h
libtransmission/open-files.h
libtransmission/peer-common.h
libtransmission/peer-io.h
libtransmission/peer-mse.h
libtransmission/port-forwarding-natpmp.h
libtransmission/session-alt-speeds.h
libtransmission/torrent-ctor.h
libtransmission/torrent-metainfo.h
libtransmission/torrent.h
libtransmission/tr-popcount.h
libtransmission/utils.h
libtransmission/values.h
libtransmission/variant.h
libtransmission/watchdir-base.h
libtransmission/web.h

I've started running `clang-tidy` on our header files. This PR cleans up some warnings in `libtransmission/*h` and `qt/*h`
The full list of warnings is super noisy right now, so (a) I'm not going to push up a PR enabling them yet, and (b) this will take a small series of PRs to clean 'em all up

fix: clang-tidy header warnings, pt. 1

---

web/src/torrent-row.js

Left: This PR, Right: Original
A refinement upon #5937 especially while seeding of ratio. This PR updates the progressbar to read percent from two places:
- Torrent ratio to render progressbar color while seeding, percentage text will be 100%
- Torrent completion to render progressbar generally
Notes: Updated progressbar to display appropriate percentages.

fix: correct percent calculation for progressbar

---

.github/workflows/actions.yml

A follow-up of #7241.
The CI tests for `REBUILD_WEB=ON` was disabled in #4669 for some reason, causing the regression at #7240. This PR re-enables it.

ci: test `REBUILD_WEB=ON`

---

.github/workflows/actions.yml

Fix CI build errors like https://github.com/transmission/transmission/actions/runs/11905342027/job/33175657804?pr=7252
See https://github.com/actions/runner-images/issues/10984
The brew formula `pkg-config` was recently renamed to `pkgconf`, which conflicts with the _sometimes_ preinstalled `pkg-config`/`pkg-config@0.29.2` on some containers.
- Using `uninstall -f` on macos-15 where it can't be unlinked
- Using `unlink` on macos-12 where it's can't be uninstalled
- The solution to use `brew update && brew upgrade` doesn't work: it fails to update when swiftlint is installed, and pkgconf installation is still failing

fix: macOS CI

---

.github/workflows/actions.yml
CMakeLists.txt
libtransmission/transmission.h

Address the CI failures at https://github.com/transmission/transmission/actions/runs/11897556121/job/33152109063.
```
CMake Error at CMakeLists.txt:574 (message):
Found NPM: C:/Program Files/nodejs/npm Found unsuitable version "", but
required is at least "8.1.307"
```
```
CMake Error at CMakeLists.txt:574 (message):
Found NPM: /usr/bin/npm Found unsuitable version "7.5.2", but required is
at least "8.1.307"
```

fix: CI errors related to `REBUILD_WEB`

---

README.md
news/news-4.0.5.md
news/news-4.0.6.md

Resolves #7222.  Includes update to README.md to refer to 4.0.6 in release build instructions.

chore: add 4.0.5 and 4.0.6 release notes to main branch

---

web/assets/css/transmission-app.scss
web/src/formatter.js

Top: This PR, Bottom: Original
Additionally this includes a fix to upload arrow clipping out of bound in the right screen due to `width` disallowing growth, it's now replaced with `min-width` to allow growth.
Notes: updated displaying number in new gigabyte per second unit

fix: utilize gigabyte per second to conserve space and upload arrow clipping fix

---

libtransmission/torrent-magnet.cc
libtransmission/torrent-magnet.h
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/torrent-magnet-test.cc

Improving on #6815.
The code now makes use of `queue_session_thread()` to perform the indirection step when the metadata transfer completes, so that the session thread does not need to periodically check on the metadata transfer, and the code is easier to read.
Also make the same fix in #6918 for `tr_torrentVerify()`.

refactor: remove `tr_torrent::do_magnet_idle_work()`

---

libtransmission/variant-json.cc
tests/libtransmission/json-test.cc

Accept a `std::string_view` input that points to `nullptr` as a normal case in the json serde.
The RPC server uses `evbuffer_pullup()` to get a contiguous buffer to be passed to the json serde. Apparantly `evbuffer_pullup()` can return `nullptr` when the buffer is empty, which can be triggered using this curl command:
```console
$ curl -X POST --data '' -H "X-Transmission-Session-Id: ${session_id}" localhost:9091/transmission/rpc
```
And in the current code, this will trigger an assert failure.

fix: handle nullptr in json serde

---

libtransmission/variant.h
tests/libtransmission/dht-test.cc
tests/libtransmission/json-test.cc
tests/libtransmission/makemeta-test.cc
tests/libtransmission/move-test.cc
tests/libtransmission/rpc-test.cc
tests/libtransmission/session-test.cc
tests/libtransmission/settings-test.cc
tests/libtransmission/test-fixtures.h
tests/libtransmission/variant-test.cc

The tests should be testing the new `tr_variant` API, so that regressions like #6630 can be avoided.

test: use new `tr_variant` API

---

web/src/prefs.js
web/src/transmission.js

Alternative of #6998.
This PR make sure that the pref values read from the cookie is always going to be the same type as the default value.
Allowing pref values to have different types from their default value creates a need to implement error checking in all places where the pref values are used, but there is no benefit to it.
Also the fallback value of the web refresh rate has been reduced from 2 seconds to 1 second, like the original PR did.

refactor: parse cookie pref values as their default values types

---

web/assets/css/transmission-app.scss
web/src/torrent-row.js

Has also been refactored to giving parent object to respective function hence their name change `get` -> `render`. One with most returns are being replaced directly with appending method, I haven't consolidate them as in possible future there would be different mix of appending methods i.e. `appendChild()` instead of `textContent` (inside `setTextContent()`) to handle possible not text objects such as SVGs, that would allow flexible exchanging of per-torrent speed down and up symbols.

refactor: softcode/consolidate strings in `torrent-row.js`, normal appendChild order for compact mode

---

libtransmission/rpc-server.cc

Fixes #7104.
Notes: Log the reason when the RPC server rejects requests.

feat: log when RPC server reject requests

---

gtk/MakeDialog.cc

Adjust slider limits in GTK

---

README.md

Replace https://www.macstadium.com/opensource with https://www.macstadium.com/company/opensource, as the former results in 404.

Fix MacStadium opensource URL

---

libtransmission/rpc-server.cc

Use evhttp public accessors instead of private implementation details in rpc server code.

refactor: use evhttp public accessors in rpc server

---

libtransmission/variant-benc.cc
libtransmission/variant-json.cc
libtransmission/variant.cc
libtransmission/variant.h
tests/libtransmission/json-test.cc

Add the ability to serialise and de-serialise the JSON `null` type in `tr_variant`.
This is a pre-requisite for supporting [JSON-RPC](https://www.jsonrpc.org/specification) in our RPC API.

feat: support the JSON `null` type in `tr_variant`

---

macosx/TorrentTableView.mm

The outline view was apply its own styling. Instead, don't mark our groups as groups.

#7290: Resolve group rows rendering incorrectly

---

libtransmission/torrent-metainfo.cc

Fixes: #7302 
Take into account only the `private` flag that is inside the `info` dictionary and not elsewhere.

fix: Take into account only the private that is inside info.

---

libtransmission/announcer-http.cc
libtransmission/benc.h
libtransmission/torrent-metainfo.cc

Regression from #2529.
Address the concerns raised in https://github.com/transmission/transmission/pull/7111#issuecomment-2357031178.
The current http tracker response parser only checks the current key, which might lead to it unexpectedly accepting some out-of-spec values. This PR fixes that by:
1. Check the full path that leads to the dictionary key.
2. Differentiate between "empty string key" and "no key" (e.g. arrays).
CC @proton-ab and @reardonia for review because I am not familiar with the nuances of the various tracker implementations.
Notes: Harden the HTTP tracker response parser.

fix: check full path when parsing http tracker responses

---

web/src/context-menu.js

The issue became pronounced when I work on another PR that allows multiple popups. Problem isn't easily apparent but if you click anywhere other than the torrent list e.g. into the toolbar, the context menu does not always dismiss. This should fix it.
Notes: Fixed an issue where Transmission web's custom context menu does not close when clicking on some outside element.

fix: close context menu with a click outside listener

---

libtransmission/file-posix.cc
libtransmission/utils.cc

Fix #7006
Notes: New files are assigned a file mode per the process _umask_ defined in `settings.json`.

fix: use process umask for new files.

---

libtransmission/bandwidth.cc
libtransmission/bandwidth.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-socket.h
libtransmission/webseed.cc

Fixes #7005.
Speeds limits are not effective when set to a value below 16KiB/s, because they act on the piece speed, and the atomic unit of BT pieces is 16KiB.
This PR fixes this by:
1. Calculating the raw speed based on system call return values instead of Transmission's read/write buffers (which aren't suited for this purpose, because they usually change in units of 16KiB blocks as well).
2. Having the speed limiters act on the raw speed instead of the piece speed.
I also took the liberty of removing the code for transport protocol overhead, in other words the raw speed will now be taking only ***application-level*** data into account. Here's why:
- If we keep them, then this PR will have the side effect of the speeds displayed in UI always being a noticible fraction lower than the …

fix: speed limits did not work below 16KiB/s

---

web/src/transmission.js

Allows context menu to be placed to where the fingertip is on a zoomed in browser (Safari iOS)
This is a refinement upon #5928 along with small refactors.

refactor: alternative x/y coords to account for zoomed in browser

---

cli/cli.cc
daemon/daemon.cc
gtk/main.cc
libtransmission/utils.cc
libtransmission/utils.h
macosx/main.mm
qt/main.cc
tests/libtransmission/announcer-udp-test.cc
tests/libtransmission/dht-test.cc
tests/libtransmission/test-fixtures.h
tests/libtransmission/watchdir-test.cc
utils/remote.cc
utils/show.cc

A follow up of #5702.
This is just to hide more implementation details.

refactor: convert `tr_net_init_mgr` to singleton

---

libtransmission/tr-strbuf.h

Warning generated by clang-tidy-20, e.g.:
> ../libtransmission/tr-strbuf.h:41:16: warning: operator=() does not handle self-assignment properly [cert-oop54-cpp]

fix: cert-oop54-cpp warnings about self-assignment in strbuf

---

macosx/Base.lproj/MainMenu.xib

The progress bar was on top of the name label (and containing stack view). This reorders the progress bar to the back.
Fixes https://github.com/transmission/transmission/issues/7299

Resolve context menu not always appearing in compact mode

---

web/assets/css/transmission-app.scss

Top: This PR, Bottom: Original
Notes: Fixed a bug inflating per-torrent rows by long torrent names in compact view.

fix: use `grid` CSS to resolve the inflating rows by long torrent names in compact view

---

web/src/prefs-dialog.js

Fixes a problem where textboxes in the preferences popup that has a checkbox that enables/disables it does not respond to session changes that are not triggered by the WebUI.
This can be demonstrated by opening the preferences for speed limit, then enable/disable the speed limit by `transmission-remote -d <limit>` and `transmission-remote -D`.

fix(web): enable/disable textbox when session changed

---

libtransmission/web.cc

Superscedes #7407.
Notes: Added workaround for crashes related to https://github.com/curl/curl/issues/10936.

fix: crashes related to curl gh10936

---

macosx/Info.plist
macosx/InfoWindowController.mm
macosx/Torrent.mm

- En dash is used to separate ranges; e.g. 2024–2025
- Em dash is used to separate expressions; e.g. 100.5 GB — remaining time unknown

Use en and em dashes where appropriate

---

libtransmission/web.cc

Closes #7035
Closes #7413
Superscedes #7304
Print warning messages for known problematic curl versions when there are no workarounds possible.

feat: warn about problematic curl versions

---

libtransmission/web.cc

Switch to http1.1 when curl 7.71.0-7.74.0 are used. Fix another http2 problem caused by curl. This will solve #1563.
Read more here: curl/curl#6312

fix: not correctly sending UA to trackers related to curl gh6312

---

libtransmission/net.cc
libtransmission/net.h
libtransmission/peer-io.cc
libtransmission/peer-io.h
libtransmission/peer-socket.h
libtransmission/session.h
libtransmission/settings.cc
tests/libtransmission/handshake-test.cc
tests/libtransmission/settings-test.cc

This PR accomplishes a few things:
- Fixes #7157. Supercedes #7348.
- Fixes regression from #4372 where Transmission will not retry the outgoing connection attempt with TCP if `utp_connect()` returns non-zero. Supercedes #7349. *Note that in practice `utp_connect()` should never return non-zero, I'm just being thorough here.*
- Removes the need for workarounds like #6881.
- Paves way for #6007 by storing the transport protocol preference in an array.

refactor: set peer io socket in constructor

---

libtransmission/web.cc

Small performance refactor to web.cc: the return version of `curl_version_info(CURLVERSION_NOW)->version_num` isn't going to change during runtime, so we can cache its return value.
Likewise, we can cache the return value of `check_curl_gh10936()` and `check_curl_gh6312()`.

perf: cache curl version

---

libtransmission/tr-popcount.h

Potentially
- Fixes #6011
- Fixes #6026
- Fixes #6691
- Fixes #7079
- Fixes #7246
- Fixes #7264
This change is an ***experiment***, I want to merge it into `main` for more people to test. The code removed in this PR are new in `4.0.0`, and by process of elimination they seem to be the most probable culprit for the piece corruptions and stuck torrent progress people have been seeing since `4.0.0`. Having said that, I cannot see any issues with the code (granted I'm not good with assembly and compiler intrinsics), but no one else have been able to come up with a theory.
I don't see any obvious downsides for doing this experiment.
While I did get people to try out this patch and got some positive results, the sample size is just too small to be conclusive, so sadly I haven't been able to …

refactor: remove builtin and asm popcount implementation

---

cmake/FindWideInteger.cmake
libtransmission/peer-mse.cc

Fixes `constexpr` issues in C++20 and above encountered at https://github.com/transmission/transmission/pull/6832#discussion_r1610621779.

chore: bump wide-integer

---

web/assets/css/transmission-app.scss
web/src/torrent-row.js

In anticipation to #7335, some codes were pulled from there.

refactor: drop className `.full` in favor of `:not(.compact)`

---

libtransmission/variant.h

Fixes this clang-tidy warning:
> libtransmission/variant.h:207:31: warning: an exception may be thrown in function 'make_map' which should not throw exceptions [bugprone-exception-escape]

fix: bugprone-exception-escape warning in `Variant::make_map()`

---

libtransmission/peer-msgs.cc

Remove the Boolean class variables that indicate whether the peer supports PEX and metadata transfer, and rely only on whether the message ID is set to check for support.
This fixes a bug where Transmission would assume a peer supports PEX or metadata transfer after receiving these messages from the peer, then start to send messages to it despite not knowing the "extended message ID" of the peer for these message types.

fix: use message id to check for pex and metadata xfer support

---

web/src/rename-dialog.js

Notes: Added a new alert message of a problem when renaming torrent or file name.

feat: error rename alert message

---

libtransmission/tr-assert.h
libtransmission/tr-macros.h

Discussion: https://blog.aaronballman.com/2020/08/dont-use-the-likely-or-unlikely-attributes/

refactor: remove `TR_LIKELY` and `TR_UNLIKELY` macros

---

libtransmission/tr-assert.h

last use was removed in 3008a99

refactor: remove unused macro `TR_UNREACHABLE`

---

libtransmission/tr-macros.h

Kind of a fixup to https://github.com/transmission/transmission/pull/4457. 
Looks like I (poorly) cribbed the previous implementation from an older version of fmt:
```c++
#if ((FMT_CPLUSPLUS >= 202002L) &&                            \
(!defined(_GLIBCXX_RELEASE) || _GLIBCXX_RELEASE > 9)) || \
(FMT_CPLUSPLUS >= 201709L && FMT_GCC_VERSION >= 1002)
```
I implemented some of this wrong, and some of it is outdated:
- `TR_GCC_VERSION` never got defined anywhere AFAICT, so that clause always evaluated false. 
- `fmt` no longer uses the `_GLIBCXX_RELEASE > 9` check
- This is the only place where the `TR_CPLUSPLUS` macro is used, so let's remove it.

refactor: simplify TR_CONSTEXPR20 macro

---

libtransmission/web.cc

Remove the conditional-compile #ifdefs around `CURLOPT_SOCKOPTFUNCTION` and `CURLOPT_SOCKOPTDATA`. 
Those were added to curl in 7.15.6 and will always be available to us at compile time because of the minimum version required in `CMakeLists.txt`:
```cmake
set(CURL_MINIMUM 7.28.0)
```

refactor: remove the test to see if curl is at least 7.15.6

---

libtransmission/peer-mgr.cc
libtransmission/peer-mgr.h
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/resume.cc

Closes #6882.
Benefits:
- The format is no longer dependent on the compiler
- We can safely modify the `tr_pex` struct without worrying about its memory structure.
- We can add/remove infomation about a peer to be stored in the resume file without worrying too much about being incompatible with other versions.

refactor: store peers as benc in resume file

---

libtransmission/peer-mgr.cc

Mark peer to be disconnected upon blocklist update. Tested on my torrent, seems to be working.
I am not familiar with transmission code or cpp. Hope the fix does not cause any problems.
Notes: Disconnect blocklisted peers immediately upon blocklist update.
Fix #732 .

feat: disconnect blocklisted peers on blocklist update

---

Transmission.xcodeproj/project.pbxproj
libtransmission/CMakeLists.txt
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/resume.cc
libtransmission/resume.h
libtransmission/session.cc
libtransmission/session.h
libtransmission/torrent-metainfo.cc
libtransmission/torrent-metainfo.h
libtransmission/torrent-queue.cc
libtransmission/torrent-queue.h
libtransmission/torrent.cc
libtransmission/torrent.h
tests/libtransmission/CMakeLists.txt
tests/libtransmission/torrent-queue-test.cc

- Implement @ckerr's suggestion at https://github.com/transmission/transmission/pull/6753#discussion_r1546430816 to move the torrent queue to a dedicated class.
- Fix the issues raised at https://github.com/transmission/transmission/pull/6753#issuecomment-2411171405.
Notes: Save upload/download queue order between sessions.

refactor: dedicated class for torrent queue

---

libtransmission/peer-msgs.cc

Part of #6986.
To saturate the upload bandwidth, send back a piece message as soon as Transmission receives a request message, instead of sending out one batch every 0.5 seconds.
~This PR won't have much effect until #7027 is merged, but it is harmless and does not conflict with other code regardless.~
Edit: It's merged.
Notes: Better utilize high Internet bandwidth.

refactor: respond immediately to block requests from peer

---

utils/remote.cc

Uses `fmt::print` to log failure messages. Results in a connection
failure being printed as:
Unable to send request to 'http://localhost:9091/transmission/rpc/': Couldn't connect to server
Fixes #7010

fix(remote): failure reason should be printed

---

libtransmission/handshake.cc
libtransmission/handshake.h

https://github.com/transmission/transmission/pull/6949#pullrequestreview-2152187191
CC @reardonia

refactor: save outgoing `len(PadA)`, `len(PadB)` and `len(IA)`

---

docs/Editing-Configuration-Files.md
docs/rpc-spec.md
libtransmission/resume.cc
libtransmission/rpcimpl.cc
libtransmission/session.h
libtransmission/torrent-ctor.h
libtransmission/torrent.cc
tests/libtransmission/rpc-test.cc

feat: sequential download in `settings.json` `torrent-add` and `sesssion-*` RPC methods

---

daemon/daemon.cc
utils/remote.cc

Closes #6658.
Add command line options for sequential download in `transmission-remote` and `transmission-daemon`.

feat: sequential download cmdline options in remote and daemon

---

cli/cli.cc
daemon/daemon.cc
docs/Editing-Configuration-Files.md
docs/rpc-spec.md
gtk/Session.cc
libtransmission/quark.cc
libtransmission/quark.h
libtransmission/resume.cc
libtransmission/rpcimpl.cc
libtransmission/session.h
qt/Session.cc
tests/libtransmission/rpc-test.cc
utils/remote.cc
web/src/prefs-dialog.js
web/src/remote.js

Rename any new quarks in `4.1.0` to snake_case so that they don't have to be changed later.

refactor: rename unreleased quarks to snake_case

---

CMakeLists.txt

CMake 3.16.3 has been our "real" minimum version since `4.0.0`, since that's what wide_integer requires.

chore: bump cmake_minimum_required to 3.16.3

---

.gitmodules
CMakeLists.txt

They now provide their own CMakeLists.txt.
On the side of bumping libnatpmp, their minimum CMake version is bumped to 3.5, which is deprecated, but still supported at the moment.

chore: bump libnatpmp

---

docs/Building-Transmission.md

Qt 5.15 is going to reach EOL even for subscription licenses in May this year, so it's about time.

docs: use Qt6 in Windows build instructions

---

daemon/CMakeLists.txt
daemon/transmission-daemon.service.in

Notes: The daemon systemd service file now uses the CMake install prefix.

build: support different install prefixes for daemon service file

---

docs/Editing-Configuration-Files.md
libtransmission/session.cc
libtransmission/session.h
libtransmission/settings.cc
libtransmission/web.cc
libtransmission/web.h
tests/libtransmission/settings-test.cc

Improving on #5038, give users the option to use CURL's environment variables to set the proxy.
Also changed some risky uses of `std::string_view` to `std::string`.
Notes: Added support for using a proxy server for web connections.

feat: make `proxy_url` nullable

---

.github/workflows/actions.yml
libtransmission/CMakeLists.txt
libtransmission/utils.h

Use CMake-provided FindIntl module to look for the library and includes. Don't check for functions existence, both `gettext()` and `ngettext()` are available for ages now. Remove Windows- and Mac-specific logic, always use the functions if found and ENABLE_NLS is set to ON; for rare cases where their use is unwanted, one could set CMAKE_DISABLE_FIND_PACKAGE_Intl to ON.
Fixes: #7579

Simplify logic around gettext/libintl use

---

libtransmission/cache.cc
libtransmission/cache.h
libtransmission/peer-mgr-wishlist.cc

https://github.com/transmission/transmission/actions/runs/14796226536/job/41543893459
```
[72/136] Building CXX object libtransmission\CMakeFiles\transmission.dir\cache.cc.obj
D:\a\transmission\transmission\src\libtransmission\cache.cc:32:59: warning: the parameter 'end' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
32 | Cache::CIter Cache::find_span_end(CIter span_begin, CIter end) noexcept
|                                                           ^
|                                                     const  &
D:\a\transmission\transmission\src\libtransmission\cache.cc:38:46: warning: parameter 'span_begin' is passed by value and only copied once; consider moving it to avoid unnecessary …
```

chore: silence clang-tidy warnings

---

gtk/.clang-tidy
libtransmission/.clang-tidy
qt/.clang-tidy
tests/libtransmission/.clang-tidy

Enabling `readability-uppercase-literal-suffix` doesn't automatically make `readability-implicit-bool-conversion` suggest uppercase literal suffixies.
We need to manually tell `clang-tidy` to do so by setting `readability-implicit-bool-conversion.UseUpperCaseLiteralSuffix` to `true`.

build: tell clang-tidy to suggest uppercase literal suffixes

---

utils/remote.cc

Fixes #7534
Regression from #6832

fix(remote): print label separators correctly

---

.gitattributes
web/.gitattributes

According to https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github, `linguist-generated=true` works only inside the `.gitattributes` file located at the root of the repository.
> Unless the *.gitattributes* file already exists, create a *.gitattributes* file in the root of the repository.

chore: move `.gitattributes` to root of repository

---

libtransmission/file-posix.cc
libtransmission/handshake.cc
libtransmission/log.cc
libtransmission/open-files.cc
libtransmission/port-forwarding-natpmp.cc
libtransmission/port-forwarding-upnp.cc
libtransmission/subprocess-posix.cc
libtransmission/variant-json.cc
libtransmission/watchdir-win32.cc
libtransmission/webseed.cc

fixup! chore: move away from fmt/core.h (#7557)

---

Transmission.xcodeproj/project.pbxproj

Crashes on [assert here](https://github.com/transmission/transmission/blob/f7373cb6483bd624c065cdc5a3b53908ee9b1902/libtransmission/web-utils.cc#L256)
Broken after https://github.com/transmission/transmission/pull/7575
Define was [changed here](https://github.com/transmission/libpsl/compare/692c69d2415e1b20378030c08607935a54434087...f88562a8d9bf79d9fb74f59b7bc5a22ee6664fda#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)

fix: use correct defines when building libpsl with Xcode after roll.
