cmake/TrMacros.cmake
Previously building with `cmake -G Ninja` would fail with this error:
```
ninja: error: 'third-party/event-c51b159cff/lib/libevent.a', needed by
'libtransmission/transmission-test-watchdir_generic', missing and no
known rule to make it
```
This was due to missing BUILD_BYPRODUCTS in the calls to
ExternalProject_Add(), as discussed here:
https://cmake.org/pipermail/cmake/2015-April/060234.html
=> Fix CMake build system with the Ninja backend

Transmission.xcodeproj/project.pbxproj, macosx/Info.plist
The Info.plist file is currently copied into the bundle twice: Contents/ and Contents/Resources/. It belongs into Contents/ and has no apparent purpose in Contents/Resources/. Xcode flags this as a warning.
I also changed the Info.plist key for the minimum version to `$(MACOSX_DEPLOYMENT_TARGET)` so that it matches the project deployment target. This is the default in new Xcode projects. The current value is 10.6, which is not correct anymore.
=> Remove Info.plist from copy phase and align minimum version

qt/transmission-qt.desktop
I don't see the name "Qtransmission" mentioned anywhere else, and it's confusing to not find Tranmission under the letter "T" in my desktop's application launcher.
=> Correct name of qt client in desktop file

m4/glib-gettext.m4
Fixes build on Xenial
Copied from https://github.com/Alexpux/MINGW-packages/issues/1351
=> Work around "error: m4_copy: won't overwrite defined macro: glib_DEFUN"

libtransmission/clients-test.c, libtransmission/clients.c
This is based on the following resources,
http://www.xfplay.com/history.html
https://down.xfplay.com/xfplay9.994.exe
https://down.xfplay.com/xfplay9.992.exe
https://down.xfplay.com/xfplay9.991.exe
https://down.xfplay.com/xfplay9.99.exe
http://q.xfplay.com/
This fixes issue https://github.com/transmission/transmission/issues/252.
=> Add Peer ID for Xfplay torrent client

daemon/remote.c
When using the transmission-remote program to list
peers(e.g. transmission-remote -t42 -ip), there is
not enough room for ipv6 addresses.
Increase the ip address column width from 20 to 40
(128/4 hex numbers + 32/4 - 1 colons + 1 space =
40 character width).
=> Enlarge IP address column in transmission-remote

qt/Torrent.h, qt/TorrentFilter.cc
Magnet transfers caused the by-progress sorting to become non-stable, as their
percentComplete() could return NaN. This patch fixes this by preferring active
downloads over magnet transfers, then sorting them by percentComplete().
=> Fix sorting by progress (Qt client)

daemon/daemon.c, daemon/transmission-daemon.1, libtransmission/rpc-server.c, libtransmission/transmission.h
Currently, the RPC listen address is only allowed to be IPv4. This isn't a technical limitation however, and it works fine if it is an IPv6 address. This commit removes this limitation and also allows IPv6 addresses and thus makes the RPC server accessible through IPv6.
Note: it is currently impossible to reliably listen on multiple addresses, as is done with the regular `bind-address-{ipv4,ipv6}` options, because of [libevent#394](https://github.com/libevent/libevent/issues/394) (summary: when binding on `::` with libevent, on most OSs, you are also automatically binding on `0.0.0.0`). I don't think that the approach of my commit is inferior however, as the use of the RPC server is much more limited, and it is fine to just listen on a single protocol/address.
Fixes #59.
=> Allow the RPC server to listen on an IPv6 address

libtransmission/torrent.c
gettext won’t pick up a comment if it’s not exactly one line above the string.
=> lib: fix translator comment extraction

libtransmission/crypto-utils-openssl.c
This seems to be the idiomatic way to fix libressl compatibility issues,
judging by what most other open source projects seem to be doing.
I've confirmed that transmission builds with libressl for me after this
patch is applied.
=> LibreSSL compatibility

libtransmission/clients-test.c, libtransmission/clients.c
Based on information from https://github.com/picotorrent/picotorrent and http://www.picotorrent.org/.
PicoTorrent uses Azureus-style peer ID: -PI-. Example: -PI0091- (major: 0, minor: 09, patch: 1).
Here is an screenshot of PicoTorrent 0.12.0 in action after this patch is applied,
NOTE: ` strint(id + 4, 2)` does not parse `09` value correctly, hence we use `%d%d` hack along with two `charint` function calls.
=> Add Peer ID for PicoTorrent

libtransmission/clients-test.c, libtransmission/clients.c
Based on experiments with FDM 5.1.32 running on Windows 10.
FDM uses Azureus-style peer ID with `-FD` prefix.
This fixes issue https://github.com/transmission/transmission/issues/335.
=> Add Peer ID for Free Download Manager (FDM)

libtransmission/clients-test.c, libtransmission/clients.c
Based on experiments with Folx version 5.2.1.13690 running on macOS Sierra.
Folx uses Azureus-style Peer ID with "-FL" prefix.
This fixes issue https://github.com/transmission/transmission/issues/359.
Before this commit,
After this commit,
=> Add Peer ID for Folx

libtransmission/net.c, libtransmission/net.h, libtransmission/peer-io.c
When Transmission tries to set TOS on an IPv6 connection, it triggers error since the original code only supports IPv4. This patch should fix issues like #128 and #341 . Also, we can finally say goodbye to the annoying `"can't set tos '0': invalid argument"` messages
(Already tested on MacOS with latest master && 2.92 codebase.)
=> Improving ToS on IPv6 connections

web/index.html
It disrupts the view and I can't come up a daily usage scenario that needs to utilize autocomplete function.
=> Disable autocomplete on torrent url field from WebUI

libtransmission/clients-test.c, libtransmission/clients.c
Baidu Netdisk uses Azureus-style Peer ID with "-BN" prefix.
This fixes https://github.com/transmission/transmission/issues/240.
Deriving the exact version number from the Peer ID does not seem to be possible.
=> Add Peer ID for Baidu Netdisk

macosx/FileOutlineController.m
This fixes the `No visible @interface for NSArray declares the selector "containsIndex:"` error that prevented Xcode (9b6) from compiling:
=> Fix `No @interface declares "containsIndex:"`

qt/FileTreeItem.cc
File names are often too long to fit. Hovering is much easier than
resizing the column and possibly the window.
And by the way, why is the tree view's horizontal scroll bar disabled?
=> Qt: Show file names in tooltips in Torrent Properties

gtk/CMakeLists.txt, gtk/icons/Makefile.am, gtk/icons/hicolor_apps_symbolic_transmission-symbolic.svg
The -symbolic icon variant (if available) is used in the GNOME top bar,
and when the high contrast theme is in use.  This icon was created by
Jakub Steiner, and comes from the gnome-icons repository:
https://github.com/gnome-design-team/gnome-icons/blob/master/apps-symbolic/Adwaita/scalable/apps/transmission-symbolic.svg
https://bugzilla.redhat.com/show_bug.cgi?id=1221292
There is some confusion over whether symbolic app icons should be
installed to icons/hicolor/scalable/apps (alongside the regular scalable
icon) or to icons/hicolor/symbolic/apps. On the one hand,
https://wiki.gnome.org/Initiatives/GnomeGoals/HighContrastAppIcons has
this to say:
> […] obtain a suitable symbolic style icon […] and install it to the
> hicolor prefix, the same way you would for the full color variant.
>
> …
=> gtk: add symbolic icon

cli/transmission-cli.1, daemon/transmission-daemon.1, daemon/transmission-remote.1, utils/transmission-create.1, utils/transmission-edit.1
Hi. I had troubles with `transmission-daemon` and was reading up on the manual. I saw something trivial.
This commit is to remove a comma to make `transmission-daemon` manual a bit more flawless. I'm also removing whitespace in other manuals too to make things a bit more nice... to kill two birds with one stone.
=> remove whitespace and a comma in the manuals

libtransmission/web.c
While zlib is mandatory for transmission, it is not mandatory for curl.
A libcurl that has been compiled with no support for zlib will return no data if compressed responses are set to on.
In the basic case this prevents the port checking functionality from working properly. It also prevents web seeding from working as well.
=> Set compression to curl defaults

qt/FileTreeModel.cc
An assertion failure happens shortly after opening the "Torrent properties" dialog if the torrent's root folder has a one-letter name, e. g.
```
A/
A/Some Linux distro.iso
A/Some other Linux distro.iso
```
Both current master and 2.93 are affected.
Off by one errors are great, eh?
This fixes https://trac.transmissionbt.com/ticket/6141 (reported by me).
=> Qt: Fix assert with one-letter root folder names

daemon/remote.c
Data added with `evbuffer_add` isn't null-terminated. This was causing
extra characters to appear at the end of the output.
Fixes: #174
=> Ensure buffer contents are null-terminated

libtransmission/crypto-utils-openssl.c
LibreSSL 2.7 adds OpenSSL 1.1 API
See also: https://bugs.freebsd.org/226953
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>
=> Fix build with LibreSSL 2.7

qt/DetailsDialog.cc
It was always 0.0% as long as the torrent was not finished.
=> Qt: Fix bad downloaded percentage in DetailsDialog

libtransmission/torrent.c
Field `etaDLSpeedCalculatedAt` was set too early, causing the condition following it to always be false (the 4000 ms comparison with `now`). The same for `etaULSpeedCalculatedAt`.
=> Fix setting the ETA timestamps

libtransmission/web.c
This fix is needed to successfully connect to https trackers with default settings.
@realPy has mentioned this bug in the comments for https://github.com/transmission/transmission/commit/44411d719c0bd6c17a794ab03eb8148f20a79b81 but I think @mikedld misunderstood what the issue actually was so this never got fixed
=> fix logic for setting the curl ca bundle file

utils/show.c
`transmission-show` does not check the return value of `localtime`. If a torrent file with an invalid creation date is shown, the return value for `localtime` may be `NULL`. Since the value is immediately dereferenced, the program crashes with a segfault.
This PR checks the return value of `localtime` before displaying the date.
=> transmission-show: Prevent crash with invalid creation date

cli/transmission-cli.1
@mikedld fixed a small typo in the manpage.
=> Fix typo in CLI manpage.

COPYING, cmake/Transmission.rc.in, gtk/main.c, macosx/Controller.h, macosx/Controller.m, macosx/Info.plist.in, macosx/NSStringAdditions.h, macosx/NSStringAdditions.m, macosx/PrefsController.h, macosx/PrefsController.m, macosx/QuickLookPlugin/QuickLookPlugin-Info.plist, macosx/TorrentTableView.h, macosx/TorrentTableView.m, macosx/da.lproj/InfoPlist.strings, macosx/de.lproj/InfoPlist.strings, macosx/en.lproj/InfoPlist.strings, macosx/es.lproj/InfoPlist.strings, macosx/fr.lproj/InfoPlist.strings, macosx/it.lproj/InfoPlist.strings, macosx/main.m, macosx/nl.lproj/InfoPlist.strings, macosx/pt_PT.lproj/InfoPlist.strings, macosx/ru.lproj/InfoPlist.strings, macosx/tr.lproj/InfoPlist.strings, qt/LicenseDialog.ui
Updated Transmission Project copyright dates to 2005-2019 in headers and code.
=> Updated copyright strings to 2019

utils/show.c
It's useful when using transmission-show in the shell scripts for selecting files to download by index.
Otherwise, transmission-daemon will recieve another files through rpc, because index order after the sort will be changed.
=> Add option "--unsorted" for transmission-show

libtransmission/blocklist-test.c, libtransmission/blocklist.c
This commit adds a new blocklist line format, namely individual IPv4 CIDR ranges separated by newlines. Text put after each entry is ignored by sscanf, so feel free to put any kind of comments there.
Fix #230.
=> Support CIDR-notated blocklists

Transmission.xcodeproj/project.pbxproj
`sourceTree = SOURCE_ROOT;` is a bad practice (and was causing a red link in the project). Better have it relative to `<group>`.
=> Fix QuickLookPlugin reference path to be relative to group

libtransmission/torrent.c
This is useful if the client script is going to access the .resume file. Ensuring an up-to-date .resume file means that user scripts will be able to access it.
=> fix: update the resume file before running scripts

libtransmission/announcer-common.h, libtransmission/announcer.c
1. Make multiscrape_max a per-scrape-url property rather than a global fixed constant.
2. Incrementally lower that limit when multiscrapes error out with messages like `GET string too long`.
=> feat: make multiscrape limits adaptive

libtransmission/peer-msgs.c, libtransmission/rpcimpl.c, libtransmission/variant-benc.c, utils/show.c
Fixes a handful of warnings that Coverity sent to my inbox.
These are generally cases where we weren't testing a return value from `tr_variantGetFoo()` because the field was optional or because we'd already confirmed the field elsewhere, so this PR is more about making Coverity happy. These probably don't need to be backported to the maintenance line.
=> fix: Coverity warnings

utils/remote.c
Under the current code, if there are over 9,999 torrents the format will shift over one space when bumping from 9999 to 10000. This fixes that by widening the field width two spaces.
=> widen the torrent-id column for cleaner formatting

CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, configure.ac, libtransmission/CMakeLists.txt, libtransmission/rpc-server.c, libtransmission/utils.c, utils/remote.c
RFC 2616 defines headers as case-insensitive, so if rpc is behind a
reverse proxy that lowers the case of headers, transmission will not
parse the headers correctly.
=> Parse session-id header case-insensitively

libtransmission/net.c, libtransmission/net.h, libtransmission/session.c
The set of pre-named TOS values are now renamed to the latest DSCP
standards, with traffic classes and everything exciting. To keep
everything in the same place, a segment has been added to net.h to keep
the currently named values.
A result of these changes is that "lowcost" is probably no longer
harmless, as it now encourages the router to preferentially drop the
packages when bandwidth requires so. "lowdelay" is assigned to a pretty
high AF class for SIP and stuff. I am not sure at all about the
"throughput" assignment. I mean, the whole point of DSCP-fication is
translating from the old ToS bits to a more precedence-based notation,
and precedence is supposed to lie alongside the old 4 ToS bits,
not be part of them...
A funny interaction between the AFxy and the old ToS fields lies in …
=> Unify/Modernize TOS to DSCP standards

libtransmission/platform-quota.c
Backport for 2.9x. It's causing build failures on OpenWrt:
https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/transmission/openssl/compile.txt
=> [2.9x] uClibc-ng since 1.0.18 has sys/quota.h synced with GNU libc

gtk/details.c, gtk/dialogs.c, gtk/file-list.c, gtk/filter.c, gtk/hig.c, gtk/main.c, gtk/makemeta-ui.c, gtk/msgwin.c, gtk/open-dialog.c, gtk/relocate.c, gtk/stats.c, gtk/torrent-cell-renderer.c, gtk/tr-core.c, gtk/tr-icon.c, gtk/tr-prefs.c, gtk/tr-window.c, gtk/util.c
Fixes some of the smaller warnings, e.g. don't use `gtk_alignment_new()` or `gtk_menu_popup()`.
This is the low-hanging fruit -- it doesn't do anything to switch to GActions, or replace the use of GtkIconFactory and GtkUIManager.
=> Fix some gtk warnings

code_style.sh
The script uses "set -o", which doesn't exist in vanilla sh, causing failure on systems that bind sh to dash rather than bash. This PR makes the bash requirement explicit.
=> fix: use bash, not sh, for code_style.sh script

qt/MainWindow.cc, qt/MainWindow.h, qt/Torrent.cc, qt/Utils.cc, qt/Utils.h
Some actions share an icon -- for example, "start all", "start now", and "start" each use "media-playback-start". When this happens, get the icon once and cache it to avoid hitting the disk more often than necessary.
In addition, the statusbar's network transfer icon was being reloaded in a periodic upkeep timer, reloading with QIcon::fromTheme each time. Only five icons are needed, so load them once and cache them.
=> refactor: don't load the same stock more than once

qt/Application.cc, qt/Application.h, qt/DetailsDialog.cc, qt/DetailsDialog.h, qt/MainWindow.cc, qt/MainWindow.h, qt/Session.cc, qt/Session.h, qt/Torrent.cc, qt/Torrent.h, qt/TorrentFilter.cc, qt/TorrentModel.cc, qt/TorrentModel.h
The Torrent->Application signal connections make up for about 5% of the app's memory use. Move this to the TorrentModel so that there are only a handful of signal connections.
Moving signals to TorrentModel means batch change signals can be emitted instead of per-change-per-torrent emissions and can be handled that way.
=> refractor: simplify torrent model signal emissions

macosx/BlocklistDownloader.m, macosx/Controller.m, macosx/CreatorWindowController.m, macosx/DragOverlayWindow.m, macosx/PrefsController.m, macosx/QuickLookPlugin/GeneratePreviewForURL.m, macosx/Torrent.m
This reverts commit c0c463d66042dc0a5299e9228d0dbb3cfe99e214, reversing
changes made to cd2587a43518f8d26fb1c10c8397cc733c71e273.
This is because of https://github.com/transmission/transmission/issues/1183
=> Revert "Merge pull request #1039 from MaddTheSane/patch-4"

gtk/tr-icon.c
Hello,
Context menu is not showing.
After right click at the tray icon I got errors in the log:
```
gtk_menu_popup_at_widget: assertion 'GTK_IS_WIDGET (widget)' failed
invalid cast from 'GtkStatusIcon' to 'GtkWidget'
```
I think we should use
`gtk_menu_popup_at_pointer(GTK_MENU(w), NULL);`
Tested, worked.
Thanks!
=> Fixed showing popup menu on RMB at tray icon

libtransmission/magnet.c
(discovered by libFuzzer, confirmed manually)
This PR fixes a small memory leak in `tr_magnetParse`. When a magnet URI is not successfully parsed, some memory allocations (created by `tr_http_unescape`) are not freed before `tr_magnetParse` returns.
To confirm the presence / fix of these leaks, the `fuzz-magnet` target from #1221 is used with [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html).
```sh-session
$ cat leaks/leak0
magnet:?dn=u
$ ./fuzz/fuzz-magnet ./leaks/leak0
INFO: Seed: 2668441529
INFO: Loaded 1 modules   (90 inline 8-bit counters): 90 [0x55aa055d6740, 0x55aa055d679a), 
INFO: Loaded 1 PC tables (90 PCs): 90 [0x55aa055d67a0,0x55aa055d6d40), 
./fuzz/fuzz-magnet: Running 1 inputs 1 time(s) each.
Running: ./leaks/leak0 …
```
=> fix: memory leak in magnet parsing

gtk/tr-core.c
A pretty simple fix: if we don't have a file path, don't test that path to see if the file exists.
Triggered when magnet links are added.
=> fix: fix console warning when adding magnet links

extras/rpc-spec.txt
The argument is actually valid for `torrent-get` only.
=> fix(rpc-spec): fix typo in `editDate` arg description

qt/AboutDialog.cc, qt/AddData.cc, qt/Application.cc, qt/ComInteropHelper.cc, qt/DBusInteropHelper.cc, qt/DetailsDialog.cc, qt/FaviconCache.cc, qt/FileTreeDelegate.cc, qt/FileTreeView.cc, qt/FilterBar.cc, qt/FilterBarComboBoxDelegate.cc, qt/Filters.cc, qt/MainWindow.cc, qt/MakeDialog.cc, qt/OptionsDialog.cc, qt/Prefs.cc, qt/PrefsDialog.cc, qt/Session.cc, qt/TorrentDelegate.cc, qt/TorrentDelegateMin.cc, qt/TrackerDelegate.cc, qt/Utils.cc, qt/Utils.h, qt/WatchDir.cc
Further reading:
* https://forum.qt.io/topic/78540/qstringliteral-vs-qlatin1string/2
* https://woboq.com/blog/qstringliteral.html
* https://www.qt.io/blog/2014/06/13/qt-weekly-13-qstringliteral
tl;dr: QLatin1Literal uses less memory than QStringLiteral; however, since most Qt APIs require a QString argument, there's extra runtime cost of converting QLatin1Strings to QStrings. QStringLiteral uses a little more memory but constructs its QStrings at compile time.
ok, the previous [`prefer-qstringliteral` branch](https://github.com/transmission/transmission/pull/1274) is getting out of control: the secondary goal of fixing a .clang-tidy issue is causing more diffs than the primary goal. So, I'm breaking it into two separate PRs.
=> chore: prefer QStringLiteral

qt/Application.cc, qt/DetailsDialog.cc, qt/DetailsDialog.h, qt/Torrent.cc, qt/Torrent.h, qt/TorrentModel.cc
edit-date got added to the backend in 3.00, but I never finished adding
it properly to the Qt client. This PR rectifies that. When a torrent is
edited, the Application and DetailsDialogs will re-query the backend to
update the torrent properties that are needed.
=> feat: add 'edit-date' support to qt client

qt/MainWindow.cc
Walking through a long list of QModelIndexes is quite expensive, but most of our tests are only done on selected rows. It's rare for all rows to be selected, so walk through selected rows instead of all of them.
This is a minor improvement that I found while working on a different piece of code. PRing it here separately so that 1 PR == 1 idea.
=> refactor: faster action sensitivity updates

qt/DetailsDialog.cc, qt/DetailsDialog.h, qt/FilterBar.cc, qt/FilterBar.h, qt/MainWindow.cc, qt/Torrent.cc, qt/Torrent.h, qt/TorrentModel.cc, qt/TorrentModel.h
Laying the groundwork for followup PRs, instead of doing expensive work every time a Torrent object has any change at all, we can be more fine-grained and do the work only if the relevant Torrent properties changed.
=> feat: Torrent::update() returns a bitset of changed properties

extras/rpc-spec.txt
The "format" is a request arg, not part of the torrent-get payload.
=> Fix typo in rpc-spec.txt

qt/Prefs.cc, qt/Session.cc, qt/VariantHelpers.h
Explicitly delete the implied function to ensure we don't get bitten by this again in the future.
Mark the string_views constexpr where possible so that we can avoid some strlen() calls at runtime.
=> fix: type deduction error introduced in 00be8d0

qt/RpcClient.cc, qt/RpcClient.h
Minor optimization: since we don't actually change our request headers very often, we can lazy-build the request once and reuse that instead of having to rebuild it each time.
=> refactor: reuse one QRequestHeader across requests

gtk/actions.c, gtk/notify.c, qt/Application.cc
Described at https://developer.gnome.org/notification-spec/#categories, this is for a file transfer or download complete notification.
=> feat: add 'transfer.complete' notification hint on XDG desktop notifications

qt/MainWindow.cc, qt/MainWindow.h, qt/WatchDir.cc, qt/WatchDir.h
Over the weekend I ran the Qt client in valgrind and found a couple of leaks -- WatchDir's QFileSystemWatcher, and the QStyle that we pass to TorrentView.setStyle() in the main window. This PR fixes both of those leaks.
=> fix: qt client memory leaks

gtk/CMakeLists.txt, gtk/actions.c, gtk/details.c, gtk/file-list.c
* Disable deprecation warnings in GTK client. Yes, updating the codebase is still a goal. (help welcomed!) But there's a deluge of deprecation warnings that drown out everythign else, so turn off the deprecation warnings for now.
* Fix a regression introduced a few days ago with 47501a4 when an argument got removed.
* Fix a couple of type warnings by casting gobjects to the correct type for the functions being called.
=> Fix or silence gtk warnings

qt/AddData.cc, qt/Session.cc, qt/Session.h, qt/TorrentFilter.cc
* If you accidentally try to add a lot of duplicates -- for example, by starting up with a lot of duplicate torrents in the watchdir -- then coalesce all of them into a single error dialog instead of spamming the desktop with a different dialog for every duplicate.
* Make the duplicate torrent dialog's error message slightly terser to make it accommodate a long list of torrents: omit the ".torrent" file suffixes and show an abbreviated form of the existing torrent's hash.
* Support searching by torrent hash in the filterbar's text entry. This is useful when copy/pasting the hash from the duplicate torrent error dialog and is also consistent with the GTK client behavior.
* Copy the GTK client's behavior of appending ".added" to the end of .torrent files after they've been added to the …
=> feat: nicer add-torrent workflow in the qt client.

qt/Session.cc, qt/Session.h
Tweak the display of the "unable to add duplicate torrents" dialog in the Qt client.
This PR is a followup to [this PR](https://github.com/transmission/transmission/pull/1410) where @mikedld had some comments that I didn't see until after it had been merged.
=> fixup: qt client nicer torrent add handling

qt/DetailsDialog.cc, qt/Torrent.cc, qt/Torrent.h, qt/TorrentFilter.cc, qt/TorrentModel.cc, qt/TorrentModel.h, qt/VariantHelpers.cc, qt/VariantHelpers.h, qt/WatchDir.cc, tests/libtransmission/clients-test.cc, tests/libtransmission/crypto-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/metainfo-test.cc, tests/libtransmission/variant-test.cc
Minor optimization to the Qt client's `Torrent` class: keep the hash in a `std::array<uint8_t, 20>` instead of in a `QString`. Since the size of the array is known at compile time, it can be built into the Torrent class and the extra heap allocs for QString's internals can be avoided.
This saves about 5 MB from the RES size on my 15K torrent testbed, which is better than I expected, considering that the raw hashString char array size was 41 bytes so the raw data savings is only (15K torrents * (41 bytes - 20 bytes)) = 0.31 MB.
5 MB out of 15K torrents isn't a huge win; however, since we don't display the hashString anywhere except for in the details dialog, building the string on demand is not expensive.
=> refactor: don't store torrent hashes in QStrings

tests/libtransmission/clients-test.cc, tests/libtransmission/crypto-test.cc, tests/libtransmission/getopt-test.cc, tests/libtransmission/magnet-test.cc, tests/libtransmission/metainfo-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/rpc-test.cc, tests/libtransmission/utils-test.cc
The tests FTBFS on the latest version of MSVC because it has a regression that crashes the compiler when it sees a constexpr std::array. This commit can be reverted when MSVC releases a fix.
https://developercommunity.visualstudio.com/content/problem/1139953/167-regression-auto-constexpr-with-deduced-array-i.html
=> refactor: work around msvc constxpr std::array bug

qt/Application.h, qt/Torrent.cc, qt/VariantHelpers.cc
Second of three PRs focused on minor memory improvements in the Qt client.
Add an app-wide interned QString cache for commonly-repeated strings. Currently used for download_dir, announce_url, comment, creator, and error_string.
=> refactor: intern repeated strings e.g. downloadDir

qt/FaviconCache.h, qt/Torrent.cc
Third of three PRs focused on small memory wins in transmission-qt. This one saves 1-2 M off RES in my 15K torrent testbed. Not a major improvement, but nice enough.
Previously we held the torrent's tracker keys in an `std::unordered_set`. That container type is overkill for this field: the list is usually short and almost never changes, so we don't need fast insertion time. We can keep the same log N lookup by using a sorted `std::vector` and avoid the excess container size & memory allocations of a `std::unordered_set`.
=> refactor: use a vector for FavIcon cache keys

qt/Application.cc, qt/FileTreeModel.cc, qt/Torrent.cc, qt/Torrent.h, qt/TorrentModel.cc
Another "small wins" patch, this time for startup load: icon loading is expensive, so calculating them for every torrent all at once on startup isn't great. By lazy-loading them, the work is spread out over time.
=> refactor: make torrents' mime icons lazy-loaded.

qt/RpcClient.cc
Final PR from the Labor Day hack session. :slightly_smiling_face: 
When set, this will log the RPC messages sent between the GUI and the
backend. This replaces the old `#ifdef DEBUG_HTTP` as a more flexible
option that can be enabled without rebuilding the app.
=> feat: add 'TR_RPC_VERBOSE' env variable in Qt app.

qt/Application.h, qt/DetailsDialog.h, qt/FileTreeModel.h, qt/Formatter.cc, qt/IconCache.cc, qt/OptionsDialog.h, qt/Prefs.cc, qt/Prefs.h, qt/RelocateDialog.cc, qt/RpcClient.cc, qt/RpcQueue.cc, qt/RpcQueue.h, qt/Session.h, qt/TorrentDelegate.cc, qt/TorrentDelegate.h, qt/TorrentModel.h, qt/TrackerDelegate.cc, tests/libtransmission/.clang-tidy
This PR fixes some warnings that I found when test-driving clang-tidy-11 on Transmission.
=> chore: fix clang-tidy-11 warnings

web/package.json
To get rid of the warning msg 'WARNING in Conflict: Multiple assets emit different content to the same filename ...',
option -d added to webpack-dev-server
=> chore(web): get rid of webpack-dev-server warning

libtransmission/file-posix.c, libtransmission/net.c, libtransmission/variant-benc.c, utils/remote.c
most of the changes in this set are to silence nullptr dereference warnings by adding `(foo != NULL)` style safeguards.
The `tr_address` comparison function is a fair call: this revision compares the struct's fields directly to avoid accidentally including padding in the `memcmp()` comparison.
The change to how `realpath()` is invoked fixes the warning but is mainly to ensure that the calling function always returns memory that's been allocated with `tr_malloc()` instead of mixing that with `realpath()`'s call to `malloc()`.
=> chore: fix more sonarcloud warnings

qt/FreeSpaceLabel.cc
Fixes a crash that could happen if a FreeSpaceLabel was destroyed while an RPC request was in-flight.
=> fix: dangling reference crash in FreeSpaceLabel

libtransmission/tr-dht.c
Per analysis by cfpp2p
(https://github.com/transmission/transmission/issues/564#issuecomment-377612224),
a duplicate search is not an error.
=> Properly parse dht_search()

libtransmission/clients.c, tests/libtransmission/clients-test.cc
This is based off of PR #1526 by azy5030 to add in: Torrent Web, BiglyBT, and FrostWire. I made the additional change requested by livings124.
In addition this also adds support for: HTTP Seed, aria2 (#532), and BitLord. Further testing revealed the BitLord -32 is not the 32 bit version as I thought, but instead part of a 3 digit build number. I've fixed this in my second commit.
This is my first PR so if there are any more changes required let me know and I'll make them.
=> Add unrecognized client names #1363

release/windows/build-qt.ps1
The previous URL returns a 302 error, which causes Invoke-WebRequest to error out. This PR changes the URL to the redirected location.
Example of CI failure: https://ci.appveyor.com/project/transmissionbt/transmission/builds/39088944/job/wy2w6jn6y8cgkjlv#L349
=> fix: Qt download URL in build-qt.ps1

appveyor.yml
The old version number is erroring out.
Sample failed run: https://ci.appveyor.com/project/transmissionbt/transmission/builds/39214635/job/43mfddhi9s5l85mn
=> chore: bump imagemagick version in choco install on appveyor

qt/BaseDialog.h, qt/DetailsDialog.cc, qt/Prefs.cc
I recently upgraded to Ubuntu 21.04 and the new versions of clang-tidy and Qt had a few new warnings for the codebase. This PR fixes the easy warnings.
There are still two remaining changes that will be a little more intrusive, so I've filed issues to discuss them first: https://github.com/transmission/transmission/issues/1704 and https://github.com/transmission/transmission/issues/1706
=> refactor: qt deprecations, pt 1

libtransmission/CMakeLists.txt
It appears this was removed by accident.
Fixes: 677dc73eac3efa769eefb1c7ec4eda232a35977a
=> Restore support for the INSTALL_LIB option

code_style.sh
Procedural PR to omit the build/ directory from clang-tidy work
=> chore: add build/ to clang-tidy exclude list

libtransmission/session.c, libtransmission/session.h, libtransmission/torrent.c, tests/libtransmission/.clang-tidy
`tr_torrentFindFromId()`, `tr_torrentFindFromHashString()`, and `tr_torrentFindFromHash()` are now O(log N) instead of O(N) where N is the number of torrents. This is done by adding sorted `tr_ptrArray` lookup tables for these three keys into `tr_session`.
=> perf: lookup tables for faster torrent searching.

libtransmission/peer-mgr.c
tr_peerMgrStartTorrent() is called once per torrent on startup, so this
can be expensive if the user has a lot of torrents.
Instead, enqueue a pending rechoke that will happen on idle. This way,
all the added torrents can be handled by a single rechoke call.
=> perf: do not rechoke in tr_peerMgrStartTorrent()

libtransmission/announcer.c, libtransmission/announcer.h, libtransmission/peer-mgr.c, libtransmission/peer-mgr.h, libtransmission/peer-msgs.c, libtransmission/resume.c, libtransmission/torrent.c, libtransmission/tr-dht.c, libtransmission/tr-lpd.c, macosx/Controller.m, macosx/Torrent.m
For private torrents, the tracker is the sole source of peers. So when a private torrent's tracker responds that there are 0 leechers, we can use that information to mark the entire swarm as seeders and to not initiate connections to those peers if we are seeding. This can help seedboxes to more efficiently pick which swarms to prioritize.
This strategy is not used on public torrents, since new seeder-to-seeder connections can be useful there for pex.
This PR changes `tr_peerMgrAddPex()` to (1) remove the `tr_atom.seedProbability` field (which was not as robust as intended) and (2) add batches of peers instead of just a single peer.
=> perf: use scrape to know when a private swarm is all-seeds

libtransmission/announcer-common.h, libtransmission/announcer.c
This change is to improve responsiveness when starting a large batch of
torrents, e.g. when starting up a seedbox, but is also generally useful.
First, try to scrape as many torrents as as quickly as possible, giving
preference to that even over announces. Thanks to multiscrape we can run
through scrapes an order of magnitude faster than announces. Then scrape
responses tell us which swarms have leechers and we can prioritize those
torrents' announces.
Second, increase how many scrapes and announces we start at a time. This
limit probably hasn't been needed since 2da97b25 and by scraping faster,
the sooner we'll know which torrents to announce first.
=> perf: prioritize announces based on scrape stats

libtransmission/handshake.c, libtransmission/peer-io.c
perf: if logs are disabled, don't build log names
No behavioral changes; just avoiding unnecessary work.
handshake.c and peer-io.c call `tr_peerIoGetAddrStr()` to build a name for passing to `tr_logAddDeepNamed()`. Since `tr_peerIoGetAddrStr()` isn't free, make sure deep logging is enabled before building the name.
In my hotspot run of running a transmission-daemon seedbox for ~2 hours, this made up about 6% of overall CPU use. No single call was very expensive; but cumulatively, they all added up. For example `tr_peerIoNew::tr_peerIoGetAddrStr` had a cumulative 1.18%, `tr_peerIoRefImpl::tr_peerIoGetAddrStr` was 0.609%, `utp_on_overhead::tr_peerIoGetAddrStr` had a cumulative 0.59%, `tr_peerIoTryWrite::tr_peerIoGetAddrStr` was 0.585%, and so on. In each case, this call was coming from the …
=> perf: do not generate address strings as log name if logging is disabled

libtransmission/announcer.c, macosx/Controller.m, macosx/Torrent.m
In `compareAnnounceTiers()`, add a safeguard to ensure that no two items compare equally.
=> fixup! perf: prioritize announces based on scrape stats (#1782)

.gitmodules, CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/crypto-utils-cyassl.c, libtransmission/crypto-utils-openssl.c, libtransmission/crypto-utils-polarssl.c, libtransmission/crypto-utils.c, libtransmission/crypto-utils.h, libtransmission/crypto.c, libtransmission/crypto.h, tests/libtransmission/crypto-test-ref.h
This frees us from expecting it being provided by one of the crypto libraries we support, all of which deprecated and/or removed it at this point.
Fixes: #1103
Fixes: #1777
=> Switch to a standalone ARC4 implementation

libtransmission/handshake.cc
The variable is being set before an unconditional assertion, which is why we get a dead-store warning when building with assertions enabled.
This PR adds an #if block so that the we assign only if assertions are disabled. That way the code will do the Right Thing whether assertions are enabled or not.
=> fix: dead store warning in handshake

libtransmission/peer-msgs.cc
Another trivial PR. Sibling to https://github.com/transmission/transmission/pull/1803.
The variable is being set before an unconditional assertion, which is why a dead-store warning is raised when building with assertions enabled.
This PR adds an #if block so that the variable is assigned only if assertions are disabled. That way the code will do the Right Thing whether assertions are enabled or not.
=> fix: dead store warning in peer-msgs.cc

extras/rpc-spec.txt
When writing code that interacted with the Transmission RPC server, I struggled to find any information regarding the authentication method used when auth is enabled on remote connections.
I found the solution with the help of Fishman in IRC, but I think it would be nice if this was documented so other people don't encounter a similar issue.
=> Add authentication information to the RPC spec

libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/torrent-magnet.h
Simple change to silence warnings, changes the offending enums to be constexprs. There is still more cleanup work to update other enums; this just addresses the ones causing compiler warnings
=> fix: 'enumerated and non-enumerated type' warnings

libtransmission/bitfield.cc, libtransmission/peer-io.cc, libtransmission/peer-mgr.cc, libtransmission/session.cc
Get libtransmission passing clang-tidy without any warnings.
There are no serious refactors in here, just silencing the warnings to set a baseline. Some of the warnings were false positives that will be better fixed with followup refactors.
=> fix: clang warnings

daemon/daemon-win32.c, libtransmission/announcer.cc, libtransmission/bandwidth.cc, libtransmission/bitfield.cc, libtransmission/fdlimit.cc, libtransmission/file-posix.cc, libtransmission/file.cc, libtransmission/inout.cc, libtransmission/makemeta.cc, libtransmission/peer-io.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/ptrarray.cc, libtransmission/quark.cc, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/subprocess-win32.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-getopt.cc, libtransmission/tr-lpd.cc, libtransmission/tr-macros.h, libtransmission/utils.cc, libtransmission/verify.cc, libtransmission/web.cc, libtransmission/webseed.cc, tests/libtransmission/copy-test.cc
- Updates C library include lines to instead include C++ wrappers
- Includes `<algorithm>` and replaces `MIN` and `MAX` macros with type safe `std::min` and `std::max`
=> C++ modernize: Replace MIN/MAX with type safe std::min/std::max

libtransmission/CMakeLists.txt
A minor followup to 4c1b6276479d177122df4ee5c9919f014c24faca, which forgot to change libtransmission/CMakeLists.txt over from C_WARNING_FLAGS to CXX_WARNING_FLAGS.
No code changes.
=> build: use CXX_WARNING_FLAGS in libtransmission

libtransmission/quark.cc, tests/libtransmission/quark-test.cc
Just something funny to do apart from all the serious stuff going on :) Helps to catch issues early, given that contributors may not run unit tests that frequently. Slightly reduced error reporting quality though: can't see the particular strings that failed the test.
=> Reimplement quarks order check as a static assert

libtransmission/rpcimpl.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/wildmat.c, tests/libtransmission/utils-test.cc, utils/remote.cc
Now returns a std::vector<int>; previously returned an array of ints that was allocated by tr_new()
=> refactor: tr_parseNumberRange returns std::vector.

libtransmission/session.cc, libtransmission/session.h
This PR replaces tr_list with std::list in tr_session's blocklists field.
=> refactor: use std::list in tr_session

libtransmission/variant-benc.cc
A minor refactor to using std:: tools instead of bespoke ones.
This PR replaces a local tr_ptrArray with a std::deque in variant-benc.cc
=> in variant-benc, use std::deque not tr_ptrArray

libtransmission/watchdir-common.h, libtransmission/watchdir-generic.cc, libtransmission/watchdir-kqueue.cc, libtransmission/watchdir.cc, tests/libtransmission/watchdir-test.cc
A minor refactor to use std:: tools instead of bespoke ones.
This PR replaces the `tr_ptrArray` field with a `std::unordered_set` in `tr_watchdir_scan()`
=> refactor: replace tr_ptrArray with std::unordered_set in tr_watchdir_scan()

libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
This PR changes `tr_torrent.labels` from being a `tr_ptrArray` to a `std::unordered_set<std::string>`.
=> refactor: use std::unordered_set for tr_torrent.labels

libtransmission/session.cc
This PR changes `loadBlocklists()` from using a `tr_ptrArray` to using a `std::unordered_set<std::string>`.
=> refactor: use std::unordered_set in loadBlocklists

libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h
This PR changes `tr_sessionGetNextQueuedTorrents()` from using a `tr_ptrArray` to using a `std::vector<tr_torrent*>`.
=> refactor: use std::vector in tr_sessionGetNextQueuedTorrents

libtransmission/announcer.cc, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h
This PR changes `tr_announcer.stops` from being a `tr_ptrArray` to a `std::set<tr_announce_request*>`.
=> refactor: use std::set in tr_announcer.stops

libtransmission/peer-mgr.cc
This PR changes `getBlockRequestPeers()` to use a `std::vector` instead of a `tr_ptrArray`.
=> refactor: use a std:: container in getBlockRequestPeers()

libtransmission/announcer.cc
This PR changes `tr_announcer.scrape_info` to be a `std::map` instead of a `tr_ptrArray`.
=> refactor: use std::map for tr_announcer.scrape_info

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc
This PR changes `tr_scrape_response.url` and `tr_scrape_response.errmsg` to be `std::string`s instead of raw `char*`s.
=> refactor: use std::string in tr_scrape_response

libtransmission/tr-getopt.cc
Use `std::string_view` in tr-getopt.cc to simplify the code and resolve some Sonarcloud read-past-end-of-memory warnings.
See the commit messages for Sonarcloud links.
=> fix: sonarcloud getopt warnings

libtransmission/torrent.cc, libtransmission/transmission.h
this field now points to `tr_torrent.errorString` instead of copying into a standalone char array.
old: sizeof(tr_torrent) 2640
new: sizeof(tr_torrent) 2136
=> refactor: make tr_info.errorString a const char*.

libtransmission/session.cc, libtransmission/session.h
These public methods weren't used anywhere except in tr_session, so make them private.
- tr_sessionGetAltSpeed_Bps()
- tr_sessionGetRawSpeed_Bps()
- tr_sessionSetAltSpeed_Bps()
- tr_sessionSetSpeedLimit_Bps()
=> refactor: make some tr_session methods private

libtransmission/variant.cc, libtransmission/variant.h
This field was assigned but never used. Shrinks sizeof(tr_variant) by 8 bytes.
=> refactor: remove unused property tr variant string.quark

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/peer-io.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/webseed.cc
This was assigned but never used. Shrinks sizeof(tr_bandwidth) by 8 bytes.
=> refactor: remove unused tr_variant_string.session

web/src/prefs.js
> If you run several Transmission web servers behind a reverse proxy at a common public domain, the explicit cookie path attribute of "/" will cause the preferences set in one web client to take effect on all other web clients at that domain. I find this behaviour counter-intuitive. I see no reason why the path should not be left at the default, in which case each web client will have a private set of preferences.
Submitted by @RobCrowston in #942, which was fine but the project didn't do anything with the patch so it fell out of sync with master. This PR is a resubmit, that resolves those conflicts, keeping Rob as author.
=> Don't set the path attribute when setting a cookie.

libtransmission/handshake.cc
A small change to avoid a buildHandshakeMessage() calculation that's unused when assertions are disabled.
=> fix: minor dead store assignment warning in buildHandshakeMessage()

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/torrent.h
Another incremental PR to update some of libtransmission to C++.
This PR makes tr_swarm a class and uses new / delete for their lifecycle.
This a relatively small PR, but it's the first step needed for other work in peer-mgr.cc because swarm needed a constructor and destructor before its fields can be updated to std:: containers.
=> refactor: make tr_swarm a class

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/webseed.cc
* Renamed `tr_bandwidth` to `Bandwidth`
* Renamed dependent structs to PascalCase and moved inside `Bandwidth`, they do not pollute global namespace anymore, but still remain in `Bandwidth`'s public section because other code refers to the fields internals.
* Moved dependent constants inside `Bandwidth`
* Renamed inner fields into `snake_case_` with trailing `_`
* Removed `struct` keyword in type names, it is unnecessary in C++.
=> Bandwidth.cc bring naming closer to C++ style of code in qt/

libtransmission/.clang-tidy, libtransmission/session.cc, libtransmission/tr-lpd.cc
=> build: have clang-tidy check for NULL in libtransmission

libtransmission/crypto-utils-cyassl.cc
wolfSSL's fastmath support requires options.h to be included before
anything else. Otherwise bad codepaths get taken and a crash occurs
during DH initialization.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> fix runtime with wolfSSL and fastmath

libtransmission/tr-assert.cc, libtransmission/tr-assert.h, libtransmission/tr-macros.h
Another PR to replace some custom code with built-in C++ code. This time, replace `TR_NORETURN` with the `[[noreturn]]` attribute.
=> refactor: use C++'s [[noreturn]] atrribute

libtransmission/.clang-tidy, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/blocklist.cc, libtransmission/cache.cc, libtransmission/clients.cc, libtransmission/crypto-utils.cc, libtransmission/crypto.cc, libtransmission/handshake.cc, libtransmission/log.cc, libtransmission/magnet.cc, libtransmission/metainfo.cc, libtransmission/natpmp.cc, libtransmission/net.cc, libtransmission/platform-quota.cc, libtransmission/session-id.cc, libtransmission/subprocess-posix.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent-magnet.cc, libtransmission/tr-assert.cc, libtransmission/tr-udp.cc, libtransmission/tr-utp.cc, libtransmission/trevent.cc, libtransmission/upnp.cc, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, libtransmission/variant.cc, libtransmission/watchdir-generic.cc, libtransmission/watchdir-inotify.cc, libtransmission/watchdir.cc
Another incremental libtransmission C++ification PR.
This PR changes code that includes deprecated headers to including the non-deprecated versions.
=> refactor: clang-tidy --fix modernize-deprecated-headers

libtransmission/.clang-tidy, libtransmission/file-posix.cc, libtransmission/subprocess-posix.cc, libtransmission/utils.cc, libtransmission/webseed.cc
Barely a PR at all, since the net change was to add three `NOLINT` to disable pointer-to-int conversion when using POSIX-defined values, and one `const` removal to allow for move-return-value.
But still, the goal of these iterative .clang-tidy changes is to add helpful warnings on future code, so: this PR adds `performance-*` to the libtransmission clang-tidy checks.
=> refactor: add performance-* to libt .clang-tidy

qt/.clang-tidy, tests/libtransmission/.clang-tidy
No code changes, just fixing FTBFS when upgrading to clang 13 / clang-tidy 13.
Also, remove 'WarningsAsErrors' from tests/libtransmission/.clang-tidy since newly-introduced clang-tidy checks cause FTBFS on Ubuntu 21.10
=> build: silence new clang-tidy 13 warnings

libtransmission/quark.cc
Missed a sv literal in #1961. HT @reardonia from https://github.com/transmission/transmission/pull/1961#issuecomment-945178281
=> refactor: fixup! tr_quark_new() now takes a std::string_view (#1961)

libtransmission/rpcimpl.cc
fix: unused variable warning in free-space code introduced in 04f8b823
=> fixup! Add total disk space to free-space RPC request (#1682)

libtransmission/.clang-tidy, libtransmission/completion.cc, libtransmission/magnet.cc, libtransmission/session.cc
part 6 of a series of PRs that applies clang-tidy's `cppcoreguidelines-init-variables` to libtransmission:
- move uninitialized variables to be declared as close as possible to where they are used
- prefer const
- prefer auto
This PR reduces the number of `cppcoreguidelines-init-variables` warnings to **443**
Previous part: #1970
=> refactor: cppcoreguidelines-init-variables pt. 6

macosx/da.lproj/Creator.xib, macosx/de.lproj/Creator.xib, macosx/en.lproj/Creator.xib, macosx/es.lproj/Creator.xib, macosx/fr.lproj/Creator.xib, macosx/it.lproj/Creator.xib, macosx/nl.lproj/Creator.xib, macosx/pt_PT.lproj/Creator.xib, macosx/ru.lproj/Creator.xib, macosx/ru.lproj/PrefsWindow.xib, macosx/tr.lproj/Creator.xib
- The inscription (Source:) needs to be moved to the right for vertical symmetry with the other inscriptions.
Before:
After the fix:
---
- At the moment, there is no word, (Source:) and input box in all localizations except English. This function is not available in other localizations, as the developer did not do this. If there is no translated word in the localization, it should be a word in English. At the moment, this is not the case. Please pay attention to this: the lack of an input box.
Before:
After the added:
_And also localized the word (Source:), in German and Russian as I know them._
- Creator (Spanish)
- Creator (Italian)
- Creator (French)
- Creator (Dutch)
- Creator (Turkish)
- Creator (Danish)
- Creator (Portugal)
- Creator (German)
- Creator (Russian)
---
- And also …
=> Fix & Added: Add support for creating torrents with a source flag #443

macosx/Controller.mm
Possible fix for the recent 236a0965 regression reported by @Oleg-Chashko.
I have no way to test locally to see if this even compiles, so I'm standing on the shoulders of the CI boxen here :sweat_smile:
=> fixup! refactor: tr_variant*Str() functions now take a std::string_view

libtransmission/peer-msgs.cc, libtransmission/torrent-magnet.cc, libtransmission/tr-getopt.cc
part 9 of a series of PRs that applies clang-tidy's `cppcoreguidelines-init-variables` to libtransmission:
- move uninitialized variables to be declared as close as possible to where they are used
- prefer const
- prefer auto
This PR reduces the number of `cppcoreguidelines-init-variables` warnings to **270**
Previous part: #1993
=> refactor: cppcoreguidelines-init-variables pt. 9

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-macros.h, tests/libtransmission/session-test.cc
- Add a `tr_peer_id_t` using/typedef which is a `std::array<char, 20>`. This can be used to pass around peer-ids and manipulate them without using `memcmp`, `memcpy`, and `PEER_ID_LEN`.
- Remove now-unused global `PEER_ID_LEN`.
- This has some minor side-effects in handshake and peer-io: `tr_peerIo.peerId` and `tr_peerIo.isEncrypted` have been removed.
=> refactor: add tr_peer_id_t

libtransmission/completion.cc, libtransmission/inout.cc, libtransmission/metainfo.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-macros.h, libtransmission/transmission.h, libtransmission/verify.cc, qt/OptionsDialog.cc
Fixes #2056.
tl;dr: in my permaseed testbed (~19,000 torrents) this cut 500 MB off of steady-state memory use
---
Even though the struct is only 32 bytes, it takes up the vast majority of memory allocation in a transmission-daemon session because there's one allocated for every piece in every torrent, so every byte get multiplied by a large factor.
This PR removes the `tr_piece` struct and replaces it with:
1. An array of sha1 digests, the checksum for each piece. (20 bytes per piece)
2. A per-torrent bitfield of do-not-download flags. When there are no flags marked as 'do not download', the bitfield is empty and only uses a few bytes per torrent.
3. An unordered_hash of piece priorities. This is more expensive than a bitfield, but it's only used while downloading and is cleared out after …
=> refactor: remove tr_piece struct

libtransmission/file-posix.cc, libtransmission/handshake.cc, libtransmission/platform-quota.cc, libtransmission/subprocess-posix.cc
part 15 of a series of PRs that applies clang-tidy's `cppcoreguidelines-init-variables` to libtransmission:
- move uninitialized variables to be declared as close as possible to where they are used
- prefer const
- prefer auto
This PR reduces the number of `cppcoreguidelines-init-variables` warnings to **10**
Previous part: #2043
=> refactor: cppcoreguidelines-init-variables pt. 15

libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc
Before this PR, it was a tr_variant for the sole reason that it was easier to use a tr_variant than roll a new data struct for this in C.
=> refactor: use a std::vector for tr_session.removed_torrents

libtransmission/torrent.cc
A small little perf improvement to `tr_torrentPrimaryMimeType()`: remove an unnecessary std::map.
=> perf: omit extra std::map in tr_torrentPrimaryMimeType()

macosx/VDKQueue/VDKQueue.m
Fix warning `Method override for the designated
initializer of the superclass '-init' not found`
with `NS_UNAVAILABLE` marker.
=> Fix clang warning in VDKQueue.m

libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
Add a version of `tr_urlParse()` that doesn't require any heap allocations
=> refactor: tr_urlParse()

qt/FaviconCache.cc
Can't take name.at(0) when name is empty...
=> fix: crash in capitalizing trackername when no trackername

libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
Add a new utility, `tr_strvstrip()` which is a string_view version of `tr_strstrip()` to strip the leading and trailing spaces from a string.
=> refactor: add util tr_strvstrip() to strip string_views

libtransmission/variant.cc, libtransmission/variant.h, tests/libtransmission/variant-test.cc
This is similar to the prior sibling function `tr_variantGetStr(variant*, char const** setme_str, size_t* setme_len)` but puts the string into a std::string_view instead of taking separate string and len arguments.
=> feat: new function tr_variantGetStrView()

libtransmission/.clang-tidy, libtransmission/blocklist.cc
part 16 -- the final part -- of a series of PRs that applies clang-tidy's cppcoreguidelines-init-variables to libtransmission:
move uninitialized variables to be declared as close as possible to where they are used
prefer const
prefer auto
This PR reduces the number of cppcoreguidelines-init-variables warnings to **0**
Previous part: #2055
=> refactor: cppcoreguidelines-init-variables pt. 16

libtransmission/torrent-ctor.cc, tests/libtransmission/metainfo-test.cc
C++ify the internals of the `tr_ctor` object. Leaves the public API  untouched.
As a side-effect, this change has a small perf win in that batch-loading torrents on startup will allocate a string to hold the torrent's source file once per batch instead of once per torrent.
=> refactor: c++ify torrent ctor

libtransmission/resume.cc, libtransmission/torrent.cc
Move piece priority initialization to later in torrent construction so that we can correctly test whether the torrent is done or not.
The reason for this is because file/piece priorities are discarded iff the torrent is already done.
=> fix: another piece priority fix

libtransmission/variant.cc
We walk a _lot_ of variant trees in Transmission -- parsing scrape results, loading .torrent files, loading .resume files, saving .resume files, parsing dht results, and so on.
This PR attempts to recycle the variant-walking helper objects by introducing a private `VariantWalker` class that encapsulates the recycling process.
Testing an 18k torrent testbed that with just starting + closing transmission-daemon, this saves about 1.4 million heap allocations.
=> perf: recycle variant tree walking helpers

README.md
MacStadium asks to "put the MacStadium Open Source Developer logo on your landing page (either your GitHub page or website)". We're using Mac Mini M1 they provide for CI builds.
SignPath asks that "a code signing policy must be specified on the project’s home page". We're using the certificate provided by SignPath Foundation and the service provided by SignPath.io to sign release builds on Windows. The policy mention is already in place and the logo is not strictly necessary, but I value their support in this area and want to link back more prominently.
=> Add MacStadum and SignPath sponsor links to readme

libtransmission/torrent-ctor.cc
handle nullptrs in the accessor functions.
The changes in #2098 a few days ago introduced a regression on this, since the GTK client passes in nullptrs when it just wants to check whether or not an option is set, not to get its value
=> fixup! refactor: c++ify torrent ctor (#2098)

tests/libtransmission/json-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/variant-test.cc, tests/libtransmission/watchdir-test.cc
Prefer `tr_variantDictFindStrView()` to `tr_variantDictFindStr()` in tests
=> refactor: prefer tr_variantDictFindStrView() in tests

gtk/transmission.gresource.xml
There is a fallback mechanism in GTK: when looking for an icon named foo-a-b-c, it'll also try to find foo-a-b, foo-a, and foo, so the only icon necessary (if all of them default to the same one) is foo. Given that we're also installing this icon, including it in resources doesn't make a lot of sense, by I'm leaving it just in case anyway (useful when debugging without installing).
=> Include GTK client icon in resources once

Transmission.xcodeproj/project.pbxproj
=> Fix building with Xcode 13.1 and macOS 12.0 SDK.

libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/session-test.cc
Add getters / setters for tr_session scripts, making the property values private fields.
Add tests for the related C++ and C API.
=> refactor: tr_session.scripts

gtk/FilterBar.cc
Total count was correct, but per-tracker counts were 1 more than in reality.
=> Fix torrent counts in tracker filter bar combo (GTK client)

libtransmission/torrent.h
fix: off-by-one when marking a range of pieces as untested
=> fixup! refactor: remove tr_piece struct (#2059)

gtk/CMakeLists.txt
These were introduced during the gtkmm update.
=> build: disable exit-time-destructor warnings in GTK client

utils/remote.cc
=> refactor: remove tr_variantDictFindStr() from transmission remote

gtk/Prefs.cc
=> refactor: remove tr_variantDictFindstr() from transmission-gtk

libtransmission/utils.h
fix: -Wshadow warning in tr_strvPath()
=> fixup! feat: add tr_strvPath() (#2134)

libtransmission/rpc-server.cc
=> refactor: remove tr_variantDictFindStr() from rpc-server.cc

gtk/Prefs.cc, libtransmission/variant.cc, libtransmission/variant.h, qt/TorrentModel.cc, qt/VariantHelpers.h, tests/libtransmission/rpc-test.cc
=> refactor: remove tr_variantGetStr()

gtk/FilterBar.cc
For non-C locales, empty string is translated into a multi-line text containing descriptive translation headers, which then affects cell size (and in turn, combo widget size) even though that cell is considered a separator.
=> Fix activity filter combo size (GTK client)

libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h
Add a member version of tr_torrentSetLocation(). This member version takes a std::string_view.
=> refactor: tr_torrent.setLocation

libtransmission/announcer-http.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/rpcimpl.cc, libtransmission/session.cc
Still chipping away at the last use cases for `tr_variantDictFindStr()` so that it can be removed.
=> refactor: tr_address_from_string() is now std::string_view-friendly

libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/torrent.h
Nearing the end of the march toward removing `tr_variantDictFindStr()`
=> refactor: add tr_torrent::renamePath()

cli/cli.cc
Just renaming the variable to prevent the -Wshadow warning.
=> refactor: fix a -Wshadow warning for a variable named optarg

libtransmission/announcer.cc, libtransmission/utils.cc, tests/libtransmission/rename-test.cc
no behavioral changes; just doing some cleanup.
- use 'if constexpr' to fix a conditional-value-known-at-compile-time C4127 warning
- break assignment/conditional statements into two separate statements to silence C4706 assignment-within-conditional warning
- fix int-implicitly-widened-to-uint64 warning in tests
=> refactor: fix some msvc compiler warnings

libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/web.cc
Fix a couple of warts that were making a tr_session shutdown slower than it needed to be:
- Don't let tr_torrentLoadResume() affect a torrent's 'torrent settings are dirty & need to be saved' flag.
- When a torrent is removed from a session, _usually_ we want to re-sequence all the other torrents' queue positions. Don't do this during shutdown because it can be expensive and those changes are all irrelevant during shutdown.
=> perf: faster shutdown

libtransmission/metainfo.cc, libtransmission/metainfo.h, libtransmission/resume.cc
A simpler API for building .torrent and .resume filenames.
Possibly a slight perf improvement in requiring fewer heap allocations for string temporaries, but mostly to simplify some slightly convoluted code.
=> refactor: add tr_buildTorrentFilename()

libtransmission/bandwidth.cc, libtransmission/bandwidth.h
These items don't get added / removed very often but the tree gets walked very frequently, so it's overall cheaper to use a std::vector and just use `std::find()` for those cases where we do need to remove.
=> refactor: make Bandwidth.children a std::vector

cli/transmission-cli.1, gtk/transmission-gtk.1, qt/transmission-qt.1
they were quite distracting
most of them seem to occur in options that take arguments
but that's not consistently so, so i removed them all
=> man pages: remove commas in option listings

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/block-info.cc, libtransmission/block-info.h, libtransmission/cache.cc, libtransmission/completion.cc, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc, libtransmission/webseed.cc, tests/libtransmission/CMakeLists.txt, tests/libtransmission/block-info-test.cc, tests/libtransmission/move-test.cc
Another attempt to break off some pieces of tr_torrent / tr_info into decoupled & tested pieces. This PR adds block-info, which handles converting between pieces / blocks / bytes.
This leads into a tr_completion refactor which is next in the queue.
=> refactor: tr_block_info class

libtransmission/trevent.cc
Fix a memory management issue introduced last week in #2194.
=> fixup! refactor: use std mutex/lock intead of bespoke (#2194)

libtransmission/subprocess-posix.cc, libtransmission/subprocess-win32.cc, libtransmission/subprocess.h, libtransmission/torrent.cc, tests/libtransmission/subprocess-test.cc
Fixed by using `setenv()` instead of `putenv()` so that we don't have to keep the strings around after `tr_spawn_async()` returns.
Fixes #1384.
=> fix: env var leak in tr_spawn_async()

libtransmission/cache.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h
When adding a magnet torrent's newly-fetched metainfo, ensure that the piece checksums are initialized.
This is Yet Another Fixup of d1f8c28 from #2130. :3rd_place_medal:
=> fixup: crash after completing magnet link metainfo

gtk/MessageLogWindow.cc
Currently it's hardcoded to black text for normal lines (non-error, non-debug info)
We probably shouldn't hardcode _any_ of these colors but at a minimum we should not hardcode the default text because it's nearly unreadable in dark mode.
=> fix: GTK client's log window should honor dark mode

libtransmission/tr-dht.cc
This bug is present in 3.00 as well but I hadn't experienced before the recent regression introduced a corrupt dht.dat file to my system.
Re-use of the local variable `len` in `tr_dhtInit()` could cause the data passed to `dht_bootstrap()` to indicate that there were > 0 nodes available even when the nodes array was nullptr.
=> fix: crash on corrupt dht.dat file

qt/FileTreeModel.cc
Also present in 3.00, not just a recent regression.
This one's been bothering me for a long time; happy to finally have tracked this down.
Fixes #1764.
=> fix: crash when renaming top-level folder in qt

gtk/Application.cc
This makes URLs closer to files in terms of convenience, since both can now be dropped onto the main window without the user having to open a Open/Open URL dialog.
Unlike files, which come as a URI list, links dragged from browsers have textual selection types:
- Firefox: `text/plain;charset=utf-8`
- Chrome: `UTF8_STRING`
If the URI list for files is empty, try to pass the selection text to `add_from_url()`.
=> gtk: accept dropping URLs from browsers onto the main window

macosx/main.mm
Fixes #2219
Not changing the logic of the code (which means that `-v` is treated as `-v0`, which is probably surprising to users). But fixing the use-after-free issue.
=> Mac client uses freed memory

gtk/FileList.cc, gtk/FilterBar.cc, gtk/Notify.cc, gtk/Session.cc, gtk/TorrentCellRenderer.cc, libtransmission/inout.cc, libtransmission/metainfo.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/verify.cc, libtransmission/webseed.cc, macosx/Torrent.mm, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc
Breaking tr_torrent into smaller, testable pieces is made more difficult by the way we've (I've) mixed public and implementation fields into tr_info. This is an interim PR that moves some fields into a 'priv' struct. This isn't the end goal; the tradeoff here is that I want to keep these PRs reasonably small and focused.
=> refactor: make parts of tr file private

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/completion.cc, libtransmission/completion.h, libtransmission/file-piece-map.cc, libtransmission/file-piece-map.h, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/quark.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, tests/libtransmission/CMakeLists.txt, tests/libtransmission/completion-test.cc, tests/libtransmission/file-piece-map-test.cc
Add small classes that handle mapping files to pieces.
This decouples the file wanted/priority tracking features from the rest of tr_torrent and makes them easier to test.
=> refactor: add file-piece-map

libtransmission/resume.cc
the scope of the buf variable was narrowed too far.
=> fixup! fix: sonarcloud warnings (#2260)

libtransmission/utils.cc
silence a nullptr-dereference warning.
=> fixup! refactor: use cpputf for utf8 validation and conversion (#2251)

cli/cli.cc, gtk/Session.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.cc, tests/libtransmission/metainfo-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/utils-test.cc
This lays groundwork for the upcoming metainfo refactor:
- add `tr_saveFile()`, whose implementation is extracted from `tr_variantToFile()`.
- add new tests for `tr_saveFile()`
- finish the extract-method step by reimplementing `tr_variantToFile()` as a wrapper around `tr_saveFiile()`
And then  use it:
- add `tr_ctorSaveContents()`, which saves the constructor's metainfo to a file.
- add new tests for `tr_ctorSaveContents()`
- use `tr_ctorSaveContents()` in `torrentInit()`
Why? Because `torrentInit()` previously serialized ctor's variant to save the contents, but the upcoming metainfo refactor no longer exposes a variant. To reduce the size & complexity of the metainfo refactor, this piece is being PR'ed as a standalone refactor.
=> refactor: add tr_saveFile()

libtransmission/inout.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/webseed.cc
Provide an accessor to get a torrent's file count.
This is an incremental step towards making tr_torrent's impl private.
=> refactor: add tr_torrent::fileCount()

libtransmission/inout.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/verify.cc, libtransmission/webseed.cc
A sibling to https://github.com/transmission/transmission/pull/2273, this PR provides an accessor to a torrent's file structures.
This is another incremental step towards making tr_torrent's impl private.
=> refactor: add tr_torrent::file()

libtransmission/metainfo.cc, libtransmission/transmission.h
Remove a previously assigned-to-but-never-read-from field tr_info.originalName
=> refactor: remove assigned-but-unused tr_info.originalName

libtransmission/peer-msgs.cc
Should fix https://github.com/transmission/transmission/issues/511. I'm not sure how to run the test suite for this.
=> Reject cancels when fast extension enabled

gtk/FileList.cc, libtransmission/resume.cc
fix: crash regression in GTK client details dialog
=> fixup! refactor: make parts of tr file private (#2241)

gtk/DetailsDialog.cc, gtk/FilterBar.cc, gtk/Session.cc, gtk/TorrentCellRenderer.cc, libtransmission/announcer.cc, libtransmission/announcer.h, libtransmission/file-piece-map.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, macosx/Torrent.mm, macosx/TrackerNode.h, macosx/TrackerNode.mm
Replace `tr_torrentTrackers()`  and `tr_torrentTrackersFree()` with `tr_torrentTracker()`, a view accessor similar to `tr_torrentFile()` and `tr_torrentWebseed()`.
=> refactor: add tr_torrentTrackers()

qt/DetailsDialog.cc, qt/DetailsDialog.h, qt/FilterBar.cc, qt/IconCache.cc, qt/IconCache.h, qt/MainWindow.cc, qt/MainWindow.h, qt/TorrentDelegate.cc
Look for RTL and symbolic icon variants for each icon that we load. The only exception here is Transmission's own icons, where it doesn't make sense (the way I see it).
=> Adjust theme icons lookup logic to resemble that of GTK (Qt client)

libtransmission/torrent.cc, utils/remote.cc
Sibling to the fix in #2212. I found the same non-portable fmt string in two other places.
=> fix: non-portable strftime() fmt string

utils/remote.cc
simple patch allowing multiple declaration in transmission-remote
passing several --tracker-add will result in extending list
passed to the transmission-deamon by each subsequent call
=> multiple tracker-add

macosx/Images/Images.xcassets/Accent Color.colorset/Contents.json
Proposed fix for #2205 
macOS has a red-ish choice for accent color built into the system, and here are the colors it uses:
- light UI: rgb 206 - 71 - 69
- dark UI: rgb 236 - 95 - 93
=> Change accent color to match macOS red choice

libtransmission/quark.cc, qt/AboutDialog.cc
No functional changes; just changing the text a little bit.
The motivation here is the word "remote" referring to the remote server could be confusing since in transmission-remote, the word 'remote' refers to the client.
The new text uses 'client' / 'server' terminology
=> refactor: tweak qt client about dialog text

macosx/InfoWindow.xib, macosx/InfoWindowController.mm
`square.grid.3x3.fill.square` is deprecated name for `square.grid.3x3.square`.
The former is available on macOS 11.0+, while the latter is for macOS 12.0+.
They are the same visually.
Fixes this report https://github.com/transmission/transmission/pull/2269#issuecomment-991980368
=> [macOS] Use old icon name for Square Grid to support older macOS

libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc
Changing some libtransmission-visible functions from `tr_torrentFoo()` to `tr_torrent::foo()`
=> refactor: make some tr_torrentFoo() methods member functions

libtransmission/announcer.cc, libtransmission/completion.h, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-lpd.cc, libtransmission/verify.cc, libtransmission/webseed.cc, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h
More prepwork for replacing tr_info. This PR adds accessor methods to tr_torrent so that the aggregated struct doesn't have to be referred to directly.
For example:
```diff
- tor->info.totalSize()
+ tor->totalSize()
```
=> refactor: add tr_info accessors to tr_torrent

libtransmission/announcer-udp.cc, libtransmission/metainfo.cc, libtransmission/platform.cc, libtransmission/quark.cc, libtransmission/torrent.cc, libtransmission/utils.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h
Similar to the previous refactor -- prefer memory-managed `tr_strv*()` methods over the raw C pointer functions e.g. `tr_strdup_printf()`
=> refactor: more prefer tr_strv*()

libtransmission/announcer.cc, libtransmission/error.cc, libtransmission/metainfo.cc, libtransmission/metainfo.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc, libtransmission/webseed.cc
Migrate more tr_torrent use to new accessor methods. This has a dual goal:
- reduce the number of references to the `tr_info` data structure to make it easier to refactor
- reduce the number of C-style accessors, e.g. migrating `tr_torrentGetFoo()` to `tor->foo()`
=> refactor: tr_torrent housekeeping

libtransmission/file-piece-map.cc, libtransmission/file-piece-map.h, libtransmission/inout.cc, libtransmission/inout.h, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/webseed.cc, tests/libtransmission/file-piece-map-test.cc
This is a relatively small change to reduce dependency on `tr_info.file` and its `priv.offset` field, since that's going away in the metainfo refactor. This change could be folded into the larger metainfo refactor PR, but doing it here as a standalone makes for simpler / more focused PRs.
Since we already have file-piece-map, migrating tr_ioFindFileLocation() to that class is relatively easy. Better yet, we can use file-piece-map's existing test code to add tests while migrating the feature.
=> refactor: move tr_ioFindFileLocation() to tr_file_piece_manager

libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/platform.cc, libtransmission/resume.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.h, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.cc, libtransmission/variant.h
Change the filename argument type in `tr_loadFile()` and `tr_saveFile()` from a `char const*` to a `std::string_view` so those functions can more easily service both c strings and std::strings
=> refactor: take string_view in tr_loadFile(), tr_saveFile()

libtransmission/announcer.cc, libtransmission/handshake.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, tests/libtransmission/rename-test.cc
The `tr_info` struct is going away, but `tr_torrent` currently aggregates it.
Loosen coupling between the two by adding accessor methods to `tr_torrent`. Client code can call the accessors instead of using `tor->info` directly, making it easier to swap `tr_info` out with replacement code.
=> refactor: further decouple tr_torrent and tr_info

cli/cli.cc, daemon/daemon.cc, gtk/OptionsDialog.cc, gtk/Session.cc, gtk/Utils.cc, gtk/Utils.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/transmission.h, macosx/Torrent.mm, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h
If the torrent couldn't be created because it's a duplicate, provide a way to get the pointer to the original torrent.
=> refactor: change tr torrent new() args

libtransmission/announcer.cc, libtransmission/interned-string.h, qt/IconCache.cc, utils/remote.cc
fix a pair of exit-time-dtor warnings in the Qt client and transmission-remote.
=> fix: exit time dtor warnings

libtransmission/block-info.h, libtransmission/magnet-metainfo.h, utils/show.cc
Replace `tr_info` with `tr_torrent_metainfo` in the `transmission-show` utility.
=> refactor: use tr_torrent_metainfo in transmission-show

qt/AddData.cc, qt/OptionsDialog.cc, qt/OptionsDialog.h, qt/Torrent.h, qt/WatchDir.cc
Replace `tr_info` with `tr_torrent_metainfo` in the `transmission-qt` app.
=> refactor: use tr_torrent_metainfo in transmission-qt

libtransmission/torrent.cc, libtransmission/transmission.h, macosx/Controller.mm, macosx/DragOverlayWindow.mm, macosx/QuickLookPlugin/GeneratePreviewForURL.mm
Replace `tr_info` with `tr_torrent_metainfo` in the macOS app.
=> refactor: use tr_torrent_metainfo in mac client

tests/libtransmission/makemeta-test.cc
Replace `tr_info` with `tr_torrent_metainfo` in the makemeta tests.
=> refactor: use tr_torrent_metainfo in makemeta tests

cli/cli.cc, daemon/daemon.cc, gtk/MakeDialog.cc, gtk/OptionsDialog.cc, gtk/Session.cc, libtransmission/metainfo.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, macosx/Torrent.mm, tests/libtransmission/metainfo-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/torrent-metainfo-test.cc
Getting a little closer to the end of the `tr_torrent_metainfo` arc.
This step uses `tr_torrent_metainfo` in `tr_ctor`, updating the `tr_ctorSetMetainfo*()` functions to return a success bool and take a `tr_error**` pointer, same as benc/json parsing, `tr_loadFile()`, and `tr_torrent_metainfo::parse*()` all do.
A side-effect of this is that `tr_torrentParse()` is no longer used, so it's been removed.
Note that this PR also introduces a small amount of interim code: adding a torrent now requires double-parsing, one through `tr_torrent_metainfo.parse*()` in the `tr_ctorSetMetainfo*()` functions, then a second time in `tr_torrentNew()` when metainfo.cc is used to parse a `tr_info`. This will be resolved in a followup PR by removing `tr_info` -- that step is omitted here in an effort to keep …
=> refactor: use tr_torrent_metainfo in tr ctor

libtransmission/completion.cc, libtransmission/completion.h, libtransmission/file-piece-map.h, libtransmission/torrent.cc, libtransmission/transmission.h, tests/libtransmission/completion-test.cc
A quick side-trip in the `tr_metainfo` refactor to continue hollowing out `tr_info` before its removal.
This PR removes `tr_file.priv.offset` and adds a public `tr_completion.getHasBytesInSpan()` function that works on a span of bytes rather than a span of blocks. Tests are added for `tr_completion.getHasBytesInSpan()`.
=> refactor: remove tr_file.offset

daemon/daemon.cc, gtk/Application.cc, libtransmission/announce-list.cc, libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/file.cc, libtransmission/file.h, libtransmission/log.cc, libtransmission/metainfo.cc, libtransmission/peer-msgs.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent-metainfo.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.cc, libtransmission/variant.h, qt/RpcClient.cc, tests/libtransmission/json-test.cc, tests/libtransmission/variant-test.cc, utils/remote.cc
`tr_variantToStr()` now returns a `std::string`. Previously it was a C-style function that returned a `char*` and the length was obtained by passing in a pointer to a `size_t`.
=> refactor: use std::string in tr_variantToStr()

libtransmission/inout.cc, libtransmission/resume.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, libtransmission/verify.cc, libtransmission/webseed.cc
yes, another incremental PR on the replace-`tr_info`-with-`tr_torrent_metainfo` chain.
This step avoids directly referring to the `tr_file` struct aggregated by `tr_info` to reduce code shear when we make the jump.
=> refactor: avoid referencing tr_file struct directly

libtransmission/platform.cc, libtransmission/platform.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/web.cc, tests/libtransmission/utils-test.cc, utils/create.cc
`tr_buildPath()` is only used in platform.cc, so make it visible only to that file.
=> refactor: make tr_buildPath() private

libtransmission/completion.cc
Fix integer overflow when calculating `sizeWhenDone`.
While the function correctly returns a `uint64_t`, internally a `size_t` variable is used to calculate the accumulated size.
On 32-bit systems (e.g. Raspbian) `size_t` is only 32-bit wide, causing overflow for torrents > 4GB.
On my Raspberry Pi 4 running Raspberry Pi OS 'Buster', this bug caused strange behavior with torrents > 4GB:
* Torrents were shown as complete after downloading the first 4GB (while downloading the rest continued)
* Re-adding the torrent after everything was downloaded showed a "Done" percentage > 100%
* `transmission-remote -t<id> -i` showed this after adding a torrent > 4GB (but not starting it):
```
1100101@raspi2:~$ transmission-remote -t8 -i
NAME
Id: 8
Name: xxxx
Hash: xxx
Magnet: xxx
TRANSFER
State: Stopped …
```
=> Fix integer overflow when calculating `sizeWhenDone`

libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, qt/AddData.cc, tests/libtransmission/crypto-test-ref.h, tests/libtransmission/crypto-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h, utils/remote.cc
Update `tr_base64_encode()` and `tr_base64_decode()` to use C++ memory-managed API
=> refactor: base64 utils

libtransmission/metainfo.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-lpd.cc, libtransmission/transmission.h, libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/announce-list-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/utils-test.cc
Another incremental PR to reduce shear between the master (`tr_info`) branch and the `tr_torrent_metainfo` branch.
=> refactor: use std::string in tr_info

libtransmission/magnet-metainfo.cc, libtransmission/magnet-metainfo.h, libtransmission/metainfo.cc, libtransmission/metainfo.h, libtransmission/resume.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent.cc
`tr_metainfo` is going away, but its function `tr_buildTorrentFilename()` will live on, so migrate that function to another part of libtransmission.
=> refactor: migrate makeFilename() to tr_magnet_metainfo

libtransmission/announcer.h, libtransmission/file-piece-map.cc, libtransmission/magnet-metainfo.cc, libtransmission/magnet-metainfo.h, libtransmission/metainfo.cc, libtransmission/peer-common.h, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, macosx/QuickLookPlugin/GeneratePreviewForURL.mm, tests/libtransmission/magnet-metainfo-test.cc, utils/show.cc
Reduce code shear between master (`tr_info`) and `tr_torrent_metainfo` branches.
=> refactor: use std::vector in tr_info

libtransmission/variant-benc.cc, tests/libtransmission/variant-test.cc
Work on magnet / metainfo is still chugging along, but I hit this unrelated benc parsing error today so this PR adds a fix and regression test.
=> fix: potential infinite loop when parsing benc

gtk/DetailsDialog.cc
=> fix: broken tooltiop in GTK client peer flag tooltip

libtransmission/clients.cc, tests/libtransmission/clients-test.cc
=> fix: parse utorrent peer-id version components as hex

libtransmission/torrent.cc, libtransmission/transmission.h, libtransmission/utils.h, macosx/NSStringAdditions.mm
fix: calculate seedratio by torrent size
Fixes #276.
Previously was calculated by number of bytes downloaded, which caused edge cases when those two numbers were not the same, e.g. if the user already had part of the torrent from another source and only downloaded a small part. When this happened, the ratio could be very large and use of seedratio would behave in a way that most people would not expect.
Note, the old behavior has been around for a VERY LONG TIME. Even though this is a bugfix, it does change semantics. I don't think there is any third-party code that depends on the old behavior but this is arguably a breaking change.
=> fix: calculate seed ratio by torrent size.

libtransmission/resume.cc, libtransmission/resume.h, libtransmission/torrent-magnet.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h
Fixes #2430.
When removing a torrent, try to remove config filenames under both old and new filename formats. This prevents torrents from being incorrectly re-added when old-format files aren't removed.
=> fix: torrents re-added due to unremoved cfg files

gtk/OptionsDialog.cc, gtk/PrefsDialog.cc, gtk/transmission-ui.xml
This solves the issue of the dialogs not centering above the main GTK client window.
Fixes #2214.
=> fix: make add-torrent dialogs modal in GTK client

libtransmission/variant-json.cc
Fixes a follow-up issue reported in https://github.com/transmission/transmission/issues/2106#issuecomment-1015797781
=> fix: explicitly use unsigned char when checking isprint()

libtransmission/net.cc, libtransmission/tr-udp.cc
fix unused variable warning from the previous commit.
=> fixup: unused variable warnings

libtransmission/torrent.cc
This prevents accidentally following a symlink that points outside of
the torrent's folder and crawling the rest of the drive for junk files
to remove.
This also prevents symlinks that point to a folder from being treated as
real directories, which would cause them to be removed even if the folder
they point to is not actually empty.
Both issues are especially bad when combined: a symlink to / inside the
torrent folder caused transmission to crawl the entire drive and delete
every single folder symlink it could find. Oops.
=> fix: don't follow symlinks when removing junk files

libtransmission/torrent.cc
make the CI code-style bot happy
=> fixup! fix: don't follow symlinks when removing junk files (#1638)

libtransmission/natpmp.cc, libtransmission/natpmp_local.h, libtransmission/port-forwarding.cc, libtransmission/session.cc
Hello,
I wrote this little patch to fix NAT-PMP behavior on my VPN. There were two issues :
- The default hard-coded lifetime on transmission of a nat-pmp entry is 20 min. This create an issue if the NAT-PMP service offers a lifetime which is less than that. I patched the code to reflect the lifetime from the nat-pmp messages and trigger a periodic update from transmission reflecting that time.
- There was a bug in the private-port/public port values, which prevented the "Test Port" RPC to work .
=> NAT-PMP private/public port and lifetime fix

libtransmission/quark.cc, libtransmission/quark.h, qt/MainWindow.cc, qt/MainWindow.h, qt/Prefs.cc, qt/Prefs.h, qt/PrefsDialog.cc, qt/PrefsDialog.ui
This PR aims to implement #1515 for the Qt frontend
When the window is focused, if the user has opted in to the functionality in the preferences, the clipboard will be searched for URLs.
(FYI: This has been implemented as part of a university course)
=> Add the option of automatically picking up URLs from the clipboard on window focus

libtransmission/port-forwarding.cc
ensure the value passed to tr_timerAdd() is non-negative.
Possibly fixes #2479
=> fixup! NAT-PMP private/public port and lifetime fix (#1602)

tests/libtransmission/magnet-metainfo-test.cc
The bug reported in #1113 was fixed as part of the `tr_info` -> `tr_torrent_metainfo` refactor but did not add any regression tests for the cases described in 1113.
https://github.com/transmission/transmission/pull/1290 _did_ add tests but is out-of-date with the codebase due to the refactor.
This PR updates those tests to the new API and marks 1290 author @clickyotomy as the author of this PR to ensure they get credit.
Fixes #1113.
=> test: magnet links with junk values

libtransmission/quark.cc
Slight refactor to libt/quark's static asserts so that the codebase formats the same between clang-format 12, 13, and 14.
=> refactor: quark's static_assert formatting

extras/libtransmission-valgrind.supp, libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, tests/libtransmission/CMakeLists.txt, tests/libtransmission/announcer-test.cc
some prepwork before swapping in new benc parsing code: test coverage for the announcer module's handling of bencoded announce responses.
=> refactor: saxlike benc pt. 2: add announce response parsing tests

gtk/DetailsDialog.cc, qt/DetailsDialog.cc, qt/DetailsDialog.h
When closing the details dialog, remember the tab selection and auto-select it the next time the details dialog is opened again.
Fixes #2300 for transmission-qt and transmission-gtk.
=> feat: remember tab selection in Details dialog

libtransmission/utils.cc, tests/libtransmission/utils-test.cc
Implements #1053 with tests.
There is no rounding as seen from tests. Some people seed until they reach a certain ratio and rounding might cause confusion as seeding would still continue even with transmission showing that the ratio is reached.
=> Add more decimals for low ratios

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, tests/libtransmission/announcer-test.cc
Does what it says on the tin: add tests for libtransmission's parsing of http tracker scrape responses. This is prepwork for refactoring how the benc response is parsed to avoid the overhead of tr_variant.
This is part 3 in the series. The previous PR was #2505.
=> test: add tests for parsing http tracker scrape responses

libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/magnet-metainfo.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, tests/libtransmission/announce-list-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/torrent-metainfo-test.cc
improve test coverage for `tr_torrent_metainfo` getters: `infoDictOffset()`, `infoDictSize()`, and `pieceOffset()`
improve makemeta coverage for building single-file torrents.
=> test: add tr_torrent_metainfo.infoDictSize() tests

libtransmission/announcer-http.cc
minor cleanup fixing three new 'use init statement' warnings on sonarcloud
=> fix: sonarcloud use-init-statement warnings in new code

libtransmission/benc.h, tests/libtransmission/benc-test.cc
fix infinite loop regression when parsing malformed bencoded data.
=> fixup! refactor: SAX-like benc parser pt. 1 (#2490)

utils/remote.cc
fix regression when adding torrent via transmission-remote
Fixes #2541.
=> fixup! refactor: base64 utils (#2381)

libtransmission/crypto-utils-cyassl.cc, libtransmission/crypto-utils-polarssl.cc, libtransmission/file-posix.cc, libtransmission/makemeta.cc, libtransmission/platform.cc, libtransmission/platform.h, libtransmission/resume.cc, libtransmission/stats.cc, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/trevent.cc, libtransmission/verify.cc, libtransmission/web.cc
Like its sibling #2520, this PR was made to replace handwritten / platform-specific code with `std::` tools:
- `std::` tools make it easier for new contributors to understand libtransmission
- `std::` tools are safer than handwritten since they have an enormous number of users / testers / maintainers
- removing handwritten code simplifies the codebase and makes libtransmission (slightly) smaller
This PR also fixes #1761
=> refactor: replace tr_thread with std::thread

libtransmission/log.cc, libtransmission/session.cc, libtransmission/tr-dht.cc, libtransmission/utils.cc, libtransmission/utils.h
implement `tr_gettimeofday()` using std::chrono` instead of OS-specific functions wrapped in #ifdefs.
See also #2548, #2520 for other use-`std::`-instead-of-OS-specific-functions
=> refactor: use std::chrono not OS-specific syscalls

libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, libtransmission/tr-dht.cc
Another code cleanup PR.
There are two forms of both `tr_peerMgrCompactToPex()` and `tr_peerMgrCompact6ToPex()` -- one form returns a raw unmanaged pointer; the other returns `std::vector<>`.
This PR removes the former raw ptr form.
=> refactor: remove raw ptr variant of tr_peerMgrCompactToPex()

libtransmission/utils.cc
A trivial PR that removes a dozen permanent heap allocations. No functional changes; just silences a Valgrind warning.
=> refactor: static allocation of formatter units

libtransmission/makemeta.cc
Fix a file descriptor leak found by Coverity. It could happen while making a new torrent if scanning and hashing a piece from a file fails. This shouldn't happen in practice but it's theoretically possible, so safeguard against it in the code.
=> fix: edge case file leak if error while making torrent

extras/rpc-spec.txt, libtransmission/rpcimpl.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, utils/remote.cc
See commit for rationale, basically metadata such as labels are likely to be known when adding a torrent, e.g. whether it's a movie, a document, music, ISO, etc. I plan on implementing this in a client after it is merged into transmission.
This still needs to be tested and should not be merged, but I wanted to make this PR for initial feedback about the implementation. I used the `torrent-set` labels call as a guide for how it should be implemented, but I am unsure if putting the declarations like I did in `torrent.h` is correct, for example.
=> add labels to torrent-add rpc method

daemon/transmission-daemon.service
Attempts to create memory mappings that are writable and executable at the same time, or to change existing memory mappings to become executable, or mapping shared memory segments as executable are prohibited.
There's no reason transmission should be doing that. If it does, it's because of malicious code exploiting a vulnerability.
See: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#MemoryDenyWriteExecute=
=> daemon: deny memory wx in transmission-daemon.service

libtransmission/CMakeLists.txt
Remove redundant include, ${UTP_INCLUDE_DIRS} is included already to fix
cross build error with buildroot:
x86_64-linux-g++: ERROR: unsafe header/library path used in cross-compilation: '-isystem' '/libutp'
=> fix cross build

libtransmission/log.cc, libtransmission/verify.cc
does what it says in the title.
Neither of these warnings caused any production issues; this is just tidying the build
=> refactor: fix a pair of win32 msvc warnings in libtransmission

gtk/Application.cc, gtk/HigWorkarea.h, gtk/MainWindow.cc, gtk/MakeDialog.cc, gtk/PrefsDialog.h, gtk/StatsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h, libtransmission/announce-list.h, libtransmission/makemeta.cc, libtransmission/makemeta.h, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/resume.h, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, macosx/CreatorWindowController.mm, qt/Application.cc, qt/FileTreeItem.cc, qt/FileTreeItem.h, qt/FileTreeModel.cc, qt/MakeDialog.cc, tests/libtransmission/rename-test.cc, utils/create.cc
A cleanup PR that migrates the older C-era enums to either `enum class`es or `constexpr` values.
=> refactor: fix sonarcloud "use enum class" code smells

libtransmission/peer-mgr-wishlist.cc, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
Part 2 in a series of web + webseed PRs. The previous PR in the series was #2611.
The series has a couple of concrete goals:
- Solve the high-CPU-when-rate-limiting-webseed problem (https://github.com/transmission/transmission/issues/1829)
- Refactor web.cc to let us [share](https://curl.se/libcurl/c/curl_share_init.html) DNS lookup info between easy handles (https://github.com/transmission/transmission/issues/1815)
And some longrt-term goals that will be unblocked by this work:
- Refactor tr_web's public API and internals into a class. Ideally I'd like to be able to DI this class so that `tr_webseed` unit tests could exist without having to make real-world network connections.
- tr_web currently requires a pre-existing transmission session. This is a little warty, e.g. this forces …
=> refactor: tr_webseed simplification

extras/rpc-spec.md, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/rpcimpl.cc
Supersedes https://github.com/transmission/transmission/pull/470, which could not be merged due to merge conflicts. Author is @mhadam.
> `percentDone` is already available as a key when calling `torrent-get` over RPC - it describes the amount of data downloaded as a percent of the files that are wanted in the torrent. I'm interested in getting `percentComplete` - the data downloaded as a percent of the complete torrent size. `percentComplete` is already included in `tr_stat` so it's an easy add.
=> Add support for torrent-get calls with the key percentComplete

libtransmission/torrent.cc
Fixes #1082. The use case is a torrent-done script that needs to know if a torrent is done because it finished downloading or if it's done because it's a newly-added seed.
=> feat: expose downloaded byte count to done script

cli/cli.cc, gtk/FaviconCache.cc, libtransmission/announcer-http.cc, libtransmission/rpcimpl.cc, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
Part 3 in a series of web + webseed PRs. The previous PR in the series was #2613. The goals are discussed [here](https://github.com/transmission/transmission/pull/2613#discussion_bucket).
---
This PR still has a lot of code smells in web.cc and webseed.cc. Refactoring the entire system is overwhelming, so instead I'm doing it in incremental steps.
- Fold `tr_webRun()`, `tr_webRunWithCookies()`, and `tr_webRunWebseed()` into a single API that takes an options argument that callers can customize to their needs.
- Also does a surface cleanup pass to the tr_webseed and tr_web internal structures, e.g. making fields const where possible, not using raw pointers, and making some fields private.
=> refactor: add fetch options object to tr_webRun()

libtransmission/session.cc, libtransmission/trevent.cc
Fixes #1437 by checking for `nullptr` before calling `evdns_base_free()`.
=> fix: crash when evdns_base_new() fails

libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
Part 4 in a series of web + webseed PRs. The previous PR in the series was #2620. The goals are discussed [here](https://github.com/transmission/transmission/pull/2613#discussion_bucket).
---
Remove `tr_webGetTaskResponseCode()`. It's not really needed anymore, and removing it is aligned with the goal of simplifying the tr_web and tr_webseed codebase.
=> refactor: remove tr_webGetTaskResponseCode()

cli/cli.cc, gtk/FaviconCache.cc, libtransmission/announcer-http.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc, libtransmission/web.h, libtransmission/webseed.cc
Part 5 in a series of web + webseed PRs. The previous PR in the series was #2628. The goals are discussed [here](https://github.com/transmission/transmission/pull/2613#discussion_bucket).
---
This PR refactors the `tr_web` module to be a C++ object instead of having global state. It also decouples `tr_web` from `tr_session` so that it can be used even by client code that doesn't have a `tr_session`. It also adds a `CURLSH` shared object and increases the DNS cache timeout to 1 hour. This PR fixes #1829 and fixes (partially) #1815 for http / https announces and scrapes, though more work on UDP announces/scrapes needs to be done for #1815.
=> refactor: tr_web

qt/MainWindow.cc
Revert #2179 (da855a72).
These icons need fallbacks, e.g. `view-statistics` does not exist on many systems.
=> revert da855a72 "Set stock icon for speed, options and statistics buttons in qt"

libtransmission/cache.cc, libtransmission/cache.h, libtransmission/inout.cc, libtransmission/peer-msgs.cc, libtransmission/session.cc, libtransmission/tr-utp.h, libtransmission/webseed.cc, tests/libtransmission/move-test.cc
Part 2 in a series of PRs to simplify piece / block / file offset math. More info [here](https://github.com/transmission/transmission/pull/2649#issue-1143873311). The previous PR in the series was #2649.
This PR updates cache.cc to use the new Location type.
=> refactor: use tr_block_info::Location in cache.cc

libtransmission/cache.cc, libtransmission/inout.cc, libtransmission/inout.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.h, libtransmission/webseed.cc
Part 3 in a series of PRs to simplify piece / block / file offset math. More info [here](https://github.com/transmission/transmission/pull/2649#issue-1143873311). The previous PR in the series was #2652.
This PR updates inout.cc to use the new Location type.
=> refactor: use tr_block_info::Location in inout.cc

libtransmission/net.cc, libtransmission/peer-mgr.cc, libtransmission/peer-socket.h, libtransmission/utils.cc
Minor refactor to reduce the amount of libtransmission code that needs to work directly with libutp.
(libutp is great; just trying to improve separation of concerns slightly in libtransmission)
=> refactor: move tr_netClosePeerSocket() impl to net.cc

libtransmission/file-posix.cc
```
libtransmission/file-posix.cc:960:10: warning: implicit conversion 'int' -> bool [readability-implicit-bool-conversion]
if (!platform_test_xfs_fd(handle)) // true if on xfs filesystem
~^
== 0
```
=> fix implicit conversion

macosx/InfoWindow.xib
They are not available on earlier versions of macOS and are reset in code.
=> Remove the info panel's icons from the xib.

libtransmission/makemeta.cc, libtransmission/trevent.cc
While running valgrind on the unit tests, I found new recent leaks. This PR fixes them.
=> fix: recent memory leak regressions

tests/libtransmission/utils-test.cc
This tests that `tr_strlcpy()` does indeed copy strings and truncates them when necessary. I understand if this is too low priority for a test.
Mostly tests system implementation of `strlcpy()`, but if someone changes transmission-provided alternative, there is a way to test it.
=> Add regression test for tr_strlcpy

docs/rpc-spec.md
Rewrote a sentence to ensure it's clear that a duplicate torrent error still returns a "success" result over RPC.
=> Clarify torrent-add result on duplicate torrents

libtransmission/makemeta.cc
Fixes #1453: transmission can now create torrents  that include 0-byte files.
=> fix: allow 0-byte files when creating torrents

qt/AddData.cc
Instead of giving the entire magnet link, which can be too long to be readable, give the magnet's display name (if available) or the info hash as a fallback.
Fixes #1217.
=> feat: better dialog when adding duplicate magnet

libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/web-utils.h, tests/libtransmission/benc-test.cc
Just removing a minor wart. The `tr_time()` call in peer-io.h both added a header dependency to utils.h and also made it harder to write future tests because of the extra complication of how to get the current time's time_t. This PR passes the timestamp in when the peer-io is created.
This still isn't a complete fix -- that timestamp is still gotten from `tr_time()` in peer-msgs when creating the peer-io -- but at least it moves the dependency one step further outward, making future cleanup easier.
=> refactor: remove utils dependency from peer-io

daemon/transmission-daemon.service
Currently, systemd may start the daemon before the network configuration is completed, which may result in errors for configurations that rely on e.g. binding to specific addresses, such as in #2720.
=> Delay start of daemon systemd service until network is configured

libtransmission/rpc-server.cc
This is a quick fix for now, I have plans of removing the `char[TrUnixAddrStrLen]` in `tr_rpc_address` and turning it into a string. However, I don't have time to make that into something proper right now and this is a serious bug that will cause RPC to fail on windows. 
cc @mikedld
=> fix broken ip address string size on windows

libtransmission/announcer-udp.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/trevent.cc
Replace some thread sleep+poll code with a std::condition_variable to wake up awaiting threads during session startup.
=> perf: use condition variables during tr thread startup

libtransmission/cache.cc, libtransmission/peer-common.h, libtransmission/peer-io.cc, libtransmission/torrent.cc
A followup to 13ad2b58dc. Now that we have `tr_block_info::BlockSize`, the `MAX_BLOCK_SIZE` const isn't needed anymore.
=> refactor: remove redundant MAX_BLOCK_SIZE constant

libtransmission/bitfield.cc, libtransmission/bitfield.h
Related to #2727. Doesn't fix it, but gives more descriptive assertion message so that if it fails again, it will give more information to help track the problem down.
=> chore: add more descriptive assertion in bitfield

libtransmission/rpcimpl.cc
Thanks to MatanZ for finding and tracking down this problem
Fixes #2757.
=> fix: memory corruption in RPC when fetching torrent piece info

daemon/daemon.cc, gtk/Session.cc, libtransmission/rpc-server.cc, libtransmission/torrent.cc, libtransmission/tr-udp.cc, libtransmission/tr-utp.cc, libtransmission/variant-json.cc, libtransmission/watchdir-generic.cc, libtransmission/watchdir-inotify.cc, libtransmission/watchdir-kqueue.cc, libtransmission/watchdir-win32.cc, libtransmission/watchdir.cc, macosx/Controller.mm
Part 7 of a series to update Transmission's logging mechanism. #2773 is the previous in the series. The goals are described [here](https://github.com/transmission/transmission/pull/2749#pullrequest-875916992).
---
This PR continues the previous three that (a) use fmt instead of vararg to improve typesafe logging and (b) ensure that all log messages of severity "Info" or higher are flagged for translation. There are a _lot_ of strings so this is a high-volume task being split up into four PRs.
There will be (at least) one more PR in the logging series, but this PR should finish off the task of updating translatable log strings in `libtransmission/`.
=> refactor: fmt pt 4

libtransmission/file-posix.cc
fix: infinite loop when pread returns 0 at EOF on POSIX. This issue was introduced on Feb 22 by #2682 / e6e1e1d2208cb2e6792b35ddbf3cd700458bb1a0.
With this PR, reading starting at EOF will return an error, both on file-win32 (existing behavior) and file-posix (new to this PR).
=> fixup! fix: ensure all bytes read / written to file (#2682)

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/interned-string.h, libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/webseed.cc
#2761 got me looking at the bandwidth code again and realizing that after a4d7e11a14f16b4bac69b99d4c0da055847b9625 it's possible to aggregate the bandwidth objects in tr_session and tr_torrent directly, rather than via new and delete.
Also implements a couple of code comments from #2761, e.g. not leaking bandwidth groups from the tr_session on shutdown. Bandwidth is designed to not be copyable, so this is done by making a map of Bandwidth unique_ptrs in tr_session.
=> refactor: aggregate bandwidth objects

daemon/daemon.cc, libtransmission/log.cc, libtransmission/log.h
Followup PR to af339a15edba96b33c51f05e4607b88f6d533436 from the logging refactor series described in #2749. The previous PR in this series was #2776.
This is a minor update that lets users choose the new log levels from the command line when starting `transmission-daemon`.
=> feat: handle new log levels in transmission-daemon's cli invocation

daemon/daemon.cc, gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/FilterBar.cc, gtk/FreeSpaceLabel.cc, gtk/MainWindow.cc, gtk/MakeDialog.cc, gtk/MessageLogWindow.cc, gtk/OptionsDialog.cc, gtk/PrefsDialog.cc, gtk/RelocateDialog.cc, gtk/Session.cc, gtk/StatsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h, libtransmission/announce-list.cc, libtransmission/makemeta.h, libtransmission/platform.h, libtransmission/torrent-magnet.cc, libtransmission/transmission.h, libtransmission/watchdir.cc, qt/WatchDir.cc, tests/libtransmission/announce-list-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, utils/show.cc
A followup / continuation of the [logging series](https://github.com/transmission/transmission/pull/2749#pullrequest-875916992) started in #2749.
- Use [`fmt::format()`](https://fmt.dev/latest/api.html#_CPPv4IDpEN3fmt6formatENSt6stringE13format_stringIDp1TEDpRR1T) to build user-visible strings.
- When appropriate, reuse the fmt strings from libtransmission.
- Fixes #1353.
- Add a custom fmt::formatter class to Utils.h so that fmt will understand Glib::ustring
- Use named placeholders for every translatable string so the strings are easier for translators to read and understand
- Use the [`C_`](https://developer.gimp.org/api/2.0/glib/glib-I18N.html#C-:CAPS) context macro to differentiate identical translation strings; previously there was a comment embedded in the string.
([Some random …
=> refactor: use fmt to build the GTK client's user-visible strings

libtransmission/announce-list.cc, libtransmission/blocklist.cc, libtransmission/fdlimit.cc, libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/file.h, libtransmission/log.cc, libtransmission/makemeta.cc, libtransmission/platform.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/trevent.cc, libtransmission/utils.cc, tests/libtransmission/announce-list-test.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/copy-test.cc, tests/libtransmission/error-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/subprocess-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/utils-test.cc, utils/create.cc
Refactor `tr_sys_path_dirname()` and `tr_sys_path_basename()` to return a `std::string` instead of `char*`
=> refactor: tr_sys_path_dirname returns a std::string

libtransmission/torrent.cc
paused torrents incorrectly fail `setLocalErrorIfFilesDisappeared` upon restarting Transmission as it incorrectly checks the pointer`*has_local_data` rather than `has_local_data`
Fixes: #2796
=> fixes "no data found..." error on restart for paused torrents

libtransmission/crypto-utils-cyassl.cc, libtransmission/crypto-utils-polarssl.cc, libtransmission/log.h, libtransmission/peer-io.cc, libtransmission/port-forwarding.cc, libtransmission/torrent-magnet.cc, libtransmission/tr-dht.cc
This PR address revisits #2776 to address some code review comments that @mikedld had after I merged the PR too quickly. :stuck_out_tongue: This is small piece of the [logging series](https://github.com/transmission/transmission/pull/2749#pullrequest-875916992) that started with #2749.
=> refactor: a little more logging

CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, daemon/CMakeLists.txt, gtk/CMakeLists.txt, libtransmission/CMakeLists.txt, libtransmission/tr-strbuf.h, tests/libtransmission/CMakeLists.txt, tests/libtransmission/strbuf-test.cc, utils/CMakeLists.txt
First in a series of PRs to introduce and use a new `tr_strbuf` class for building temporary strings. It's a growable string buffer based on `fmt::basic_memory_buffer` that has an initial size which is large enough to build most filenames or URLs without  heap allocations. It also has some extra helpers, such as a `c_str()` method to make it easier to use with old zero-terminated string APIs easier.
Series Goals:
- Reduce the number of heap allocations that Transmission uses when making temporary strings
- Remove API assumptions, e.g. `tr_saveFile()` requires the filename to be a `std::string` so that `tr_saveFile()` can be sure to get a zero-terminated C string without having an extra heap allocation. 
---
This PR:
- introduces `tr_strbuf`
- introduces `tr_pathbuf` which is …
=> feat: add tr_strbuf

tests/libtransmission/file-test.cc
Fix an edge case that causes the file-info test to fail once in awhile.
=> test: fix file-info test edge case

gtk/TorrentCellRenderer.cc
Possible fix for https://github.com/transmission/transmission/issues/2817.
=> fix: missing fmt::arg calls in GTK client

libtransmission/peer-io.cc
=> fix: set peer-io destructor log level to trace

libtransmission/session.cc, libtransmission/tr-strbuf.h, tests/libtransmission/strbuf-test.cc
- add `.starts_with()`
- add `.ends_with()`
- handle zero-terminated string inputs
- `.append()` and the constructor now take arbitrary number of arguments
- strbuf is always zero-terminated, so `c_str()` is now a const method
- made methods `constexpr` / `[[nodiscard]]` where applicable
=> feat: strbuf features

libtransmission/file.h, libtransmission/platform.cc, libtransmission/resume.cc, libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent-metainfo.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.cc, tests/libtransmission/announce-list-test.cc, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/utils-test.cc, utils/remote.cc
Third in the `tr_strbuf` series. The previous PR was #2821 and the series goals are described [here](https://github.com/transmission/transmission/pull/2810#issue-1180004274).
---
This PR updates tr_loadFile() and tr_saveFile() to take a std::string_view filename parameter.
In some places, the previous `std::string const&` parameter type required callers to instantiate a short-term `std::string` to satisfy the requirement. In those cases,  use a `tr_pathbuf` instead.
It also swaps the order of the `filename` and `contents` parameters in `tr_loadFile()` so that it and `tr_saveFIle()` use the same order.
=> refactor: tr_loadFile() tr_saveFile() take a std::string_view filename arg

libtransmission/announce-list.cc, libtransmission/block-info.h, libtransmission/session.cc, libtransmission/stats.cc, libtransmission/tr-dht.cc, libtransmission/variant.cc, libtransmission/variant.h, qt/Prefs.cc, utils/edit.cc
Fourth in the `tr_strbuf` series. The previous PR was #2822 and the series goals are described [here](https://github.com/transmission/transmission/pull/2810#issue-1180004274).
---
This PR builds on the previous one: now that `tr_saveFile()` and `tr_loadFile()` no longer require a `std::string const& filename` argument, some of the caller functions don't need to take them either. `tr_variantToFile()` and `tr_variantFromFile()` are two such methods.
As with previous PRs, this also means that we can avoid heap allocations by using `tr_pathbuf` instead of `std::string` for these short-term filename strings.
=> refactor: tr_variantToFile() takes a string_view filename

cli/cli.cc, daemon/daemon.cc, gtk/OptionsDialog.cc, libtransmission/blocklist.cc, libtransmission/fdlimit.cc, libtransmission/file-posix.cc, libtransmission/file.h, libtransmission/inout.cc, libtransmission/log.cc, libtransmission/makemeta.cc, libtransmission/platform.cc, libtransmission/rpcimpl.cc, libtransmission/session-id.cc, libtransmission/session.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent.cc, libtransmission/utils.cc, libtransmission/verify.cc, libtransmission/watchdir.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/copy-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/subprocess-test-program.cc, tests/libtransmission/subprocess-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/watchdir-test.cc
minor refactor: in the `tr_sys_file_*()` and `tr_sys_path_*()` functions that take a `tr_error*` as the final argument, make the error optional.
There were 100+ places that were just passing in `nullptr`, so this PR makes `nullptr` the default value.
=> refactor: make err arg optional in tr_sys_* funcs

Transmission.xcodeproj/project.pbxproj, libtransmission/announcer-udp.cc, libtransmission/interned-string.h, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/tr-strbuf.h, libtransmission/utils.cc, tests/libtransmission/peer-mgr-active-requests-test.cc, tests/libtransmission/quark-test.cc, tests/libtransmission/strbuf-test.cc
Fifth in the `tr_strbuf` series. The previous PR was #2824 and the series goals are described [here](https://github.com/transmission/transmission/pull/2810#issue-1180004274).
---
This is a small PR that adds `fmt::formatter`s for `tr_strbuf` and also `tr_interned_string` so that objects of those two types don't have to be manually converted into `std::string_view`s when being formatted with `fmt::format`.
Also adds `noexcept` to methods in those two classes that shouldn't ever be able to throw.
=> refactor: add fmt::formatters

libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/announcer-http.cc, libtransmission/announcer.cc, libtransmission/magnet-metainfo.cc, libtransmission/magnet-metainfo.h, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/utils.cc, libtransmission/web-utils.cc, libtransmission/web-utils.h, libtransmission/webseed.cc, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/torrents-test.cc, utils/show.cc
Sixth in the `tr_strbuf` series. The previous PR was #2829 and the series goals are described [here](https://github.com/transmission/transmission/pull/2810#issue-1180004274).
---
Migrate some of the code that uses temporary strings from using `std::string` to `tr_pathbuf` and `tr_urlbuf`:
- `announce_url_new` now returns a `tr_urlbuf` instead of a `std::string`
- `scrape_url_new` now returns a `tr_urlbuf` instead of a `std::string`
- `tr_magnet_metainfo.magnet()` now returns a `tr_urlbuf` instead of a `std::string`
- `tr_torrent_metainfo.torrentFile()` now returns a `tr_pathbuf` instead of a `std::string`
- `tr_torrent_metainfo.resumeFile()` now returns a `tr_pathbuf` instead of a `std::string`
- `tr_torrent_metainfo.magnetFile()` now returns a `tr_pathbuf` instead of a `std::string`
- …
=> refactor: strbuf for metainfo files

gtk/FileList.cc
Not sure when this regressed -- e.g. if it was when moving over to gtkmm or if it's been broken for longer --  but the "Have" column in the files tab of the GTK client's Details Dialog just showed an unformatted integer and did not set the progressbar's "fill" value.
This PR sets the fill value and formats the string with a trailng `%` character
=> fix: file progress in GTK Details dialog

libtransmission/torrent-metainfo.h, tests/libtransmission/move-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/rpc-test.cc, tests/libtransmission/test-fixtures.h
When creating a test torrent, populate its files _before_ instantiating the torrent rather than after.
This should solve a should-have-been-obvious-from-the-beginning race condition of the torrent verifying its files in the background vs. the torrent's files being populated.
=> test: fix race condition in move-test

libtransmission/tr-strbuf.h, tests/libtransmission/strbuf-test.cc
`tr_strbuf`'s move constructor and move assignment operator incorrectly assumed that the aggregate object `buffer_`'s full contents, including the implicit zero termination at `buffer[buffer.size()]`, would be moved. The full buffer is not guaranteed, so the recipient object needs to re-ensure zero termination.
=> fix: tr_strbuf move op loses zero-termination

libtransmission/inout.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc
Eighth in the `tr_strbuf` series. The previous PR was #2843 and the series goals are described [here](https://github.com/transmission/transmission/pull/2810#issue-1180004274).
---
- Remove `tr_torrentFindFile2()`; use `tr_torrent::findFile()` everywhere instead.
- Migrate `tr_torrent::findFile()` to use `tr_pathbuf` instead of `std::string`
=> perf: replace tr_torrentFindFile2() with tr_torrrent.findFile()

gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/FreeSpaceLabel.cc, gtk/MakeDialog.cc, gtk/PrefsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, libtransmission/announcer-http.cc, libtransmission/error.cc, libtransmission/file-posix.cc, libtransmission/inout.cc, libtransmission/log.cc, libtransmission/makemeta.cc, libtransmission/peer-msgs.cc, libtransmission/resume.cc, libtransmission/subprocess-posix.cc, libtransmission/torrent-metainfo.cc, libtransmission/webseed.cc
When calling `fmt::format()` with a fmt string that's fixed at compile time (that is, strings that we're not passing through `gettext()` first), use the `FMT_STRING()` macro to pick up compile-time safety checks.
=> refactor: prefer FMT_STRING

libtransmission/session.cc
Without this the bandwidth groups file is written correctly, but it is not read at session start.
=> Bandwidth group are written to a dict, not to a list.

libtransmission/session.cc
=> fix: getBandwidthGroup() uses the wrong Bandwidth group

daemon/daemon-win32.cc, libtransmission/subprocess-win32.cc, libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
remove one of the C-era utilities; use `fmt::format()` instead.
=> refactor: remove tr_strdup_printf()

gtk/DetailsDialog.cc, gtk/MainWindow.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h
fix: formattted speeds and percentages.
Discussed by @catadropa at https://github.com/transmission/transmission/issues/2817#issuecomment-1079652989.
Fixes #2817
=> fixup! refactor: use fmt to build the GTK client's user-visible strings

libtransmission/bitfield.cc, libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/handshake.cc, libtransmission/net.cc, libtransmission/peer-io.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/subprocess-win32.cc, libtransmission/tr-assert.cc, libtransmission/tr-assert.h, libtransmission/tr-assert.mm
Another step towards removing `-cert-dcl50-cpp` (do not define C-style variadic functions) from `libtransmission/.clang-tidy`.
=> refactor: remove varargs from TR_ASSERT_MSG()

libtransmission/benc.h, libtransmission/bitfield.cc, libtransmission/bitfield.h, libtransmission/block-info.h, libtransmission/completion.h, libtransmission/magnet-metainfo.h, libtransmission/net.cc, libtransmission/net.h, libtransmission/session.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.h, libtransmission/torrents.h
No functional changes. Just adding annotation to help the compiler to flag warnings and / or to better optimize the build.
=> refactor: annotate nodiscard, constexpr, noexcept methods

cli/cli.cc, daemon/daemon.cc, utils/remote.cc
replace `tr_snprintf()` calls with `fmt::format()`, part 1: utils / cli / daemon
=> refactor: remove tr_snprintf() pt 1

libtransmission/announcer.cc, libtransmission/makemeta.cc, libtransmission/net.cc, libtransmission/rpcimpl.cc, libtransmission/tr-dht.cc, libtransmission/tr-strbuf.h, libtransmission/upnp.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/utils-test.cc
part 1 [here](https://github.com/transmission/transmission/pull/2867).
Not much to say about this; it's part of the C++ification to phase out use of manually-allocated / manually-freed C strings.
=> refactor: remove tr_snprintf() pt 2

daemon/transmission-daemon.1, utils/transmission-remote.1
While reading the man page for `transmission-daemon` I stumbled upon a typo and fixed it.
Additionally I decided to check all the man pages for similar errors and found another one.
=> Fix typographical errors in the man pages.

libtransmission/magnet-metainfo.cc, tests/libtransmission/magnet-metainfo-test.cc
Add fuzz-testing for `tr_magnet_metainfo.parseMagnet()`.
Fix off-by-one issue in base32 decoding.
=> test: fuzz test tr_magnet_metainfo.parseMagnet()

libtransmission/variant-benc.cc, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/web-utils-test.cc
- Add fuzz testing for `tr_torrent_metainfo.parseBenc()`
- Fix an error that caused `tr_torrent_metainfo.parseBenc()` to return success on some malformed benc
- Fix an error that caused `tr_torrent_metainfo.parseBenc()` to keep parsing after hitting invalid data
=> test: fuzz test tr_torrent_metainfo.parseBenc()

docs/Bug-Submission.md, docs/Building-Transmission.md, docs/Editing-Configuration-Files.md, docs/Environment-Variables.md, docs/Peer-ID-and-User-Agent.md, docs/Port-Forwarding-Guide.md, docs/Release-Notes.md, docs/Scripts.md, docs/Why-Are-My-Speeds-So-Slow.md, docs/Why-is-my-port-closed.md, docs/rpc-spec.md
The same deal as with pull request #2875.
This time I was reading the specification of the RPC interface, saw "terinal" instead of "terminal" and then spell checked all the other documentation files.
The capitalisation of many words is also questionable, but I decided not to change it.
Additionally the file Port-Forwarding-Guide.md uses DOS line endings, but I decided to keep it that way because changing it would introduce a ton of diff noise.
=> Fix typographical errors in the documentation.

libtransmission/watchdir.cc
A partial refactor of `tr_watchdir`.
This is a partial refactor that addresses manually-managed pointers in `tr_watchdir` and `tr_watchdir_retry`.  There is still further work to be done to modernize the inotify / kqueue / win32 / generic backends.
=> refactor: convert watchdir to C++

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/files.cc, libtransmission/files.h, libtransmission/inout.cc, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc, tests/libtransmission/CMakeLists.txt, tests/libtransmission/files-test.cc
First of a small series of refactors to reduce coupling & dependencies in our file management code. As a very small example, in order to unit test `tr_torrent.findFile()` we currently need to have a `tr_torrent`, which in turn needs an entire `tr_session` to be spun up. That shouldn't be necessary for a `findFile()` unit test.
---
This PR extracts the 'files' methods and structures of `tr_torrent_metainfo` into a standalone class `tr_files`, a simple collection of subpaths and filesizes.
Replace `tr_torrent.findFile()` with `tr_files.find()` and add tests. `tr_torrent.findFile()` is now a simple pass-through.
=> refactor: extract some file management into tr_files class

Transmission.xcodeproj/project.pbxproj, libtransmission/block-info.cc, libtransmission/block-info.h, libtransmission/torrent-metainfo.cc, libtransmission/transmission.h, utils/show.cc
This strengthens the expected behaviour for piece_size, avoiding meta_info giving a value greater than `UINT32_MAX`. Also addressing a couple of conversion warnings.
Alternative considered: changing `final_block_size_` and `final_piece_size_` to `uint64_t`, but that would be an untested scenario (potentially broken) and reasonably unneeded for some years.
=> meta info piece_size should be maximum UINT32_MAX

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/file-posix.cc, libtransmission/inout.cc, libtransmission/torrent-files.cc, libtransmission/torrent-files.h, libtransmission/torrent-metainfo.cc, libtransmission/torrent-metainfo.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/utils.h, tests/libtransmission/CMakeLists.txt, tests/libtransmission/files-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/remove-test.cc, tests/libtransmission/test-fixtures.h, tests/libtransmission/variant-test.cc
Third in a small series of refactors to reduce coupling & dependencies in our file management code. Previous in this series: #2906 and #2911.
---
This PR extracts `tr_torrentSetLocation()` and `tr_torrentDeleteLocalData()` implementations from `tr_torrent` into the smaller class `tr_torrent_files` where they are more decoupled from the rest of libtransmission -- e.g. unit tests that don't involve spinning up a `tr_session` are now possible.
`tr_torrent_files::remove()`, has several new tests to check for edge cases. I'm looking forward to seeing how they play on non-Linux CI boxes... :lady_beetle:
=> refactor: add tr_torrent_files::move() and remove()

gtk/DetailsDialog.cc, libtransmission/peer-msgs.cc
Fix a couple of places where I broke the user-visible strings while migrating them over to libfmt. Previous related fixups: #2913
=> fixup: more libfmt usage regressions

libtransmission/torrent.h
Remove an unnecessary field from `tr_torrent`.
=> refactor: remove tr_torrent.magicNumber

tests/libtransmission/clients-test.cc
Use case: `libtransmission-test --gtest_filter='*Fuzz' --gtest_repeat N`
=> test: use uniform naming scheme for fuzz tests.

libtransmission/announcer.cc, libtransmission/utils.h, libtransmission/web-utils.cc, libtransmission/web-utils.h, tests/libtransmission/web-utils-test.cc
This field was redundant with `tr_url_parsed.port`, so remove it
=> refactor: remove tr_url_parsed_t.portstr

libtransmission/announce-list.cc, libtransmission/announce-list.h, tests/libtransmission/announce-list-test.cc, tests/libtransmission/magnet-metainfo-test.cc, utils/show.cc
`tr_url_parsed_t` is pretty large -- 134 bytes -- so remove the unused instance that held the parsed scrape URL.
=> refactor: remove tr_announce_list.tracker_info.scrape

libtransmission/announce-list.cc, libtransmission/announce-list.h, libtransmission/announcer.cc, libtransmission/magnet-metainfo.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent.cc, macosx/QuickLookPlugin/GeneratePreviewForURL.mm, tests/libtransmission/announce-list-test.cc, tests/libtransmission/magnet-metainfo-test.cc, utils/show.cc
`tr_url_parsed_t` is pretty large -- 134 bytes -- so remove the parsed announce URL from `tr_announce_list::tracker_info`.
=> refactor: remove tr_announce_list::tracker info.announce

cmake/TrMacros.cmake
This is needed for consistent building when using compiler-specific tooling such as address sanitizer flags.
=> build: pass cmake compiler values to submodules

tests/libtransmission/file-piece-map-test.cc
Fixes https://github.com/transmission/transmission/issues/2923
=> fix: new MSVC warning in file-piece-map-test.cc

libtransmission/bitfield.cc
Noticed when using `transmission-gtk` a large amount of my systems total CPU time is spent in `tr_bitfield::countFlags`.
Optimize the code a bit, a better long term approach for most x86_64 machines would be to use the `popcnt` instruction (accessible via `std::popcount` for std >= c++20 or some library like [libpopcnt](https://github.com/kimwalisch/libpopcnt)). But for now this change get a bit of a speedup that will hopefully help.
All unit tests pass:
```
$> ./libtransmission-test 
[----------] 5 tests from Bitfield
[ RUN      ] Bitfield.count
[       OK ] Bitfield.count (69 ms)
[ RUN      ] Bitfield.ctorFromFlagArray
[       OK ] Bitfield.ctorFromFlagArray (0 ms)
[ RUN      ] Bitfield.setRaw
[       OK ] Bitfield.setRaw (0 ms)
[ RUN      ] Bitfield.bitfields
[       OK ] …
```
=> perf: fix misc inefficiencies in bitfield.cc

libtransmission/peer-mgr.cc
Trying to remove the last instances of `tr_ptrArray` so that it can be removed. This PR removes one of the remaining four by making `tr_peerMsgs.webseeds` a `std::vector`.
=> refactor: make tr_peerMgr.webseeds a std::vector

libtransmission/torrent-files.h
=> fix: uninintialized field tr_torrent_files.total_size_

libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.cc, libtransmission/torrent.h
=> refactor: use std::vector<tr_quark> for torrent labels

libtransmission/.clang-tidy
small housekeeping PR: re-enable a clang-tidy test that we didn't need to have disabled.
=> build: re-enable cert str34 c clang tidy

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/natpmp.cc, libtransmission/natpmp_local.h, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/port-forwarding.h, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/tr-udp.cc, libtransmission/tr-utp.cc, libtransmission/transmission.h, libtransmission/upnp.cc, libtransmission/web-utils.cc, macosx/PrefsController.mm, qt/Session.cc
This is a very simple little class -- literally just a wrapper around a `uint16_t`.
It exists to ensure the byte ordering never gets mixed up.
=> refactor: add a tr_port safety class

libtransmission/announcer-http.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-mgr.cc, libtransmission/tr-dht.cc
Works similarly to `tr_port::fromCompact()`; this is for building ipv4 and ipv6 addresses from compact format in BitTorrent messages
=> refactor: add tr_address::fromCompact()

libtransmission/variant-json.cc
Ensure that our buffer is large enough to hold the JSON data that we generate.
Fixes #2953.
=> fix: heap-buffer-overflow in variant-json

libtransmission/bitfield.cc, libtransmission/tr-popcount.h
Same as [PR #2938](https://github.com/transmission/transmission/issues/2938) but instead of relying on [libpopcnt](https://github.com/transmission/libpopcnt) just makes new header file [tr-popcnt.h](https://github.com/transmission/transmission/compare/main...goldsteinn:submittable-hdr?expand=1#diff-ef11ec5a5d3fd4a66efbaafcd1ff9933faa5db09d766ec5f5bac20556ed13131) that accomplishes the same logic (but better for smaller types such as the `uint8_t` currently used).
Some notes: Tested with GCC11 on ubuntu20.04
Tested `tr_popcnt` independently with GCC11/Clang12 on ubuntu20.04 but the MSVC  preprocessor logic is untested. 
All `count` implementations are tested, however.
All tests either pass or are skipped:
```
$> libtransmission-test
...
[----------] 5 tests from Bitfield
[ RUN      ] …
```
=> perf: use popcnt in tr_bitfield

libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/transmission.h
Replace the older C-style API methods to be class methods.
Old: `tr_rpcServerDoFoo(tr_rpc_server*, ...);`
New: `tr_rpc_server::doFoo(...);`
=> refactor: partially c++ifiy tr_rpc_server

libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc
minor refactor to make tr_torrent's `verify_state_` and `verify_progress_` fields private.
=> refactor: make tr_torrent::verify_state_ private

README.md, cli/transmission-cli.1, daemon/transmission-daemon.1, gtk/transmission-gtk.1, qt/transmission-qt.1
Some admin removed the wiki at:
https://github.com/transmission/transmission/wiki
So let's remove the references to it as well.
=> Replacing references to wiki

gtk/FileList.cc, gtk/IconCache.cc, gtk/IconCache.h, gtk/TorrentCellRenderer.cc
Used to make  viewing https://github.com/transmission/transmission/issues/1504 possible at all. That torrent has 166,068 files
=> perf: faster file-lists in the GTK client's details dialog

gtk/FileList.cc, libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h
ex: `tr_peer_stats`, `peer_atom`, `tr_stat`.
Also, sort those structs' fields to reduce the gaps / padding
=> refactor: use smaller integral types in some structs

libtransmission/announcer.cc, libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/torrent.cc, libtransmission/torrent.h
does what it says on the tin. Re-arrange the fields in `tr_torrent`, `tr_tier`, `tr_announcer` etc. to reduce struct padding where possible.
=> refactor: reduce field padding in some structs

docs/Editing-Configuration-Files.md, libtransmission/rpc-server.cc, libtransmission/session.cc, libtransmission/utils.h
The umask and IPC socket permission will now be stored as strings representing octal numbers in the settings file.
They now can also be loaded from such a string as well as from the old base 10 number to remain backwards compatibility.
The octal format is more familiar to the users of Unix-like operating systems than the previous base 10 version of the same number, since those systems represent their file system permissions in octal.
I could not find automated tests for the settings file to which I could have added own tests, but I tested everything manually and very thoroughly. Normal permissions, empty strings, strings containing non-octal numbers or numbers representing a number bigger than 777 and so on.
The new format handles all these cases exactly as the old format did. Which means …
=> Specify the umask and IPC socket permission as strings.

libtransmission/bandwidth.h, libtransmission/bitfield.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc
There were a few fields in `tr_torrent` that were only assigned to; never read. Remove them.
=> refactor: remove unused tr_torrent fields

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h
This count could get corrupted due to imprecise bookkeeping when processing peers' cancel messages, which in some cases could be nasty since the value is used as an array index. This PR replaces the field with a `prefetched` flag in the struct that represents a peer request. This approach has simpler code, simpler logic, and is harder to break.
Fixes #3018.
Looks like this is broken in older stable releases as well.
=> fix: invalid tr_peerMsgsImpl::prefetchCount value

Transmission.xcodeproj/project.pbxproj, macosx/CocoaCompatibility.h, macosx/Info.plist, macosx/Torrent.mm
Same as #3022, but with dual compatibility by using the `//` comment trick which is used in many places already in Transmission.
=> clang-format version 12.0.1 + 14.0.3

libtransmission/file-posix.cc
Fix spurious tr_error being set when reading up to EOF. This regression generated invalid error messages when no error occurred.
See: #2682, #2780
=> fixup! fix: ensure all bytes read / written to file

Transmission.xcodeproj/project.pbxproj
This fixes building miniupnp with Xcode in #3020.
Note: Previously, we were beneficing from https://github.com/transmission/miniupnpc/commit/c60cfb0d33feb7fe701679dddf0d37c950e5c646 for updateminiupnpcstrings.sh.
But not anymore.
So I've ~~copy-pasted our fixed version of updateminiupnpcstrings.sh~~ added `mv miniupnpcstrings.h src/miniupnpcstrings.h` in the xcodeproj build phase directly.
=> deps: update miniupnp to 2.3.0 - Fix building miniupnp from Xcode

Transmission.xcodeproj/project.pbxproj, macosx/Info.plist, macosx/QuickLookPlugin/QuickLookPlugin-Info.plist
This change has no impact at all on our product identifier or signing identity (the default is already "-").
But it simply gets ride of multiple Xcode warnings by adopting the related recommended settings.
=> Set recommended CODE_SIGN_IDENTITY and PRODUCT_BUNDLE_IDENTIFIER

daemon/daemon-posix.cc, libtransmission/platform-quota.cc
>daemon/daemon-posix.cc:62:16: warning: implicit conversion turns string literal into bool: 'const char [18]' to 'bool' [-Wstring-conversion]
>libtransmission/platform-quota.cc:134:20: warning: comparison of array 'mnt[i].f_mntonname' not equal to a null pointer is always true [-Wtautological-pointer-compare]
=> Address some core build warnings

macosx/TorrentTableView.mm
Minimal implementation support for #439.
It could be improved slightly to support returning multiple types of objects, like both NSString and NSURL, but I haven't found the use case, so it should be fine like that.
Fix #439.
=> Add ⌘C support

gtk/Session.cc, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, macosx/Torrent.mm, tests/libtransmission/move-test.cc
This reverts commit 27fbfd8da62d39127b891cb8dc481938fbf13d72.
Fixes #3088.
=> Revert "refactor: move tr_torrent callbacks to tr_session (#3003)"

Transmission.xcodeproj/project.pbxproj, libtransmission/torrent-files.h, libtransmission/torrent.cc, macosx/NSStringAdditions.mm, macosx/QuickLookPlugin/CMakeLists.txt, macosx/QuickLookPlugin/GeneratePreviewForURL.mm, macosx/QuickLookPlugin/GenerateThumbnailForURL.mm, macosx/QuickLookPlugin/QuickLookPlugin-Prefix.pch, macosx/QuickLookPlugin/main.cc
1. Fix QuickLook execution. I believe broken by #1830 since the fix is to add the missing `extern "C"` when compiling as C++.
2. Fix displaying size, which was an in-code warning-todo since 093d968b95e17f678e3b7a3490e64d80de130243. Adopted uTorrent format: filename separated from size by " - ".
3. Fix sorting alphabetically (#45)
4. Removes unnecessary `NSApplicationAdditions.mm` from QuickLookPlugin
Tested on macOS Mojave and macOS Monterey.
Fixes #45.
=> Fix QuickLook

libtransmission/bitfield.cc, libtransmission/blocklist.cc, libtransmission/blocklist.h, libtransmission/rpc-server.cc, qt/DetailsDialog.cc, qt/MainWindow.cc, tests/libtransmission/blocklist-test.cc
Fix a handful of minor compiler warnings that had snuck into the codebase over the last month or so.
=> fix: compiler warnings

qt/DetailsDialog.cc, qt/DetailsDialog.ui
Resolves  #1729 in qt version.
=> Add new information about when torrent was added to transmission in the Information Tab in transmission-qt

gtk/DetailsDialog.cc
Thought I'd make this change as per #1729 although I note that's been closed now. I struggle to see in the docs anywhere whether QT is meant to replace the GTK build altogether in the long run, in which case maybe this didn't need doing.
=> Show torrent added date/time in details dialog (GTK).

libtransmission/net.cc, libtransmission/peer-socket.h, libtransmission/session.h, libtransmission/tr-lpd.cc, libtransmission/tr-udp.cc
The root cause was a bug in 0a3018d706494d4327876b4dcda5a7f56baf0fef where  `createSocket()` would return `{}` isntead of `TR_BAD_SOCKET` in some error cases. This `{}` value was zero, so the calling code wound up unintentionally manipulating stdin.
This PR adds some other correctness changes made while tracking the problem down, e.g. const correctness and ensuring that `tr_socket_t` member fields in libtransmission classes are initialized to `TR_BAD_SOCKET`.
=> fix: ESPIPE "illegal seek" error while seeding

libtransmission/bandwidth.cc, libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc
Some mild C++ification of `tr_peerIo`. There is still a lot of work to do in that class; this is just some prepwork for another refactor that removes `tr_ptrArray` from peer-mgr.cc.
=> refactor: make tr_peerIoGetAddress() a member function

libtransmission/peer-mgr.cc
partial C++fication of `peer_atom`: make some fields private and make some functions into methods
=> refactor: struct peer_atom

libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/ptrarray.cc, libtransmission/ptrarray.h
Remove one of the two remaining places where `tr_ptrArray` was still in use (https://github.com/transmission/transmission/pull/3108 will remove the other).
Previously, tr_swarm.pool was a `tr_ptrArray` that held raw pointers to `peer_atom`. This is now a `std::vector<std::unique_ptr<peer_atom>>`.
I'd like to aggregate this and make this a `std::vector<peer_atom>` but that's a little out-of-scope for this PR because `tr_peer` holds a pointer to the atom, so that code will need to be updated too. This change will take place in a separate PR.
This PR also removes some now-unused tr_ptrArray mehods.
=> refactor: use std::vector instead of tr_ptrArray in peer-mgr

libtransmission/web-utils.cc
We were incorrectly duplicating most domains because the "do we need to convert before feeding to psl" test incorrectly returned true for many domains.
=> perf: avoid some unnecessary psl domain strdups

libtransmission/session.cc, libtransmission/session.h, libtransmission/web.h
A pretty small perf refactor: use a compile-time `std::string_view` for the User-Agent string provided to libcurl, instead of generating a new std::string from libfmt each time.
=> perf: use std::string_view for compile-time UserAgent

libtransmission/session.cc, libtransmission/torrent-ctor.cc, libtransmission/torrent.h
This is a minor performance patch that replaces a few `std::string` temporaries with `std::string_view` in `sessionLoadTorrent()`.
=> perf: avoid std::string temporaries in sessionLoadTorrent()

utils/remote.cc, utils/transmission-remote.1
This PR adds support for filtering torrents by various criteria to transmission-remote, per the discussion in #2948.
The possible filters are  uploading, downloading, label, torrent name, and upload ratio. But it is easy to add more.
Filters may be chained and may be negated.
The implementation is not the most efficient. In particulat it causes double calling of torrent-get RPC if this call is needed for the action that follows the filter. But I think it is does not matter for most use cases.
=> Filtering torrents in transmission-remote

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, libtransmission/webseed.cc
Start decoupling tr_peer from tr_peer_atom.
Not a fix for #3166 yet, but lays some groundwork for the upcoming fix.
=> refactor: add tr_peerMsgs.networkSocket()

libtransmission/peer-mgr.cc
Fixes #3166.
Fixes #3153.
This is a hack, really. The goal is just to unbreak the nightly builds without having to wait on the peer_atom / tr_peer refactor.
=> fix: do not crash when pruning idle peer atoms

macosx/Controller.mm
Fixes a crash on startup with some regional settings (I'm using French).
=> Fix: "Cannot begin activity without reason string or empty reason string"

daemon/transmission-daemon.service
I noticed that on startup the system.d service warns 
```
Jun 05 05:07:40 schwarzschild transmission-daemon[15562]: WARN: --log-error is deprecated. Use --log-level=error
```
which is easily fixed.
=> daemon: deprecated --log-error -> --log-level=error

macosx/Controller.mm, macosx/MainWindow.h, macosx/Mainwindow.mm, macosx/da.lproj/MainMenu.xib, macosx/de.lproj/MainMenu.xib, macosx/en.lproj/MainMenu.xib, macosx/es.lproj/MainMenu.xib, macosx/fr.lproj/MainMenu.xib, macosx/it.lproj/MainMenu.xib, macosx/nl.lproj/MainMenu.xib, macosx/pt_PT.lproj/MainMenu.xib, macosx/ru.lproj/MainMenu.xib, macosx/tr.lproj/MainMenu.xib
Fixes #1906.
Fixes #1903.
* Fixes for toggling status Bar, Groups, Compact view and Toolbar while in Fullscreen mode.
* Fixes window size when toggling Toolbar.
* Fixes toolbar button artefacts when toggling toolbar
=> more FullScreen fixes, and some toolbar animation fixes

macosx/CMakeLists.txt
add missing macOS icon asset to CMakeLists.txt.
Fixes #3199.
=> add gearshape template to macOS CMakeLists.txt

macosx/CreatorWindowController.mm, macosx/PrefsController.mm, macosx/da.lproj/Creator.xib, macosx/de.lproj/Creator.xib, macosx/en.lproj/Creator.xib, macosx/es.lproj/Creator.xib, macosx/fr.lproj/Creator.xib, macosx/it.lproj/Creator.xib, macosx/nl.lproj/Creator.xib, macosx/pt_PT.lproj/Creator.xib, macosx/ru.lproj/Creator.xib, macosx/tr.lproj/Creator.xib
* fixes a number of UI issues in the macOS torrent creator window mentioned in: https://github.com/transmission/transmission/issues/1891
* also fixes positioning of the source field, the piece info textfield, and the piece info stepper
* also updates the  tracker add/remove control to use the newer rounded rect style as in the rest of the UI
=> fix a number of UI render issues in the macOS torrent creator window

libtransmission/tr-strbuf.h
This should fix redundant redeclaration warnings for `tr_sys_path_dirname` mentioned in #3196
=> Move function declaration to scoped area

macosx/InfoPeersViewController.mm
various discussions on this... most recent is here:
closes https://github.com/transmission/transmission/pull/3217
=> replace macOS encrypted image on macOS 11+

macosx/AddMagnetWindowController.mm, macosx/Controller.mm, macosx/FileOutlineController.mm, macosx/FilePriorityCell.mm, macosx/PrefsController.h
Just fixing macOS warnings which are apparent when building with `make`
=> fix: macOS build warning "cannot find protocol definition for 'PortCheckerDelegate'"

gtk/DetailsDialog.cc, gtk/TorrentCellRenderer.cc
This fixes the strings erroneously marked as c-strings by gettext, so they make translation possible.
Fixes #3203.
=> fix: mark non-c-strings for gettext i18n

libtransmission/announcer-http.cc
=> fix: too-small scrape request packets may trip SYN flood detection

AUTHORS
Readd Dean Ostetto who was wrongly removed.
Add myself, since the proper authorship information in the Git history
is lost when squashing the commits.
My contributions so far are: Pull request #2875 merged with commit hash
`738431169cce5cc60e935df44d0616891162dee9`, pull request #2889 merged with
commit hash `8d11f0bc22ec7e1f87e573d1232e8faa72e745a3`, pull request #2900
merged with commit hash `7c76d40a4d8748199903cf0a9d7cd0e38ec9e3f1` and
pull request #2984 merged with commit hash `d8c5c6572559136569f00e0c9c3cb068b6256938`.
All are currently attributed to `maxz <6818198+maxz@users.noreply.github.com>`,
while I expected them to be attributed to `Max Zettlmeißl <max@zettlmeissl.de>`.
=> Update the AUTHORS file.

libtransmission/session.cc
This change has been in the back of my head since I made pull request #2984.
Dropping the zero does not change any of the behaviour.
And this way the format is more familiar to users of the unixoid
octal permissions. Those permissions would not be specified with
a leading zero.
If they were specified with a leading zero, it would mean that some
special permission bits (setuid, setgid or sticky) should be cleared.
Thus removing the leading zero in our settings format removes two
cases of possible confusion.
Additionally the permissions are always padded to three digits to avoid
strangely looking permission strings.
=> Drop the leading zero for permissions in the settings file.

libtransmission/rpcimpl.cc, libtransmission/torrent.h
=> fix: filename too long warning when adding magnet links

macosx/TorrentCell.mm
the current Group indicator PR #3183 uses bars. I feel using circles is a better fit with the overall theme of Transmission #3224 and macOS. Also added a similar style for the Compact view.
Uses the group icons images from @Coeur
=> replace macOS Groups indicators with dots

qt/FileTreeItem.h, qt/Filters.h, qt/IconCache.h, qt/MainWindow.h, qt/Prefs.h, qt/RpcQueue.h, qt/Session.h, qt/Speed.h, qt/Torrent.h, qt/TrackerModelFilter.h
does what it says on the tin: make simple getter methods in transmission-qt `[[nodiscard]] constexpr noexcept`.
=> refactor: make accessor functions constexpr

macosx/MessageWindowController.mm, macosx/en.lproj/Localizable.strings
=> [macOS] Fix assert on save for WARN and TRACE log levels in Log window.

macosx/GroupsController.mm, macosx/Torrent.mm, macosx/da.lproj/GroupRules.xib, macosx/de.lproj/GroupRules.xib, macosx/en.lproj/GroupRules.xib, macosx/es.lproj/GroupRules.xib, macosx/fr.lproj/GroupRules.xib, macosx/it.lproj/GroupRules.xib, macosx/nl.lproj/GroupRules.xib, macosx/pt_PT.lproj/GroupRules.xib, macosx/ru.lproj/GroupRules.xib, macosx/tr.lproj/GroupRules.xib
Rename issue after [this commit](https://github.com/transmission/transmission/commit/54d1a02e92d020374692d4fdb3a3d60eccd07560#diff-e7ff71cde5aad9e2a4a4a8d5994b8d10dc20400248a1dffb896ce322ebc9c543)
Allow execution of `NSPredicate` restored from new APIs in `NSKeyedUnarchiver` after [this commit](https://github.com/transmission/transmission/commit/aafedcaae11ef73a7008a4013c9a99cd3ad97bd8#diff-397f92b949bd7ee562d28e0a10c8ebd03d6bb24889e89efe302d484c9d6211ef)
Possibly fixes #3099.
=> [macOS] Fix Group auto-assigning based on NSPredicate

macosx/CMakeLists.txt
Icon was removed from project in #3178
=> macOS remove GearshapeTemplate from CMakeLists.txt

macosx/TorrentTableView.mm
Fixes #3293
P.S.
I think I should make solution more general and extract the logic to a separate class.
I want to illustrate:
If target view is not in the safe zone - NSPopover should be detached.
More specifically - target view rect should be inside safe zone rect for arrow to be displayed.
[There's already some APIs available for it](https://developer.apple.com/documentation/appkit/nsscreen/1388369-visibleframe?language=objc)
=> [macOS] Hide NSPopover Arrow for Torrent options.

libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/transmission.h
a minor cleanup refactor: `const`ify a couple of public methods that should've been const but had been overlooked.
=> refactor: make tr_sessionGetEncryption() const

libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/torrent.cc, libtransmission/torrent.h
Proposed PR makes Transmission to avoid reordering labels (because of using transitional `std::set`).
Removing duplicates implemented using trivial algorithm with `O(N^2)` complexity, but it should be ok since labels vector usually pretty small.
=> keep labels in order added, rather than alphabetically

web/src/torrent.js, web/src/transmission.js
I noticed that filtering in web client is broken. Proposed PR fixes state and labels filters. 
Tracker filter is broken too, I'm working on getting it fixed and planning to provide PR later.
Updated.
Fixed tracker filter withing a commit in the scope of the current PR. Fix is much simpler than I initially thought.
=> Web client: fix broken state and labels filter.

gtk/Application.cc, gtk/DetailsDialog.cc, gtk/DetailsDialog.h, gtk/Dialogs.cc, gtk/Dialogs.h, gtk/FileList.cc, gtk/FileList.h, gtk/Notify.cc, gtk/Notify.h, gtk/RelocateDialog.cc, gtk/RelocateDialog.h, gtk/Session.cc, gtk/Session.h, libtransmission/cache.cc, libtransmission/inout.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/torrents.cc, libtransmission/torrents.h, libtransmission/transmission.h, libtransmission/webseed.cc, qt/DetailsDialog.cc, qt/Torrent.h, qt/Typedefs.h, tests/libtransmission/torrents-test.cc
A minor cleanup PR: use the semantic type `tr_torrent_id_t` instead of `int` when referring to torrents by ID.
Since the former is an alias to the latter this doesn't involve any functional changes; it just expresses intent more clearly.
=> refactor: use tr_torrent_id_t

CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, macosx/Controller.mm, macosx/GroupsController.mm, macosx/GroupsPrefsController.mm, macosx/MessageWindowController.mm, macosx/TorrentCell.mm, macosx/TorrentTableView.mm
Looking at all comments in https://github.com/transmission/transmission/issues/3302 there seems to be a general agreement that 10.13 is a conservative value for `MACOSX_DEPLOYMENT_TARGET`. The corresponding Xcode is 10.
=> Raise minimum supported target to macOS 10.13 (High Sierra)

macosx/Credits.rtf
Fix links for libevent and Sparkle, which were out of date (libevent link was redirected, sparkle link was not reachable anymore).
=> Update links in macOS credits

macosx/AboutWindowController.mm
Do not use the deprecated `[NSAttributedString initWithPath:documentAttributes:]` method.
=> Fix NSAttributedString deprecation

libtransmission/torrent-magnet.cc, libtransmission/torrent-magnet.h, libtransmission/torrent.cc, libtransmission/transmission.h, macosx/Controller.h, macosx/Controller.mm
1. Open a magnet link
2. Open a corresponding torrent file
Expectation: metainfo should be added to Transmission
Actual result: metainfo is still missing and you get a popup about duplicate entry
=> Set torrent file's metainfo for magnets

Transmission.xcodeproj/project.pbxproj, macosx/CMakeLists.txt, macosx/Controller.h, macosx/Controller.mm, macosx/Toolbar.h, macosx/Toolbar.mm
since refactoring to use Autolayout, systems using the older style **Expanded** NSToolbar have issues when Showing/Hiding the toolbar. This PR addresses that
=> macOS fix Toolbar show/hide on macOS Mojave

macosx/PiecesView.mm
* remove gradient from pieces view background image - This looks out of place on macOS Monterey
* add Dark mode support to pieces view background image - This is only a very subtle change
=> macOS remove gradient from PiecesView

AUTHORS, docs/Bug-Submission.md, docs/Port-Forwarding-Guide.md, docs/Scripts.md, gtk/Application.cc, macosx/Credits.rtf, qt/AboutDialog.cc
- Update “Mac OS X” or “Mac OS” or “OS X” to the current naming: macOS.
- Except in older release notes, and historical information.
- Remove outdated info in two places (for Transmission 1.60, and Mac OS X 10.4 and older)
=> Rename Mac OS X to macOS

libtransmission/peer-msgs.cc
fix: assertion on magnet link receiving a have bitfield from peers
=> fixup! refactor: tr_peerMsgs.percentDone() (#3363)

libtransmission/peer-mgr.cc
A minor code modernization patch to tr_peerMgr: previously its timers were public raw pointers; now they're private and memory-managed `std::unique_ptr`s.
=> refactor: make tr_peerMgr.timers private std::unique_ptrs

macosx/InfoPeersView.xib
This is a minor _code change_ and not an icon fix, that will be of little interest to most. I'm not sure if i explained this particularly well the first time around. I'll try again.
This illustrates the current values for how the columns in the Peer Inspector can be maximised.
That 0 is the encryption column, and because it currently can't be minimised further, or maximised at all, it becomes stuck next to everything if it is moved from the far right of the inspector window.
This PR resolves that by adding maximum values to that column. This is how it looks on my current build.
=> Fix: Flexibility of the Encryption column

libtransmission/peer-mgr.cc
This is another incremental PR to decouple peer-mgr's different pieces. This step limits the scope / visibility of a lot of the file-visible code by either making them member functions of `tr_peerMgr` or `tr_swarm`, or by placing them inside namespaces.
No functional changes; just reducing scope / reducing visibility / decoupling code.
=> refactor: use namespaces in peer-msgs.cc

macosx/AddMagnetWindowController.mm, macosx/AddWindowController.mm, macosx/BlocklistDownloader.mm, macosx/BlocklistDownloaderViewController.mm, macosx/Controller.h, macosx/Controller.mm, macosx/CreatorWindowController.mm, macosx/MessageWindowController.mm, macosx/NSImageAdditions.mm, macosx/NSStringAdditions.h, macosx/PiecesView.mm, macosx/PrefsController.mm, macosx/ProgressGradients.mm, macosx/QuickLookPlugin/GeneratePreviewForURL.mm, macosx/StatsWindowController.mm, macosx/Toolbar.mm, macosx/Torrent.h, macosx/TrackerCell.mm
This doesn't include designated initializers refactoring.
=> [macOS] Apply ObjC modernizations once again.

macosx/MessageWindowController.mm, macosx/da.lproj/Localizable.strings, macosx/de.lproj/Localizable.strings, macosx/en.lproj/Localizable.strings, macosx/es.lproj/Localizable.strings, macosx/fr.lproj/Localizable.strings, macosx/it.lproj/Localizable.strings, macosx/nl.lproj/Localizable.strings, macosx/pt_PT.lproj/Localizable.strings, macosx/ru.lproj/Localizable.strings, macosx/tr.lproj/Localizable.strings
Discussion is in #3280.
Translators at Transifex prefer an unambiguous "Warning" as a noun for translation than a suspicious "Warn" as a verb that needs to be translated like a noun.
=> Fix Warn -> Warning

libtransmission/torrent-metainfo.cc, tests/utils/CMakeLists.txt, tests/utils/assets/bittorrent-v2-hybrid-test.show
Fix #3386
Test case updated to show lack of support for bep 47 relates to: #3387
=> Ensure hybrid torrents are handled correctly

libtransmission/peer-common.h, libtransmission/peer-msgs.cc, libtransmission/webseed.cc
No functional changes; this just changes the structure of the BitTorrent and Webseed peer parent class `tr_peer` to add a `requestBlocks()` method.
This is another prerequisite for https://github.com/transmission/transmission/pull/3372. I'm trying to lay the groundwork to 3372 incrementally in a series of single-topic PRs so that 3372 doesn't wind up being Too Big To Merge.
=> refactor: add tr_peer.requestBlocks()

libtransmission/utils.cc
There're places where e.g. `size_t` is used which may or may not match one of
`(u)intXX_t` types.
=> fix: Instantiate `tr_parseNum()` template using basic types

libtransmission/peer-common.h, libtransmission/peer-msgs.cc, libtransmission/webseed.cc
This is another PR in a small series (previous: #3384) to lay groundwork for #3372 by adding API to `tr_peer`. This PR exposes the peer's preferences of how many blocks it could request right now (e.g. by looking at the peer's reqq).
Essentially, what's happening here 3372 will change how & when we decide what blocks to request from which peers:
- Currently this is done bottom-up when the `tr_peer` decides that it's time and requests a list from the manager.
- 3372 will change it to be top-down where the manager decides that it's time and sends the peer a list.
=> refactor: add tr_peer.canRequest()

.gitmodules
Fixes https://github.com/transmission/transmission/issues/3414
This is a proposal for testing the update to 9.0.0
It switches the submodule to the upstream repo, if we want to retain the fork it needs to be updated
=> Update fmt to 9.0.0

libtransmission/peer-io.cc, libtransmission/peer-io.h
minor refactor to `tr_peerIo` to use a std container instead of a bespoke datatype.
TBH this is just nibbling around the real problem. I want to make `tr_peerIo` testable but there are so many interdependencies that I'm starting with these baby steps. :angry:
=> refactor: use std::deque for tr_peerIo.outbuf_info

libtransmission/crypto.cc, libtransmission/crypto.h, libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, tests/libtransmission/crypto-test-ref.h, tests/libtransmission/crypto-test.cc
This is prerequisite work necessary to make tr_handshake testable. I plan to record peer data for replay in unit tests; but before we can compare test result network traffic to prerecorded network traffic, the unit teats need to be able to inject non-random PadA and PadB segments during PE/MSE handshakes. Otherwise the comparisons in the unit tests will always fail.
=> refactor: migrate tr_crypto C functions to members

gtk/transmission-gtk.metainfo.xml.in
The body text omitted Linux as a platform; and a bit repetitious with its use of frontend/backend. Fixed.
=> Minor Gtk metainfo changes

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h
This adds a shim between the handshake code and the rest of the codebase to improve decoupling so that a followup PR can add handshake unit tests / regression tests.
The handshake code no longer directly relies on tr_torrent, tr_session, tr_dht, or tr_peerMgr.
=> refactor: decouple tr_handshake

gtk/TorrentCellRenderer.cc
fix: invalid fmt type when downloading metadata
CC @mikedld since this changes the strings for translation again :dizzy_face:
=> fixup! refactor: use fmt to build the GTK client's user-visible strings (#2788)

libtransmission/handshake.cc, tests/libtransmission/handshake-test.cc
During the MSE handshake, older code could keep a handshake alive even if PadA or PadB exceeded the maximum length (512 bytes). This fix terminates the handshake when either pad is too long.
=> fix: limit pad search during encrypted handshake

gtk/MakeDialog.cc, libtransmission/makemeta.cc, libtransmission/makemeta.h, macosx/CreatorWindowController.mm, qt/MakeDialog.cc, tests/libtransmission/makemeta-test.cc, utils/create.cc, utils/transmission-create.1
* libtransmission/makemeta.cc (tr_makeMetaInfo): new argument omitPII.
(tr_realMakeMetaInfo): skip addition of TR_KEY_created_by and
TR_KEY_creation_date if omitting PII.
* libtransmission/makemeta.h (tr_metainfo_builder, tr_makeMetaInfo):
new omitPII field and function argument.
* macosx/CreatorWindowController.mm: adjust call to tr_makeMetaInfo
default to false (maintains previous behaviour)
* gtk/MakeDialog.cc: adjust call to tr_makeMetaInfo default to false
(maintains previous behaviour)
* qt/MakeDialog.cc: adjust call to tr_makeMetaInfo default to false
(maintains previous behaviour)
* tests/libtransmission/makemeta-test.cc: adjust calls to
tr_makeMetaInfo defaulting to false.
* utils/create.cc: new '--omit-pii' option without one letter form.
* utils/transmission-create.1: document …
=> tr_makeMetaInfo: new anonymize option (closes #3420)

docs/Editing-Configuration-Files.md, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/session.cc, libtransmission/session.h
This PR adds possibility to user to set custom announce IP address. Announce IP is sent using `ip` URL parameter. UDP announce works for IPv4 addresses only. It addresses https://github.com/transmission/transmission/issues/2477 feature request.
I used https://github.com/transmission/transmission/pull/655 as a reference -- this PR in face a core part of https://github.com/transmission/transmission/pull/655 without GTK/QT clients' changes. It is intended that user will edit `settings.json` and set IP manually. `settings.json` example:
```
"announce-ip": "11.22.33.44",
"announce-ip-enabled": true,
```
- - - 
Since it is related to IP announce I'd like to ask a question here. Announce IP using `ipv4` and `ipv6` parameters looks like outdated legacy mechanism. I did a brief research and I'm …
=> Add announce-ip and announce-ip-enabled parameters.

macosx/Base.lproj/InfoOptionsView.xib
=> macOS fix clipping and crashing on the Info Inspector Options tab

libtransmission/platform.cc, libtransmission/session.cc
These warnings were harmless but annoying,  so this PR fixes the two that I know of.
- bandwidth-groups.txt
- user-dirs.dirs
Fixes #3500.
=> fix: silence "couldn't read file" warnings

libtransmission/platform.cc, libtransmission/platform.h, libtransmission/rpc-server.cc, libtransmission/rpc-server.h
Fix a very minor string leak: `tr_getWebClientDir()` would cache its value and never free it.
Now it's not cached in the function itself; the caller (tr_rpc_server's constructor) caches it in a member string instead.
=> fix: do not leak in tr_getWebClientDir()

libtransmission/platform.cc, libtransmission/torrent.cc, libtransmission/utils.h, tests/libtransmission/test-fixtures.h, tests/libtransmission/utils-test.cc
no functional changes; just removing a utility function that's not needed because we can use fmt::format()
=> refactor: remove tr_strvPath()

cli/cli.cc, gtk/Prefs.cc, gtk/main.cc, libtransmission/platform.cc, libtransmission/platform.h, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc, libtransmission/transmission.h, macosx/Controller.mm, qt/Application.cc, qt/Prefs.cc, tests/libtransmission/CMakeLists.txt, tests/libtransmission/assets/user-dirs.dirs, tests/libtransmission/platform-test.cc
Add tests for the following functions:
- tr_getDefaultDownloadDir()
- tr_getDefaultConfigDir()
- tr_getWebClientDir()
This _does_ involve a semantic change to this API: Previously, these functions returned `char const*` of strings that were permanently cached. That  permanent cache made testing difficult (and made Valgrind slightly sad), so I've removed the cache. Each call now returns a newly-allocated string.
Since `tr_getDefault*Dir()` were only called on startup they didn't really need the caching anyway. `tr_getWebClientDir()` was called more frequently by the web server, so this PR caches it as a const std::string property of tr_web_server.
=> test: add platform tests

gtk/Session.cc, libtransmission/crypto-utils-ccrypto.cc, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/transmission.h, macosx/Controller.mm, macosx/Torrent.h, macosx/Torrent.mm, tests/libtransmission/move-test.cc
A minor space-saving measure: This change removes 10 pointers from each tr_torrent object.
I'd appeciate code review for the `macos/Controller.*` and `macos/Torrent.*` changes from anyone in @transmission/contributors :smiley_cat:
=> refactor: replace per-torrent callbacks with per-session ones.

libtransmission/platform.cc, libtransmission/platform.h, libtransmission/resume.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/stats.cc, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/tr-dht.cc, libtransmission/transmission.h, tests/libtransmission/blocklist-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/move-test.cc, tests/libtransmission/open-files-test.cc, tests/libtransmission/remove-test.cc
No functional changes; this is another pathname cleanup refactor in libtransmission.
=> refactor: make tr_session's directory fields private

macosx/Controller.mm, macosx/GroupToolbarItem.h, macosx/GroupToolbarItem.mm
Fixes #3498
Will be simplified a lot when deployment target is 10.15
=> [macOS] Revamp Toolbar Segments

libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/blocklist.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-msgs.cc, libtransmission/session.cc, libtransmission/tr-dht.cc, libtransmission/web-utils.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/peer-msgs-test.cc
It's a redundant function: use `tr_address::fromString()` instead
=> refactor: remove tr_address_from_string()

libtransmission/platform.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/web.cc, tests/libtransmission/subprocess-test-program.cc, tests/libtransmission/utils-test.cc, utils/remote.cc
No functional changes; this is a cleanup PR to reduce the use of raw unmanaged pointers.
=> refactor: tr_env_get_string() now returns a std::string

libtransmission/session.cc, libtransmission/torrent.cc
Before trevent.cc got refactored, functions invoked via `tr_runInEventThread()` had to take a single `void*` callback data argument. 
Since the refactor, `tr_runInEventThread()` captures and forwards the arguments along to the event thread. We no longer need to create temporary `void*` user data struct that holds all the args.
=> refactor: remove tr_runInEventThread() temp data structs

libtransmission/utils.cc
Remove some byte-wrangling code; let `fmt::format_to_n()` do the heavy lifting.
=> refactor: reimplement tr_strlcpy() using fmt::format_to_n()

macosx/Base.lproj/InfoActivityView.xib, macosx/Base.lproj/InfoOptionsView.xib
unifies the margin between headers and content on the **Activity** tab and the **Options** tab in the **Info Window**
Fixes #3489.
**The General tab (unchanged):**
**Info Window - Activity/Options tabs Current:**
**Info Window - Activity/Options tabs with this PR:**
=> macOS small layout fixes to Info Window

libtransmission/handshake.cc
tiny handshake.cc refactor to avoid `tr_new()` / `tr_free()` when reading the peer's PadC
=> refactor: avoid unnecessary heap alloc when reading PadC

libtransmission/rpcimpl.cc
tiny RPC refactor to avoid an unnecessary `tr_new()` / `tr_free()` when sending a magnet link over RPC
=> refactor: avoid unnecessary heap alloc when sending magnet link over RPC

libtransmission/crypto-utils.h, libtransmission/peer-mgr-wishlist.cc, libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, tests/libtransmission/crypto-test-ref.h
There are a handful of places in libtransmission where an array of items is built and each item needs a field containing some random number as a sort key to introduce some randomness.
This  PR adds a small convenience class that effectively batches RNG calls for those random number fields. It calls `tr_rand_buf()` on a larger private buffer and then parcels out that data one byte at a time to client code.
=> perf: batch up calls to the RNG

gtk/MainWindow.cc, gtk/StatsDialog.cc, libtransmission/inout.cc, libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/stats.cc, libtransmission/stats.h, libtransmission/transmission.h, macosx/Controller.mm, macosx/StatsWindowController.mm, macosx/StatusBarController.mm
C++ify  the libtransmission tr_stats class.
Includes superficial changes to the clients because the public API changed slightly.
=> refactor: tr_stats

libtransmission/torrent-files.cc, news/news-4.0.0-beta-1.md
Finally fixing that missing `.` in `ReservedPrefixes`
Some extra spaces were automatically removed by my text editor.
=> Add some missing characters and remove extra whitespaces

libtransmission/port-forwarding.cc, libtransmission/session.cc, libtransmission/session.h
This socket binding code is still more complicated than it needs to be, but this PR removes some clumsy memory allocation logic by just aggregating the bindinfo fields directly in tr_session.
=> refactor: aggregate bindinfo in tr_session

libtransmission/rpc-server.cc, libtransmission/rpcimpl.cc, libtransmission/rpcimpl.h
This hasn't been used in ages, but the code never got removed. This PR removes it.
=> refactor: remove unused GET handler in rpc-server.cc

libtransmission/tr-dht.cc, libtransmission/utils.cc, libtransmission/utils.h
This was the last use of tr_memdup(), so remove that too. :tada:
=> refactor: remove closure struct in tr-dht

libtransmission/tr-getopt.cc, libtransmission/verify.cc
does what the description says; use fmt::format() when printing options.
=> refactor: use fmt::format() in tr-getopt

gtk/TorrentCellRenderer.cc
Replaced wrong variable for uploading speed for active torrent seeding
Fixes #3448 and #3357
=> fix: use correct variable for uploading speed

macosx/InfoWindowController.mm
=> macOS disable green maximize button on Inspector window

libtransmission/blocklist.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/file.h, libtransmission/makemeta.cc, libtransmission/open-files.cc, libtransmission/session.cc, libtransmission/torrent-files.cc, libtransmission/utils.cc, libtransmission/watchdir.cc, tests/libtransmission/copy-test.cc, tests/libtransmission/file-test.cc, tests/libtransmission/test-fixtures.h
Minor refactor to return a `tr_sys_path_info` by value instead of taking a pointer to it as an out argument.
=> refactor: tr_sys_path_get_info() now returns a tr_sys_path_info

libtransmission/bitfield.cc, libtransmission/block-info.h, libtransmission/completion.cc, libtransmission/torrent.cc, libtransmission/upnp.cc, libtransmission/variant.cc, libtransmission/watchdir-generic.cc, libtransmission/watchdir-inotify.cc, qt/AboutDialog.cc, qt/Session.cc, qt/TrackerDelegate.cc, qt/Utils.h
Fix a handful of warnings that were uncovered by trying a devel build of clang-tidy-15.
=> fix: clang-tidy-15 warnings

libtransmission/peer-msgs.cc
minor refactor to sendPex() to use `std::vector` instead of `tr_new() / tr_free()`
=> refactor: in sendPex(), reuse the temporary buffer

libtransmission/session.cc
This PR fixes https://github.com/transmission/transmission/issues/2983
Testing: I've simulated this feature in GTK client and now it works as expected -- function returns new correct port number, the same open port I see in `netstat`.
=> Fix broken tr_sessionSetPeerPortRandom() function.

macosx/MessageWindow.xib
fixes some clipping in the macOS Message Log window
fixes #3574.
**Before**
**After**
=> macOS convert message window to autolayout

.github/workflows/actions.yml, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/port-forwarding.cc, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/timer.h, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, libtransmission/tr-utp.cc, libtransmission/trevent.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/webseed.cc
- Replace all remaining uses of `evtimer` with `libtransmission::Timer`.
- Remove unused `tr_timerAdd()`
- Remove unused `tr_timerAddMsec()`
- Remove unused `tr_gettimeofday()`
=> refactor: timer pt 2

libtransmission/session.cc, libtransmission/session.h
An incremental refactor to `tr_session`.
Making `web_mediator_` private involved a little bit of groundwork to make the session init & set functions to be tr_session member functions, when they had previously been legacy C functions.
=> refactor: make tr_session.web_mediator_ private

libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc
No functional changes; just baby steps towards encapsulating pieces of tr_session.
=> refactor: make tr_session.queue fields private

libtransmission/peer-mgr.cc, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent-ctor.cc
No functional changes; just baby steps towards encapsulating pieces of tr_session.
=> refactor: make tr_session.peer_count private

macosx/PiecesView.mm, macosx/Torrent.mm, qt/RpcClient.cc
a small chore PR to continue reducing the instances of unmanaged heap-allocated memory, e.g. tr_malloc / tr_free
=> refactor: reduce use of tr_malloc / tr_free

.github/workflows/actions.yml, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h
these tests have been flaking out occasionally for awhile now. This _might_ fix it.
The main diff is that, when the test scaffolding is waiting for the torrent to finish verifying, it does so via `tor->verifyState() == TR_VERIFY_NONE`
=> test: possibly fix rename-test flakes

docs/Environment-Variables.md
As @ilf mentioned in https://github.com/transmission/transmission/issues/3651 TR_CURL_SSL_NO_VERIFY's documentation is missing. I decided to fix this documentation lack.
=> Add documentation for TR_CURL_SSL_NO_VERIFY environment variable.

libtransmission/rpcimpl.cc
- in the idle data struct, aggregate a variant instead of a pointer-to-variant
- manage the idle structs with new / delete instead of malloc / free
=> refactor: avoid tr_new in rpcimpl

libtransmission/quark.cc, libtransmission/utils.cc, libtransmission/utils.h, libtransmission/variant.cc
- use `new[]` and `delete[]` instead of `tr_new()` and `tr_free()`.
- but don't use std containers. Current plan is that `variant.h` needs to be safe for use by C code
=> refactor: avoid tr_new(), tr_free() in tr_variant

libtransmission/utils.cc
- avoid using `tr_new()` / `tr_free()` in `tr_main_win32()`.
- as a side refactor, add namespaces to utils.cc's impl / helper functions to reduce their scope in utils.cc. For example, it limits the visibility of `tr_main_win32()`'s helper functions to `tr_main_win32()` itself.
=> refactor: avoid tr_new() in tr_main()

libtransmission/utils.cc, libtransmission/utils.h, tests/libtransmission/utils-test.cc
it was only used as an impl helper, so make it private.
=> refactor: remove tr_utf8_validate() from public API

libtransmission/announcer-http.cc, libtransmission/web-utils.cc, libtransmission/web-utils.h, utils/show.cc
We previously had two separate implementations for URL escaping, but only one is needed.
=> refactor: use OutputIterator for url-escaped info hash strings

libtransmission/file-win32.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-macros.h, libtransmission/transmission.h, tests/libtransmission/session-test.cc
remove some unused code:
- remove tr_sessionSetRPCUrl()
- remove tr_sessionGetRPCUrl()
- remove TR_PATH_DELIMITER_STR
- remove native_local_path_prefix
- remove native_unc_path_prefix
and reduce the scope of some keys:
- make TR_DEFAULT_BIND_ADDRESS_IPV4 private
- make TR_DEFAULT_BIND_ADDRESS_IPV6 private
- make TR_DEFAULT_RPC_HOST_WHITELIST private
=> refactor: remove unused

libtransmission/announcer-http.cc, libtransmission/magnet-metainfo.cc, libtransmission/web-utils.cc, libtransmission/web-utils.h, libtransmission/webseed.cc, utils/show.cc
Taking a second run at this; yesterday's PR had a regression in it.
This PR removes redundant code for escaping characters in a URI
=> refactor: replace tr_http_escape() with tr_urlEscape()

libtransmission/session.h
fix a recent regression that caused shutdown to block.
=> fix: close all timers before destroying the event loop

libtransmission/torrents.cc
=> fix: 3579 assertion when RPC client asks for torrent-id 0

.gitmodules, CMakeLists.txt, Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/crypto-utils.cc, libtransmission/peer-mse.cc, libtransmission/peer-mse.h, libtransmission/tr-arc4.h, licenses/bsd-3-clause.txt
arc4 is using about 15% of CPU, so move it to where we can `constexpr` it.
CC @mikedld 
When built with `RelWithDebInfo` this gives enough improvement to make the change worthwhile. Performance in `Debug` builds is about the same. :man_shrugging:
=> refactor: aggregate arc4 into libtransmission

libtransmission/crypto-utils-ccrypto.cc, libtransmission/crypto-utils-cyassl.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/crypto-utils-polarssl.cc, libtransmission/crypto-utils.h, libtransmission/inout.cc, libtransmission/makemeta.cc, libtransmission/quark.cc, libtransmission/torrent-ctor.cc, libtransmission/verify.cc, libtransmission/watchdir-base.h, libtransmission/watchdir.cc, libtransmission/webseed.cc
- fix code smell warnings + minor perf by fixing warnings about unnecessary temporary objects
- rename `tr_sha1_digest_t::final()` as `finish()` since the former uses a C++ keyword
=> perf: sonarcloud warnings about temp objects

gtk/Actions.cc, gtk/Actions.h, gtk/Application.cc, gtk/MainWindow.cc, gtk/MainWindow.h, gtk/transmission-ui.xml
This is a draft of the changes discussed with @mikedld in https://github.com/transmission/transmission/pull/1759.
The current state is that the actions have been split into window actions, like "win.quit" and "win.alt-speed-enabled", and torrent actions, like "torrent.show-torrent-properties" and "torrent.torrent-start".
What's left to do is to actually disable the torrent action group when the torrent list is not focused. I don't know how to do that. I tried using `gtk_action_group_set_sensitive` but that is deprecated. I also tried inserting the action group into widgets related to the torrent list but that doesn't seem to work. Another thing I tried is setting all the actions' sensitivity in the view's focus events but these events don't seem to fire reliably.
I hope that somebody more …
=> gtk: Disable torrent actions that override text entry field actions

libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc, libtransmission/web.h
Looks like this issue causes bug reported in https://github.com/transmission/transmission/issues/3424.
When Transmission listens on both IPv4 and IPv6 interfaces IPv4 listen address
is always passed to CURL's `CURLOPT_INTERFACE`. In general it stays unnoticed but
if user has multiple IPv6 addresses configured on his system random (first?)
IPv6 address is used. It happens because passed value to `CURLOPT_INTERFACE`
is not correct -- IPv6 expected but IPv4 is passed.
I wanted to use single `publicAddress(tr_address_type type)`  instead of two separate `publicAddressV4()` and `publicAddressV6()` function, but including `net.h` causes compilation error `only libtransmission should #include this header`. Not sure how to solve it in other way.
=> Fix IPv6 announce socket binding interface.

libtransmission/quark.cc
Fix a dangling pointer bug introduced last week.
=> fixup! perf: sonarcloud warnings about temp objects (#3686)

libtransmission/tr-lpd.cc, libtransmission/tr-lpd.h
fix incorrect number of terminating \r\n characters at the end of an LSD announce message if no cookie is present.
=> fix: lpd fixup

gtk/MessageLogWindow.cc
`Glib::ustring::sprintf()` doesn't support formatting `std::string_view`. Use `fmt::format()` instead.
Broken in #3626 (7c5862a5f5).
=> Fix GTK client crash opening message log containing errors

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/net.cc, libtransmission/peer-io.cc, libtransmission/peer-mgr.cc, libtransmission/quark.cc, libtransmission/quark.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/handshake-test.cc, tests/libtransmission/rpc-test.cc
This adds an option to disable TCP connections. This is desirable for several reasons, but in my case it is due to congestion. Even one TCP connection can cause congestion on a normally functioning router and ISP, so the proposed solution in #1519 is not sufficient.
A few notes on this patch:
- it does not disconnect existing TCP connections or in progress handshakes when toggled
- it might disable web-seeds. unclear if this is desirable or not
- I only added UI for English on macOS, because those are what I use
=> option to disable TCP

libtransmission/inout.cc, libtransmission/peer-io.cc, libtransmission/torrent.cc
Fixes #3712.
For the "simple repro" testcase described in that issue, this change will set a torrent error and pause the torrent.
=> fix: when renaming local data files fails, set torrent error and pause it

libtransmission/torrent.h, libtransmission/transmission.h
it is only used via RPC, so remove it from the public C API in transmission.h.
=> refactor: remove tr_ctorSetBandwidthPriority() from public API

libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-msgs.cc
pt 1/n of tr_peerIo refactor.
The goal of the series is to remove the `tr_peerIoRef()` and `tr_peerIoUnref()` warts & use `std::shared_ptr<tr_peerIo>` instead.
This goal of this PR is to make `tr_peerIoFoo()` methods into `tr_peerIo::foo()` members. This means that followup PRs will be smaller because they won't have a hundred
```diff
- tr_peerIoReadFoo(msgs->io);
+ tr_peerIoReadFoo(msgs->io.get());
```
=> refactor: tr_peerIo read buffer

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/cache.cc, libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h, tests/libtransmission/handshake-test.cc
pt 3/3 of tr_peerIo refactor. Part 1 at #3732.
This PR replaces the manual refcounting in `tr_peerIo` with use of `std::shared_ptr`.
=> refactor: tr_peerIo ref, unref

libtransmission/peer-msgs.h, libtransmission/session.h, libtransmission/timer-ev.h, libtransmission/torrent.h, libtransmission/tr-strbuf.h, libtransmission/watchdir-base.h
Minor refactor / perf fix: remove unnecessary derived class default destructors.
=> refactor: remove unnecessary default destructors

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/rpc-server.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc, libtransmission/webseed.cc, tests/libtransmission/handshake-test.cc
There were some instances in the code where `std::shared_ptr` was being used instead of `std::unique_ptr` not for semantic reasons, but rather as a quick-and-dirty way of passing in a random deleter. This PR cleans that up.
=> refactor: prefer std::unique_ptr over std::shared_ptr

qt/TorrentDelegate.cc, qt/TorrentDelegateMin.cc
If torrent is paused progress_bar_state drops QStyle::State_Horizontal setting. This patch fixes this behaviour.
=> Fix a progressBar direction for QT 5.15 for paused torrents

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/webseed.cc
Minor cleanup; no functional changes.
- Add helper functions for creating `tr_peer_event` instances
- Use the helper functions in both peer-msgs and webseed
- Make the event enumeration an `enum class`
=> refactor: tr_peer_event

gtk/MainWindow.cc
This is https://github.com/transmission/transmission/pull/2201 with a fix for https://github.com/transmission/transmission/issues/3697: Instead of checking the global input focus the focus of the window is checked and when right clicking on the view it grabs the focus.
=> fix(gtk): fix conflicting hotkeys

libtransmission/clients.cc, tests/libtransmission/clients-test.cc
Add missing client names:
[Advanced Download Manager](https://play.google.com/store/apps/details?id=com.dv.adm&gl=US)
[LibreTorrent](https://gitlab.com/proninyaroslav/libretorrent)
=> Add Advanced Download Manager & LibreTorrent client names

gtk/Utils.cc
Current window management approach results in secondary windows being destroyed once they are hidden. Since those windows are managed by `std::unique_ptr<>`, we can't just [temporarily] increase their refcount to avoid use-after-free situation, so retrieve updated top-level windows list every time we hide one instead.
=> Don't crash when hiding top-level windows

libtransmission/session.h
shouldDeleteSource() was returning the same value as shouldPauseAddedTorrents()
=> fix tr_session::shouldDeleteSource()

utils/edit.cc, utils/transmission-edit.1
This PR addresses #3724. I would probably have preferred to use the same argument for the source in both transmission-add and transmission-edit utils but as '-r' was already taken I just went with the obvious '-s' for setting the source flag/tag instead.
=> transmission-edit: Allow changes to torrent source flag

libtransmission/announcer-http.cc
Fix the following warning emitted when using `-flto` with GCC 12.2.1:
```
libtransmission/announcer.cc:929:8: warning: type ‘struct announce_data’ violates the C++ One Definition Rule [-Wodr]
929 | struct announce_data
|        ^
libtransmission/announcer-http.cc:299:8: note: a different type is defined in another translation unit
299 | struct announce_data
|        ^
libtransmission/announcer.cc:931:15: note: the first difference of corresponding definitions is field ‘tier_id’
931 |     int const tier_id;
|               ^
libtransmission/announcer-http.cc:301:22: note: a field with different name is defined in another translation unit
301 |     tr_sha1_digest_t info_hash;
|
```
=> refactor: fix warning issued during LTO build

libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/torrent.h, libtransmission/verify.cc, libtransmission/verify.h, tests/libtransmission/file-test.cc, tests/libtransmission/rename-test.cc, tests/libtransmission/test-fixtures.h
This also adds a more reliable way for unit tests to know when a torrent is done being verified, which may ameliorate some of the CI flakes that deal with checking and/or moving local data.
=> refactor: move the verify worker thread into a wrapper class

qt/MakeDialog.cc, qt/MakeDialog.h, qt/MakeDialog.ui
Qt has been behind the GTK build insofar as the ability to select piece size on torrent creation for a while. This PR should sort that.
~Also, as there was some discussion around the upper bound (#3402) of piece sizes I've set it to 64MB and also bumped the GTK limit to match.~
=> Qt: Allow piece size selection on torrent creation

libtransmission/file-posix.cc
Fixes #3654 
Add fallback to other copy routines in case of error in previous attempt.
I tried to keep it generic, but for now it targets `EXDEV` error in `copy_file_range` explicitly.
For efficiency sake, I kept the tiered approach to available kernel routines which was previously selected by compile flags.
To do the fallback in runtime I had to duplicate some code. The effort to refactor this went a bit above the scope of a bugfix. At least for now it keeps the change readily accessible for review.
Added some comments for the one trying to clean this up.
**Functional changes:**
Previously:
Try one of `copy_file_range` or `sendfile64` in this order selected during compile time, if it fails exit `tr_sys_path_copy`
Use user-space copy if neither was available during compile time
Now:
First …
=> Add fallback for copy_file_range EXDEV error

libtransmission/file-posix.cc, libtransmission/session.h, libtransmission/transmission.h
fix minor clang-tidy warnings that came from #3756 and #3784.
No functional changes; just making clang-tidy happy.
=> fixup new minor warnings

libtransmission/file-posix.cc
When `transmission-daemon` is running with '--foreground' option, log messages are emitted to standard error, which may be referred to a tty. Since an attempt to `fsync()` tty is always an error, an extra `isatty()` precaution should be applied.
=> Do not fsync descriptor referred to a tty

CMakeLists.txt, daemon/daemon-posix.cc, daemon/daemon-win32.cc, daemon/daemon.cc, daemon/daemon.h
If `signalfd(2)` interface is available, prefer it over traditional signal
handlers. This is mostly intended to drop dedicated signal handling thread
and hook signal processing into `libevent` event loop in the most natural way.
=> daemon: use signalfd-based signal handling if available

qt/AddData.h, qt/MainWindow.cc, qt/MainWindow.h, qt/OptionsDialog.cc, qt/Session.cc, qt/Session.h
Fix a bug that made it difficult to add magnet links in transmission-qt when the Add dialog was enabled.
=> fix: qt open magnet dialog munges magnet url

qt/Formatter.cc, qt/Formatter.h
minor refactors in transmission-qt's Formatter class.
No translatable string changes, but time estimates now match those calculated in transmission-gtk
=> refactor: inline short Formatter utils

gtk/DetailsDialog.cc, gtk/PrefsDialog.cc
Fix the following warnings reported by `clang-16`:
```
----
gtk/DetailsDialog.cc:2135:10: warning: 'on_response' overrides a member function but is not marked 'override' [-Wsuggest-override]
void on_response(int response);
^
/usr/include/gtkmm-3.0/gtkmm/dialog.h:303:16: note: overridden virtual function is here
virtual void on_response(int response_id);
^
----
gtk/DetailsDialog.cc:2246:10: warning: 'on_response' overrides a member function but is not marked 'override' [-Wsuggest-override]
void on_response(int response);
^
/usr/include/gtkmm-3.0/gtkmm/dialog.h:303:16: note: overridden virtual function is here
virtual void on_response(int response_id);
^
----
gtk/PrefsDialog.cc:206:5: warning: '~DownloadingPage' overrides a destructor but is not marked 'override' …
```
=> gtk: fix warnings recently reported by clang-16

libtransmission/handshake.cc, libtransmission/peer-io.h, tests/libtransmission/file-test.cc
A minor refactor to help decouple handshake.cc from evbuffer.
=> refactor: add tr_peerIo::peek()

gtk/Application.cc, gtk/DetailsDialog.cc, gtk/Dialogs.cc, gtk/FileList.cc, gtk/FilterBar.cc, gtk/HigWorkarea.cc, gtk/IconCache.cc, gtk/MainWindow.cc, gtk/MakeDialog.cc, gtk/MessageLogWindow.cc, gtk/Notify.cc, gtk/OptionsDialog.cc, gtk/Prefs.cc, gtk/PrefsDialog.cc, gtk/RelocateDialog.cc, gtk/Session.cc, gtk/StatsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h
Newer versions (gtkmm 4 and its dependencies) of these libraries have switched from enums to enum classes. Wrap the names with macros to support both.
=> Support change to enum definitions in gtkmm/glibmm/pangomm

gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/RelocateDialog.cc, gtk/StatsDialog.cc
GTK 4 drops blocking `run()` method for dialogs. Switch to non-blocking `show()` to support both GTK 3 and 4.
=> Run GTK dialogs in non-blocking fashion

utils/remote.cc, utils/transmission-remote.1
Commit message should be self explanatory
closes #3817
closes #2299
=> utils/remote: add option to dump RPC response as JSON

qt/Torrent.cc, qt/Torrent.h, qt/TorrentFilter.cc
This is for issue #3796.
I don't like how complicated this turned out, but there are a lot of cases since each torrent can have either a normal limit, a limit of 0, or no limit at all.
The similar function `compareRatio` also accounts for the possibility that `ratio()` can be infinite, but I don't think this is actually possible because it could only result from a `downloadedBytes` of 0 which can't happen if you're seeding. Even seeding your own torrent the `downloadedBytes` is still positive. (If infinty is possible then we should probably also take care of `TR_RATIO_NA` in both functions.)
This commit also introduces some `-Wfloat-equal` warnings, but actually I think I'm right and the warning is stupid. If you really want to avoid the warning then I'll rearrange the code a bit to deal …
=> Qt: Correct 'Sort by Progress' for seeding torrents

libtransmission/.clang-tidy, libtransmission/announcer-http.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-msgs.cc, libtransmission/session.h, libtransmission/tr-udp.cc
This was also the last place in libtransmission's code where `malloc()` and `free()` were being used, so also add `cppcoreguidelines-no-malloc` to `libtransmission/.clang-tidy` :partying_face:
=> refactor: tr_globalIPv6() returns a std::optional<in6_addr>

libtransmission/clients.cc, tests/libtransmission/clients-test.cc
[BitTorrent Web](https://www.bittorrent.com/products/win/bittorrent-web-free/) "-BW" decades ago used by BitWombat, unlikely someone still uses it
[Free Download Manager 6](https://www.freedownloadmanager.org/) v6 uses "FD6<random>" as clientid, opposed to "-FD" used in v5
[Torch Browser](https://en.wikipedia.org/wiki/Torch_(browser))  uses "-TB" + last 4 digits of build number
=> add clientIDs for BitTorrent Web, Free Download Manager 6, Torch Browser

libtransmission/log.cc, libtransmission/tr-macros.h, tests/libtransmission/platform-test.cc, utils/edit.cc, utils/remote.cc, utils/show.cc
Use libfmt instead of print().
=> refactor: remove TR_PRIsv macros

libtransmission/blocklist.cc, libtransmission/blocklist.h, libtransmission/session.cc, libtransmission/session.h
As mentioned in https://github.com/transmission/transmission/pull/3835#discussion_r982744627 
Move the tr_session::loadBlocklists() function to BlocklistFile::loadBlocklists() and have the tr_session::initImpl() call it from there.
=> Blocklist/Session: move loadBlocklists function to BlockListfile struct

libtransmission/net.cc, libtransmission/net.h
I was working on a fix for #8345 last night and hit a point where `tr-dht.cc` needed to be able to convert a `tr_address` + `tr_port` into a `sockaddr`.
That already exists as a private method in `net.cc`, so this side PR exposes it as a public method in `tr_address`.
=> refactor: add tr_address::toSockaddr()

CMakeLists.txt
There should be only one commit with the name `4.0.0-beta.1`, so switch the `dev` setting back to true :smiley_cat:
=> chore: bump version to post-4.0.0-beta.1 dev

gtk/Application.cc
GTK 4 doesn't have an action button and uses standard close button in header bar instead, which works fine.
Broken-by: #3805
Fixes: #3888
=> Workaround about dialog closure with GTK 3

gtk/DetailsDialog.cc
Since we're already overriding `on_response()`, there's no point in connecting `signal_response` to it, making it being called twice.
Broken-by: #3781
=> Don't show duplicate add/edit tracker error dialogs

utils/remote.cc
Quite a simple fix for a funny-looking bug that I came across today
=> remote: fix invalid format string

libtransmission/port-forwarding-upnp.cc
Got error `FMT_STRING: identifier not found` due lack of include
=> Add missing include in port-forwarding-upnp.cc

macosx/Controller.mm
Also specify Unified Toolbar Style explicitly, as hiding title triggers Unified Compact style.
Fixes #3891
Signed-off-by: Dzmitry Neviadomski <nevack.d@gmail.com>
=> macos: Hide Title (App Name) on BigSur and later.

.github/workflows/actions.yml, gtk/CMakeLists.txt, qt/CMakeLists.txt
This allows to test against GTK 4 and Qt 6.
Changes to CMakeLists.txt files are non-functional and are meant to trigger the components rebuild, nothing more.
=> Add build job based on Fedora 37

docs/Building-Transmission.md
I was reading how to build from the *docs* folder and there git submodule doesnt have the recursive flag.
=> docs: git submodule on building should be recursive

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml
Problem: Several GitHub issues are hard to triage without asking for minimal information regarding which version of Transmission is being used.
Solution: We add a minimal GitHub issue template with all fields optional (to be welcoming), guiding the contributors on what minimal information would be appreciated.
Here is a screenshot, and you may temporary test it on https://github.com/Coeur/transmission/issues, but I'll disable and delete all issues on my fork once this PR is merge.
---
=> Adding ISSUE_TEMPLATE

macosx/CreatorWindowController.mm, macosx/FileOutlineController.mm, macosx/Torrent.mm
Problem: `__autoreleasing parent` is passed to a recursive concurrent method.
Solution: Adopt a recursive block and assign to `__autoreleasing parent` outside the block.
Testing: Create or open a torrent with directories inside; Open the torrent inspector; Open the files tab; Use the filter.
=> Fix "Capture of autoreleasing out parameter inside autorelease pool that may exit before method returns"

macosx/CocoaCompatibility.h
A recent build regression from #3919.
Just doing the minimal fix, as 4.0 will be the last Transmission version with support for Xcode 11.
=> Xcode 11.3.1 compatibility

gtk/Utils.cc
Calling such functions on e.g. Wayland GDK surfaces results in a crash.
=> Don't call X11 functions on non-X11 GDK surfaces

macosx/AboutWindowController.mm, macosx/BlocklistDownloaderViewController.mm, macosx/CreatorWindowController.mm, macosx/FileRenameSheetController.mm, macosx/GroupsPrefsController.mm, macosx/StatsWindowController.mm, macosx/URLSheetWindowController.mm
The commit date is "3 February 2019" and it't not an error... I started this long time ago. ^_^
In some sort, this is the continuation of #1579 which did part of what I was originally attempting to address in #827.
Fix 1: `NSApp endSheet:` is deprecated:
>NSWindow's -beginSheet:completionHandler: and -endSheet:returnCode: should be used instead.  NSApplication's -beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo: will continue to work as it previously did, leaking contextInfo and failing when there is already an existing sheet.
Fix 2: `orderOut:` is not needed when using `beginSheet:`.
Testing:
I tested all those changes on both macOS Ventura 13.0 and macOS Mojave 10.14.6.
- Closing the License sheet
- Closing the Blocklist sheet
- Closing the GroupRules sheet
- Closing …
=> Fix 'modalDelegate:' is deprecated to avoid contextInfo leaks.

libtransmission/session.cc, libtransmission/session.h
supersedes https://github.com/transmission/transmission/tree/refactor/session-field-order.
This is a more incremental version of that PR and should be ready for merging. No behavioral changes and  does not fix the crash-on-shutdown problem.
Ultimately the crash-on-shutdown problem will be solved by reducing coupling between tr_session's fields and destroying them in the correct sequence when the `tr_session` is destroyed. To make that future work easier, this housekeeping PR reorganizes the `tr_session` class declaration into this order:
- classes and types
- constructor
- methods
- constexpr fields
- const fields
- trivial fields
- loosely-coupled fields
- other fields
=> refactor: tr_session declaration cleanup

libtransmission/announcer-http.cc, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/rpcimpl.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, libtransmission/tr-utp.cc, libtransmission/webseed.cc
A followup to #3958.
No functional changes; doesn't fix the crash-on-shutdown problem.
This is an incremental janitorial PR that makes more `tr_session` fields private to reduce coupling.
=> refactor: session private fields

gtk/Session.cc
In GLIB 2.68+ `Glib::RefPtr<>` is an alias for `std::shared_ptr<>` which has no idea about GLIB's reference counting, thus destroying the object instead of unreferencing it. Use `Glib::make_refptr_for_instance()` to construct the smart pointer which passes in a custom reference-aware deleter for us.
Fixes: #3954
=> Fix session use after free (GTK client)

libtransmission/dns-ev.h, libtransmission/dns.h, tests/libtransmission/dns-test.cc, tests/libtransmission/net-test.cc
A followup to #3977 for caching addresses
- add `dns.cached()` which only queries the cache, returning immediately & not running an async lookup
- the `lookup()` callback now also has a TTL argument
=> feat: add libtransmission::Dns.cached()

utils/remote.cc
fix: invalid format string passed to fmt::print. This bug first appeared in 4.0.0-beta.1
=> fixup! refactor: remove TR_PRIsv macros (#3842)

macosx/MessageWindow.xib
Fix: #3627 
This commit:
- Set the minimum size of the Message column of the message log window to 200 (previously was 10) to fix #3627
- Align the log level indicator to the top
Previously:
=> Update to the message log window on macOS

macosx/BlocklistDownloader.mm
fixes a potential hang when updating the blocklist on macOS via gunzip
see here for more details:
https://github.com/transmission/transmission/issues/3969
* Added the `--force` flag to NSTask to overwrite any previously interrupted downloads
=> macOS fix a potential hang when updating the blocklist

libtransmission/rpcimpl.cc
Fixes #2916.
Not actually a Transmission bug, but restores undefined behavior to be consistent with 3.00's undefined behavior in the RPC spec.
=> fix: ignore unrecognized torrent-get fields

libtransmission/peer-msgs.h, tests/libtransmission/peer-msgs-test.cc
Removing declaration for a function which itself was removed in #3764.
=> Remove tr_generateAllowedSet declaration

libtransmission/bandwidth.cc, libtransmission/file-posix.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-msgs.cc, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/timer-ev.cc, libtransmission/torrent-magnet.cc, libtransmission/torrent-magnet.h, libtransmission/tr-buffer.h, libtransmission/transmission.h
Fix nonportable use of `ssize_t` by changing code to return a `size_t` and take a `tr_error` argument to record error cases.
The alternative would be to import `ssize_t` in from either libevent or from libutp, but using `tr_error` is more consistent with how other libtransmission API handles error cases.
This changes some pretty central code that doesn't have good testing coverage, so I'm going to testdrive this for a little while and do another code review before merging. I've read over it and don't see any issues yet, but I'd like to treat this with a little caution.
=> fix: FTBFS on Windows

macosx/Controller.mm, macosx/FileOutlineController.mm, macosx/FilterBarController.mm, macosx/GroupsController.mm, macosx/NSStringAdditions.h, macosx/SparkleProxy.mm
This fixes the localization warnings that were recommended by #3940.
The documentation of NSMenu says that the title is being ignored for our usage, so no need to localize it.
Alternatively, for debugging purposes, we could keep that non-displayed string and proxy it through `LocalizationNotNeeded`.
=> Fix "User-facing text should use localized string macro"

web/webpack.config.js
I found 'ERROR in Conflict: Multiple assets emit different content to the same filename transmission-app.js.map'  msg occurs everytime code changes during dev mode.
This commit resolves the error message.
=> chore: get rid of webpack error while creating source map

web/assets/css/transmission-app.scss, web/src/open-dialog.js
Comparing with 3.0 web interface, open torrent dialog layout has no margin between items.
3.0
Current 4.0
Adjusted
=> fix: open torrent dialog layout adjusted

macosx/FilterBar.xib, macosx/FilterBarController.mm
Basic implementation.
It may not be the most reactive design, but it solves the issue that previously the search string was always hidden for users on a narrow window.
https://user-images.githubusercontent.com/839992/199260091-8e7035b9-e687-474f-810d-559b5e0de51f.mov
=> Auto enlarge search field when editing

.github/workflows/actions.yml
37 is still "rawhide" and it starts to pull in packages from 38 making things weird.
=> Downgrade Fedora image used in GitHub Actions CI to 36

cmake/FindUTP.cmake
Since libutp provides no version information, and one readily noticeable change between the old and the new API is the change in public function names, check to see if the functions we use are available. Old version won't have them, and so any old system libutp will be discarded in AUTO mode and result in an error in ON mode for USE_SYSTEM_UTP option.
Fixes: #3543
=> Check for functions we use when looking for system libutp

libtransmission/blocklist.cc, libtransmission/blocklist.h, libtransmission/net.h, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/blocklist-test.cc
* Replace the `AddressRange` struct with a `std::pair<tr_address, tr_address>`: The `AddressRange` searching / sorting code is complicated and hard-to-read. The pre-existing `tr_address` class already handles comparisons and has test coverage. The blocklist ascii file parsers even generate `tr_address` temporary objects before converting them into `AddressRange. So a lot of complex, redundant code goes away if we remove `AddressRange`.
* Embed a format version string at the front of each `.bin` file. This makes it simpler to sniff out incompatible binary files without rules that sniff around address data.
* Make blocklists std::movable. This was disabled once upon a time because each object held an fd to a memory-mapped file, but not anymore. This also means we can use …
=> refactor: simplify blocklist code

web/assets/css/transmission-app.scss, web/stylelint.config.js
Currently mime icons are not shown properly in Chrome. To fix this, vendor prefix(-webkit-) should be added to style.
(https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image#browser_compatibility)
And I'm not sure if I'm allowed to change stylelint config, but I added "property-no-vendor-prefix": null in it.
=> fix: chrome needs vendor prefix(-webkit-) for mask

web/assets/css/transmission-app.scss
- vendor prefix(-webkit-mask) added for icons in inspector dialog (for Chrome)
- When overflow menu opened in chrome, there is scroll bar(x, y) even it's not needed. set overflow to auto and it solved.
=> fix: some style edited for chrome

libtransmission/platform.cc
=> Fix web client directory name on Windows

libtransmission/blocklist.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/port-forwarding.cc, libtransmission/port-forwarding.h, libtransmission/session.cc, libtransmission/session.h, tests/libtransmission/net-test.cc
A smaller PR in the tr_session Lifecycle PR Arc.
- Add `BoundSocket` whose constructor binds a socket & uses libevent to monitor it for incoming connections. The destructor cleans it all up and closes the socket. Unlike the `tr_bindinfo` class that it replaces, does not rely on / does not know about tr_session internals
- `tr_session::publicAddress()` no longer requires the bound sockets. This fixes a minor regression when TCP is disabled.
- Add helper function `tr_session::setSettings(tr_session_settings)` that can be used to make settings changes in a single batch. This is useful because some changes can have side-effects that need to be applied in a specific order. `setSettings()` handles knowing this sequencing so simplify callers' responsibilities.
- Minor perf: replace …
=> refactor: replace tr_boundinfo with tr_session::BoundSocket

libtransmission/peer-mgr.cc
Fix #4106
fun fact: rechokePulseMarshall was introduced by a PR related to unique_ptr (#3366) and broken by a PR related to unique_ptr (#4069)
=> Fix "upload/download connectivity is broken"

macosx/Torrent.mm
=> Fix: values above INT_MAX (68 years) are interpreted as negative values

macosx/BadgeView.mm
For all that is holy, upload should be above download when these two actions happen simultaneously.
=> macOS: Change BadgeView.mm so that up is up and down is down

web/src/action-manager.js
I think 'show-inspector' icon should be set to disabled as default like other default disabled icons like trash, resume, and pause.
Currently the icon is enabled when load web interface or refresh it, then it switches to disabled soon. Even it stays enabled when there is no torrent in the list.
=> fix: inspector icon should be disabled as default

libtransmission/timer-ev.cc
Minor perf: Instead of creating new events, use event_asign() to update existing ones.
=> perf: reuse existing evtimers instead of creating new ones

Transmission.xcodeproj/project.pbxproj, libtransmission/session.h
Fix #4108
I'm not expert in C++, so I just applied to session.h the syntax found in session-thread.h:
https://github.com/transmission/transmission/blob/162035a65397fb3977ad67e33e24938a971b2ffe/libtransmission/session-thread.h#L37
=> Fix "Forwarding reference passed to std::move"

macosx/AddMagnetWindowController.mm, macosx/AddWindowController.mm, macosx/BadgeView.mm, macosx/BlocklistDownloader.mm, macosx/BlocklistDownloaderViewController.mm, macosx/BlocklistScheduler.mm, macosx/CreatorWindowController.mm, macosx/FileListNode.mm, macosx/FileNameCell.mm, macosx/FilterBarController.mm, macosx/GroupsController.mm, macosx/GroupsPrefsController.mm, macosx/InfoActivityViewController.mm, macosx/InfoFileViewController.mm, macosx/InfoGeneralViewController.mm, macosx/InfoOptionsViewController.mm, macosx/InfoPeersViewController.mm, macosx/InfoTrackersViewController.mm, macosx/InfoWindowController.mm, macosx/MessageWindowController.mm, macosx/PortChecker.mm, macosx/PrefsController.mm, macosx/StatsWindowController.mm, macosx/StatusBarView.mm, macosx/Torrent.mm, macosx/TorrentCell.mm, macosx/TorrentTableView.mm, macosx/TrackerCell.mm, macosx/URLSheetWindowController.mm
In Objective-C, declaring methods in the private interface is superfluous at least since Xcode 5.0. We only support Xcode 11.3.1 or newer.
=> Removing superfluous interface declarations

gtk/.clang-tidy, gtk/Actions.cc, gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/FilterBar.cc, gtk/FreeSpaceLabel.cc, gtk/Notify.cc, gtk/PrefsDialog.cc, gtk/Session.cc, gtk/Session.h, gtk/TorrentCellRenderer.cc, gtk/Utils.cc, gtk/Utils.h
Of the four disabled `readability` checks, three (`function-cognitive-complexity`, `identifier-length`, `magic-numbers`) require extensive refactoring and were left for later, and one (`redundant-access-specifiers`) is not planned to be fixed due to the current coding style - using extra sections to separate methods from variables of the same visibility.
=> Fix issues reported by clang-tidy `readability` checks (GTK client)

libtransmission/session-thread.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc
Another `tr_session` Lifecycle Arc PR.
Still doesn't _totally_ fix the crash-on-shutdown problem but the number of possible failures is getting ever-smaller.
=> refactor: fix thread sanitizer warnings in tr_sessionClose()

tests/libtransmission/test-fixtures.h
fix: thread-sanitizer warnings in SandboxedTest::blockingTorrentVerify
fix: thread-sanitizer warnings in SandboxedTest::createTorrentAndWaitForVerifyDone()
=> fix: thread-sanitizer warnings in SandboxedTests

docs/Building-Transmission.md
This removes:
- docs for building on Debian Squeeze, which has been end of life for a long time now.
- Switches for now unsupported ./configure script
- "Normal"-section about dependencies on Unix, since they're outdated and some of them are not even needed anymore
- tarball build instruction, because it's outdated like "Normal"-section
Added:
- Instructions for building daemon, GTK 3 and QT 5 clients on Debian 11
I've tested the added docs on freshly installed Debian virtual machines with both Gnome and Kde desktop environments.
=> Update building docs for Debian

gtk/.clang-tidy, gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/FilterBar.cc, gtk/MainWindow.cc, gtk/MessageLogWindow.cc, gtk/Prefs.cc, gtk/PrefsDialog.cc, gtk/TorrentCellRenderer.cc, gtk/Utils.cc
Enable all `modernize` checks except for one (`use-trailing-return-type`) which is an extensive stylistic change for later.
=> Fix issues reported by clang-tidy `modernize` checks (GTK client)

Transmission.xcodeproj/project.pbxproj, macosx/CMakeLists.txt, macosx/CocoaCompatibility.h, macosx/GroupsController.mm, macosx/NSKeyedUnarchiverAdditions.h, macosx/NSKeyedUnarchiverAdditions.mm, macosx/SparkleProxy.mm, macosx/TorrentTableView.mm
Problem: NSUnarchiver is deprecated but we need it for data archived with Transmission 3
Solution: We silence the warning for as long as Apple supports this class
=> ignoring deprecation warning on NSUnarchiver

gtk/.clang-tidy, gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FaviconCache.cc, gtk/FileList.cc, gtk/FilterBar.cc, gtk/MainWindow.cc, gtk/MakeDialog.cc, gtk/MessageLogWindow.cc, gtk/Notify.cc, gtk/OptionsDialog.cc, gtk/PathButton.cc, gtk/Prefs.cc, gtk/PrefsDialog.cc, gtk/Session.cc, gtk/SystemTrayIcon.cc, gtk/TorrentCellRenderer.cc, gtk/TorrentCellRenderer.h, gtk/Utils.cc, gtk/Utils.h, gtk/main.cc
Enable all `cppcoreguidelines` checks except for three (`avoid-magic-numbers`, `avoid-non-const-global-variables`, `narrowing-conversions`) which require [more] extensive refactoring and were left for later.
=> Fix issues reported by clang-tidy `cppcoreguidelines` checks (GTK client)

libtransmission/web.cc
clear CURLOPT_CAINFO, CURLOPT_CAPATH iff verification is disabled.
This prevents curl from re-checking this each time when verification is disabled
=> refactor: better TR_CURL_SSL_NO_VERIFY

macosx/Controller.mm, macosx/InfoWindowController.mm
Problem: VoiceOver will say "YingYangGroupTemplate" or "radiowaves".
Solution: Replace image accessibilityDescription with tooltip description.
=> Accessibility description for images

libtransmission/verify.cc, libtransmission/verify.h
Previously was doing it manually with a looped `tr_wait_msec()`
=> refactor: use condition_variable in tr_torrent_verifier.remove()

gtk/MainWindow.cc, gtk/Utils.cc, gtk/Utils.h
View-relative coordinates were treated as bin window-relative, leading to incorrect selected item calculation.
Broken since the introduction of GTK 4 support in #3916.
=> Fix incorrect selection behavior when building against GTK 4

tests/libtransmission/timer-test.cc
These 25ms timers are not repeatable enough on the CI boxes.
=> test: increase timer interval in TimerTest.repeatingThenSingleShot

libtransmission/file-posix.cc, libtransmission/file-win32.cc, libtransmission/file.h, tests/libtransmission/file-test.cc
I thought I did this when refactoring `tr_sys_path_dirname()`, but apparently not.
=> perf: tr_sys_path_basename() returns a std::string_view

Transmission.xcodeproj/project.pbxproj
Problem: when changing commit, version.h isn't regenerated and the build hash version becomes incorrect
Solution: always regenerate version.h
=> Fix incorrect build hash when building with Xcode

Transmission.xcodeproj/project.pbxproj, macosx/CMakeLists.txt, macosx/NSDataAdditions.h, macosx/NSDataAdditions.mm, macosx/Torrent.mm
Fix #3434
This solves downloading torrents with filenames in non-UTF8 (like Japanese).
The solution comes essentially from encoding auto-detection with https://developer.apple.com/documentation/foundation/nsstring/1413576-stringencodingfordata.
(this PR is complementary to #3442, as to prevent crashes on launch or similar nastiness on corrupted torrents)
=> Fix crash on torrent filenames in non-UTF-8 encoding

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/announcer.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/torrent.cc, tests/libtransmission/announcer-udp-test.cc
- make tr_announcer a class that is owned by tr_session via a unique_ptr
- reduce use of new / delete in announcer module
- begin limiting scope inside announcer.cc by making some fields, methods private. (de-C-ification)
=> refactor: incremental announcer refactor pt. 2

libtransmission/announcer.cc, libtransmission/crypto-utils.cc, libtransmission/peer-io.h, libtransmission/peer-mse.cc, libtransmission/peer-mse.h, libtransmission/port-forwarding-upnp.cc, libtransmission/tr-arc4.h, libtransmission/watchdir-inotify.cc
Instead of having each peer connection instantiate a new arc4 filter + new encode + new decode objects & wrapping them in `std::unique_ptr`s, just aggregate them into each peer to avoid extra heap allocations & fragmentation.
=> refactor: aggregate dh in peer io

libtransmission/bandwidth.cc, libtransmission/peer-mgr.cc, libtransmission/resume.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/torrent.h
More performance microimprovements found from profiling. 
- make tr_torrentGetActivity() constexpr
- reduce the number of mutex locks in tr_bandwidthPulse()
- lazy-calculate tr_swarm_stats.active_webseed_count
=> perf: constexpr and move work outside of loops

libtransmission/announcer.cc
fixes #4222.
Checks to ensure that the session is still managing the announcer before using it in scrape & announce responses.
=> fixup: heap-use-after-free in announce, scrape response on shutdown

gtk/DetailsDialog.cc
Fix broken ETA formatting in the GTK client's display dialog.
=> fix: eta display in GTK client details dialog

gtk/DetailsDialog.cc, libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/bandwidth.cc, libtransmission/peer-mgr.cc, libtransmission/peer-mse.h, libtransmission/session.cc, tests/libtransmission/bitfield-test.cc
Fix new warnings found by gcc, Sonarcloud, and Coverity.
These are small changes, but since this touches some code that y'all have been working in recently, courtesy CC to @mikedld for changes to GTK DetailsDialog and to @Coeur for implicit conversions in libtransmission. Code review welcome but not required :smile_cat:
=> fix: new sonarcloud, coverity, gcc warnings

macosx/Controller.h, macosx/Controller.mm, macosx/DragOverlayWindow.h, macosx/DragOverlayWindow.mm
Another deprecation biting the dust.
This time, NSFilenamesPboardType and NSURLPboardType.
I tested the change is non-breaking by drag&dropping files and urls.
=> Fix "NSFilenamesPboardType is deprecated"

Transmission.xcodeproj/project.pbxproj
Fix a build regression from #4195.
And I hope to get Transmission 4.0 released soon: I don't want to maintain Mojave forever. :)
=> Fix building on macOS Mojave

gtk/FaviconCache.cc, gtk/Session.cc, libtransmission/announcer-http.cc, libtransmission/handshake.cc, libtransmission/peer-msgs.cc, libtransmission/rpc-server.cc, libtransmission/session.cc, libtransmission/verify.cc, libtransmission/verify.h, qt/FileTreeItem.cc, tests/libtransmission/file-test.cc
Another pass at lowering the open issue count at Coverity and Sonarcloud.  Most of these just silence / fix ordinary warnings, but three edge-case bugs are fixed:
- fix a potential nullptr dereference in clientGotBlock()
- fix a potential negative array index in FileTreeItem::row()
- fix a potential incorrect comparison when sorting by ETA and two torrents have the same ETA
=> fix: coverity warnings, sonarcloud code smells

macosx/CMakeLists.txt
Fix build regression from #4147
Tested: Sparkle and User Notifications are still working with this change.
=> Fix building with cmake on macOS Mojave

libtransmission/peer-io.cc
See https://github.com/transmission/transmission/issues/2996#issuecomment-1164703109 and https://github.com/transmission/transmission/issues/4233#issuecomment-1326682226
>Trying to interpret the code that leads to "utp_on_error -- errcode is 2", it seems to theoretically happen after 2-4 absences of responses:
https://github.com/transmission/libutp/blob/bf695bdfb047cdca9710ea9cffc4018669cf9548/utp_internal.cpp#L1187-L1191
>
>...with a timer set to fire every 50-150ms:
https://github.com/transmission/transmission/blob/6b861806a653c6490c247819f7959ca39f54e752/libtransmission/tr-utp.cc#L160-L163
>
>So total it seems equivalent to a peer not connecting in less than 0.1s-0.3s.
=> refactor: log UTP_ETIMEDOUT errors to 'trace' messages

libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/peer-mgr-wishlist.cc, libtransmission/peer-mse.cc, libtransmission/rpc-server.cc, libtransmission/session-id.cc, libtransmission/tr-dht.cc, libtransmission/tr-lpd.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/clients-test.cc, tests/libtransmission/completion-test.cc, tests/libtransmission/crypto-test-ref.h, tests/libtransmission/dht-test.cc, tests/libtransmission/handshake-test.cc, tests/libtransmission/lpd-test.cc, tests/libtransmission/magnet-metainfo-test.cc, tests/libtransmission/test-fixtures.h
There are a lot of places in the codebase where we need to populate an integral type or a fixed-size array with random data. To do this, we instantiate a local on the stack, fill it with tr_rand_buffer(), and then use it.
This PR creates a helper function to make this a one-liner.
=> refactor: add tr_rand_obj()

macosx/MessageWindow.xib, macosx/MessageWindowController.mm
This addresses #4233 for macOS only. I'll leave the GTK fix to someone else.
The issue with Trace messages on macOS is:
- well, unsupported by default (we read from the default config, which sets the level to DEBUG)
- and attempting to support it would overwhelm the app just like described in #4233
=> feat: remove option to show trace messages in UI because it floods the log

libtransmission/announcer-common.h, libtransmission/announcer.cc
Discussed in part [here](https://github.com/transmission/transmission/pull/4235#issuecomment-1327815003).
This PR changes the key type from `int` to `uint32_t` to more accurately reflect BEP 15.
=> refactor: make tr_announcer.key a uint32_t

libtransmission/file.cc, libtransmission/file.h
`TR_NATIVE_EOL_STR` and `TR_NATIVE_EOL_STR_SIZE` are only used in one function, so remove them from the global namespace.
=> refactor: reduce scope of TR_NATIVE_EOL_STR, TR_NATIVE_EOL_STR_SIZE

libtransmission/torrent.cc, libtransmission/utils.cc, libtransmission/variant-json.cc, qt/FreeSpaceLabel.cc
Use `std::optional.value_or()` to simplify the code a little.
Fixes Sonarcloud cpp:S6023 warnings.,
=> refactor: use std::optional.value_or()

libtransmission/peer-io.cc, libtransmission/tr-buffer.h
The use of `tr_buffer::Iterator` -- even though it got a speedup in #4220 -- is still using too much CPU in `tr_peerIo::write()`. Change write() to avoid it.
Notes: Lowered CPU overhead in `tr_peerIo::write()` when writing to encrypted streams.
=> perf: remove cpu bottleneck in tr_peerIo::write()

libtransmission/torrent.cc
Fixes #4259.
Notes: Fixed `4.0.0-beta.1` regression that broke the `TR_TORRENT_LABELS` environment variable when running user scripts.
=> fix: TR_TORRENT_LABELS env var in scripts

libtransmission/peer-msgs.cc, libtransmission/rpc-server.cc, libtransmission/rpc-server.h, libtransmission/session.h, libtransmission/tr-lpd.cc, libtransmission/utils-ev.h
Small code cleanup: add an RAII helper for managing evhttp objects.
=> refactor: add std::unique_ptr<evhttp> handler to utils-ev

libtransmission/announcer-http.cc, libtransmission/bandwidth.cc, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/tr-lpd.cc, libtransmission/variant-benc.cc, libtransmission/variant-json.cc, libtransmission/verify.h, libtransmission/webseed.cc
Literally just making variables `const`.
Addresses a handful of cpp:S5350 sonarcloud warnings.
=> refactor: make some local pointer vars pointer-to-const

CMakeLists.txt, gtk/PrefsDialog.cc, qt/PrefsDialog.cc
These are not needed anymore after #893.
Fixes #309.
=> refactor: remove references to FD_SETSIZE

gtk/FaviconCache.cc, libtransmission/announcer-http.cc, libtransmission/web.cc, libtransmission/web.h
Minor improvement to GTK's favicon lookup to handle cases. Basically this is better handling of failure cases.
- We have a list of file suffixes to try, e.g. `.ico`, `.png`, etc. and in the past have kept trying until we got a hit. Now, check for a response code of 0 so that we don't keep trying for unreachable servers.
- Set the timeout to 15s; previously used the default of 120s. Favicons are _small_ and shouldn't take two minutes to get.
CC @mikedld
=> refactor: GTK favicon lookup improvements

libtransmission/announcer-common.h, libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc
TCP and UDP announces had been using different timeout values. This PR makes them consistent.
=> refactor: UDP and TCP announces use same timeout interval

libtransmission/announcer-udp.cc, libtransmission/announcer.cc, libtransmission/announcer.h, libtransmission/session.cc, tests/libtransmission/announcer-udp-test.cc
Move announcer shutdown responsibilities from `tr_announcer_udp` to `tr_announcer`
=> refactor: add tr_announcer.startShutdown()

utils/show.cc
In transmission-show, use the `tr_web` wrapper instead of using libcurl directly.
Since transmission-show is reasonably small, this provides a nice way to expose`tr_web` code to sanitizer tests.
=> refactor: use tr_web instead of curl in transmission-show

libtransmission/session.cc
This prevents uTP callbacks from being routed to other pieces that have already been shutdown. :boom:
=> fix: shut down utp sooner during session shutdown

libtransmission/bandwidth.cc, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h
1. Fix the modulo bias in `tr_rand_int` (https://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator).
2. Fix the warning "_Implicit conversion loses integer precision_" in some usages of `tr_rand_int` and `tr_rand_int_weak` by adding support for `size_t`.
=> Fix tr_rand_int modulo bias and fix tr_rand_int for values larger than INT_MAX

.github/workflows/actions.yml, code_style.sh, libtransmission/variant.cc, macosx/VDKQueue/VDKQueue.h
Bump required `clang-format` version to 15 and fix the following noise:
```
./macosx/VDKQueue/VDKQueue.h:101:42: error: code should be clang-formatted [-Wclang-format-violations]
typedef NS_OPTIONS(u_int, VDKQueueNotify)
^
./libtransmission/variant.cc:58:17: error: code should be clang-formatted [-Wclang-format-violations]
delete[]((char*)(str->str.str));
^
```
Signed-off-by: Mike Gelfand <mikedld@mikedld.com>
=> refactor, ci: switch clang-format to LLVM 15

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, tests/libtransmission/handshake-test.cc
Instead of allocating a new one for each handshake, just keep reusing the same one.
=> refactor: only need a single handshake mediator

Transmission.xcodeproj/project.pbxproj, libtransmission/CMakeLists.txt, libtransmission/handshake.cc, libtransmission/net.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-socket.cc, libtransmission/peer-socket.h, libtransmission/session.cc, libtransmission/tr-utp.cc, tests/libtransmission/handshake-test.cc
Some small refactors to `tr_peer_socket` in preparation of changing the `tr_peerIo` lifecycle.
- Add address, port properties
- Make `tr_peer_socket.type_` private
- Make `close()` a member function that knows how to close both TCP and uTP sockets
=> refactor: tr_peer_socket

libtransmission/net.cc, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-socket.cc, libtransmission/peer-socket.h, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-utp.cc, tests/libtransmission/handshake-test.cc
A followup to https://github.com/transmission/transmission/pull/4325. This is more work to make `tr_peer_socket` easier for `tr_peerIo` to use.
- Remove copy assignment, copy constructor
- Move tos / congestion algorithm application into the peer_socket constructor
=> refactor: peer-socket pt 2

libtransmission/session.cc, libtransmission/session.h
Fixes #4316.
Notes: Fixed `4.0.0-beta.2` crash on shutdown in `utp_set_userdata()`.
=> refactor: fix shutdown order of utp

libtransmission/peer-msgs.cc
Notes: Fixed detection of the peer's UDP port during peer handshake.
=> fix: broken detection of peer udp port

libtransmission/handshake.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-common.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, libtransmission/peer-socket.cc, libtransmission/peer-socket.h, libtransmission/port-forwarding.cc, libtransmission/session.cc, libtransmission/tr-udp.cc, libtransmission/webseed.cc, tests/libtransmission/announcer-test.cc, tests/libtransmission/dht-test.cc, tests/libtransmission/net-test.cc
Minor housekeeping PR: rename a few class' methods to `display_name()` for consistency and for commonly-used naming.
Renamed:
- `tr_address::readable()`
- `tr_peer_socket::readable()`
- `tr_peerIo::addrStr()`
=> refactor: tr_address::display_name()

libtransmission/announcer-http.cc, libtransmission/announcer-udp.cc, libtransmission/blocklist.cc, libtransmission/net.cc, libtransmission/net.h, libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/peer-mgr.h, libtransmission/peer-msgs.cc, libtransmission/session.cc, libtransmission/session.h, libtransmission/tr-dht.cc, libtransmission/tr-utp.cc, libtransmission/variant-converters.cc, libtransmission/web-utils.cc, tests/libtransmission/announcer-test.cc, tests/libtransmission/announcer-udp-test.cc, tests/libtransmission/blocklist-test.cc, tests/libtransmission/dht-test.cc, tests/libtransmission/handshake-test.cc, tests/libtransmission/net-test.cc
Minor tr_address and tr_address-adjacent cleanup.
- move `announcer_url_new()` helpers into their own namespace
- move `tr_globalIPv6()` helpers into their own namespace
- move `tr_address_is_valid_for_peers()`  helpers into their own namespace
- make `tr_address_compare()` a member function
- make `tr_address_is_valid()` a member function
- make `tr_address_is_valid_for_peers()` a member function
=> refactor: tr_address cleanup

Transmission.xcodeproj/project.pbxproj, macosx/CMakeLists.txt, macosx/Controller.mm, macosx/GroupTextCell.h, macosx/GroupTextCell.mm, macosx/TorrentTableView.mm
Fixes #3397
Notes: Fix for UI issues in the macOS client main window when using Groups
https://user-images.githubusercontent.com/7323792/206352891-66bf1534-2688-43df-b9c5-116aa1c3ebd8.mov
https://user-images.githubusercontent.com/7323792/206353139-ea429f85-69e1-4a8a-b498-7ff9097142f7.mov
=> MacOS empty tableview rows fix

libtransmission/bitfield.cc
These two assertion are failing because they were invalid; it's OK for the bitfields to have different sizes.
Fixes #4312.
=> fix: remove invalid assertion from bitfield code

gtk/CMakeLists.txt
Broken with switch to CMake. Ideally, need an API/RPC method to request core capabilities to support remote sessions.
Notes: Fixed an issue with "Enable µTP for peer communication" checkbox in preferences dialog being always hidden for CMake-based builds.
=> Show "Enable uTP" checkbox in preferences if supported (GTK client)

libtransmission/utils.cc
Problem: DoMatch returns `ABORT` (`-1`) for some pattern failures, `false` for some other failures and `true` for successes.
Solution: tr_wildmat shall assert success with `> 0` instead of `!= 0`.
Example: `tr_wildmat("", "a")` should return false, not true.
=> Fixed logic in tr_wildmat

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mgr.cc, libtransmission/tr-udp.cc, tests/libtransmission/handshake-test.cc
Code cleanup from yesterday's refactor:
1. simplify flag handling
2. move larger functions from header to cc
3. make more fields private static constexpr
4. iwyu
=> refactor: tr_handshake

macosx/Controller.mm, macosx/GroupsController.mm, macosx/GroupsPrefsController.mm, macosx/TorrentTableView.mm
Tested: secure coding is already supported (since #2973 + #3053)
=> Fixed `archivedDataWithRootObject:` is deprecated

CMakeLists.txt, macosx/CMakeLists.txt
This refactor is to ensure consistency and unique source of truth between the default value and the minimum value of CMAKE_OSX_DEPLOYMENT_TARGET.
=> Moving CMAKE_OSX_DEPLOYMENT_TARGET FATAL_ERROR next to its default setting

macosx/Controller.mm
Fix #4361
Notes: Sorting by size is now sorting by total size of selected files.
=> Sorting by size should be instead by sizeWhenDone

libtransmission/announcer.cc, libtransmission/bandwidth.cc, libtransmission/crypto-utils-polarssl.cc, libtransmission/peer-mgr.cc, libtransmission/session.cc, libtransmission/tr-dht.cc, libtransmission/tr-utp.cc, tests/libtransmission/bitfield-test.cc, tests/libtransmission/crypto-test.cc, tests/libtransmission/makemeta-test.cc, tests/libtransmission/utils-test.cc
Adopting tr_rand_int instead of tr_rand_int_weak everywhere except in Polar SSL, because in Polar SSL my_rand is used to seed the initial tr_rand_int.
=> Dropped tr_rand_int_weak (where possible).

macosx/Controller.h, macosx/Controller.mm
Problem: NSURLDownload is deprecated
Solution: adopted NSURLSession by starting an NSURLSessionDataTask, inspecting the response for its suggested filename, and finally converting it to NSURLSessionDownloadTask.
Tested with no regressions:
1. dragged & dropped an URL which isn't a torrent (for the error alert)
2. dragged & dropped an URL which is a torrent (for the add torrent window)
=> Replaced deprecated NSURLDownload with NSURLSessionDownloadTask

gtk/Application.cc, gtk/DetailsDialog.cc, gtk/FileList.cc, gtk/PrefsDialog.cc, gtk/Session.cc
This is applicable to any signals where emitter's lifetime isn't controlled by the receiver.
There're still about 7 `Glib::signal_idle()` connections which aren't tracked but I see the possibility of it leading to major issues as quite low.
=> Disconnect some more signals on widgets destruction

docs/Building-Transmission.md
This PR adds instructions to the docs how to build the qt client in windows.
Also added python as a dependency, because third-party/libpsl needs it to build.
=> Add Qt dependencies for Windows build instructions and minor fixes

libtransmission/peer-io.cc, libtransmission/peer-io.h, libtransmission/peer-mgr.cc
No behavioral changes this time; this is a housekeeping-only PR:
- do not include `<ctime>`, `<string>`, and `<tr-assert.h>` in peer-io.h since that header doesn't use them
- group related methods together (this shuffling is what makes the diff big)
- make `tr_peerIo.is_seed()` and `tr_peerIo.decrypt()` private since only peer-io uses them
- remove unused `tr_isPeerIo()` method
- rename `tr_peerIo.set_parent()` setter to `tr_peerIo.set_bandwidth()` for symmetry with the `tr_peerIo.bandwidth()` getter
=> refactor: group related tr_peerIo methods together

gtk/ui/gtk3/PrefsDialog.ui, gtk/ui/gtk4/PrefsDialog.ui
This regressed with the switch to `Gtk::Builder` because the dialog was non-modal before.
This is the cause of the issue with blocklist update status dialog: it seems that if there's a modal dialog running, showing another non-modal dialog will make it inaccessible to the user until the first dialog is closed thus leaving the modal mode.
Fixes: #4311
Notes: Fixed `4.0.0-beta.1` regression causing preferences dialog to be modal and making it impossble to close the blocklist update status dialog.
=> Make preferences dialog non-modal

gtk/PrefsDialog.cc, gtk/Session.cc, gtk/Session.h
Make it behave [almost] the same way port test works: display update status and final result in the label below the URL entry. The only difference is that label returns to its usual mode showing total number of rules after a while once update is finished; could probably have done it differently but decided against it to avoid affecting translations.
=> Don't use message dialog to display blocklist update status

daemon/daemon.cc, libtransmission/crypto-utils-ccrypto.cc, libtransmission/log.cc, libtransmission/log.h, libtransmission/tr-assert.cc, libtransmission/tr-assert.h, libtransmission/tr-assert.mm
Problem: tr_log_message declares line as `size_t`, but that type is too large for usage and triggers a warning.
Solution: adopt `long`, as the maximum value supported for `__LINE__`, see https://stackoverflow.com/questions/5075928/cwhat-is-the-type-of-the-line-macro
=> Fixed implicit conversion warning: __LINE__ is a long

libtransmission/handshake.cc, libtransmission/peer-io.cc, libtransmission/session.cc, libtransmission/session.h
Fix Yet Another Permutation of the tr_session shutdown bug.
Since UTP relies on udp_core, ensure that udp-core is cleared _after_ UTP in shutdown part 2.
=> fixup: 3899255

libtransmission/peer-socket.cc, libtransmission/tr-buffer.h
Its two calls to evbuffer_peek() used 3.5% of CPU use (measured with perf when built with RelWithDebInfo). I added vecs() so that libtransmsision could send noncontiguous buffers via utp_writev(); but in my testing, all the buffers being sent are contiguous and so this is unnecessary work.
=> perf: remove libtransmission::Buffer.vecs()

libtransmission/bandwidth.cc
In `tr_bandwidth::phaseOne`, shuffle the peer array once at the beginning of the function instead of repeatedly calling `tr_rand_int()` to pick a random index.
This reduces the cost of `phaseOne()` by about 50%. In profiling, the calls to `tr_rand_int()` in `phaseOne()` cost 2.61% of runtime.
=> perf: reduce excess rand() calls in tr_bandwidth::phaseOne()

libtransmission/resume.cc, libtransmission/session.cc, libtransmission/torrent.cc, libtransmission/torrent.h
The current codebase's CPU profiling is looking pretty good when permaseeding -- there's not a lot of low-hanging fruit left for easy performance wins.
Once per second in `tr_session::onNowTimer()` we iterate through all the torrents and update their `secondsSeeding` and `secondsDownloading` fields, which uses about 1.98% of cycles according to perf. This PR removes that update and instead lazy-evaluates it based on current time, startTime, and doneTime.
=> perf: lazy-calculate torrent seconds-seeding stat

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mse.h
Generating these keys is expensive, so recycle them if the peer was unreachable. We do not recycle keys that were shared in handshakes that succeeded / handshakes that failed due to invalid communication.
This can be a substantial savings in cases where you have a long list of peers that may be invalid, e.g. when resuming from an old session s.t. you have a cold cache of peers that may not be online anymore.
=> perf: recycle Diffie-Hellman keys iff peer was unreachable

libtransmission/peer-socket.cc, libtransmission/peer-socket.h
- Remove unused `tr_netOpenPeerUTPSocket` function.  Apologies if I'm mistaken but I couldn't find other uses of it and I think call to `utp_create_socket` is in the `tr_peerIo::new_outgoing` function in `peer-io.cc`.  Not important -just cleanup if indeed it is unused.
=> Remove unused UTP Socket code.

libtransmission/handshake.cc, libtransmission/handshake.h, libtransmission/peer-mse.h
Generating these keys is expensive, so recycle them if the peer was unreachable. We do not recycle keys that were shared in handshakes that succeeded / handshakes that failed due to invalid communication.
This can be a substantial savings in cases where you have a long list of peers that may be invalid, e.g. when resuming from an old session s.t. you have a cold cache of peers that may not be online anymore.
=> perf: recycle DH MSE keys iff peer was unreachable

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/crypto-utils.h, tests/libtransmission/crypto-test-ref.h
Refactor to address review comments in https://github.com/transmission/transmission/pull/4404
- Use crypto-utils instead of mt19937 when calling `std::shuffle`. This is partially to get the OS' RNG, and partially to enable batching up calls to the RNG by implementing the URBG with `tr_salt_shaker()`.
=> fixup! perf: reduce rand() calls in tr_bandwidth::phaseOne() (#4404)

.github/workflows/actions.yml
tests depend on utils; so if we unconditionally enable tests, we need to do the same for utils.
This should fix a CI edge case that was showing up in https://github.com/transmission/transmission/pull/4418
=> build: fix utils tests on win32 CI

libtransmission/bandwidth.cc, libtransmission/bandwidth.h, libtransmission/peer-mgr.cc
Previously `bandwidth.allocate()` was called twice in a row, once for upload bandwidth and once for download bandwidth.
It has some semi-expensive housekeeping though, so avoid doing that work twice by having a single call to `bandwidth.allocate()` operate on both up and down bandwidth.
=> perf: make bandwidth.allocate() bidirectional

libtransmission/session-thread.cc
This function took 1% of runtime during an 8hr transmission-daemon session. Instead of rehashing it every time, hash it once and cache the result in a const thread_local variable.
=> perf: cache the result of thread_current_id()

libtransmission/announcer.cc, libtransmission/crypto-utils-ccrypto.cc, libtransmission/crypto-utils-cyassl.cc, libtransmission/crypto-utils-openssl.cc, libtransmission/crypto-utils-polarssl.cc, libtransmission/crypto-utils.cc, libtransmission/crypto-utils.h, libtransmission/file-win32.cc, libtransmission/session.cc, libtransmission/tr-dht.cc, libtransmission/tr-utp.cc, tests/libtransmission/bitfield-test.cc, tests/libtransmission/crypto-test-ref.h, tests/libtransmission/crypto-test.cc, tests/libtransmission/magnet-metainfo-test.cc, tests/libtransmission/torrent-metainfo-test.cc, tests/libtransmission/utils-test.cc, tests/libtransmission/variant-test.cc, tests/libtransmission/web-utils-test.cc
Another pass at refactoring our RNG. Previous discussion: #4235, #2089
1. `tr_rand_buffer()` now tries the system's crypto library first, then uses `std::mt19937` as a fallback if the crypto library fails for whatever reason. Since `tr_rand_buffer()` doesn't fail anymore, it now returns `void` instead of a success flag. Remove client code that checked for and handled failure.
2. Remove `tr_rand_int_weak()`. It was used as a fallback in case `tr_rand_int()` failed, but `tr_rand_int()` is implemented `tr_raned_buffer()` which now has its own fallback mode (described in previous bullet point).
3. Reimplement `tr_rand_int()`. It now has an internal thread_local buffer and calls `tr_rand_buffer()` so it can buffer up a batch of numbers that can be returned by subsequent calls to …
=> refactor: tr_rand_buffer(), tr_rand_int() again

libtransmission/peer-common.h, libtransmission/peer-mgr.cc
Another permaseed perf improvement -- the more torrents you have, the more it cost to recalculate the number of peers and atoms.
On my seedbox this gives about a 1% win.
=> perf: cache peer and atom counts instead of always recomputing them

gtk/Application.cc, gtk/CMakeLists.txt, gtk/FilterBar.cc, gtk/FilterBar.h, gtk/Flags.h, gtk/ListModelAdapter.cc, gtk/ListModelAdapter.h, gtk/MainWindow.cc, gtk/MainWindow.h, gtk/OptionsDialog.cc, gtk/Session.cc, gtk/Session.h, gtk/Torrent.cc, gtk/Torrent.h, gtk/TorrentCellRenderer.cc, gtk/TorrentCellRenderer.h, gtk/TorrentFilter.cc, gtk/TorrentFilter.h, gtk/TorrentSorter.cc, gtk/TorrentSorter.h, gtk/Utils.cc, gtk/Utils.h
Switch from `Gtk::{TreeModel,ListStore}` in preparation for cell renderers deprecation in GTK 4.10. That will require switching to the new view classes (`Gtk::{Column,List}View`) which only work with `Gio` models. Implement an adapter to support GTK+ 3 where the old view class (`Gtk::TreeView`) only works with `Gtk` models; it is effective enough but requires a signal connection per item to notify on row changes.
Refactor filtering and sorting (which now happen over the new model) to use compatible `Gtk::Filter` and `Gtk::Sorter` classes. Although these classes are only present in GTK 4, the abstraction is suitable for GTK+ 3 as well so make our subclasses work for both versions.
Since items (of `Torrent` class) of the new model provide only a very limited (by design) layer of …
=> Use `Gio::List{Model,Store}` for torrents

macosx/CMakeLists.txt, macosx/GroupPopUpButtonCell.h, macosx/GroupPopUpButtonCell.mm, macosx/PriorityPopUpButtonCell.h, macosx/PriorityPopUpButtonCell.mm
They were added with #3156. The missing files were unnoticed because the difference is small (icon and title moved a pixel or two):
And SparkleProxy.mm (from #3050) for alerting devs when signing is incorrect.
Also adding CocoaCompatibility.h (from #2844) for older Xcodes.
=> Add missing GroupPopUpButtonCell and PriorityPopUpButtonCell to CMakeLists.txt

Transmission.xcodeproj/project.pbxproj
Fix minor Xcode build regression from #1830. Those two files don't belong to libtransmission.
=> Removing WebSeedTableView.mm and InfoViewController.h from libtransmission

libtransmission/peer-common.h, libtransmission/peer-mgr.cc, libtransmission/peer-msgs.cc, libtransmission/peer-msgs.h
Fix a regression introduced yesterday in 9a4797d52f510385fe0290c65ec6ec3e10ea83af that could potentially crash when Transmission reaches its limit of peer connections.
tl;dr is we were counting the number of `tr_peer` objects that were instantiated and using that as a count for the number of bittorrent peers; however, this gave an incorrect number because webseeds subclass from `tr_peer` as well
Fixes #4446
=> fixup: peer counts

libtransmission/session.cc, libtransmission/session.h, libtransmission/web.cc, libtransmission/web.h, utils/show.cc
Fixes #4294.
Notes: FIxed 4.0.0-beta.2 regression that caused `transmission-show --scrape` to not exit cleanly.
=> fix: 4.0.0-beta.2 regression transmission-show --scrape did not exit cleanly

libtransmission/webseed.cc
Fix #4450.
Fix #3899.
That code was from #2689, so it might have been an old regression.
=> Fixed crash on exit while downloading from webseed

libtransmission/torrent.cc
Problem: torrents with a single folder containing a single file are only showing their folder name, but not the file name in the File Inspector.
Solution: torrents with a single folder containing a single file should return true for `is_folder`.
(Alternative solution considered: in Torrent.mm createFileList, we ignore `is_folder` and we parse `fileCount()` and `fileSubpath(0)` manually to get the real information about whether it's a folder or not... but then that would make the `is_folder` property useless and always ignored)
=> Fix tr_torrent_view incorrectly returning is_folder false for single files in a single folder

libtransmission/announce-list.h, libtransmission/bitfield.h, libtransmission/completion.h, libtransmission/file-piece-map.h, libtransmission/magnet-metainfo.h, libtransmission/makemeta.h, libtransmission/peer-io.h, libtransmission/peer-mgr.cc, libtransmission/session.h, libtransmission/torrent-files.h, libtransmission/torrent-metainfo.h, libtransmission/torrent.h, libtransmission/torrents.cc, libtransmission/torrents.h, libtransmission/tr-buffer.h, libtransmission/tr-macros.h, libtransmission/tr-popcount.h, qt/FileTreeItem.h, qt/Torrent.h
No behavioral changes.
Add `TR_CONSTEXPR20` and `TR_CONSTEXPR23` placeholders that we can use for easily migrating code if/when we bump the C++ dependency from 17 to 20 or 23 in the future.
=> refactor: add TR_CONSTEXPR20 to make future C++20 migration easier

macosx/TorrentTableView.mm
Fixes: #4375
Notes: Fix for selected torrents font color in macOS client
=> set selected torrentTableView backgroundstyle

libtransmission/net.cc, libtransmission/net.h, tests/libtransmission/net-test.cc
Update the `global_unicast_address()` function that was private in net.cc:
- Make the function visible to tests so it can be tested.
- Add tests.
- Update the implementation to cover more [IPv4 reserved address ranges](https://en.wikipedia.org/wiki/Reserved_IP_addresses).
=> refactor: add tr_address.is_global_unicast_address()
